### ISSUE TITLE
Change Access Token

### ISSUE THREAD

**Issue by pollardfamily** [shanalikhan/code-settings-sync#10]
Hello, it seems that if I needed to move from one git account to another I am not able to change my access token. I run both Windows 10 and Fedora 23. If you could enable a account change option that would be great. I have also tried to remove the plugin and re install and it still fails.

Steve

**Comment by shanalikhan** [comment]
Please use this command : 

> Sync : Reset Token and Gist ID

In order to remove the Token and GIST ID.
And then

> Sync : Upload Settings

to upload all the settings on new github account by entering new token and GIST ID.


Let me know if you face any problem in doing that :)

**Comment by shanalikhan** [comment]
No, its working - Try removing the extension and then installing.

**Comment by ldhios** [comment]
@shanalikhan  sorry, that's my mistake.  The command [Sync : Reset Token and Gist ID] is not found.
