### ISSUE TITLE
Option to ignore sync some settings, files and folders?

### ISSUE THREAD

**Issue by KayLeung** [shanalikhan/code-settings-sync#100]
Using VSCode in few platforms & devices. Sometimes, I liked larger font size in Desktop but smaller in Laptops. Windows & OSX, we may have different settings too. It would be useful if we can ignore to sync some settings.

**Comment by shanalikhan** [comment]
It would be the least priority to only show some of the JSON keys from the settings or any other JSON files. You can go ahead and send me a pull request, i'll be more happy to accept that or we can talk about this after several months and i will see what can be done.

Meanwhile i'm closing this request if you are interested to send a pull request let me know i will re open it and i will help you doing that.

**Comment by shanalikhan** [comment]
Apart from ignoring only the screen size, there is another scenario where users working in proxies needs to ignore the proxy settings which allow them to to sync the settings to non proxy environments.

There is a need to ignore some settings while sync.
I will work on it later on.

**Comment by macroloft** [comment]
It would be great if we could exclude entire *.json-files. For example I use the extension [alefragnani/vscode-project-manager](github.com/alefragnani/vscode-project-manager) and I sync my work machines settings with my private one. I'm happy to have all my settings in both environments but I don't need the projects.json which is created by the extension. I think there are other cases too.

**Comment by shanalikhan** [comment]
@macroloft can you provide the path of all Json files that extension is creating.

**Comment by macroloft** [comment]
@shanalikhan on my Mac it's ~/Library/Application Support/Code/User/ and the projects.json seems to be the only file the extension creates.

**Comment by unional** [comment]
> It would be great if we could exclude entire *.json-files. For example I use the extension alefragnani/vscode-project-manager and I sync my work machines settings with my private one.


Same situation here. In fact, one overwrites the other causing all the project settings gone.

**Comment by shanalikhan** [comment]
Thanks for Explaining well.
I understand i will solve this in next version.
Meanwhile you can try to save it on another location until next version.

**Comment by fredrikaverpil** [comment]
Also, if you're on the insider build of vscode you have this path: 

    /Users/USERNAME/Library/Application Support/Code - Insiders/User

I find code-settings-sync excellent but I wish I could've disabled sync of `projects_cache_git.json` as it both reveals which projects I'm working on and wrongly syncs this onto machines which may be using a different path. From my `syncSummary.txt`:

```

Files Upload.

extensions.json
projects.json
projects_cache_git.json
settings.json
vsicons.settings.json
```

**Comment by shanalikhan** [comment]
This will be the format for local settings file for the extension where you can set this.
```
{
    "ignoreFiles": ["projects.json","projects_cache_git.json"],
    "ignoreFolders": [
        "workspaceStorage"
    ],
    "ignoreCodeSettings": [
        {
            "name": "files.autoSave",
            "value": "afterDelay"
        }
    ]
}
```
When the value is empty for the `nameValue` Pair in the `ignoreCodeSettings`. Extension will remove that key from the downloaded `settings.json` file is there is any value. It will add that local value in the `settings.json` file.

`ignoreFiles` will be from `User` folder
`ignoreFolders` will be any folder inside `User` folder


When the extension is installed, it will add `syncCustomSettings.json` file for these features.

If anyone from you guys are using insiders version please let me know, i can release this for insiders before public release else if there is no one i will release publicly after testing myself.

**Comment by fredrikaverpil** [comment]
If you like, I could try this with insiders.

**Comment by fredrikaverpil** [comment]
Do you mean to say this would make sync-settings ignore backing up and restoring the projects cache?

```json
"sync.ignoreFiles": ["projects_cache_git.json"]
```

**Comment by shanalikhan** [comment]
> "sync.ignoreFiles"

No, i dont think its necessary to put the above files with "sync." > in settings.json
 
New file inside users folder will be created with the name `syncCustomSettings.json` 

For example in Computer A, in which you have `"ignoreFiles": ["projects.json","projects_cache_git.json"]` in `syncCustomSettings.json` inside user folder, these files wont upload in **GIST** so wont have backup, in computer B when you download this file wont be downloaded in computer B as its not inside GIST

I will push a version for insiders tomorrow and let you know =) and Thanks!

**Comment by shanalikhan** [comment]
@fredrikaverpil I have pushed a version fixing this issue for Insiders, release notes and explanation is not made available in docs. Please have a look 
If all worked well, i will release to public with complete guide.

**Comment by fredrikaverpil** [comment]
Ok, I just gave this a try and I think there are some problems.

I did not get a `syncCustomSettings.json` file created when updating the extension or by uploading/downloading the settings.

I created one manually with the contents you posted. Then after having uploaded/downloaded the settings I now also see that a `syncLocalSettings.json` file was created with these contents:

```json
{"ignoreUploadFiles":["projects.json","projects_cache_git.json"],"ignoreUploadFolders":["workspaceStorage"],"replaceCodeSettings":[]}
```

**Comment by fredrikaverpil** [comment]
I'm also having trouble resetting the plugin. I've chosen to "reset" through the menu but upon hitting "download", I am only asked to enter the gist and not my token.

**Comment by fredrikaverpil** [comment]
I also notice that after having reset (and not being able to enter both gist and token), I get this when I attempt to download my settings:

![screen shot 2017-02-19 at 13 34 38](https://cloud.githubusercontent.com/assets/994357/23102363/3b5596f6-f6a8-11e6-8da7-a1cab94e9b8b.png)

**Comment by shanalikhan** [comment]
Yes i had change the file let me write the detail here, keys are changed for better understanding:
Extension will only create the `syncLocalSettings.json` on code start and connect with it.
`syncCustomSettings.json` is changed to localSettings name so extension will think it as some JSON file and upload and download it also.

`syncLocalSettings.json` file wont be upload and download. Following are the keys or layout for the file.
```
{
    "ignoreUploadFiles": [
        "projects.json",
        "projects_cache_git.json"
    ],
    "ignoreUploadFolders": [
        "workspaceStorage"
    ],
    "replaceCodeSettings": [
        {
            "name":"http.proxy",
            "value":""
        }
    ]
}
```

U know first two files allows extension to ignore files and folders to **UPLOAD**
Third key `replaceCodeSettings` will be used to replace the key in the value after **downloading** the GIST.

For users who are using proxy in one computer and dont want to set proxy in second one after downloading or need to change the value for proxy. 
They need to add value as
```
 {
            "name":"http.proxy",
            "value":""
 }
```
After downloading the settings, extension will check if the value is defined, it will replace the the `http.proxy` value to defined value in `settings.json` after downloading.

If the value is not defined as some user dont want to use proxy in Home computer but they have proxy in office computer and they upload from office and it will have proxy in GIST to remove it from Home computer to make it work, the value need to set as empty so extension will delete the `http.proxy` from the Home computer.

Hope This is better for understanding.

> I believe you should be able to repro this like so

I have reset the extension and re installed the extension and hit download and added the GIST ID, Settings are downloaded successfully. 

Can you please provide the console logged image from the console ?

**Comment by fredrikaverpil** [comment]
> Hope This is better for understanding.

Aha, yes I understand now. I was confused by the former post in the thread.

> Can you please provide the console logged image from the console ?

For some reason, I do no longer get this error. I suspect that maybe I had been pasting the token into the field which was expecting the gist id.

To me, this all just works great now. 😄 👏 

About `replaceCodeSettings`, how would you go about copy-pasting e.g. this from `settings.json`?

```json
    "python.pythonPath": "${env.HOME}/miniconda3/envs/pythondev_35",
    "python.linting.pylintPath": "${env.HOME}/miniconda3/envs/pythondev_35/bin/pylint",
    "python.linting.pep8Path": "${env.HOME}/miniconda3/envs/pythondev_35/bin/pep8",
    "python.formatting.autopep8Path": "${env.HOME}/miniconda3/envs/pythondev_35/bin/autopep8",
    "python.formatting.yapfPath": "${env.HOME}/miniconda3/envs/pythondev_35/bin/yapf",
```

Right now it seems you'd have to carefully reformat that into a list of dictionaries containing the `name` and `value` keys:

```json
{
    "replaceCodeSettings": [
        {
            "name": "python.pythonPath",
            "value": "${env.HOME}/miniconda3/envs/pythondev_35"
        },
        {
            "name": "python.linting.pylintPath",
            "value": "${env.HOME}/miniconda3/envs/pythondev_35/bin/pylint"
        },
        {
            "name": "python.linting.pep8Path",
            "value": "${env.HOME}/miniconda3/envs/pythondev_35/bin/pep8"
        },
        {
            "name": "python.formatting.autopep8Path",
            "value": "${env.HOME}/miniconda3/envs/pythondev_35/bin/autopep8"
        },
        {
            "name": "python.formatting.yapfPath",
            "value": "${env.HOME}/miniconda3/envs/pythondev_35/bin/yapf"
        }
    ]
}

```

It would've been very helpful to just be able to copy paste from `settings.json` into `replaceCodeSettings`.

**Comment by fredrikaverpil** [comment]
But all in all, the features works perfectly fine without issues for me. Awesome job!

**Comment by shanalikhan** [comment]
> It would've been very helpful to just be able to copy paste from settings.json into replaceCodeSettings.

Please open a new issue with your ideas 😄 to do such task.
As this works, i'm going to push newer version for public in few hours.

Thanks for your time =)

**Comment by fredrikaverpil** [comment]
> Please open a new issue with your ideas 😄 to do such task.

Ok! 👍 

> As this works, i'm going to push newer version for public in few hours.

😀 🎉

**Comment by shanalikhan** [comment]
Public build released v2.4.4.

Closing this issue. Feel free to let me know about any problem.

**Comment by borekb** [comment]
This was v2.5-worthy :) Nice feature.

**Comment by shanalikhan** [comment]
> This was v2.5-worthy :)
Yes i forgot this idea though 
I will push v2.5 by integrating it more with menus and more options.

**Comment by borekb** [comment]
Just a quick question about this feature: can `replaceCodeSettings` be set up so that it doesn't even upload the real value? I understand that the download direction is more important but for example if some value changes rapidly, having it entirely removed from the uploaded file (or replaced with some placeholder value) would prevent the Gist from having many useless revisions.

**Comment by shanalikhan** [comment]
Please post a new issue for it and we will see about it

**Comment by borekb** [comment]
@shanalikhan Done, https://github.com/shanalikhan/code-settings-sync/issues/232.
