### ISSUE TITLE
Sync Pragmas not working as expected

### ISSUE THREAD

**Issue by comicchang** [shanalikhan/code-settings-sync#1003]
🐛 **Describe the bug**  
Sync Pragmas not working as expected,  some of the ``` // @sync``` lines are mistakenly un-commented when uploading, and this may also affect the downloading process.

🌴 **Visual Studio Code Version :** [ 1.37.0 ] 
🌴 **Code Settings Sync Version :** [ 3.4.1 ] 
🌴 **Standard or Insiders :** [ Standard ] 
🌴 **Portable or Installed :** [ Installed ] 
🌴 **OSS or Official Build :** [ Official ] 
🌴 **Operating System :** [ archlinux ] 
🌴 **Occurs On:** [Upload / Download ]
🌴 **Proxy Enabled:** [ Yes ]
🌴 **Gist Id:** [ 9b1c41c641e03f6e3f266f43fc3acea6 ]

📰 **To Reproduce**
1. Go to settings, and add to local settings.json
```
    // @sync host=cc-mbp os=mac
    // "vim.autoSwitchInputMethod.enable": true,
    // @sync host=cc-mbp os=mac
    // "vim.autoSwitchInputMethod.defaultIM": "com.apple.keylayout.ABC",
    // @sync host=cc-mbp os=mac
    // "vim.autoSwitchInputMethod.obtainIMCmd": "/usr/local/bin/im-select",
    // @sync host=cc-mbp os=mac
    // "vim.autoSwitchInputMethod.switchIMCmd": "/usr/local/bin/im-select {im}",
    // @sync os=linux
    "vim.autoSwitchInputMethod.enable": true,
    // @sync os=linux
    "vim.autoSwitchInputMethod.defaultIM": "1",
    // @sync os=linux
    "vim.autoSwitchInputMethod.obtainIMCmd": "/usr/bin/fcitx-remote",
    // @sync os=linux
    "vim.autoSwitchInputMethod.switchIMCmd": "/usr/bin/fcitx-remote -t {im}",
```
2. Upload
3. Check on gist.github.com
4. Download on another machine

💪 **Expected behavior**
expected uploaded gist
```
    // @sync host=cc-mbp os=mac
    "vim.autoSwitchInputMethod.enable": true,
    // @sync host=cc-mbp os=mac
    "vim.autoSwitchInputMethod.defaultIM": "com.apple.keylayout.ABC",
    // @sync host=cc-mbp os=mac
    "vim.autoSwitchInputMethod.obtainIMCmd": "/usr/local/bin/im-select",
    // @sync host=cc-mbp os=mac
    "vim.autoSwitchInputMethod.switchIMCmd": "/usr/local/bin/im-select {im}",
    // @sync os=linux
    "vim.autoSwitchInputMethod.enable": true,
    // @sync os=linux
    "vim.autoSwitchInputMethod.defaultIM": "1",
    // @sync os=linux
    "vim.autoSwitchInputMethod.obtainIMCmd": "/usr/bin/fcitx-remote",
    // @sync os=linux
    "vim.autoSwitchInputMethod.switchIMCmd": "/usr/bin/fcitx-remote -t {im}",
```

actually gist uploaded
```
    // @sync host=cc-mbp os=mac
    "vim.autoSwitchInputMethod.enable": true,
    // @sync host=cc-mbp os=mac
    "vim.autoSwitchInputMethod.defaultIM": "com.apple.keylayout.ABC",
    // @sync host=cc-mbp os=mac
    "vim.autoSwitchInputMethod.obtainIMCmd": "/usr/local/bin/im-select",
    // @sync host=cc-mbp os=mac
    "vim.autoSwitchInputMethod.switchIMCmd": "/usr/local/bin/im-select {im}",
    @sync os=linux
    "vim.autoSwitchInputMethod.enable": true,
    @sync os=linux
    "vim.autoSwitchInputMethod.defaultIM": "1",
    @sync os=linux
    "vim.autoSwitchInputMethod.obtainIMCmd": "/usr/bin/fcitx-remote",
    @sync os=linux
    "vim.autoSwitchInputMethod.switchIMCmd": "/usr/bin/fcitx-remote -t {im}",
```

and when another machine downloading the config (host=cc-mbp os=mac), it will get
```
    // @sync host=cc-mbp os=mac
    "vim.autoSwitchInputMethod.enable": true,
    // @sync host=cc-mbp os=mac
    "vim.autoSwitchInputMethod.defaultIM": "com.apple.keylayout.ABC",
    // @sync host=cc-mbp os=mac
    "vim.autoSwitchInputMethod.obtainIMCmd": "/usr/local/bin/im-select",
    // @sync host=cc-mbp os=mac
    "vim.autoSwitchInputMethod.switchIMCmd": "/usr/local/bin/im-select {im}",
    @sync os=linux
    "vim.autoSwitchInputMethod.enable": true,
    @sync os=linux
    "vim.autoSwitchInputMethod.defaultIM": "1",
    @sync os=linux
    "vim.autoSwitchInputMethod.obtainIMCmd": "/usr/bin/fcitx-remote",
    @sync os=linux
    "vim.autoSwitchInputMethod.switchIMCmd": "/usr/bin/fcitx-remote -t {im}",
```

📺 **Console Error Log** 
nothing related

📺  **Additional context**

**Comment by shanalikhan** [comment]
@protium-dev can assist us on it :)

**Comment by protium-dev** [comment]
The problem seems to come from after this line `"/usr/local/bin/im-select {im}"`. Since the extension looks up for open brackets or curly braces for multiline configs.
This is the exact line in the source [pragmaUtil.ts#L267](https://github.com/shanalikhan/code-settings-sync/blob/9e061c1a6fbbea99e086ac2f64729b018d177271/src/pragmaUtil.ts#L267)

It should use the same regex as in [pragmaUtil.ts#L268](https://github.com/shanalikhan/code-settings-sync/blob/9e061c1a6fbbea99e086ac2f64729b018d177271/src/pragmaUtil.ts#L268)

I'll drop a PR as soon as I can

**Comment by shanalikhan** [comment]
> I'll drop a PR as soon as I can

@protium-dev Nice catch.

Can we release your PR in the new version coming in this week?

**Comment by shanalikhan** [comment]
@comicchang 
Its fixed and released in new version.

let me know if you are having some problem.

**Comment by comicchang** [comment]
thanks, the new version works great.
