### ISSUE TITLE
summary.txt is empty

### ISSUE THREAD

**Issue by Gelio** [shanalikhan/code-settings-sync#101]
**Visual Studio Code Version :** 1.5.2
**Code Sync Settings Version :** 2.2.4
**Operating System :** Windows 10

After uploading settings the _summary.txt_ file is empty. It worked before for me, listing all the uploaded settings, however after the last update it doesn't. There is no output from this extension in the console.

Here's a GIF reproducing the issue:
![](https://i.gyazo.com/8fef4314c63c5aeb015c7b60dae47d54.gif)

I have checked and the settings are saved properly in the gist, so it's just an interface bug.

**Comment by Gelio** [comment]
I managed to open the developer console and I saw an error there.
```
TypeError: Cannot read property 'length' of null
    at e.edit.edit (C:\Users\voren\.vscode\extensions\Shan.code-settings-sync-2.2.4\out\src\commons.js:242:42)
```
Here's the problematic bit:
```javascript
                    if (removedExtensions) {
                        if (removedExtensions.length > 0) {
                            edit.insert(new vscode.Position(row, 0), deletedExtension + " \r\n");
                            row += 1;
                            removedExtensions.forEach(ext => {
                                edit.insert(new vscode.Position(row, 0), ext.name + " - Version :" + ext.version + " \r\n");
                                row += 1;
                            });
                        }
                    }
                    if (addedExtensions) {
                        row += 1;
                        if (addedExtensions.length > 0) {
                            edit.insert(new vscode.Position(row, 0), " \r\n" + addedExtension + " \r\n");
                            row += 1;
                            addedExtensions.forEach(ext => {
                                edit.insert(new vscode.Position(row, 0), ext.name + " - Version :" + ext.version + " \r\n");
                                row += 1;
                            });
                        }
                    }
                    if (removedExtensions.length == 0 && addedExtensions.length == 0) {  // line with error
                        edit.insert(new vscode.Position(row, 0), "\r\n \r\nYou already have all extensions." + " \r\n");
                    }
```
I believe the issue is that there is no guard against `removedExtensions` being null. I browsed through the repository and found out that in [commonts.ts](https://github.com/shanalikhan/code-settings-sync/blob/master/src/commons.ts#L255) there is an if statement, which I believe would fix it.

It seems to me that it's the case of publishing a new version with this updated code.

**Comment by shanalikhan** [comment]
Thanks, i have updated the code and removed this check instead it will now show added extensions and deleted extensions in their sections.
