### ISSUE TITLE
Welcome page always show up

### ISSUE THREAD

**Issue by litong534** [shanalikhan/code-settings-sync#1013]
🐛 **Describe the bug**  
A clear and concise description of what the bug is. You are always welcome to check the [Troubleshooting](https://github.com/shanalikhan/code-settings-sync/wiki/Troubleshooting) section before filing the ticket.

🌴 **Visual Studio Code Version :** [ 1.37.1 ] 
🌴 **Code Settings Sync Version :** [ 3.4.1 ] 
🌴 **Standard or Insiders :** [ _here_ ] 
🌴 **Portable or Installed :** [ _here_ ] 
🌴 **OSS or Official Build :** [ _here_ ] 
🌴 **Operating System :** [ macOS Mojave 10.14.6 ] 
🌴 **Occurs On:** [Upload / Download / Help Configuring ]
🌴 **Proxy Enabled:** [ Yes / No ]
🌴 **Gist Id:** [ ID_HERE ]

📰 **To Reproduce**
the welcome page always shows on launching vscode, even though I unchoose the "Show this page on startup" option.
💪 **Expected behavior**
don't show welcome page when I unchoose the option, and offer a command in order to show it.

**Comment by shanalikhan** [comment]
> even though I unchoose the "Show this page on startup" option.

Have you reset the extension settings. Welcome page will always show on startup once you reset your settings.
