### ISSUE TITLE
Protected local settings

### ISSUE THREAD

**Issue by lalloni** [shanalikhan/code-settings-sync#1014]
I would like to have some settings marked as "protected" o "local" so they're not modified when downloading new settings and not included when uploading.

Some examples of why we this is needed are:

- Fonts (dependent on hardware or font availability)
- Paths to tools (dependent on OS and/or environments)
- URL to services (dependent on environments)
- Credentials or tokens (obvious reasons)
- Behavior configuration (at work I want tests to run automatically, at home I don't)
- etc.

So I believe this extension might have a configuration allowing to specify lists of json paths of configuration settings to exclude from application over download and/or for inclusion in uploads.

For instance maybe something like:

```json
"sync.settings-keep-local": [ "editor.font", "git.alwaysSignOff" ],
"sync.settings-exclude": [ "aws.token" ],
```

- `sync.settings-keep-local`: would forbid Setting Sync to ever overwrite local settings listed
- `sync.settings-exclude`:  would forbid Settings Sync to ever upload or overwrite local settings listed

Note that both could include themselves o the other to keep those lists local.

**Comment by shanalikhan** [comment]
Can you look into it and let me know if it helps

https://github.com/shanalikhan/code-settings-sync/wiki/Sync-Pragmas#ignoring-certain-settings

**Comment by lalloni** [comment]
I will check into that ASAP,

**Comment by lalloni** [comment]
Interesting!

I didn't know Settings Sync had that feature. I still didn't try it yet but first thing that come to mind is  that AFAIK Code settings are JSON files and JSON syntax doesn't allow comments so it seems risky compatibility-wise to use those, particularly when other tools might be involved.
