### ISSUE TITLE
Fail to download/upload gist after syncronized the first time

### ISSUE THREAD

**Issue by julionienow** [shanalikhan/code-settings-sync#1015]
Hi!

First of all, thank you for the amazing plugin, it's a shorthand for work on different environments.

So, today i'have downloaded my settings from an existing gist, and downloaded manually one more plugin that was missing. After that, i wanted to upload/update to my gist, and, everytime that i try to do it, by pressing SHIFT+ALT+U or even by CTRL+SHIFT+P and going to "sync: update/upload settings" it opens a new tab with the "Welcome to Settings Sync" page.
The problems occours now even if i try to download the settings again, it dosnt open the input to insert the gist, it always open the welcome to setting sync tab.

🌴 **Visual Studio Code Version :** [ 1.37.1 ] 
🌴 **Code Settings Sync Version :** [ v3.4.2 ] 
🌴 **Standard or Insiders :** [ Standart ] 
🌴 **Portable or Installed :** [ Installed ] 
🌴 **OSS or Official Build :** [ Official Build i guess] 
🌴 **Operating System :** [ Windows 10 ] 
🌴 **Occurs On:** [Upload and Download (after downloaded the  first time)]
🌴 **Proxy Enabled:** [  No ]
🌴 **Gist Id:** [ 8332e0abd9200b6969c1443d365cd6df ]

📰 **To Reproduce**
Described on top

💪 **Expected behavior**
Open the input to insert gist id

📺 **Console Error Log** 
None

![1](https://user-images.githubusercontent.com/11317664/63440396-1f91af80-c406-11e9-828a-16c51354c9dc.png)

![2](https://user-images.githubusercontent.com/11317664/63440412-23bdcd00-c406-11e9-8e63-c1011c1d87c7.png)

**Comment by shanalikhan** [comment]
@julionienow 

> i'have downloaded my settings from an existing gist, and downloaded manually one more plugin that was missing. After that, i wanted to upload/update to my gist

How you download the existing gist ?  Downloading process also opens welcome page to configure. Did you download by clicking on the `Download Public Gist` ? Public Gist download doesnt require `token` else download process needs to get your token.

**Comment by julionienow** [comment]
Hi!

i've downloaded by my private gist id that i uploaded weeks ago. pressing shift + alt + d. and it worked.

But afterwards, i installed one more extension and then every shortcut to download or even upload/update, opens the welcome tab and dosn't open the input at the top to insert gist id to do the action.

**Comment by tommulkins** [comment]
@julionienow Can you try opening the dev tools in VS Code in Help -> Toggle Developer Tools?
I had a similar problem that was due LiveShare Audio breaking and ruining the sync.

To fix it I removed `<HOME DIR>/Library/Application\ Support/Code/User/globalStorage/ms-vsliveshare.vsliveshare-audio/`

**Comment by shanalikhan** [comment]
@julionienow 
Is it working for you on the latest `v3.4.3` version of Settings Sync. ?

**Comment by julionienow** [comment]
> Is it working for you on the latest `v3.4.3` version of Settings Sync. ?
@shanalikhan 

no, actually it did'nt :/
when i try to upload or download, it still open the "Welcome to settings sync" page
![1](https://user-images.githubusercontent.com/11317664/65515793-34a2a800-deb6-11e9-8f58-73b318791e32.png)
![2](https://user-images.githubusercontent.com/11317664/65515794-353b3e80-deb6-11e9-904d-02068560dab3.png)

**Comment by julionienow** [comment]
actually, i resolved it clicking on "login with github"
