### ISSUE TITLE
Slack invite link is no longer active

### ISSUE THREAD

**Issue by toojazzy** [shanalikhan/code-settings-sync#1025]
🐛 **Describe the bug**  
So I wanted to join your slack! But I can't, because the link is no longer active. Can *we* fix it?

**Comment by shanalikhan** [comment]
The new link is :
https://join.slack.com/t/codesettingssync/shared_invite/enQtNzQyODMzMzI5MDQ3LWNmZjVkZjE2YTg0MzY1Y2EyYzVmYThmNzg2YjZkNjhhZWY3ZTEzN2I3ZTAxMjkwNWU0ZjMyZGFhMjdiZDI3ODU

This link will be updated with the new release soon.

**Comment by toojazzy** [comment]
Great!
