### ISSUE TITLE
Sync to Folder

### ISSUE THREAD

**Issue by tarrant** [shanalikhan/code-settings-sync#103]
**Visual Studio Code Version :** Version 1.5.2
**Code Sync Settings Version :** N/A
**Operating System :** OSX 10.11.6

This may already be possible but I can't find any references in the documentation so I'm opening this ticket.

You currently sync settings to a gist and then download that gist onto multiple computers. I already use Dropbox to sync my settings. I generally do this by symlinking all the right files. It would be nice if code-settings-sync supported setting a folder to sync to and then writing and reading the file into a location where Dropbox/OneDrive/etc can do the syncing for you.

**Comment by shanalikhan** [comment]
This would be the lowest priority to connect the extension with dropbox or onedrive as main feature of extension was to use the GIST. 
May be we can talk about this feature after several months and i'll see what can be done as i have other main features and issues in backlog to work on.
Or you can go ahead and start working on it and send me a pull request with configurations added - i will be more happy to accept that
