### ISSUE TITLE
This notification is appeared very frequently: "Sync: Share the Id with other extension users to share the settings."

### ISSUE THREAD

**Issue by Gigacee** [shanalikhan/code-settings-sync#1033]
This notification is appeared very frequently: "Sync: Share the Id with other extension users to share the settings."

![image](https://user-images.githubusercontent.com/5264444/64216979-4c5dc080-cef6-11e9-9ec5-a8298d49bbaf.png)

(This image is Japanese, but this notification is appeared on English environment.)

🌴 **Visual Studio Code Version : 1.37.1 (user setup)
🌴 **Code Settings Sync Version : 3.4.2
🌴 **Standard or Insiders : Standard
🌴 **Portable or Installed : Installed
🌴 **OSS or Official Build : Official Build 
🌴 **Operating System : Windows 10 Pro 1903
🌴 **Occurs On: ?
🌴 **Proxy Enabled: No
🌴 **Gist Id: b126c62c73c860eef8fa034146b9d1c9

**Comment by shanalikhan** [comment]
> This notification is appeared very frequently: "Sync: Share the Id with other extension users to share the settings."

Can you post your Settings Sync Global Settings contents to assist me. Can you write the reproducing steps.

**Comment by Gigacee** [comment]
This occurs when the automatic upload of the configuration file is completed.

![image](https://user-images.githubusercontent.com/5264444/64258003-684a7c00-cf61-11e9-839a-14751eed6404.png)

**Comment by Gigacee** [comment]
This occurs when the upload of the settings file is completed.

I checked the following settings:
```json
// settings.json
{
    "sync.autoUpload": true,
    "sync.forceUpload": true,
    "sync.gist": "e9078200a6b112c33c5e85110538c07a"
}
```

**Comment by shanalikhan** [comment]
Can you post the Global Settings of Settings Sync, check the readme for details about the configurations.

**Comment by Gigacee** [comment]
Oh, I'm sorry, I misunderstood.

Actually, this is my Global Settings:

```
{
    "ignoreUploadFiles": [
        "state.*",
        "syncLocalSettings.json",
        ".DS_Store",
        "sync.lock",
        "projects.json",
        "projects_cache_vscode.json",
        "projects_cache_git.json",
        "projects_cache_svn.json",
        "gpm_projects.json",
        "gpm-recentItems.json"
    ],
    "ignoreUploadFolders": [
        "workspaceStorage"
    ],
    "ignoreExtensions": [],
    "gistDescription": "Visual Studio Code Settings Sync Gist",
    "version": 342,
    "token": "**",
    "downloadPublicGist": false,
    "supportedFileExtensions": [
        "json",
        "code-snippets"
    ],
    "openTokenLink": true,
    "disableUpdateMessage": false,
    "lastUpload": "2019-09-04T18:04:00.734Z",
    "lastDownload": "2019-09-04T14:40:08.943Z",
    "githubEnterpriseUrl": null,
    "askGistName": false,
    "customFiles": {},
    "hostName": null,
    "universalKeybindings": false,
    "autoUploadDelay": 20
}
```

Thank you for your support!

**Comment by ramblingjordan** [comment]
Came looking for a solution to this as well.

**Comment by hulizhen** [comment]
+1
The notification is really frequent and I cannot find a way to disable it :(

**Comment by Admiralfeb** [comment]
This notification appears every time that an upload occurs.

**Comment by shanalikhan** [comment]
Guys its fixed, scheduled to release in upcoming build.

>It is really noise!

If you want to get that build now.

Download 
[code-settings-sync-3.4.3.zip](https://github.com/shanalikhan/code-settings-sync/files/3636587/code-settings-sync-3.4.3.zip)

**Comment by shanalikhan** [comment]
`v3.4.3` Released. Let me know if there is any problem :)

**Comment by haakonstorm** [comment]
Awesome, thanks a lot!

**Comment by Sanch3z2** [comment]
> Can you post the Global Settings of Settings Sync, check the readme for details about the configurations.

Yes
