### ISSUE TITLE
Ability to sync across platform?

### ISSUE THREAD

**Issue by kid1412621** [shanalikhan/code-settings-sync#1038]
This is the scenario:
I use Linux or Windows at work. I set a parameter in `settings.json`, to say JAVA_HOME. And sync via this plugin. When I come home using MacOS, that parameter just doesn't fit into this OS Platform properly.  Is there any solution out there?

**Comment by shanalikhan** [comment]
See the Sync Pragmas here and let me know if it helps.

https://github.com/shanalikhan/code-settings-sync/wiki/Sync-Pragmas

Also can you paste the expected output in `settings.json` and current value for the `JAVA_HOME` with an example. So i can better understand it.
