### ISSUE TITLE
Connection to webpage refused when trying ti login with github

### ISSUE THREAD

**Issue by Damjan99** [shanalikhan/code-settings-sync#1045]
When trying to upload my settings, clicking on the "Login with github" button takes me to a webpage with a refused connection which says :

This site can’t be reached.
 localhost refused to connect.

Don't know what might be causing this issue.

Thanks.

**Comment by Damjan99** [comment]
It was an issue related with the windows firewall.

**Comment by dalisoft** [comment]
I have same issue, how to fix it?

**Comment by dimitrov-d** [comment]
> I have same issue, how to fix it?

As I mentioned before, it was a problem related with the windows firewall. Try to look at your firewall settings.

**Comment by o-l-a-v** [comment]
I have the same issue. Tried changing my current connected network from Public to Private in network and sharing center, did not work. Also tried open 54321 TCP and UDP inbound from 127.0.0.1 in the firewall.

* What rule did you add @dimitrov-d?

**Comment by dimitrov-d** [comment]
@o-l-a-v Unfortunately I don't remember at all, sorry

**Comment by dalisoft** [comment]
Remove extension, restart machine and try install Extension again
