### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by ghost** [shanalikhan/code-settings-sync#1049]
- Issue Type: `Performance`
- Extension Name: `code-settings-sync`
- Extension Version: `3.4.3`
- OS Version: `Windows_NT x64 10.0.17134`
- VSCode version: `1.38.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\Administrador\Shan.code-settings-sync-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by shanalikhan** [comment]
> warning Make sure to attach this file from your home-directory:
warningC:\Users\Administrador\Shan.code-settings-sync-unresponsive.cpuprofile.txt
