### ISSUE TITLE
Removes newly-installed not-previously-synced Extensions

### ISSUE THREAD

**Issue by eashi** [shanalikhan/code-settings-sync#105]
**Visual Studio Code Version :** [1.5.2 ] Commit 66f37fd2a99eb9d628dd374d81d78835b410c39b
**Code Sync Settings Version :** [2.2.6 ]
**Operating System :** [ Windows 10 ]

I have updated VSCode and the extensions today, then I wanted to Install the PowerShell extension, when I restart VSCode to enable the newly installed extension the Sync extension runs somehow, and it removes all extensions that are not listed in my previously synced extensions.

I get the following report:

```
VISUAL STUDIO CODE SETTINGS SYNC 

Download SUMMARY 

-------------------- 
GITHUB TOKEN: ***
GITHUB GIST: ***
GITHUB GIST TYPE: Secret 
 
-------------------- 
  

Files Download. 
 
extensions.json 
keybindings.json 
locale.json 
settings.json 

EXTENSIONS REMOVED : 
 
PowerShell - Version :0.7.2 
 

EXTENSIONS ADDED : 
 
No Extension needs to install. 
```

**Comment by shanalikhan** [comment]
Yes it will remove the extensions that are not synced so u need to kake a new backup when u install new extension.
Or u can turn off the auto download

**Comment by eashi** [comment]
I disabled the Auto Download feature, it works fine now. But actually this should be considered an issue; this feature should be Off by default as it produced a very unpleasant behaviour of being "locked" to what is synced before.

Thanks for the good extensions BTW 👍

**Comment by shanalikhan** [comment]
> this feature should be Off by default 
Its fixed, will be released in newer version.

By default auto download is turned off
