### ISSUE TITLE
Unable to update settings, with info 'Sync: internet not connected'

### ISSUE THREAD

**Issue by royling** [shanalikhan/code-settings-sync#106]
**Visual Studio Code Version :** [ 1.5.2 ]
**Code Sync Settings Version :** [ 2.2.6 ]
**Operating System :** [ OSX 10.11.4 ]

I am sure the connection is fine, since I can install another extension.
No error in console, but sync download/update keeps reporting the issue, see the screenshot:
<img width="265" alt="screen shot 2016-09-19 at 12 17 18 pm" src="https://cloud.githubusercontent.com/assets/1917351/18622561/a6d6ca34-7e63-11e6-889d-502b0a628446.png">

it was working fine in v2.2.5, but failed after upgrading to the latest.

**Comment by Bill-Stewart** [comment]
Same issue here.

**Comment by shanalikhan** [comment]
Yes i tried to solve the issue https://github.com/shanalikhan/code-settings-sync/issues/97
 i will test it again and update after completing the auto upload feature

**Comment by czmecho** [comment]
the same issue.

**Comment by czmecho** [comment]
Visual Studio Code Version : [ 1.5.1 ]
Code Sync Settings Version : [ 2.2.6 ]
Operating System : [ win10  1607]

**Comment by zephrxx** [comment]
Yes, same issue here. Disabling the connection check can workaround it. Waiting for the fix.

**Comment by euconectei** [comment]
**Visual Studio Code Version :** 1.5.2
**Code Sync Settings Version :** 2.2.7
**Operating System :** Win 7 Pro

**Comment by fasfsfgs** [comment]
Same here.
Visual Studio Code Version: 1.5.3
Code Sync Settings Version: 2.2.7
Operating System: Win 7 Pro

I'm also behind an enterprise proxy. VSC is configured for it tho. Not sure if it matters.

**Comment by shanalikhan** [comment]
@fasfsfgs extension is not supported for proxy so far, already issue opened at https://github.com/shanalikhan/code-settings-sync/issues/60

I have pushed an update 2.3.0 and let me know if there is any problem :)

**Comment by Bill-Stewart** [comment]
@shanalikhan - it works for me now, thanks!
