### ISSUE TITLE
OS-specific settings

### ISSUE THREAD

**Issue by evertiro** [shanalikhan/code-settings-sync#1061]
💡 **Is your feature request related to a problem? Please describe.**
I use VSCode on both Windows and Linux and have an almost identical configuration between the two. However, there are certain things that I only do in certain environments. As such, there are a few Windows-specific extensions/settings and a few Linux-specific extensionsMa/settings. Some of these throw a fit when starting VSCode on an unsupported OS or one which is missing a given executable.

💡 **Describe the solution you'd like**
I'd like to see the extensions/settings allow OS-specific settings in much the same way that keybindings do (or whatever solution works). Since _most_ of the configuration is shared, I'd rather keep it all in one gist. But, I'd like to be able to segregate out some things that don't work in certain scenarios. Allowing `extensionsMac.json`, `extensionsWin.json`, etc seems the logical way to handle this, though I'm not sure how to express that segregation to the user...

**Comment by auxves** [comment]
For settings, see [Sync Pragmas](https://github.com/shanalikhan/code-settings-sync/wiki/Sync-Pragmas)
