### ISSUE TITLE
Failing on vscode on Mac OS Catalina

### ISSUE THREAD

**Issue by pitosalas** [shanalikhan/code-settings-sync#1063]
<img width="474" alt="Screen Shot 2019-10-08 at 5 22 11 PM" src="https://user-images.githubusercontent.com/44681/66434423-89830a00-e9f0-11e9-9364-448727ae9539.png">

I just updated MacOS to Catalina. I haven't hardly changed anything. Various apps are misbehaving a little, including this one:

I uninstalled and re-installed. Lgged in with github. Got what looked like success. And then when I tried to sync I got the error above.

Everything is the same except I upgraded to Catalina. Very hard for me to tell from the error what's wrong. I suppose it's a path or similar annoying issue. But I am unable to troubleshoot.

**Comment by shanalikhan** [comment]
Can you post the console log. (Help Menu > Developer Tool)

**Comment by pitosalas** [comment]
I seem to have fixed it by uninstalling vscode and reinstalling it. Thanks.

Pito Salas
Brandeis Computer Science
Volen 134

**Comment by cerealmilkmedia** [comment]
![Screen Shot 2020-03-13 at 12 01 30 PM](https://user-images.githubusercontent.com/57355862/76638218-72f25900-6522-11ea-86f8-0c2481c02e1d.png)
