### ISSUE TITLE
Extension host terminated unexpectedly

### ISSUE THREAD

**Issue by alikhil** [shanalikhan/code-settings-sync#1065]
🐛 **Describe the bug**  
VS Code from time to time shows exception `Extension host terminated unexpectedly` when extension enabled. [Proof](https://github.com/ritwickdey/vscode-live-server/issues/250#issuecomment-480698479)

🌴 **Visual Studio Code Version :** [ 1.39 ] 
🌴 **Code Settings Sync Version :** [ 3.4.3 ] 
🌴 **Standard or Insiders :** [ Standard ] 
🌴 **Portable or Installed :** [ Installed ] 
🌴 **OSS or Official Build :** [ Oficial Build ] 
🌴 **Operating System :** [ MacOS Siera 10.12.6 ] 
🌴 **Proxy Enabled:** [ No ]

📰 **To Reproduce**
It's thing that appear from time to time.

💪 **Expected behavior**
Everything works fine and does not crash.

📺 **Console Error Log** 
<img width="656" alt="Screen Shot 2019-10-10 at 15 50 17" src="https://user-images.githubusercontent.com/7482065/66570157-ad238d00-eb75-11e9-8044-7b792f0e6c24.png">

📺  **Additional context**
[Related](https://github.com/ritwickdey/vscode-live-server/issues/250#issuecomment-480698479) comment.

**Comment by auxves** [comment]
@alikhil Can you try disabling every other extension besides Settings Sync and reproducing this? This issue was fixed a long time ago, and the comments you linked are from about 5 months ago.

**Comment by shanalikhan** [comment]
@alikhil have you tried by the steps by @arnohovhannisyan 
Let us know it there is problem else we can close this issue assuming fixed.
