### ISSUE TITLE
Is name of the gist static?

### ISSUE THREAD

**Issue by alekdavis** [shanalikhan/code-settings-sync#1068]
Does the name of the GitHub gist have to be `cloudSettings` or can I rename it to something more descriptive (e.g. `VisualStudioCodeCloudSettings`)? Thanks.

**Comment by shanalikhan** [comment]
There is no Gist Name property specified by GitHub. Gist is identified by using the Gist ID and Gist Description. You can change the Gist Description using Settings Sync Global Settings.

`cloudSettings` is just a file for Settings Sync internal use. So donot change/ rename this file.

**Comment by alekdavis** [comment]
I assume Gist ID is the GUID, but GitHub also uses the name:
![cloudSettings](https://user-images.githubusercontent.com/2113681/67110199-0481b880-f187-11e9-8f5c-1b483d8b9509.PNG)

**Comment by maomosi** [comment]
I think this may help.[How to change the name of a gist in github?](https://stackoverflow.com/questions/19896900/how-to-change-the-name-of-a-gist-in-github)

**Comment by alekdavis** [comment]
I know how to change the name of the Gist. My question was: would doing so break the extension? Given that gist ID (GUID) will remain the same.

**Comment by jerone** [comment]
~I added _another_ file called `Visual Studio Code Settings Sync Gist.md` and it looks like everything is still working.~

**Edit**: the file was removed when new settings were uploaded to the gist. This issue has to be fixed programmatically.

**Comment by Remodor** [comment]
Same problem, renaming the gist just gets reset on synchronisation..
