### ISSUE TITLE
Whitespaces before access token cause a sync fail

### ISSUE THREAD

**Issue by agostinocinelli** [shanalikhan/code-settings-sync#108]
**Visual Studio Code Version :** 1.5.2 + 1.6.0 insider
**Code Sync Settings Version :** Where can I find it?
**Operating System :** Windows 10

There's an error syncing settings from Git, due to copying and pasting the access token:
would be nice if you could trim the access token and the gist id  :)

P.S.
Thanks for your great work!

**Comment by shanalikhan** [comment]
I am already trimming the token and GIST ID.
You may see the saved token and GIST in sync settings.
What is the error you are getting.

**Comment by agostinocinelli** [comment]
I copied and pasted from another app, so i'm not 100% sure they were whitespaces! i'm sure i deeted two "blank" chars and it worked

**Comment by shanalikhan** [comment]
you pasted in settings or from the input dialog box ?

**Comment by agostinocinelli** [comment]
the input dialog box
