### ISSUE TITLE
Manual sync feature

### ISSUE THREAD

**Issue by sim4life** [shanalikhan/code-settings-sync#1082]
💡 **Is your feature request related to a problem? Please describe.**
Since VS Code Sync seems to be permanently broken: Issue #1079 #983 etc. ... can we be guided to a manual sync of extensions settings file?

💡 **Describe the solution you'd like**
Some documentation to be able to manually sync the settings using third party options like mackup, dropbox etc. would be super useful.

💡 **Additional context**

**Comment by shanalikhan** [comment]
>Some documentation to be able to manually sync the settings using third party options like mackup, dropbox etc. would be super useful.


Duplicate of #256
