### ISSUE TITLE
Custom Extension

### ISSUE THREAD

**Issue by Moraledalx** [shanalikhan/code-settings-sync#1086]
Hello,

I wrote a couple of very simple extension which are then located in the user folder of vscode. The upload/download indeed list the extention but does not seem to actually upload the files.
I suppose it's because it's not an actual marketplace extension so it cannot be downloaded from there ?

I saw the possibility to specify custom sync file, however i am wondering if it can be used across multiple machines (including multiple OS) since the absolute path of those files are likely to differ.
Could this usecase be done ?

Tx for the help.

**Comment by shanalikhan** [comment]
>  I suppose it's because it's not an actual marketplace extension so it cannot be downloaded from there.

Yes, you are right. There is already issues opened to support custom extension offline.

**Comment by shanalikhan** [comment]
Duplicate of #778

**Comment by Moraledalx** [comment]
Thank you for your reply.
