### ISSUE TITLE
How can we manually open the Welcome Screen and Settings Sync webview-panels?

### ISSUE THREAD

**Issue by schittli** [shanalikhan/code-settings-sync#1087]
Good morning
**Thank you very much** for this very useful VS Code extension!

#### code-settings-sync has two very useful webview-panels,
see the screenshots below. How can we reopen them sometime later once they've been closed?
#### It would be great if we could use commands to open the webview-panels:
`>sync Show Welcome Screen`
`>sync Show Settings Screen`

The background is that the welcome screen is not always displayed automatically and if one wants to change / validate the configuration, then both screens are perfect and very useful.

Thanks a lot!, kind regards,
Thomas

![image](https://user-images.githubusercontent.com/8282673/69476401-b42af580-0dd9-11ea-8ffd-28d51ac7b4fc.png)

![image](https://user-images.githubusercontent.com/8282673/69476403-b8571300-0dd9-11ea-86bd-9f988ff26487.png)

**Comment by shanalikhan** [comment]
#### Settings UI

You can view the Settings UI from Advance Settings. Its mentioned in readme.

https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync#settings


#### Welcome UI

It can be only opened when Settings Sync isnt configured. 


Feel free to send PR and improve README if you think we can further improve the readme.
