### ISSUE TITLE
Pick specific settings to not sync

### ISSUE THREAD

**Issue by pgsandstrom** [shanalikhan/code-settings-sync#1088]
💡 **Is your feature request related to a problem? Please describe.**
Im using the vim plugin for vscode. A setting for this plugin is the path of a neovim binary. On different computers my path to this binary differs. Thus I dont want that setting to be synced

💡 **Describe the solution you'd like**
I would like to have a textfield named something like "do not sync these settings" and there I could simply write "vim.neovimPath". And then that would be excluded from the sync.

**Comment by shanalikhan** [comment]
See [Sync Pragma](https://github.com/shanalikhan/code-settings-sync/wiki/Sync-Pragmas#ignoring-certain-settings) in detail.
