### ISSUE TITLE
Can't upload settings - even to a public gist

### ISSUE THREAD

**Issue by owennicol** [shanalikhan/code-settings-sync#109]
**Visual Studio Code Version :** [1.5.2 ]
**Code Sync Settings Version :** [ 2.2.6 ]
**Operating System :** [ OSX El Capitan ]

Hi,
It's always worked perfectly for me, and thanks very much for this awesome extension, but I'm now getting this error:

I've tried using the gist id I had previously, creating a new one with a new personal access token, and a public one, but nothing seems to work.

Thanks,

Owen

Please make sure to write the versions and console logged error picture or copied text.
```
shell.ts:428 Unexpected token /: SyntaxError: Unexpected token /
    at Object.parse (native)
    at /Users/owen.nicol/.vscode/extensions/Shan.code-settings-sync-2.2.6/out/src/extension.js:353:58
    at next (native)
    at /Users/owen.nicol/.vscode/extensions/Shan.code-settings-sync-2.2.6/out/src/extension.js:7:65
    at __awaiter (/Users/owen.nicol/.vscode/extensions/Shan.code-settings-sync-2.2.6/out/src/extension.js:3:12)
    at /Users/owen.nicol/.vscode/extensions/Shan.code-settings-sync-2.2.6/out/src/extension.js:345:32
    at process._tickCallback (internal/process/next_tick.js:103:7)e.onUnexpectedError @ shell.ts:428
threadService.ts:217 [Extension Host] Darwin
threadService.ts:217 [Extension Host] {"message":"Validation Failed","errors":[{"resource":"Gist","code":"missing_field","field":"files"}],"documentation_url":"https://developer.github.com/v3/gists/#edit-a-gist"}(anonymous function) @ threadService.ts:217
threadService.ts:217 [Extension Host] false(anonymous function) @ threadService.ts:217
messageService.ts:119 Error Logged In Console (Help menu > Toggle Developer Tools). You may open an issue using 'Sync : Open Issue' from advance setting command.e.doShow @ messageService.ts:119
threadService.ts:217 [Extension Host] lineCount: 16
threadService.ts:217 [Extension Host] lineCount: 17
2threadService.ts:217 [Extension Host] Darwin
threadService.ts:217 [Extension Host] {"message":"Validation Failed","errors":[{"resource":"Gist","code":"missing_field","field":"files"}],"documentation_url":"https://developer.github.com/v3/gists/#edit-a-gist"}(anonymous function) @ threadService.ts:217
threadService.ts:217 [Extension Host] false(anonymous function) @ threadService.ts:217
messageService.ts:119 Error Logged In Console (Help menu > Toggle Developer Tools). You may open an issue using 'Sync : Open Issue' from advance setting command.e.doShow @ messageService.ts:119
```

**Comment by shanalikhan** [comment]
I will put the log in the next update so you may show the console log that whats in your GIST post object as some token is causing this problem.
but for now,

you can check what text / file is added to your old scenario that was working. or post here the change of files text since the last working upload and update.

**Comment by owennicol** [comment]
Sorry, I can't check what was working before as I deleted the GIST to try to see if that was causing the issue

**Comment by shanalikhan** [comment]
I actually might need that delta upon which adding you faced this issue. May be you can remember the minimal settings and then add the settings by parts and see upon which part of delta this type of error id occurred so i can further figure it out :)
