### ISSUE TITLE
Functional suggestions

### ISSUE THREAD

**Issue by huangxinrui** [shanalikhan/code-settings-sync#1093]
Can I add an option to ignore a setting? Because the screen of my two computers is not the same size, the font size is not appropriate each time I synchronize, and CMD does not necessarily exist on another computer, so I may need to adjust the font size every time, or download a CMD for the first time

**Comment by shanalikhan** [comment]
See this

https://github.com/shanalikhan/code-settings-sync/wiki/Sync-Pragmas#ignoring-certain-settings
