### ISSUE TITLE
Does not work in insider version

### ISSUE THREAD

**Issue by SrTobi** [shanalikhan/code-settings-sync#11]
Since this week there is an insider version available. See [anouncement](https://blogs.msdn.microsoft.com/vscode/2016/02/01/introducing-insiders-builds/) and [download here](https://code.visualstudio.com/insiders). It is a standalone program with it's own paths.

Since a lot of paths in this extension are hardcoded. The sync does not work with the new insiders version.

**Comment by shanalikhan** [comment]
I have updated. Please Update it.
Im closing this issue. Let me know if you find any problem
