### ISSUE TITLE
Cannot read property 'close' of null

### ISSUE THREAD

**Issue by jwhipp** [shanalikhan/code-settings-sync#112]
**Visual Studio Code Version :** [ 1.5.3 ]
**Code Sync Settings Version :** [ 2.3.0 ]
**Operating System :** [ Windows 10 ]
**Occurs On:** [Download]

When I setup sync for the first time, I commonly invoke download settings which in tern prompts for git token and gist id.  Instead, I just get "Cannot read property 'close' of null".

I am not seeing any console output, not sure where I grab that.

**Comment by shanalikhan** [comment]
oh yes! i forget to add that
Fixed in 2.3.1 :).
Let me know if its not working

**Comment by jwhipp** [comment]
Confirmed fixed, thanks!
