### ISSUE TITLE
extra comma in first @sync-ignore object or array on sync

### ISSUE THREAD

**Issue by ctf0** [shanalikhan/code-settings-sync#1121]
🐛 **Describe the bug**  
the issue happens usually when the editor is reloaded while the ext is sync uploading/downloading.

- the ext adds an extra `,` to the first array/object it encounter in the settings file ex.

```jsonc
    // @sync-ignore
    "workbench.settings.useSplitJSON": false,
    // @sync-ignore
    "material-icon-theme.folders.color": "#ffffff",
    // @sync-ignore
    "workbench.colorCustomizations": {, // <<< this is added by sync
        "activityBar.border": "#00000000",
        // ...
    }
```

🌴 **Visual Studio Code Version :** [ 1.42.0 ] 
🌴 **Code Settings Sync Version :** [ 3.4.3 ] 
🌴 **Standard or Insiders :** [ insider ] 
🌴 **Portable or Installed :** [ installed ] 
🌴 **OSS or Official Build :** [ official ] 
🌴 **Operating System :** [ osx 10.14.6 ] 
🌴 **Occurs On:** [Upload / Download ]
🌴 **Proxy Enabled:** [ No ]
🌴 **Gist Id:** [ isnt it a secret gist ? ]

📰 **To Reproduce**

1. add `@sync-ignore` to an object or array in settings file
2. do a sync upload/download and reload the editor or open a new workspace
3. settings file gets the extra comma and shows an error

💪 **Expected behavior**

the `,` shouldn't be added or if the ext is doing something in the background, maybe a notification b4 editor is reloaded would be helpful.

📺 **Console Error Log** 
If applicable, add screenshots or paste the console log from developer console of VSCode (Help Menu > Developer Tool - Console Tab). 

```
Sync: Result content is not a valid JSON. Unexpected token , in JSON at position 128 {
    "workbench.settings.useSplitJSON": false,

    "material-icon-theme.folders.color": "#ffffff",

    "workbench.colorCustomizations": {,
```

📺  **Additional context**

**Comment by tblijlevens** [comment]
Can I ask why this issue was closed? I have the same problem. Is there another solution?

**Comment by ctf0** [comment]
because most of the tickets in here doesnt get answered 😢

**Comment by shanalikhan** [comment]
> because most of the tickets in here doesnt get answered 😢

Because unfortunately, i'm not actively maintaining this extension as of now. Looking forward for someone to connect and improve with me

**Comment by tblijlevens** [comment]
I see. I don't have much time (young kid and stuff), but if you can point me in the right direction I might be able to fix this issue (some day). The right direction, meaning: where can I find the functionality related to `// @sync-ignore`?
