### ISSUE TITLE
Error happened after enable auto download + upload

### ISSUE THREAD

**Issue by calvin620707** [shanalikhan/code-settings-sync#113]
**Visual Studio Code Version :** 1.5.3
**Code Sync Settings Version :** 2.3.1
**Operating System :** Windows 10 x64
**Occurs On:** Upload

I have enabled auto download and upload on my Macbook and Windows desktop. I'm pretty sure the gist access token and gist ID is correct since I re-generate the token and reset sync settings. I can use the new access token to download settings from gist but issue happened again after I enable auto download and upload. Shouldn't I enable auto upload on 2 computers?

**Console error**
keybindingsRegistry.ts:109Ctrl+Alt+ keybindings should not be used by default under Windows. Offender:  40995  for  PowerShell.ExpandAlias
threadService.ts:217[Extension Host] Spell and Grammar checker active...
threadService.ts:217[Extension Host] Default Settings
threadService.ts:217[Extension Host] Code Actons Registering for: markdown
threadService.ts:217[Extension Host] Code Actons Registering for: plaintext
4threadService.ts:217[Extension Host] Windows_NT
2threadService.ts:217[Extension Host] GIST Object - [object Object]
threadService.ts:217[Extension Host] {"message":"Server Error","documentation_url":"https://developer.github.com/v3/gists/#edit-a-gist"}(anonymous function) @ threadService.ts:217
threadService.ts:217[Extension Host] false(anonymous function) @ threadService.ts:217
messageService.ts:119Error Logged In Console (Help menu > Toggle Developer Tools). You may open an issue using 'Sync : Open Issue' from advance setting command.e.doShow @ messageService.ts:119
threadService.ts:217[Extension Host] {"message":"Server Error","documentation_url":"https://developer.github.com/v3/gists/#edit-a-gist"}(anonymous function) @ threadService.ts:217
threadService.ts:217[Extension Host] false(anonymous function) @ threadService.ts:217
messageService.ts:119Error Logged In Console (Help menu > Toggle Developer Tools). You may open an issue using 'Sync : Open Issue' from advance setting command.e.doShow @ messageService.ts:119
threadService.ts:217[Extension Host] Windows_NT

![image](https://cloud.githubusercontent.com/assets/1777081/18825502/60345374-83fb-11e6-9c08-2b14bce31c9d.png)

**Comment by jhlee8804** [comment]
+1

**Comment by calvin620707** [comment]
Is there any limitation of query times or APIs calling times in gist? I can upload the settings now.

**Comment by shanalikhan** [comment]
> For requests using Basic Authentication or OAuth, you can make up to 5,000 requests per hour.

Does this occur when you save the setting file multiple time in 5 seconds ? this error is due to GIST

**Comment by calvin620707** [comment]
It's possible since I enable auto upload on two computer within a short period. If this is GIST's limitation, should I close this issue?

**Comment by shanalikhan** [comment]
Yes, because it downloads the old GIST and change the GIST. Both computers download the older version of GIST and update to their own , first one updated first and second one failed.

**Comment by calvin620707** [comment]
Got it. Thanks for the answer~ 😄
