### ISSUE TITLE
Auto Translation Settings

### ISSUE THREAD

**Issue by omerbguclu** [shanalikhan/code-settings-sync#1132]
Hey,
My computer's local language is Turkish but I use vscode in English. Sometimes your extension giving errors while uploading downloading etc. Notifications, error messages from your extension is coming with auto translated to Turkish and I cant understand whats the problem with auto translated message.

Can you add a option to auto translate settings or just switch the language to English ?

**Comment by omerbguclu** [comment]
any progress ?

**Comment by diogo-rossi** [comment]
I have this problem too.
My local system is in portuguese. But I want to use all VS Code environment in english.

Could you add a feature to disable auto translate?

**Comment by diogo-rossi** [comment]
@omerbguclu 

I think it was discussed in this issue: #987

I solved my problem [following this help page](https://code.visualstudio.com/docs/getstarted/locales#_changing-the-display-language)

Hope it helps

**Comment by vlaci** [comment]
See also #1205 

It is not only confusing to have mixed language user interface in a single application but the translated interface is unusable. As a native Hungarian speaker I have no idea what the translated text actually means...

On a somewhat unrelated note: many labels starts with (or even ends with) the literal `Fordította:` which means `Translated (by):` I have no idea why the translation service adds this additional garbage :/

**Comment by omerbguclu** [comment]
Solved with this comment
https://github.com/shanalikhan/code-settings-sync/issues/1132#issuecomment-620264884

**Comment by setanarut** [comment]
> Solved with this comment
> [#1132 (comment)](https://github.com/shanalikhan/code-settings-sync/issues/1132#issuecomment-620264884)

@omerbguclu sorun bunu yaparak çözülüyor fakat ilk defa yükleyenler için sorun devam ediyor. bence Issue'yi tekrar aç

<img width="603" alt="cap" src="https://user-images.githubusercontent.com/36481442/92541296-46f42e00-f24e-11ea-8688-e2f2c030a342.png">
