### ISSUE TITLE
Consider using status bar messages instead of Info Boxes for errors, etc

### ISSUE THREAD

**Issue by Jakobud** [shanalikhan/code-settings-sync#114]
**Visual Studio Code Version :** 1.5.2
**Code Sync Settings Version :** latest
**Operating System :** all

Currently, this extension utilizes the showInformationBox method to report things like errors (for example when your laptop is offline and therefore a sync does not occur). You should highly consider switching over to reporting errors like this in the Status Bar in Code instead of InformationBox. If someone has their laptop offline but starts up Code, they get the offline sync error and have to manually press OK on the InformationBox to continue.

**Comment by shanalikhan** [comment]
yes i will do in next update

**Comment by shanalikhan** [comment]
I'm closing this issue.
I am now using the status bar for connectivity problems.
If you want to make some other specific errors in status bar let me know.
