### ISSUE TITLE
Error after (other) config file changes saved.

### ISSUE THREAD

**Issue by zschopper** [shanalikhan/code-settings-sync#115]
**Visual Studio Code Version :** 1.5.2
**Code Sync Settings Version :** 2.3.1
**Operating System :** Microsoft Windows - Version 6.1.7601
**Occurs On:** Upload

This error occured after I made changes in one of my settings json file.

[syncSummary.txt](https://github.com/shanalikhan/code-settings-sync/files/497670/syncSummary.txt)
[syncSettings - removed git data.json.txt](https://github.com/shanalikhan/code-settings-sync/files/497678/syncSettings.-.removed.git.data.json.txt)

![image](https://cloud.githubusercontent.com/assets/964957/18909097/944da0c0-8572-11e6-963c-8954200828a6.png)

**Comment by shanalikhan** [comment]
can you share your settings.json and the text u added that caused this problem so i may reproduce at my end to solve it.

**Comment by zschopper** [comment]
F1 > Preferences: Open User Snippets > SQL
..and I simpy add space and save sql.json file.

I attached my settings.json.

**Comment by shanalikhan** [comment]
>F1 > Preferences: Open User Snippets > SQL
>..and I simpy add space and save sql.json file.

please share the sql.json file as after adding this file extension has caused problem

**Comment by zschopper** [comment]
[sql.json.txt](https://github.com/shanalikhan/code-settings-sync/files/498696/sql.json.txt)

If I change one of my config this error occurs again.

**Comment by shanalikhan** [comment]
@zschopper can you test with 2.3.3 if this error occurs there again.
I have placed the sql.json in my settings and its working fine.

**Comment by zschopper** [comment]
![image](https://cloud.githubusercontent.com/assets/964957/19479538/87f4fa64-9547-11e6-8589-d0af616e5abc.png)

Thanks for help, but I still have problems :/

I uninstalled your plugin.
I closed VS Code
I removed syncSettings.json from my user folder
I deleted my SyncSettings gist on github.
I opened VS Code
I reinstalled your plugin (2.3.3) (I didn't touch syncSettings config file.)
I closed VS Code
I opened VS code
One update available.
I got "Sync: Settings Created." message
SyncSettings version went back to 2.3.1
I updated your plugin, and enabled it.
I closed VS Code
I opened VS code
I got "Sync: Migration to new version complete. Read Release Notes for details.." message.
SyncSettings version still was 2.3.1.

I don't know why :(

**Comment by shanalikhan** [comment]
> SyncSettings version still was 2.3.1.

can you delete all the extensions from the extensions directory ( not from vscode ) and then remove the synsettings.json file and install sync extension again and then create new GIST and perform upload action with new gist

VScode does offer such error sometimes that extension when updated doesnt appear in code rather then shows older version.

**Comment by zschopper** [comment]
I removed every package from Code, I deleted it's user folder (c:\Users\<user>\AppData\Roaming\Code).

After I reinstalled Sync and reopen Code, the version went back again :(

![image](https://cloud.githubusercontent.com/assets/964957/19486640/806f1c6c-955f-11e6-886c-b4118812b5bb.png)

**Comment by shanalikhan** [comment]
Its really a strange problem regarding Vscode that it still download the older version of extension
I suggest you to remove the code complete from the computers , the extension folder and user folder 
Then install the code version 1.6 and check the issue is gone.
i suggest you to open an issue about the problem that vscode repo and let them know.

We can work on the issue when we are sure code is working right and have latest exnteion and settings.

**Comment by zschopper** [comment]
With Code 1.6 the plugin update was successful.
Tomorrow I can make further tests (gist registration in Code, plugin reinstalls, etc.).
Until then I think you can close this ticket.

Thank you for your help, and If I can help anything don't hesitate to ask for it :)

**Comment by shanalikhan** [comment]
ok let me know if the error is still there :)
