### ISSUE TITLE
Sync pragma fails on array of objects 

### ISSUE THREAD

**Issue by arznaar** [shanalikhan/code-settings-sync#1157]
🐛 **Describe the bug**  
When downloading settings with array of objects, limited to some host with sync pragma, code-settings-sync fails to correctly uncomment an array. Check reproduction steps for example.

🌴 **Visual Studio Code Version :** [ 1.42.1 ] 
🌴 **Code Settings Sync Version :** [ 3.4.3 ] 
🌴 **Standard or Insiders :** [ standart ] 
🌴 **Portable or Installed :** [ installed ] 
🌴 **OSS or Official Build :** [ official build ] 
🌴 **Operating System :** [ Windows_NT x64 10.0.18363 ] 
🌴 **Occurs On:** [ Download ]
🌴 **Proxy Enabled:** [ No ]
🌴 **Gist Id:** [ private ]

📰 **To Reproduce**
1. Use mssql extension and set the following options in settings.json:
```
...
    // @sync host=host1 os=windows
    "mssql.connections": [
        {
            "authenticationType": "Integrated",
            "database": "",
            "password": "",
            "server": "(LocalDB)\\base1"
        },
        {
            "authenticationType": "Integrated",
            "database": "",
            "password": "",
            "server": "(LocalDB)\\base2"
        }
    ],
...
```
2. Set hostname as "**host2**"
3. Force upload settings and the force download them

Actual result:
```
    // @sync host=host1 os=windows
    // "mssql.connections": [
        // {
            // "authenticationType": "Integrated",
            // "database": "",
            // "password": "",
            // "server": "(LocalDB)\\base1"
        // },
        {
            "authenticationType": "Integrated",
            "database": "",
            "password": "",
            "server": "(LocalDB)\\base2"
        }
    ],
```

💪 **Expected behavior**
```
    // @sync host=host1 os=windows
    // "mssql.connections": [
        // {
            // "authenticationType": "Integrated",
            // "database": "",
            // "password": "",
            // "server": "(LocalDB)\\base1"
        // },
        // {
            // "authenticationType": "Integrated",
            // "database": "",
            // "password": "",
            // "server": "(LocalDB)\\base2"
        // },
    // ],
```

📺 **Console Error Log** 
Errors: 
- `Result content is not a valid JSON...` with my current settings.json
- 
```
Error: Unable to write into user settings. Please open the user settings to correct errors/warnings in it and try again.    at k.reject (file:///C:/Users/arzna/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:4735:465)    at file:///C:/Users/arzna/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:4739:349    at async k.doWriteConfiguration (file:///C:/Users/arzna/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:4732:711)
```

**Comment by arznaar** [comment]
Something like https://github.com/shanalikhan/code-settings-sync/issues/1062 would solve this and would be more predictable

**Comment by arznaar** [comment]
Warning: Experimenting with this for some reason will create new gists. As far as i understand it's because of invalid json. Maybe it would be good to look into it too.

**Comment by jvalecillos** [comment]
I can confirm the behavior, but in my case it behaves as follows:

If I have this in my config:

```json
{
  // @sync-ignore
  "my_array_key": [
    {
      "key": "value"
    }
  ],
  "other_key": "value"
}
```

The following is synced in the gist:

```json
{
  ],
  "other_key": "value"
}
```

**Please notice the closing square bracket and the comma.**

I'm using v3.4.3 of the extension.
```
Version: 1.43.0
Commit: 78a4c91400152c0f27ba4d363eb56d2835f9903a
Date: 2020-03-09T19:44:52.965Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.4.13-arch1-1
```

**Comment by arznaar** [comment]
I'll close this as I don't use it anymore, don't see any activity in repo and want to cleanup my issues list. Please don't reopen it and just create a copy if needed
