### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by yazver** [shanalikhan/code-settings-sync#116]
**Visual Studio Code Version :** [ 1.5.3 ]
**Code Sync Settings Version :** [ 2.3.1 ]
**Operating System :** [ Windows 10 64 bit ]
**Occurs On:** [Upload]

Please make sure to write the versions and console logged error picture or copied text.

**Comment by shanalikhan** [comment]
please explain the problem.
Iam closing this issue, feel free to contact :)
