### ISSUE TITLE
No scroll in settings page

### ISSUE THREAD

**Issue by AndreyChursin** [shanalikhan/code-settings-sync#1169]
I could not scroll settings page 
<img width="1680" alt="Снимок экрана 2020-03-18 в 23 46 21" src="https://user-images.githubusercontent.com/11028058/77006037-d2ad9180-6972-11ea-9c27-35e8a0319684.png">

**Comment by jerone** [comment]
Duplicate https://github.com/shanalikhan/code-settings-sync/issues/1114
