### ISSUE TITLE
only local extensions are synced in wsl2

### ISSUE THREAD

**Issue by tianxiayu007** [shanalikhan/code-settings-sync#1182]
🐛 **Describe the bug**  
extensions are not all synced in wsl2, does any body meet this?
below picture  shows the extensions i installed,but turn to github, i find that only local extensions
are synced..

![批注 2020-04-11 192936](https://user-images.githubusercontent.com/3746672/79042706-6ef24d80-7c2c-11ea-9406-c52d5d4037a0.png)

[https://gist.github.com/lubocheng/ea4f9b1dcabd5e60edea334aeb9984c3/revisions](url)
from this link of config revisions we can see that, remote extensions are missing..
![image](https://user-images.githubusercontent.com/3746672/79042740-ac56db00-7c2c-11ea-8590-0019d2efdd49.png)

🌴 **Visual Studio Code Version :** [ v1.44.0] 
🌴 **Code Settings Sync Version :** [ v3.4.3] 
🌴 **Standard or Insiders :** [ Standard ] 
🌴 **Portable or Installed :** [ Installed ] 
🌴 **OSS or Official Build :** [ Official Build] 
🌴 **Operating System :** [ Win10 2004] 
🌴 **Occurs On:** [Upload]
🌴 **Proxy Enabled:** [ No ]
🌴 **Gist Id:** [ ea4f9b1dcabd5e60edea334aeb9984c3]

💪 **Expected behavior**
sync all extensions correctly

**Comment by tianxiayu007** [comment]
may be i could close this..
it's strange that when i update vs code to version that support wsl2,my extensions are split to local and
remote, which cause sync unexpectedly
i could reinstall extensions to fix it

**Comment by iamdevlinph** [comment]
This is still a valid issue. The extensions in the "wsl:ubuntu" are not synced to the gist. In fact, they are removed since they are no longer in the "local"
