### ISSUE TITLE
[GitHub API] Deprecation notice for authentication

### ISSUE THREAD

**Issue by kulbhushanchand** [shanalikhan/code-settings-sync#1185]
Hi, recently GitHub is sent a mail about change in authentication method. 

> Please use the Authorization HTTP header instead, as using the `access_token` query parameter is deprecated. If this token is being used by an app you don't have control over, be aware that it may stop working as a result of this deprecation.

[Official post by GitHub](https://developer.github.com/changes/2020-02-10-deprecating-auth-through-query-param/)

We still have time till 30th Sept, 2020, to make relevant changes.

**Comment by TBBle** [comment]
VS Code now has a built-in GitHub authenticator which is exposed by the [Authentication Provider API](https://github.com/microsoft/vscode/issues/88309), which would remove this code from this extension.

**Comment by Gozde74** [comment]
B
