### ISSUE TITLE
Is ok to store OAuth App clientId and clientSecret in a extension

### ISSUE THREAD

**Issue by ftzi** [shanalikhan/code-settings-sync#1195]
Hello. I am studying about the GitHub OAuth, and as I knew that Settings Sync uses it, I found out that this extension stores the clientId and the clientSecret in its code. Is it safe? Couldn't people get users data by using it?

This may be a little Off-Topic, but, may also increase (or decrease lol) people trust in this extension, besides answering my question hehe

I was going to post this in Slack, but there isn't too much movement there.

**Comment by shanalikhan** [comment]
Do you have any idea then let me know and send PR. I will add my values or config over there to release.

**Comment by ftzi** [comment]
Hey there! I ended up using Vercel to safely hold those values in my extension (GitHub Repository Manager). However, as soon I have free time, I will move to the new VsCode GitHub integrated auth, maybe in a month or two.

I will base my code in this one https://github.com/microsoft/vscode-pull-request-github/blob/5d009c2623c6060a7453a53c4ef3c57004c9ef00/src/github/credentials.ts , that maybe was the first extension that used this new functionality (as it is an extension from Microsoft).

If I do it before you, I will happily share my code here :)
