### ISSUE TITLE
Republish with new vsce version

### ISSUE THREAD

**Issue by SrTobi** [shanalikhan/code-settings-sync#12]
The old version of `vsce` (the publishing tool) was not very advanced in the way it ignored devDependency node_modules. Because of that the current published `code-settings-sync` extension contains a lot of unused packages: __128__ node dependency packages but only __10__ are actually used! Since then we improved this (see https://github.com/Microsoft/vscode-vsce/pull/58) and with the new version [v1.1.0](https://github.com/Microsoft/vscode-vsce/releases/tag/v1.1.0) only productive dependencies are uploaded.

Just don't forget to update `vsce` before publishing the next time :smile:

**Comment by shanalikhan** [comment]
Thank you. I have updated it.

Yes the size has decreased from 2MB to just 250KB. 
Great !
