### ISSUE TITLE
Sync should ignore proxy settings

### ISSUE THREAD

**Issue by the-ress** [shanalikhan/code-settings-sync#120]
Proxy configuration is typically specific for the machine so I think `http.proxy*` settings should be ignored when synchronizing.

**Comment by shanalikhan** [comment]
extension is not supported proxy settings for now, i will soon connect it with http.proxy* settings.
There is already issue opened for proxy related discussion [#60](https://github.com/shanalikhan/code-settings-sync/issues/60). Closing this issue please comment there.
