### ISSUE TITLE
Sync to simple file

### ISSUE THREAD

**Issue by EpeR1** [shanalikhan/code-settings-sync#1206]
It would be a nice feature if we can choose a simple file to sync destination+source without/instead of Github.
This file can be easily shared with GoogleDirve, Dropbox, Nextcloud, FTP, or via e-mail.

Best Regards,
Eper

**Comment by rajeshpal007** [comment]
This can be really good feature!

**Comment by shanalikhan** [comment]
Duplicate of #256
