### ISSUE TITLE
Configuration Page Does Not Open Automatically - No Manual Way to Access Config

### ISSUE THREAD

**Issue by KraigHamady-VA** [shanalikhan/code-settings-sync#1214]
🐛 **Describe the bug**  
Configuration page does not load on startup or opening of the extension.  There is not a documented way to open the config page. Since this is a new install of VSCode, I cannot any gists I had set up previously since I cannot access the config page.

🌴 **Visual Studio Code Version :** 1.45.1
🌴 **Code Settings Sync Version :** 3.43
🌴 **Standard or Insiders :** Standard 
🌴 **Portable or Installed :** Installed 
🌴 **OSS or Official Build :** Official 
🌴 **Operating System :** win10 
🌴 **Occurs On:** Help Configuring ]
🌴 **Proxy Enabled:** No
🌴 **Gist Id:** N/A

**Comment by KraigHamady-VA** [comment]
Note:  Looks like you have to uninstall and then fully close the VS code instance.  Reloading the window will not trigger the config page. 

It would be nice to have the config page accessible from the command palette.

**Comment by NilsJPWerner** [comment]
I think this should remain open. I had previously uninstalled the app and then reinstalled it. I had to reset the sync settings and then restart vscode to see the startup page.
