### ISSUE TITLE
Download is very dangerous

### ISSUE THREAD

**Issue by atvorch** [shanalikhan/code-settings-sync#1218]
I just installed your extension.
Wanted to share settings from my office computer to my home PC since I work remotely on quarantine.
Following the instructions, I pressed Shift + alt + D trying to know what does it do ("Download Key" says nothing for me). And extension viped all the settings on me office PC without any warnings or confirmations. It’s very very wrooong, you need to ask for confirmation. The most interesting thing is that there is a warning on the update ...
Very, very disappointed.

Who had the idea to erase the settings from git without asking for confirmation ....

Please add the confirmation, i just lost 2 years config :(

**Comment by rajeshpal007** [comment]
> I just installed your extension.
> Wanted to share settings from my office computer to my home PC since I work remotely on quarantine.
> Following the instructions, I pressed Shift + alt + D trying to know what does it do ("Download Key" says nothing for me). And extension viped all the settings on me office PC without any warnings or confirmations. It’s very very wrooong, you need to ask for confirmation. The most interesting thing is that there is a warning on the update ...
> Very, very disappointed.
> 
> Who had the idea to erase the settings from git without asking for confirmation ....
> 
> Please add the confirmation, i just lost 2 years config :(

**Share logs from VS CODE. This will help.**
