### ISSUE TITLE
Publish to Open VSX

### ISSUE THREAD

**Issue by zettlrobert** [shanalikhan/code-settings-sync#1219]
💡 **Is your feature request related to a problem? Please describe.**
Wanted to clean my VsCodium installation and get a few unnecessary extensions out.
As they have there own extension regsitry now, your extension is unfortunately not available anymore.
It is really easy to publish though. (https://www.gitpod.io/blog/open-vsx/)

💡 **Describe the solution you'd like**
You either puplish it yourself or i will look into creating a PR to automatically integrate it in there store

Feel free to message me

**Comment by TBBle** [comment]
Dupe of #1217?

**Comment by zettlrobert** [comment]
@TBBle yes, seems like it. :)

**Comment by shanalikhan** [comment]
Duplicate of #1217

Open for PR.
