### ISSUE TITLE
autoUpload not working as expected

### ISSUE THREAD

**Issue by DavidBabel** [shanalikhan/code-settings-sync#122]
**Visual Studio Code Version :** [ 1.6.1 ]
**Code Sync Settings Version :** [ 2.3.3 ]
**Operating System :** [ windows 7 / MacOs Sierra ]
**Occurs On:** [Upload]

Hey ! I enjoy a lot this plugin, but i'm not sure to understand the way certains options work.
i have this config file : 

```
{
    "Token": "working token",
    "Gist": "working gist",
    "lastUpload": "2016-10-22T21:26:22.519Z",
    "firstTime": true,
    "autoDownload": true,
    "autoUpload": true,
    "allowUpload": true,
    "lastDownload": "2016-10-21T16:10:51.186Z",
    "Version": 233,
    "showSummary": true,
    "publicGist": false,
    "forceDownload": false,
    "showLog": true,
    "openLinks": false
}
```

But when i change thing on my extensions or configs, nothing seems to "auto upload", i have to do it manually.

Other "issue", the "download feature, don't restore theme and theme icons. Not a big deal, but still a non expected behaviour.

Thanks for this amazing project anyway

**Comment by shanalikhan** [comment]
> download feature, don't restore theme and theme icons. Not a big deal, but still a non expected behaviour.

There is no way in API to set icons or themes

> when i change thing on my extensions or configs,

Only config change will hit auto upload , new extension wont hit it as for now, i will add this one also in future updates.

Have you tried checked the developer console if there is any error logged when you change the vs code settings and it doesnt hit.

**Comment by DavidBabel** [comment]
Hey, thanks for your reply and for the infos.

Yes i tried with the console and it seems it's not triggered at all.
I supposed you talk about de user "settings.json", but whatever i edit inside this file, it does not fire the upload.

Anyway, i did not specified that i use vscode in french.

**Comment by shanalikhan** [comment]
Is it triggering auto upload now, as i see your second issue regarding upload in loop. ?
autoUpload when set to true , vs code needs to be restarted in order to allow that change

**Comment by vietduc01100001** [comment]
I'm having the same issue. Whenever I change my settings it doesn't trigger Auto Upload. I checked the Developer Console while I changed settings, it doesn't log out anything.

> OS: **Windows 10 Pro (1809)**
> Visual Studio Code: **1.31.1**
> Code Settings Sync: **3.2.5**
