### ISSUE TITLE
Partial sync of settings

### ISSUE THREAD

**Issue by petrnymsa** [shanalikhan/code-settings-sync#1224]
On one of my machine, I have different default terminal shell, on the other machines this shell is not available. Is there any way to exclude this setting from syncing? 

I am talking specifically about `settings.json` and this part
```
"terminal.integrated.shell.windows": ....
```

Thanks for clarification

**Comment by shanalikhan** [comment]
https://github.com/shanalikhan/code-settings-sync/wiki/Sync-Pragmas#ignoring-certain-settings
