### ISSUE TITLE
Thoughts on upcoming native support in VS Code?

### ISSUE THREAD

**Issue by anishkny** [shanalikhan/code-settings-sync#1238]
Looks like VS Code is planning to support settings sync **natively** - see [June 2020 Update](https://code.visualstudio.com/updates/v1_47#_settings-sync) and https://github.com/microsoft/vscode/issues/2743

What does this mean for the future of this plugin? @shanalikhan @arnohovhannisyan

**Comment by shanalikhan** [comment]
Duplicate of #1188
