### ISSUE TITLE
Does this extension support multiple profiles regarding different systems?

### ISSUE THREAD

**Issue by fengyuentau** [shanalikhan/code-settings-sync#1240]
I work across different systems: Windows 10 (desktop), MacOS (mobile), Linux (server).
So I would like to have 3 different profiles to 3 different systems, and I don't want some system-specific extensions to be installed in a system which it does not support, such as the extension `Remote - WSL` specific to the Windows system.
I know that I can ignore some extensions to avoid them being downloaded, but this is kind of annoying every time I install a new system-specific extension.

**Comment by andrey6498** [comment]
Thats would be good. But concept needs to be extended to multiple workspace profiles(examples: another os or for home & work pc's separate presets, etc), so you will be able to bind current instance to a specific profile.

**Comment by andrey6498** [comment]
But probably vscode itself will add such feature faster(it is already planned).

**Comment by shanalikhan** [comment]
I'm open for PR.

**Comment by fengyuentau** [comment]
> I'm open for PR.

Actually I have an easy idea, which is adding a function to automatically filter out extensions which does not support the current system when syncing. I haven't check whether every extension page contains such information, but if so, it should not be hard to implement. Unfortunately, I don't have time for the implementation at this time.

**Comment by cyberbiont** [comment]
@fengyuentau I wrote an extension, which allows you to use different profiles and it works with Settings Sync.,
Give it a try
[vscode-profiles](https://marketplace.visualstudio.com/items?itemName=cyberbiont.vscode-profiles )

**Comment by fengyuentau** [comment]
@cyberbiont Thanks for you great work. I would like to try but I have switched to the official syncing just by logging in my Microsoft account in vscode.
