### ISSUE TITLE
Stuck in infinite upload loop

### ISSUE THREAD

**Issue by DavidBabel** [shanalikhan/code-settings-sync#125]
Visual Studio Code Version : [ 1.6.1 ]
Code Sync Settings Version : [ 2.3.3 ]
Operating System : [ MacOs Sierra ]
Occurs On: [Launch VSCode]

Hey, sorry it's me again :(

As you can see on my gist (i put it in public), i was stuck on auto upload loop when launching my VScode on my work computer this morning (look at revisions) : 
https://gist.github.com/DavidBabel/4d3ee20908324edd0c94567083c6d390

This behaviour completly wipe my default config and make vscode unusable since i don't change the property "showlog" to false

Here is my config file :

```
{  
   "Token":"valid token",
   "Gist":"4d3ee20908324edd0c94567083c6d390",
   "lastUpload":"2016-10-24T08:51:52.815Z",
   "firstTime":true,
   "autoDownload":true,
   "autoUpload":true,
   "allowUpload":true,
   "lastDownload":"2016-10-24T08:50:52.406Z",
   "Version":233,
   "showSummary":true,
   "publicGist":false,
   "forceDownload":false,
   "showLog":false,
   "openLinks":false
}
```

If i have any way to give you a hand for finding why this issue occurs, let me know how.

**Comment by shanalikhan** [comment]
Can you check your workspaceStorage folder content ? does that change everytime upload hits ?

>  "showlog" 
has no functionality for now , i will add it to show the logs in console for users who wants to get logs in console.

**Comment by DavidBabel** [comment]
Do you mean "Library/Application Support/Code/User/" folder ? (i'm a mac user)

ref: https://code.visualstudio.com/Docs/customization/userandworkspace#_settings-file-locations

for the moment it did not append again

**Comment by shanalikhan** [comment]
i have tried to fix it, will publish the new version soon

**Comment by shanalikhan** [comment]
Can you check with new version 2.3.5 and let me know

**Comment by shanalikhan** [comment]
@andreagrandi was this update be able to resolve the problem ?

**Comment by andreagrandi** [comment]
@shanalikhan no :(
it's stuck in a loop and I can't even deactivate auto upload because whenever I try to access the Sync settings, the popup disappears because of the sync summary.

**Comment by shanalikhan** [comment]
@andreagrandi 
Is there any other extension you have installed that interacts with Code "User" folder ?
can you show me your the User Folder? May be a picture , and your snippets folder.

**Comment by andreagrandi** [comment]
@shanalikhan how do I access/show the "User" folder?

**Comment by shanalikhan** [comment]
The path for user folder is for me in Windows 10 is : C:\Users\shana\AppData\Roaming\Code\User

It contains settings.json , keybindings.json and snippets you add in code

**Comment by andreagrandi** [comment]
@shanalikhan if you mean the settings.json etc... they are accessible from Code --> Preferences --> User Settings, under OSX. Do you want me to copy paste the settings somewhere?

**Comment by andreagrandi** [comment]
@shanalikhan is this what you want https://www.dropbox.com/s/zw9y4zqmjqyesw5/Screenshot%202016-10-31%2019.57.02.png?dl=0 ?

**Comment by shanalikhan** [comment]
yes, can you make backup of all the contents in "User" Folder and delete all the files and folders in Code.
and then start a code and let me know which file is added in user folder.

I dont have OSX actually so i might not be to generate from my end, you may help me in order to solve the problem. Following are steps so i can make a judgement.

1. If nothing add, try adding settings.json from vs code and check any other files added on it.
2. Do this with keybinding.json , launch and local one by one and check other any files are created in the User folder. ( u need to add these files from vscode , mean copy those content and paste from vs code settings.json )
3. When does DS_Store file is created in user folder and when it updates.
4. What is in your both vsicons like files ?

**Comment by andreagrandi** [comment]
Hi @shanalikhan I've been quick enough to disable the AutoUpload feature and it stopped the infinite loop. Apart from this, I'm not understanding much from your instructions and I don't know exactly what to do.

1) "try adding settings.json from ..." what does it mean? Adding where?
2) "Do this with keybinding.json , launch and local one by one and check other any files are created in the User folder." - what does it mean? What do I have to do with keybindings.json ?
3) How are the vsicons relates to this bug?

Thanks

**Comment by shanalikhan** [comment]
After making backuyp and removing all the files in the user folder.
Extension is constantly listensing the "user folder" on any folder or files is changed , it runs the upload instrruction so you need to check which file is changing again and again making it hitting upload again and again.

> 1) "try adding settings.json from ..." 
try adding the vscode settings from the editor

> 2) "Do this with keybinding.json , launch and local one by one and check other any files are created in the User folder." - what does it mean? What do I have to do with keybindings.json ?
> 3) How are the vsicons relates to this bug?

Because its in the user folder , i suspect your icons file is changing again and again also DS_Store file is changing again and again in the user folder causing extension to hit upload in loop.

**Comment by andreagrandi** [comment]
Ohhhhh now I start to understand what you meant! :)
Basically, your extension watches for changes and if there are it uploads them.
My DS_Store is being updated and it counts as change... so the extension is triggered. Correct?

**Comment by shanalikhan** [comment]
yes if thats is the only one than i can add this file in exception
can you tell me what is DS_Store, as i dont find this in my windows :) and when it updates ?
What is complete file name for DS_Store ?

**Comment by andreagrandi** [comment]
@shanalikhan .DS_Store is a Mac specific file, created and updated automatically by the operating system https://en.wikipedia.org/wiki/.DS_Store
When you want to exclude it from git, you just put .DS_Store in your .gitignore, for example. I hope it helps.

**Comment by shanalikhan** [comment]
so you sure that only .DS_Store file in updating other than that, no file is updating.

Thanks, will push a newer version solving this isssue and post here.

**Comment by andreagrandi** [comment]
As far as I know, the .DS_Store is the only file that is updated automatically by OSX. I should check the time/date of the other files, but 99,999% is that one.

**Comment by shanalikhan** [comment]
@andreagrandi and @DavidBabel can you test again

i have pushed the version 2.3.6 to solving this issue. if it doesnt solve than let me know about the console log , which will tell you path upon which file its hitting upload.

**Comment by andreagrandi** [comment]
@shanalikhan hi! I've just installed the new version, I've re-enabled the auto upload and.... it's not stuck in a loop anymore! Thanks!!! :)

I've just a quick (slightly unrelated) question: if I want to setup this addon on a new computer, where can I recover my GitHub token and the gist id?

Also the instructions you provide in the readme seem to cover only the case when you're setting up a new account from scratch.. am I wrong?

**Comment by DavidBabel** [comment]
@shanalikhan good for me too.

Good job

**Comment by shanalikhan** [comment]
@a

**Comment by shanalikhan** [comment]
@a

**Comment by shanalikhan** [comment]
@andreagrandi u need to save the token that is generated while adding in first PC, then the GIST ID is generated, u need to copy that GIST ID and insert that token and GIST ID when hitting download settings on the second computer.

U can get both settings when you open the extension settings from advanced option menu other way is when the summary generates both shows in the page

**Comment by andreagrandi** [comment]
@shanalikhan hi, I'm sorry but I spoke too soon :(
I just triggered the Sync --> Upload settings and now it's back to infinite loop.
I didn't enable the auto upload I just wanted to manually upload them and instead the auto upload has been triggered.

**Comment by andreagrandi** [comment]
@shanalikhan also, if I disable auto upload and then I manually try to upload settings, auto-upload is enabled back again. Basically I can't sync-up my settings without endind in a infinite loop.
How can I collect more informations? Do you have a way to enable and collect logs in your extension?

**Comment by shanalikhan** [comment]
U can open console and see upon which file it hitting auto upload in text.

**Comment by andreagrandi** [comment]
@shanalikhan apologise for my newwbieness, but... how do I open the console? Do you mean the "Debug Console" under the View menu?

**Comment by shanalikhan** [comment]
Help > Toogle Developer Tools.

Please take time and read about VS Code in details :)

**Comment by andreagrandi** [comment]
Ok this is what I see in console:

![screenshot 2016-11-05 16 21 46](https://cloud.githubusercontent.com/assets/636391/20031739/3b2b003a-a374-11e6-8e49-84154ccedd17.png)

p.s: about the "take time to read about VS Code etc...", the point is that VSCode users are not supposed to know/learn all the VSCode internals, like an extension developer is supposed to do. I'm willing to help, triaging, debugging etc... but I'm still a Python/Django/Golang developer, I don't know how VSCode works.

**Comment by andreagrandi** [comment]
is it possible that auto-sync is triggered every time the summary is generated? In this case I think you should ignore that file just like you ignored .DS_Store

**Comment by shanalikhan** [comment]
I have ignored that file already but i think for your OS its not working right, as i can test for Windows.

I have applied the required checks in the file, Will release the next build when other issues get solved also that are opened, most probably after week.
Will let you know till then.

Feel free to report any other issues or ideas.

**Comment by DavidBabel** [comment]
Maybe it's bullshit, but the file "syncSummary.txt" is created in the same directory as all others options files. Any chance it trigger the loop ?

**Comment by shanalikhan** [comment]
>Maybe it's bullshit, but the file "syncSummary.txt" is created in the same directory as all others options files. Any chance it trigger the loop ?
Yes extension is watching all the files.

I have published newer version @andreagrandi 2.3.7. Let me know if solve the problem

**Comment by andreagrandi** [comment]
@shanalikhan hi, I've just tried it on my work MacBook and it seems to work fine. I've also tried to manually upload settings, to verify if the loop was triggered and it wasn't. I will test on my home MacBook too this evening and I will let you know.

**Comment by andreagrandi** [comment]
@shanalikhan I've tried the 2.3.7 on my MacBook at home and it behaves well, just like on my office MacBook. If you are not in a rush to close this issue I would like to test it on Linux too at this point, and tell you if it works there as well.

**Comment by shanalikhan** [comment]
@andreagrandi No Rush! 
Take Your Time :)
