### ISSUE TITLE
Extension not updating

### ISSUE THREAD

**Issue by npenin** [shanalikhan/code-settings-sync#127]
**Visual Studio Code Version :** 1.5.0-insider
**Code Sync Settings Version :** 2.3.1
**Operating System :** Windows 7
**Occurs On:** Update

VScode keep telling me the extension can be updated, but I am stuck to extension 2.3.1, whereas version 2.3.5 seems to be available

**Comment by shanalikhan** [comment]
Try updating vs code to 1.6+ version and let me know.

**Comment by npenin** [comment]
it worked, thanks
