### ISSUE TITLE
Stuck when not found extention

### ISSUE THREAD

**Issue by talktokim** [shanalikhan/code-settings-sync#1276]
Issue Type: <b>Bug</b>

I am using VSCode at local with extension <b>steoates.autoimport</b> and I was sync my setting before I get its from vscode server. At vscode server, it not found extension <b>steoates.autoimport</b>  and stuck forever

Extension version: 3.4.3
VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz (4 x 3000)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.90GB (2.38GB free)|
|Process Argv|--crash-reporter-id ab8330f8-ec92-4db8-a481-11c73def977e|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by maestrow** [comment]
Why this is closed without any explanation? I'm facing with the same issue. If some extension not found vscode-sync doens't have to just terminate.

**Comment by toremato** [comment]
Bumping. Same issue. Though I don't know why it can't find the extension in the first place. Anyways this issue is disabling me from downloading my settings on new VSCode instance :(
