### ISSUE TITLE
download shutdown when installing a missing extension

### ISSUE THREAD

**Issue by luciouskami** [shanalikhan/code-settings-sync#1277]
Issue Type: <b>Bug</b>

1.Upload your settings include "ms-python.anaconda-extension-pack"
2. Clear Vscode cache,and Uninstall it,ReInstall vscode,Insall Settings sync.
3.Login and Download.
4.It shows
```log
  ERR 找不到扩展“ms-python.anaconda-extension-pack”。: Error: 找不到扩展“ms-python.anaconda-extension-pack”。
    at handler (file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:7798:303)

console.ts:137 [Extension Host] Error: Error: Error: 找不到扩展“ms-python.anaconda-extension-pack”。	at c:\Users\Administrator\.vscode-insiders\extensions\shan.code-settings-sync-3.4.3\out\extension.js:290:22293	at c:\Users\Administrator\.vscode-insiders\extensions\shan.code-settings-sync-3.4.3\out\extension.js:290:11611	at Object.throw (c:\Users\Administrator\.vscode-insiders\extensions\shan.code-settings-sync-3.4.3\out\extension.js:290:11716)	at s (c:\Users\Administrator\.vscode-insiders\extensions\shan.code-settings-sync-3.4.3\out\extension.js:290:10513)	at runMicrotasks (<anonymous>)	at processTicksAndRejections (internal/process/task_queues.js:97:5) (at Function.e.LogException (c:\Users\Administrator\.vscode-insiders\extensions\shan.code-settings-sync-3.4.3\out\extension.js:74:5878))
```

Extension version: 3.4.3
VS Code version: Code - Insiders 1.53.0-insider (4fe3f75c6d3d88a19c47f029524172303f1a1a82, 2021-01-06T15:36:33.674Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4700HQ CPU @ 2.40GHz (8 x 2394)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (10.04GB free)|
|Process Argv|--crash-reporter-id 84ace5d5-2f38-4aaa-a597-a6035141502f|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221882
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30208929
wsl2prompt:30219162
pythonvsdeb440:30224570
unusedprompt:30219164
folderexplorer:30219166
openfilemenu:30219168
pythonvsded773:30223139
core-portspanel:30233467

```

</details>

**Comment by nakawankuma** [comment]
when deleted package that shutdown sync process.
I think skip deleted package to the installation.

**Comment by luciouskami** [comment]
> when deleted package that shutdown sync process.
> I think skip deleted package to the installation.

I've deleted the missing package,it works.
