### ISSUE TITLE
Download is not working

### ISSUE THREAD

**Issue by mseld** [shanalikhan/code-settings-sync#128]
**Visual Studio Code Version :** [ 1.6 ]
**Code Sync Settings Version :** [ 2.3.5  ]
**Operating System :** [ 10.0]
**Occurs On:** [Upload / Download]

**Comment by shanalikhan** [comment]
any exception ? provide the steps.

**Comment by mseld** [comment]
Press Shift + Alt + D
Enter the github account and click enter.
Enter Your GIST ID  and click enter.
vs code display error message that 

BTW i solve my issue by replacing [**syncSettings.json**] file
that exist in [%appdata%\code\user\syncSettings.json](url)
