### ISSUE TITLE
Sync: Error Logged... "validating: Corrupt ZIP"

### ISSUE THREAD

**Issue by FunctionDJ** [shanalikhan/code-settings-sync#1284]
🐛 **Describe the bug**  
When i start VSCode / try to download my settings, i get a popup:
![image](https://user-images.githubusercontent.com/34871211/107203030-2bf33900-69fb-11eb-8c34-e13d92e970d4.png)

(See further down for console views)

This error seems to halt the sync process, since my settings from the Gist are not applied, and only about 2 extensions were installed and not the rest.

🌴 **Visual Studio Code Version :** 1.53.0 (system setup)
🌴 **Code Settings Sync Version :** 3.4.3
🌴 **Standard or Insiders :** standard
🌴 **Portable or Installed :** installed
🌴 **OSS or Official Build :** official build (using `choco install vscode`) 
🌴 **Operating System :** Windows 10 x64 Version 10.0.19042 Build 19042
🌴 **Occurs On:** Download
🌴 **Proxy Enabled:** No
🌴 **Gist Id:** 81eee5ebf7a4ecebfae4b24152a38f2a

📰 **To Reproduce**
1. Use my gist
2. Attempt download

💪 **Expected behavior**
A normal sync (download) of the settings and extensions.

📺 **Console Error Log** 
When i open the DevTools i see this:
![image](https://user-images.githubusercontent.com/34871211/107203020-27c71b80-69fb-11eb-860f-89d38f03defc.png)

The extensions output shows this and doesn't change beyond this point:
![image](https://user-images.githubusercontent.com/34871211/107203067-3b728200-69fb-11eb-99ff-008786bfd283.png)

**Comment by shanalikhan** [comment]
PR is welcome

**Comment by FunctionDJ** [comment]
> PR is welcome

I would make a PR if i knew what the issue was 😅

**Comment by FunctionDJ** [comment]
Manually removing the java extension from my `extensions.json` in the Gist solved the issue.
