### ISSUE TITLE
Settings that are local-only?

### ISSUE THREAD

**Issue by peterjuras** [shanalikhan/code-settings-sync#131]
Have you thought about having a feature to store settings that are specific to one machine and merge them into the user settings after a download / remove them from the uploaded settings before upload?

The PHP user extension for example stores the path to the executable. This can be in different places and completely different paths for different platforms.

**Comment by shanalikhan** [comment]
May be you can give a use case for my extension so i can understand better :) about which senario you need

**Comment by shanalikhan** [comment]
May be you can give a use case for my extension so i can understand better :) about which senario you need

**Comment by peterjuras** [comment]
OK I'll try =)

Your sync settings extension uses a GitHub token to access the gist. This token should be unique to a PC. Therefore, there should be a local only space - which is not synchronized - but can still be accessed by VSCode and extensions via user settings.

**Comment by shanalikhan** [comment]
U meant to say that extension own settings needs to be syncronized between all computers ?

**Comment by peterjuras** [comment]
No, maybe a short example could help:

The PHP extension needs access to the executable. You have two computers:

- A Mac, where PHP is in /usr/local/bin/PHP
- A Windows PC, where PHP is in C:/Users/some user/PHP/bin/PHP.exe

The extension stores the path in the user settings. How would you sync them now?

**Comment by shanalikhan** [comment]
Yes that is real example.

You can either open a issue in that extension to provide different settings for path in settings.json like windowsPath and macPath settings seperatly so when this extension downloads and uploads that settings.json you always have all the paths.
