### ISSUE TITLE
access token 

### ISSUE THREAD

**Issue by MrYZhou** [shanalikhan/code-settings-sync#1315]
error:
Must specify access token via Authorization header. https://developer.github.com/changes/2020-02-10-deprecating-auth-through-query-param

question:
How do I carry an access token over the HTTP header

answer:  ?

**Comment by Youpiiiii** [comment]
Did you find a solution ?

**Comment by MrYZhou** [comment]
> Did you find a solution ?
1. go to settings->applications->authorized oauth apps ,then generate a gist id
2. config the sync setting plugin key "sync.gist" with that id

**Comment by Youpiiiii** [comment]
On my side it was just necessary to update vscode, but thanks MrYZhou for your quick response
