### ISSUE TITLE
Visual Studio Code Settings Sync could not generate GIST key to upload setting to Github

### ISSUE THREAD

**Issue by hieutranagi47** [shanalikhan/code-settings-sync#133]
**Visual Studio Code Version :** [ 1.7.1 ]
**Code Sync Settings Version :** [ 2.3.6]
**Operating System :** [ Windows 10 - last update ]
**Occurs On:** [Upload / Download]
**Proxy Enabled:** [ No ] there is no proxy

extensionHost.ts:255 [Extension Host] {"message":"Not Found","documentation_url":"https://developer.github.com/v3/gists/#create-a-gist"}

Please help me solve the issue. I got the Personal access tokens from github, then i copied from it then paste to input field when I prompt Sync>Update/ Upload Setting.

Thanks!

**Comment by shanalikhan** [comment]
Have you added the **GIST** scope while creating new token from github ?

**Comment by hieutranagi47** [comment]
Oh, Thank you so much! I don't know the issue because I don't see this in the guide line. I checked in gist option when I was generating token on github.

**Comment by shanalikhan** [comment]
Actually its shown in picture, thanks for the suggesstion i will highlight this on guide line
