### ISSUE TITLE
sync os pragma won't work on M1 mac

### ISSUE THREAD

**Issue by up2moon** [shanalikhan/code-settings-sync#1336]
🐛 **Describe the bug**  
// @sync os pragma won't work on M1 mac.

🌴 Visual Studio Code Version : 1.65.2
🌴 Code Settings Sync Version : 3.4.3
🌴 Standard or Insiders : Standard
🌴 Portable or Installed : Installed
🌴 OSS or Official Build : Official Build
🌴 Operating System : macOS Monterey 12.3(M1)
🌴 Occurs On: startup
🌴 Proxy Enabled: No
🌴 Gist Id: Not relevant I think, will be added if needed

📰 To Reproduce
1. Open settings.json and comment out as follows
// @sync os=windows
"python.pythonPath": {windowsPath}
// @sync os=mac
"python.pythonPath": {macPath}
2. Save and restart the vscode
3. See if the line that contains {windowsPath} gets commented out automatically

💪 Expected behavior
The line belonging to // @sync os=windows should be commented out

📺 Console Error Log
None

**Comment by ziqq** [comment]
Any news? I catch this bug in windows and mac.
![image](https://user-images.githubusercontent.com/20646071/175312063-0a06dd69-1695-4ae4-b621-adda54bb7310.png)
