### ISSUE TITLE
Uses 15% CPU in background

### ISSUE THREAD

**Issue by maxxborer** [shanalikhan/code-settings-sync#1349]
Issue Type: <b>Bug</b>

Install and enable sync

Extension version: 3.4.3
VS Code version: Code - Insiders 1.68.0-insider (Universal) (4589815e4849499c67125ff68563fa102646b869, 2022-06-01T05:17:25.414Z)
OS version: Darwin x64 21.5.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 6, 4|
|Memory (System)|8.00GB (0.76GB free)|
|Process Argv|--crash-reporter-id adabc273-1580-432e-b9ac-5739d117ddac|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by lethefrost** [comment]
Hi, I suppose now VSC natively has a settings sync feature, and this extension is no longer maintained. 

Please check the [official document](https://code.visualstudio.com/docs/editor/settings-sync).
