### ISSUE TITLE
Error Logged In Console. On download

### ISSUE THREAD

**Issue by kuzyas** [shanalikhan/code-settings-sync#136]
**Visual Studio Code Version :** [1.7.1]
**Code Sync Settings Version :** [2.3.7]
**Operating System :** [windows 10]
**Occurs On:** [Download]
**Proxy Enabled:** [Yes]

![275811478598964782474655858271](https://cloud.githubusercontent.com/assets/17053017/20094564/835766b8-a5aa-11e6-9f79-db194b571d30.png)

**Comment by shanalikhan** [comment]
Duplicate to https://github.com/shanalikhan/code-settings-sync/issues/135

Which extensions you have installed,
Can you make your GIST public and share with me so i can see data coming from the GIST in downloading and generate this issue.
U may write ID here or email me.


Closing this issue, please post updates there. https://github.com/shanalikhan/code-settings-sync/issues/135
