### ISSUE TITLE
Summary should be loaded in VS Code Output Window

### ISSUE THREAD

**Issue by fleed** [shanalikhan/code-settings-sync#137]
**Visual Studio Code Version :** 1.6.1
**Code Sync Settings Version :** 2.3.6
**Operating System :** MacOS Sierra
**Occurs On:** Download
**Proxy Enabled:** No

The `syncSummary.txt` becomes the active tab/item, stealing focus. I often find myself writing there instead of the previously active tab.
This becomes very annoying when combined with issue #125

**Comment by shanalikhan** [comment]
have you tried disabling the summary page from the advance options ?

**Comment by fleed** [comment]
Yes, I'm using it as workaround.
But I'd still like to see the report, just not in such _invasive_ way.
Anyway I think that it shouldn't be that annoying once the issue #125 is fixed. Just a small improvement.

**Comment by fleed** [comment]
@shanalikhan #125 is fixed for me too. If you don't think that the tab with `syncSummary.txt` file should open _in the background_ you can close this issue too.

**Comment by shanalikhan** [comment]
Yes Good suggesstion, i will see what i can do for background tab

**Comment by shanalikhan** [comment]
This is limitation in vs code for now. I have request feature https://github.com/Microsoft/vscode/issues/15319 , once its done i will implement this.

**Comment by fleed** [comment]
Great, thanks for feedback

**Comment by ThisIsManta** [comment]
How about showing `showInformationMessage(...)`? I'm referring to https://code.visualstudio.com/docs/extensionAPI/vscode-api

**Comment by shanalikhan** [comment]
detailed summary cant be shown in information message
The main purpose is to dont interrupt the user after sync, information message will require an action to close that.
Setting the summary page to other tab will allow user to keep working on the current tab while sync completes

**Comment by ThisIsManta** [comment]
@shanalikhan, my thought is:
- showing the sync summary in the foreground is too aggressive, giving that it took a few secs to finish and it stole the attention from the current working file.
- hiding the sync summary completely is too optimistic. I want to be certain if the settings were updated, so I could continue working confidently.

I want **something in between**, so I thought giving users a new configuration option, so they can choose to show just "The settings have been synced" in `showInformationMessage`.

**Comment by shanalikhan** [comment]
Nice! Yes this can be done.
I will look into it
also i have opened issue to open tab in background in code.
https://github.com/Microsoft/vscode/issues/22847

**Comment by Jeff-Lewis** [comment]
It would be really nice it always wrote to its own [Output Window](https://code.visualstudio.com/docs/extensionAPI/vscode-api#OutputChannel).

**Comment by smbkr** [comment]
The output window definitely seems like the correct place for this, rather than a new buffer.

**Comment by shanalikhan** [comment]
Nice Suggestion @Jeff-Lewis ! Thanks
Will work on it.

**Comment by shanalikhan** [comment]
Pull Request is welcome.

Just need to change the function and call output API to write instead of file

https://github.com/shanalikhan/code-settings-sync/blob/master/src/commons.ts#L537

**Comment by ThisIsManta** [comment]
I have opened the PR. Please check it out.

**Comment by shanalikhan** [comment]
released!
