### ISSUE TITLE
Git PAT expired and now can't update to new PAT in code-settings

### ISSUE THREAD

**Issue by asapsmc** [shanalikhan/code-settings-sync#1372]
I had a Git Personal access token for code-settings-sync that expired. I generated another one, but I don't know how to update code-settings-sync to it. I already uninstalled code-settings-sync and reinstalled again, but I don't know where to update PAT.
When I try to sync I always get the message: "Sync: Invalid/Expired GitHub Token. Please generate new token with scopes mentioned in readme. Exception Logged in Console."

**Comment by cmidkiff87** [comment]
hit `F1` to bring up the "command pallet", and search "sync: Advanced Options" > "sync: Open Settings"

The option to update the PAT is there

**Comment by asapsmc** [comment]
Thank you.
