### ISSUE TITLE
Proxy Issues with User Settings

### ISSUE THREAD

**Issue by JoshCork** [shanalikhan/code-settings-sync#139]
**Visual Studio Code Version :** [ 1.6.1 ]
**Code Sync Settings Version :** [ 2.3.4 ]
**Operating System :** [ 10.12.1 ]
**Occurs On:** [Download]
**Proxy Enabled:** [ Yes ]

When syncing from my non-work machine it seems like the first thing that gets overwritten are my work proxy rules. 

How does one go about syncing between two machines, one of which is behind a corporate proxy and the other is not?

I have posted frequently asked questions on 
http://shanalikhan.github.io/2016/11/07/visual-studio-code-frequently-asked-questions.html 
so you may able to resolve the error quickly. 
Please make sure to write the versions and console logged error picture or copied text

**Comment by shanalikhan** [comment]
if the auto upload is enabled than it will overwrite all the instances in all other machines no matter what proxy settings are.

**Comment by JoshCork** [comment]
Thanks for the reply.  In this case I just went and modified the GIST manually to include the same proxy settings to see how that would impact it.  Still having issues downloading behind a proxy using the extension.  Downloading behind the proxy manually by clicking on 'install' for each extension I want works just fine.

**Comment by shanalikhan** [comment]
2.3.8 version is released to fix this issue https://github.com/shanalikhan/code-settings-sync/issues/135 as behind proxy there were some problems in downloading the extension.
Let me know if you are able to download all the things behind a proxy

**Comment by Spinarooni** [comment]
@JoshCork For the machine behind the proxy try specifying the proxy in the Environmental Variables instead of the VS Code http.proxy setting like so:
  
![image](https://cloud.githubusercontent.com/assets/331866/20317022/5de0dd50-ab32-11e6-8102-1efb9b009fb0.png)

That way you will not have to worry about the http.proxy setting being overwritten in the settings file.

**Comment by shanalikhan** [comment]
@JoshCork 
Sorry, i understand your problem now.
This extension will keep your settings file in sync.
you may try @Spinarooni way 
I am closing this issue for now, i will say this is the limitation, may be you can update after few months about it than we will see what can be done to make it more configurable

**Comment by totkeks** [comment]
@Spinarooni this usually works, but some workplace environments are a bit troublesome. For example I can't set the proxy globally, because then some programs stop working properly. So I have to set it on a per application basis.
