### ISSUE TITLE
Does not work with 0.10.8

### ISSUE THREAD

**Issue by borekb** [shanalikhan/code-settings-sync#14]
Hi, I've just tried this extension with VSCode 0.10.8 (January 2016) and it doesn't seem to work - Alt+Shift+u does nothing and I can't see the "Sync" command of the extension in the pallete. Is it compatible with this version?

I am on Windows 10 x64, VS Code's path is `"C:\Program Files (x86)\Microsoft VS Code\Code.exe"`.

**Comment by shanalikhan** [comment]
yes its compatible. can you check the extension is installed. you can try by uninstalling and installing it again.

**Comment by borekb** [comment]
Had to reinstall it twice - some weird version 1.3.0 or 1.0.3 was downloaded, not sure about that, but now, everything is fine with 1.0.1. Thank you, it's a great extension!

**Comment by shanalikhan** [comment]
There was some problem in package json file though, i have fixed in update
