### ISSUE TITLE
shell.ts:440 Unexpected number in JSON at position 247

### ISSUE THREAD

**Issue by onfqzmpgvr** [shanalikhan/code-settings-sync#140]
**Visual Studio Code Version :** [ 1.7.1]
**Code Sync Settings Version :** [ 2.3.8 ]
**Operating System :** [ Windows 10 1607 ]
**Occurs On:** [Start Up]
**Proxy Enabled:** [ No ]

I have posted frequently asked questions on 
http://shanalikhan.github.io/2016/11/07/visual-studio-code-frequently-asked-questions.html 
so you may able to resolve the error quickly. 

![picture](https://cloud.githubusercontent.com/assets/12532557/20246409/dc9bcb64-a9e8-11e6-9aa6-9722ff15ea95.png)

**Comment by shanalikhan** [comment]
have you manually added the GIST or token in settings ?

**Comment by onfqzmpgvr** [comment]
I didn't manually change the setting file
Basically, I accidentally fill wrong (in "Sync: Download Settings), tried to reset extension setting but nothing happened, no error notification appeared !

**Comment by shanalikhan** [comment]
ok whats in the setting file ? can you share the file in users folder. with the name *syncsettings.json*

**Comment by onfqzmpgvr** [comment]
Oh I found the problem, just delete syncsettings.json and reconfig the extension resolved the issue. The extension crash when misconfiguring. Thank you anyway 🍡 , but can you add a feature that auto reset the setting file when it misconfiged ?

**Comment by shanalikhan** [comment]
i will the extension setting entirely from syncsettings.json file to vs code own settings file so i dont think this will be feasible now.
