### ISSUE TITLE
Sync File Icon Settings

### ISSUE THREAD

**Issue by Jonatino** [shanalikhan/code-settings-sync#145]
**Visual Studio Code Version :** 1.0.8-Insider
**Code Sync Settings Version :** 2.3.8
**Operating System :** Windows 10 x64
**Occurs On:** Both
**Proxy Enabled:** No

Can we get settings sync for File Icon Theme (File->Preferences->File Icon Theme)? Thanks!

**Comment by shanalikhan** [comment]
Already asked code team to provide an API
https://github.com/Microsoft/vscode/issues/12178

**Comment by shanalikhan** [comment]
Settings Sync will automatically sync the color themes from the next next version of code ! 😄

**Comment by shanalikhan** [comment]
If the file icon extension is not installed, you need to reload the code in order to Apply the file icons.
