### ISSUE TITLE
Adding Support for Workspace Settings like tasks.json

### ISSUE THREAD

**Issue by jchannon** [shanalikhan/code-settings-sync#146]
**Visual Studio Code Version :** 1.7.0
**Code Sync Settings Version :** N/A
**Operating System :** OSX 10.11
**Occurs On:** N/A
**Proxy Enabled:** N/A

Hi,

Would it be possible to sync tasks.json somehow.  I know they are workspace specific but I find most tasks I have I use across multiple projects and its a pain copying them into each new project. Having to sync them would be great.

Thanks

**Comment by shanalikhan** [comment]
Yes i will work on support workspace settings not only task.json but other files in workspaces, but for now there are much work to do for supporting the current defined process for syncing the default settings from which some features are limitations by vs code, code team is already acknowledged off and will work on that

Once the default syncing features complete , i will start work on the work space settings :)

**Comment by shanalikhan** [comment]
Adding this issue in the https://github.com/shanalikhan/code-settings-sync/issues/146 and closing this.
