### ISSUE TITLE
Enhancement: option for alternate github location

### ISSUE THREAD

**Issue by rothskeller** [shanalikhan/code-settings-sync#150]
Enhancement request:  please add an option to provide a different URL for GitHub, so that one may use a corporate installation of GitHub Enterprise rather than the default github.com.

**Comment by shanalikhan** [comment]
Duplicate of https://github.com/shanalikhan/code-settings-sync/issues/67
I will work on it later on once i add other important features :), Feel Free to comment there

**Comment by rothskeller** [comment]
Sorry I missed the dup.
