### ISSUE TITLE
Cant Download Settings on VM

### ISSUE THREAD

**Issue by Jonatino** [shanalikhan/code-settings-sync#151]
**Visual Studio Code Version :** [ 1.8.0-insider ]
**Code Sync Settings Version :** [ 2.3.8 ]
**Operating System :** [ Windows 7 64bit ]
**Occurs On:** [Download]
**Proxy Enabled:** [ No ]

I'm trying to setup vscode on my dev box (Windows 7 VM) but I get an issue whenever I try to sync my settings (it's worked fine on 3 other computers).

Here is the error:
```
2extensionHost.ts:291[Extension Host] Windows_NT
extensionHost.ts:291[Extension Host] Error: read ECONNRESET
    at exports._errnoException (util.js:1026:11)
    at TLSWrap.onread (net.js:564:26)x.logExtensionHostMessage @ extensionHost.ts:291
messageService.ts:126Error Logged In Console (Help menu > Toggle Developer Tools). You may open an issue using 'Sync : Open Issue' from advance setting command.e.doShow @ messageService.ts:126
extensionHost.ts:291 [Extension Host] Windows_NT
```

![error](https://cloud.githubusercontent.com/assets/1808569/20682990/53db48ae-b578-11e6-9661-c30679317e92.png)

Thanks!

**Comment by shanalikhan** [comment]
Hi, i have tested this on VM and its working fine, there migth be come problem with your VM network connectivity.
