### ISSUE TITLE
[Request] Add tasks.json to list of sync files

### ISSUE THREAD

**Issue by Shackless** [shanalikhan/code-settings-sync#155]
VSCode allows you to define [custom tasks](https://code.visualstudio.com/Docs/editor/tasks) in a file called tasks.json that are usually triggered by keybinding that code-settings-sync already handles. It would be nice if we could (have an option to) also sync the tasks.json file.

**Comment by shanalikhan** [comment]
is this defined in directly in User folder or inside workspace folder ?
Here it states that 
> You should now see a tasks.json file in your workspace .vscode folder with the following content:
```
{
    "version": "0.1.0",
    "command": "echo",
    "isShellCommand": true,
    "args": ["Hello World"],
    "showOutput": "always"
}
```

**Comment by shanalikhan** [comment]
Sorry
