### ISSUE TITLE
Ability to set 'Advanced Options' in settings.json

### ISSUE THREAD

**Issue by jahands** [shanalikhan/code-settings-sync#157]
**Visual Studio Code Version :** [ 1.8.0 ]
**Code Sync Settings Version :** [ 2.3.8 ]
**Operating System :** [ Windows 10 1607 ]

Between multiple computers/vm's, I'm constantly setting things like hiding the post-sync page.
Could you please add the ability to set these in settings.json? eg. `codesync.showSummaryPage`

**Comment by shanalikhan** [comment]
Try with this command
"Sync : Advance Options > Toggle Summary Page On Upload / Download"

let me know if there is any problem :)

**Comment by jahands** [comment]
That works, but I still have to set it on each machine. This plugin is for
syncing settings, so it's odd to me that you can't sync settings for it.

Also, for some reason I have to toggle it back off every now and then.

What is the reason behind not exposing sync settings like sync.showsummary
in settings.json, which is synced?

**Comment by shanalikhan** [comment]
Its not saved in settings.json for now, it uses its own json settings file to save its settings. I am working on it and will integrate with settings.json
