### ISSUE TITLE
{"message":"Bad credentials","documentation_url":"https://developer.github.com/v3"}

### ISSUE THREAD

**Issue by joneqing** [shanalikhan/code-settings-sync#159]
**Visual Studio Code Version :** [ 1.8.0]
**Code Sync Settings Version :** [ 2.3.8 ]
**Operating System :** [ win10]
**Occurs On:** [Download]
**Proxy Enabled:** [ No ]

I have posted frequently asked questions on 
http://shanalikhan.github.io/2016/11/07/visual-studio-code-frequently-asked-questions.html 
so you may able to resolve the error quickly. 
Please make sure to write the versions and console logged error picture or copied text

**Comment by shanalikhan** [comment]
this is because you have invalid github token added, make sure you have valid token saved in github.

**Comment by joneqing** [comment]
I know. bug how can i add invalid token . i tried to  uninstall vs code and ext, it doesn't work.

**Comment by shanalikhan** [comment]
are you sure that token name is saved in github for which you are adding in extension ?

**Comment by joneqing** [comment]
ok, thanks a lot.
