### ISSUE TITLE
Code overhaul

### ISSUE THREAD

**Issue by SrTobi** [shanalikhan/code-settings-sync#16]
Hi,
I really like the extension but the code is ...nja... so I started a complete code overhaul of the repo's code to make it a little bit less redundant and overall easier to read and debug (had in mind to add some tests), mainly by splitting the code in more files/classes and the extensive use of [async/await](https://blogs.msdn.microsoft.com/typescript/2015/11/03/what-about-asyncawait/), which I think is perfect for simplifying the code structure.

I already restructured some code. You can see it [here](https://github.com/SrTobi/code-settings-sync). The problem is that the code changed a lot and I don't want to displease you by making a PR that changes your code so much :worried:.

Maybe you can have a look at my fork and say if you would accept such a code overhaul :no_mouth:. If not that's ok with me, then you can close this issue. If you like the changes I would continue and we can discuss and merge.

**Comment by shanalikhan** [comment]
Yes i understand the code needs much improvements.
I like the way you have written.
Can you please help me in accepting the PR by converting it to at least 3,4 PR so i would know what you have changed, just by adding some integration with my code step by step and so i will understand the code in a better manner, as it seems it completely changing the code.
Thanks, Looking forward :)

**Comment by shanalikhan** [comment]
@SrTobi sorry, I think i should integrate your code, myself. Thanks will look in it.

**Comment by SrTobi** [comment]
wait. it is not ready! currently it will not work. There is still much to do. Currently I only have 40% done. I was just asking if I should continue at all :smile:

**Comment by shanalikhan** [comment]
no problem i had to refactor it i will work on it myself just as i have seen your code. if you have time, one pending feature is to add proxy support in the current code. I would be happy and accept a pull request if you can add that feature :smiley:
