### ISSUE TITLE
Vscode Issue

### ISSUE THREAD

**Issue by godbuttton** [shanalikhan/code-settings-sync#163]
**Visual Studio Code Version :** [ 1.8.1 ]
**Code Sync Settings Version :** [ 2.3.8 ]
**Operating System :** [ win7 ]
**Occurs On:** [Upload / Download]  and Download was not successed 
**Proxy Enabled:** [ Yes ]

the plugin is very good，but something is wrong when i upload      
but when I download  it show me you have ...latest    
in fact ,it is not worked!

**Comment by shanalikhan** [comment]
what is the error in the console
