### ISSUE TITLE
Update Error

### ISSUE THREAD

**Issue by BenLampson** [shanalikhan/code-settings-sync#164]
Error Logged In Console (Help menu > Toggle Developer Tools). You may open an issue using 'Sync : Open Issue' from advance setting command.

Error: connect ECONNREFUSED 127.0.0.1:1080
But I can't find the "ECONNREFUSED 127.0.0.1:1080"... where it is ?

**Comment by shanalikhan** [comment]
Operating System : [ ? ]
Occurs On: [Upload / Download] ?
Proxy Enabled: [ Yes/no ]

please answer the question above

**Comment by BenLampson** [comment]
Operating System : WIN10
Occurs On: Upload 
Proxy Enabled: I don't know

**Comment by spicydonuts** [comment]
I see this error on the insiders build (1.9, 04f541160e0d41be95df9a964b1b570aec549157) when running either upload or download.  It works fine on my 1.8.1 installation.

Operating System: macOS 10.12.2
Proxy Enabled: no

**Comment by shanalikhan** [comment]
can you please provide the stack trace of exception or a image of console i would know and check further

**Comment by BenLampson** [comment]
Issue has fixed.. 
Maybe the github's token have some dely  ?
If I use  new token  to upload ... It's must be failed.
But the old token can successed. 
1 day? maybe few hour.. 
The problem last night was fine this morning.

**Comment by shanalikhan** [comment]
Yes github has some delay , i also felt this while testing but i thought im the only one :P 
Thanks
