### ISSUE TITLE
Cannot update previous uploaded settings

### ISSUE THREAD

**Issue by lazymanpt** [shanalikhan/code-settings-sync#165]
**Visual Studio Code Version :** [ 1.8.1 ]
**Code Sync Settings Version :** [ 2.3.8 ]
**Operating System :** [ WIN10 ]
**Occurs On:** [Upload]
**Proxy Enabled:** [ No ]

Error: [Extension Host] {"message":"Validation Failed","errors":[{"resource":"Gist","code":"missing_field","field":"files"}],"documentation_url":"https://developer.github.com/v3/gists/#edit-a-gist"}.

**Comment by shanalikhan** [comment]
do you have any snippet file or setting file as empty ?

**Comment by lazymanpt** [comment]
Snippets no and settings file as empty afaik no.

**Comment by shanalikhan** [comment]
Recently error was found https://github.com/shanalikhan/code-settings-sync/issues/161 as some of the file was empty.
So you are sure that in user folder ? All the settings files including settingsjson keybinding,json and snippets and other files are NOT EMPTY.

Next step is can you make backup of snippets and remove the snippets file manually from file explorer and then check error is still there?

**Comment by lazymanpt** [comment]
Since my keybindings.json and my Snippets folder were empty, I removed them but now I get a different error, saying it couldn't find the snippets folder.
 However after restarting vscode it worked.

**Comment by shanalikhan** [comment]
Problem was due to keybinding json file, I have fixed this, will release in 2.4 version
