### ISSUE TITLE
disable extensions for certain workplace 

### ISSUE THREAD

**Issue by maxisam** [shanalikhan/code-settings-sync#170]
**Visual Studio Code Version :** 1.8.1
**Code Sync Settings Version :** 2.4.0
**Operating System :** Windows 10
**Occurs On:** Upload
**Proxy Enabled:**  No 

It is a great extension. However I found an issue when you disable extensions for workplace.

If you disable an extension for certain workplace, code setting sync will remove this extension for good.

**Comment by shanalikhan** [comment]
>Visual Studio Code Version : 1.8.1
Code Sync Settings Version : 2.4.0

I pushed 2.4 for 1.9 Code version, you got an update in 1.8.1 ?

Do you meant that you disabled the extension for some workspace and it didnt upload that extension so when you downloaded the settings , that disabled extension was not downloaded.
may be if you define a proper use case for scenario so i can better understand ?

**Comment by maxisam** [comment]
My mistake. It should be 2.3.8. I assumed I am on the latest.

Yes, you understand it correctly. I checked the list on download summary, and it doesn't show the disabled extension. And when I enable it and upload again, it shows up in the list.

**Comment by shanalikhan** [comment]
This is the behavior from Code API.

Already issue opened for the disabled extension https://github.com/shanalikhan/code-settings-sync/issues/143 for which i have posted request for code team on https://github.com/Microsoft/vscode/issues/15466. Lets see when it gets solved.
