### ISSUE TITLE
Missing version tags

### ISSUE THREAD

**Issue by x3rAx** [shanalikhan/code-settings-sync#171]
Hi,

this is not a bug report this is more like an improvement suggestion to your workflow.

But first let me thank you for this great extension: THANK YOU! :+1: :kissing_heart:

Back to topic: I just cloned the repository at master branch, installed npm dependencies and hit F5 and was surprised that a message said that the extension is not compatible with my version of vscode. It turned out that I have the stable build installed (which is v1.8.1 at the time of writing) instead of the insider build (which is currently at v1.9.0). 

I looked up the version of code-settings-sync that I have installed in my stable build vscode (v2.3.8) and tried to find a branch or tag with that version, so that I could checkout that exact version.

I found some version tags but they were v1.x, which is not helping me at all.

Therefor I suggest you to provide an appropriate version tag to every commit that you release to the marketplace, so that other developers can quickly find the source state they have installed.

**Comment by shanalikhan** [comment]
Thank you!

Sure i will follow the complete workflow.

Currently the latest version of extension is 2.4.0 that is available for insiders, i have made huge changes so its better to hit it for insiders for about week so if i dont get any issues i will publish it for normal code build.

What you can do to make it run in your code for now is find the `^1.9.0` in the package.json and replace it with `^1.8.0` to make it run for your code version.
