### ISSUE TITLE
Can't download extensions.

### ISSUE THREAD

**Issue by fengcen** [shanalikhan/code-settings-sync#172]
**Visual Studio Code Version:** 1.8.1
**Code Sync Settings Version:** 2.3.8
**Operating System:** Windows 7
**Occurs On:** Download
**Proxy Enabled:** Yes

It should show network problem instead of showing "downloading extension in the background".

**Comment by shanalikhan** [comment]
can you please provide the developer console error logged picture so i can see where is the problem
