### ISSUE TITLE
macOS Questions

### ISSUE THREAD

**Issue by petty** [shanalikhan/code-settings-sync#173]
**Visual Studio Code Version :** 1.9
**Code Sync Settings Version :** 2.4.0
**Operating System :** macOS 10.12.2
**Occurs On:** N/A
**Proxy Enabled:** No

I'm stuck on this step:

Press Shift + Alt + U it will ask your github account access token.

... on my Mac I'm using Shift - Option - U ... and nothing happens.

I've tried manually opening the Command Palette & typing in "Sync" but that autocompletes to Git Sync

##

It's been a long time since I've had to think about keybinding translations from a Windows OS to macOS ... maybe this is something ridiculously simple.  I'm pretty sure your extension is installed & unless it just isn't supported on macOS I _should_ be to get going.

**Comment by petty** [comment]
When I re-started VSCode, "Sync" in Command Palette had options aside from Git : Sync ...

**Comment by shanalikhan** [comment]
Great! 
Glad to know you solved it
