### ISSUE TITLE
"Sync : Advance Options > Toggle Auto-Download On Startup" always shows OFF

### ISSUE THREAD

**Issue by Ravencrow** [shanalikhan/code-settings-sync#174]
**Visual Studio Code Version :** [ 1.8.1 ]
**Code Sync Settings Version :** [ 2.4.0 ]
**Operating System :** [ MacOS Sierra 10.12.2 ]
**Occurs On:** [Setting auto-download]
**Proxy Enabled:** [ What is this? ]

When I try to use "Sync : Advance Options > Toggle Auto-Download On Startup" the message is always:
info: Sync: auto download turned OFF upon VSCode Startup.

I guess it should change from OFF to ON on successive invocations of this function, but always is the same message: OFF.

Thanks for this awesome extension!

**Comment by shanalikhan** [comment]
is there any developer console error logged ?
