### ISSUE TITLE
bad credential

### ISSUE THREAD

**Issue by lv7777** [shanalikhan/code-settings-sync#177]
**Visual Studio Code Version :** [ VERSION_HERE ]
**Code Sync Settings Version :** [ VERSION_HERE ]
**Operating System :** [ VERSION_HERE ]
**Occurs On:** [Upload / Download]
**Proxy Enabled:** [ Yes / No ]

I have posted frequently asked questions on 
http://shanalikhan.github.io/2016/11/07/visual-studio-code-frequently-asked-questions.html 
so you may able to resolve the error quickly. 
Please make sure to write the versions and console logged error picture or copied text

In console
```
Overwriting extension <<.vue>> to now point to mime <<text/x-vue>>
workbench.main.js:98 [Extension Host] Windows_NT
workbench.main.js:35 Overwriting extension <<.vue>> to now point to mime <<text/x-vue>>
workbench.main.js:98 [Extension Host] Windows_NT
2workbench.main.js:98 [Extension Host] {"message":"Bad credentials","documentation_url":"https://developer.github.com/v3"}(anonymous function) @ workbench.main.js:98
workbench.main.js:89 Error Logged In Console (Help menu > Toggle Developer Tools). You may open an issue using 'Sync : Open Issue' from advance setting command.e.doShow @ workbench.main.js:89
workbench.main.js:98 [Extension Host] Windows_NT
2workbench.main.js:98 [Extension Host] {"message":"Bad credentials","documentation_url":"https://developer.github.com/v3"}(anonymous function) @ workbench.main.js:98
workbench.main.js:89 Error Logged In Console (Help menu > Toggle Developer Tools). You may open an issue using 'Sync : Open Issue' from advance setting command.e.doShow @ workbench.main.js:89
2workbench.main.js:98 [Extension Host] Windows_NT
2workbench.main.js:98 [Extension Host] {"message":"Bad credentials","documentation_url":"https://developer.github.com/v3"}(anonymous function) @ workbench.main.js:98
workbench.main.js:89 Error Logged In Console (Help menu > Toggle Developer Tools). You may open an issue using 'Sync : Open Issue' from advance setting command.e.doShow @ workbench.main.js:89
2workbench.main.js:98 [Extension Host] Windows_NT
2workbench.main.js:98 [Extension Host] {"message":"Bad credentials","documentation_url":"https://developer.github.com/v3"}(anonymous function) @ workbench.main.js:98
workbench.main.js:89 Error Logged In Console (Help menu > Toggle Developer Tools). You may open an issue using 'Sync : Open Issue' from advance setting command.
```

**Comment by shanalikhan** [comment]
This is due to **_Authenticating with invalid credentials_**
**Solution** : Try generating new token.

**Details:**
![capture](https://cloud.githubusercontent.com/assets/8774556/21578543/22951192-cfa6-11e6-88ef-7f92bba687d0.PNG)



Source : [Github API](https://developer.github.com/v3/#failed-login-limit)

**Comment by drewklassen** [comment]
Well thanks, but in other words, for me to sync, I have to generate **New Tokens** every freaking time I attempt to sync???  Surely I'm missing something here... ?!

Thanks for your response and look forward to a better solution - hear from you soon yes?

**Comment by drewklassen** [comment]
Also, Is there a YouTube video on how to properly sync across multiple operating systems & boxes?  **without** having to generate new tokens every time?

**Comment by shanalikhan** [comment]
> I have to generate New Tokens every freaking time I attempt to sync
Sometimes it happened with me that valid token doesnt seem to work, i get this error but this error is from their API.

I dont think all users are experiencing this error from github.

Yes when you reset your settings and set anonmyous gist setting to true, it wont ask you token but generate new GIST every time.
But if you want to work with same GIST every time, it will require token

**Comment by shanalikhan** [comment]
Another user reported previously about **Github Delays** at https://github.com/shanalikhan/code-settings-sync/issues/164#issuecomment-268416164

**Comment by StevenCHowell** [comment]
I have no success syncing between MacOS and Ubuntu.  I cannot get the Ubuntu machine to validate the gist token.  Tried re-creating the token several times.  The same steps work fine on the Mac, using the same token.

Where do I find the logs to check for a 401 or 403 error?

**Comment by shanalikhan** [comment]
@StevenCHowell you can use fiddler to see the details.
Developer console shows the exception.
In the recent update i have set an option for token in local settings so you can see which token is added, and change it manually.
Besides that i'm also including https://github.com/shanalikhan/code-settings-sync/issues/256 for the users have problems connecting with github.

**Comment by shanalikhan** [comment]
@StevenCHowell as these are coming from github api directly. What i will be doing in the future updates to implement this.
https://github.com/shanalikhan/code-settings-sync/issues/256
