### ISSUE TITLE
How to sync from a public GIST without entering a personal token?

### ISSUE THREAD

**Issue by mystrdat** [shanalikhan/code-settings-sync#179]
**Visual Studio Code Version :** 1.81
**Code Sync Settings Version :** 2.4.1
**Operating System :** Windows 10, Linux Mint
**Occurs On:** Upload
**Proxy Enabled:** No

It seems that when the Update / Upload Settings feature is selected, the plugin immediately asks for a Github token. I don't see why downloading settings from a random public GIST would require my own token. Am I missing something or is that intended behavior?

**Comment by shanalikhan** [comment]
Yes token is required to connect with Github to get the Gist.

**Comment by mystrdat** [comment]
Thanks for the answer. In that case, would you consider it a possible suggestion to remove said limitation? Or is the token a somehow necessary step to make things work?

**Comment by shanalikhan** [comment]
Yes there is a possibility. I will work on it.

**Comment by shanalikhan** [comment]
I have created a story for this, at https://github.com/shanalikhan/code-settings-sync/issues/180
Im closing this issue, please comment there for suggestion regarding Anonymous Gist that doenst require token to create.
