### ISSUE TITLE
Sync Color Theme Settings

### ISSUE THREAD

**Issue by totkeks** [shanalikhan/code-settings-sync#185]
Visual Studio Code Version : 1.8.1
Code Sync Settings Version : 2.4.2
Operating System : Windows 10 x64
Occurs On: Both
Proxy Enabled: No

Similar to #145 ... Can we get settings sync for Color Theme (File->Preferences->Color Theme)? Thanks!

**Comment by shanalikhan** [comment]
Limitation in Code itself, i have already posted an issue.
https://github.com/Microsoft/vscode/issues/12178

You may upvote that issue from there and comment them to provide the feature soon :) 
Once implemented i will start work on it.

**Comment by shanalikhan** [comment]
Settings Sync will automatically sync the color themes from the next next version of code ! 😄

**Comment by shanalikhan** [comment]
If the theme extension is not installed, you need to reload the code in order to Apply the theme if set in settings.json file
