### ISSUE TITLE
Incorrect default setting

### ISSUE THREAD

**Issue by gregoralbrecht** [shanalikhan/code-settings-sync#187]
Great extension, I just installed it! I noticed something small, but maybe you want to update it. If not, just close this issue. 

When you click `Sync : How To Configure` from the VScode command palette it links to [this post explaining the default configurations](http://shanalikhan.github.io/2015/12/15/Visual-Studio-Code-Sync-Settings.html). In there it says that `auto download` is *enabled* by default. In the docs it says it's *disabled* by default, which is correct (at least for me).

I just got confused for a second because it didn't automatically sync. Other than this the two pages seem to be identical.

**Comment by shanalikhan** [comment]
Thanks, i will update the post to the docs today :)
