### ISSUE TITLE
Gist ID ?

### ISSUE THREAD

**Issue by jarod51** [shanalikhan/code-settings-sync#19]
Hi

The extension asks me for a token but never ask for a gist id ?

**Comment by shanalikhan** [comment]
I have updated it day before.
make sure you have the latest version.
Also check there is no file named "gist_sync" in %appdata%\Code\User. If you find delete this file and try again download settings it will ask for GIST ID

Let me know if this solve your problem

**Comment by jarod51** [comment]
It does not seem to work for me. Checked out everything and it seems to be up to date.

I have a brand new token from Github, the extension asks for it, but after it does not give me a gist id back ! Nothing is uploaded nor sync to github

**Comment by andre-f** [comment]
I have exactly the same issue. I enter the token and then nothing happens and I do not get a Gist.

**Comment by shanalikhan** [comment]
okay i will check it out.

**Comment by fortinmike** [comment]
See #20 for a possible workaround.

**Comment by shanalikhan** [comment]
Please update and let me know.

**Comment by andre-f** [comment]
Now I get "ERROR ! Logged In Console. Please open an issue in Github Repo." when I enter the new token. However the debug console in Code shows nothing...

**Comment by adusak** [comment]
I have the same issue, apparently the extension can't create the gist by itself (in the initial setup), but when I manually create the gist and fill in the gist id in extensions settings it works.

**Comment by afnpires** [comment]
![image](https://cloud.githubusercontent.com/assets/5302351/14192863/5662591c-f798-11e5-873d-8364e5c04f30.png)

Here's the error that is thrown when a insert the gist id.

Hope it helps

**Comment by shanalikhan** [comment]
Error [resolved ](https://github.com/shanalikhan/code-settings-sync/pull/22)
Please update the extension. I have checked its working at my side. For double check Can anyone please check its working now so i can close the issue :)

**Comment by jarod51** [comment]
It works for me now
