### ISSUE TITLE
Clear/change github account value

### ISSUE THREAD

**Issue by alexeygrant** [shanalikhan/code-settings-sync#191]
**Visual Studio Code Version :** 1.8.1
**Code Sync Settings Version :** 2.4.2
**Operating System :** Windows 10
**Occurs On:** Download
**Proxy Enabled:** Yes

I've incorrectly pasted my gist token code to github account field and I don't see any option to correct this problem. How can I clear/change the github account value? Thanks.

**Comment by shanalikhan** [comment]
Hit the command "Sync : Reset Settings" and try again.
