### ISSUE TITLE
Ability to exclude certain files?

### ISSUE THREAD

**Issue by smlombardi** [shanalikhan/code-settings-sync#193]
**Visual Studio Code Version :** Version 1.9.0-insider
**Code Sync Settings Version :** 2.4.2
**Operating System :** 10.12.2
**Occurs On:** n/a
**Proxy Enabled:** no

I use the extension [Project Manager](https://marketplace.visualstudio.com/items?itemName=alefragnani.project-manager), which allows me to create "projects" which in this case are ssimple paths to folders of files I am working on.

So, if I am currently viewing `/Users/stevel/somefolder`, I can "save project" as "My Project".  Then I can use the extension to quickly select "My Project" and that folder opens up for work.

It saves these projects to `'/Users/stevel/Library/Application Support/Code - Insiders/User/projects.json'

The problem I am having is that Settings Sync is syncing this file -- and the projects and their paths are not likely to be the same on multiple computers. So, if the projects are correct on my work computer, they are backed up and downloaded to my home computer and are no longer valid.  And the projects i _had_ created on my home computer are overwritten.

Seems to me the solution would be to have a user setting to exclude specified files from synchronization.

**Comment by shanalikhan** [comment]
Thanks for Explaining well.
I understand i will solve this in next version.
Meanwhile you can try to save it on another location until next version.
Similar issue opened https://github.com/shanalikhan/code-settings-sync/issues/100.
Post there :)
