### ISSUE TITLE
Updated keybindings failed to update on other machines.

### ISSUE THREAD

**Issue by jimzhan** [shanalikhan/code-settings-sync#194]
**Visual Studio Code Version :** 1.8.1
**Code Sync Settings Version :** 2.4.2
**Operating System :** Mac OS Sierra ver 10.12.2
**Occurs On:** Download
**Proxy Enabled:** No
**Reproduce** 
1. Update & upload keybindings settings on Mac machine A (corresponding **keybindingsMac.json** gets uploaded correctly without keybindings.json).
2. on Mac machine B, try download the new settings, **keybindingsMac.json** gets downloaded correctly, but the old keybindings.json is still still and takes the priority, thus the updated **keybindingsMac.json** won't take any effects.

**Comment by shanalikhan** [comment]
So you are saying that there are two files in MAC keybindings.json and keybindingsMac.json in User folder? Mac settings are not in keybindings.json but in keybindingsMac.json ?

**Comment by jimzhan** [comment]
Exactly, settings-sync only upload the latter one.

**Comment by shanalikhan** [comment]
can you share your gist so i can test it

**Comment by jimzhan** [comment]
https://gist.github.com/jimzhan/1b6e50ed2190d3a9dd073da9dd8cae6a

tks :-)

**Comment by jrwiegand** [comment]
I have also noticed that my general keybindings.json is not being synced but the OS specific keybindings.json is synced properly.

**Comment by dlech** [comment]
Somehow we are getting both `keybinding.json` and `keybindingsMac.json` in our local `/Users/` folder. `keybinding.json` is the real file, but both are being uploaded as `keybindingsMac.json` to the gist.

| local | gist |
|-|-|
|`keybindings.json` | `keybindingsMac.json` |
| `keybindingsMac.json` | `keybindingsMac.json` |

The first upload is correct (`keybindings.json` > `keybindingsMac.json`) but then `keybindingsMac.json` in the gist is replaced by the second upload (`keybindingsMac.json` > `keybindingsMac.json`)

**Comment by shanalikhan** [comment]
Thanks @dlech i will test and release new version in this week.

**Comment by shanalikhan** [comment]
I have release the build. 
Please let me know if there is still problem

**Comment by skellock** [comment]
Not working for me.  It keeps wanting to change `keybindings.json` into `keybindingsMac.json`.  Is that a thing?   Code doesn't seem to want to use that file.

**Comment by dlech** [comment]
When you upload, `keybindings.json` from your computer is saved as `keybindingsMac.json` in the gist. When you download, the opposite happens. `keybindingsMac.json` from the gist is saved as `keybindings.json` on your computer. Is this not what is happening? It seems to be working for me with v2.4.3.

**Comment by jrwiegand** [comment]
This does seem to be working. Could you explain the rationale behind uploading the `keybindings.json` then is saved in the gist as the OS specific version vs using the generic `keybindings.json`. Is this is separate the keybindings that are specific to the OS?

**Comment by skellock** [comment]
One second while I take my foot out of my mouth here.

So.. it's now working.

The only explanation I have is I perhaps didn't reload vscode after upgrading to the latest version on my other computer.

Gah.  My apologies.  And also my thanks for this project!

**Comment by shanalikhan** [comment]
>Is this is separate the keybindings that are specific to the OS?

Yes
Extension is designed in such a way to store both your OS dependent key bindings

**Comment by peppy** [comment]
Is there no way to have shared key bindings between different platforms with this extension?

**Comment by shanalikhan** [comment]
@peppy please open a new issue with your scenario
