### ISSUE TITLE
Unable to specify existing Gist ID when setting up new install

### ISSUE THREAD

**Issue by patridge** [shanalikhan/code-settings-sync#195]
**Visual Studio Code Version :** 1.8.1
**Code Sync Settings Version :** 2.4.2
**Operating System :** 10.0.14393 Build 14393
**Occurs On:** Configure
**Proxy Enabled:** No

When I follow the [instructions](https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync), it asks for my [existing] GitHub token, but instead of asking for a Gist ID so I can sync multiple installs, it immediately creates a new Gist every time.

If I reset and try again, I end up with yet another new Gist.

If I delete that new Gist manually on GitHub and try to force it to ask again with a `>Sync: Download Settings`, it simply gives an error that it can't find a URL.

```
{"message":"Not Found","documentation_url":"https://developer.github.com/v3"}
```

**Comment by shanalikhan** [comment]
It will create the new GIST first time when you hit upload.
Save the Gist ID, then on other computer select sync download command and enter token and than enter GIST ID that you copied to download those uploaded settings.

**Comment by patridge** [comment]
Those were the exact steps I tried without ever being asked for a Gist ID. I already had a settings Gist from a previous machine. I did another settings reset just now and started over again and now it asked for a Gist ID. So, whatever the problem was, it does ask sometimes.
