### ISSUE TITLE
sync download issue. not sure if it is my machine or the extension

### ISSUE THREAD

**Issue by Icorson** [shanalikhan/code-settings-sync#196]
**Visual Studio Code Version :** [ 1.8.1 ]
**Code Sync Settings Version :** [ 2.4.2 ]
**Operating System :** [ windows 10 (insider preview15007) ]
**Occurs On:** [download]
**Proxy Enabled:** [ No ]

Havent tested download in about a week. I was able to upload from home easily yesterday.

extensionHost.ts:293 [Extension Host] unable to find corresponding version of extension from galleryA.logExtensionHostMessage @ extensionHost.ts:293A.onMessaage @ extensionHost.ts:232(anonymous function) @ extensionHost.ts:171emitTwo @ events.js:106emit @ events.js:191process.nextTick @ internal/child_process.js:744_combinedTickCallback @ internal/process/next_tick.js:67_tickCallback @ internal/process/next_tick.js:98
messageService.ts:126 Error Logged In Console (Help menu > Toggle Developer Tools). You may open an issue using 'Sync : Open Issue' from advance setting command.e.doShow @ messageService.ts:126e.show @ messageService.ts:105(anonymous function) @ mainThreadMessageService.ts:55n.Class.derive._oncancel @ winjs.base.raw.js:1641t.$showMessage @ mainThreadMessageService.ts:25e.handle @ abstractThreadService.ts:34s @ ipcRemoteCom.ts:269f @ ipcRemoteCom.ts:226_combinedTickCallback @ internal/process/next_tick.js:67_tickCallback @ internal/process/next_tick.js:98

**Comment by shanalikhan** [comment]
This is not exception of extension but the marketplace where its not found. May be that extension gets update and you can sync that too
