### ISSUE TITLE
Unable to Update/Upload Settings

### ISSUE THREAD

**Issue by brendenseidel** [shanalikhan/code-settings-sync#197]
After selecting *Sync: Update / Upload Settings* nothing happens. I would expect the browser to open the github personal access tokens page and a drop down in VS Code where I could enter the token.

Also note that this is on a remote AWS machine.

**Visual Studio Code Version :** 1.8.1
**Code Sync Settings Version :** v2.4.2
**Operating System:** Windows Server 2012 R2
**Occurs On:** Upload
**Proxy Enabled:** ?

I have posted frequently asked questions on 
http://shanalikhan.github.io/2016/11/07/visual-studio-code-frequently-asked-questions.html 
so you may able to resolve the error quickly. 
Please make sure to write the versions and console logged error picture or copied text

**Comment by brendenseidel** [comment]
I should note that this is on a remote AWS machine.

**Comment by shanalikhan** [comment]
any console logged, ?
