### ISSUE TITLE
Silent first-upload failure when launch.json is missing in the user settings directory

### ISSUE THREAD

**Issue by fortinmike** [shanalikhan/code-settings-sync#20]
Hi there, I'm trying to get the extension to work and encountered an issue where the initial settings upload would silently fail after entering a valid Github API token (no message displayed, nothing happens).

I downloaded the extension's source, ran it with the debugger and saw that there was a file not found exception where the extension tries to access the `launch.json` file (which didn't exist on my machine, for some reason). 

The extension assumes this file exists, but it should not:
`/Users/[username]/Library/Application Support/Code/User/launch.json`

Adding a `launch.json` file (with an empty root) fixes the initial upload on my machine.

I suppose there are other similar assumptions about file existence that would need fixing to make the extension more robust. I hope this helps!

**Comment by shanalikhan** [comment]
Thank you. This small check was present in the last version but somehow i forgot to added in this version. I have committed the code will be release in the upcoming update.

**Comment by shanalikhan** [comment]
I have updated the extension. Please update and let me know if you still facing that problem for that file. you can delete that file and try with that.
