### ISSUE TITLE
Possible issue with sync extension reading ExtensionHomePath argument

### ISSUE THREAD

**Issue by sheldonhull** [shanalikhan/code-settings-sync#200]
**Visual Studio Code Version :** 1.8.1 (VsPortable Version)
**Code Sync Settings Version :** 2.4.2
**Operating System :** Windows 10
**Occurs On:** Download
**Proxy Enabled:** No

I am running the portable edition. 
I traced activity through ProcessHacker and identified that the extensions were being installed to 
C:\Users\%username%\.vscode\extensions and not the the portable extension directory. 

The portable version launches with the following arguments to tell vscode to run the data/settings from specific directory. 

I reviewed the arguments for VscodePortableIni and it seems to be passing through the environment of VSCODE_HOME as the code directory in the portable app as well as the extensionhomepath argument. I would think these would be downloaded to the passed in directory of %VSCODE_HOME=%PAL:DataDir%\code%` for the sync extension. 

Any ideas?

```
[Launch]
ProgramExecutable=VSCode\code.exe
CommandLineArguments='--user-data-dir="%PAL:DataDir%\code" --extensionHomePath="%PAL:DataDir%\code\extensions"'
DirectoryMoveOK=yes
DisableSplashScreen=true
SplashTime=0
SupportsUNC=yes
MinOS=7

[Environment]
VSCODE_HOME=%PAL:DataDir%\code

[DirectoriesCleanupIfEmpty]
1=%APPDATA%\Code
2=%USERPROFILE%\.vscode\extensions
3=%USERPROFILE%\.vscode
```

**Comment by sheldonhull** [comment]
Doing some reading on related discussion
https://github.com/Microsoft/vscode/issues/329

**Comment by shanalikhan** [comment]
Extension doenst support portable, Only supports Insiders and normal build

**Comment by yuki-takei** [comment]
@shanalikhan 

I also hope this extension respects `--user-data-dir=` and `--extension-dir=`.
These are official options.

```
$ code --help
Visual Studio Code 1.9.0

Usage: code.exe [options] [paths...]

Options:
  -d, --diff                  Open a diff editor. Requires to pass two file
                              paths as arguments.
  -g, --goto                  Open the file at path at the line and character
                              (add :line[:character] to path).
  --locale <locale>           The locale to use (e.g. en-US or zh-TW).
  -n, --new-window            Force a new instance of Code.
  -p, --performance           Start with the 'Developer: Startup Performance'
                              command enabled.
  -r, --reuse-window          Force opening a file or folder in the last active
                              window.
  --user-data-dir <dir>       Specifies the directory that user data is kept
                              in, useful when running as root.
  --verbose                   Print verbose output (implies --wait).
  -w, --wait                  Wait for the window to be closed before
                              returning.
  --extensions-dir <dir>      Set the root path for extensions.
  --list-extensions           List the installed extensions.
  --show-versions             Show versions of installed extensions, when using
                              --list-extension.
  --install-extension <ext>   Installs an extension.
  --uninstall-extension <ext> Uninstalls an extension.
  --disable-extensions        Disable all installed extensions.
  --disable-gpu               Disable GPU hardware acceleration.
  -v, --version               Print version.
  -h, --help                  Print usage.
```

I think the same issue should be occured even when users uses insiders or normal build.

scenario
---------

> Why using portable build if this extension will sync all the extension and user folder :)

I'm using VSCode in 3 different situations.

1. development for Angular
    * includes some extensions for Angular 2
1. development for Rails
    * includes some extensions for Ruby on Rails
1. markdown editor
    * includes some markdown editor extension

There are many many extensions in VSCode Marketplace.
Some extensions are stable, but some things may be unstable.
I'd like to keep a split VSCodes.

And I'd like to change keybinds a little only when I use VSCode as markdown editor if it possible.
