### ISSUE TITLE
keybindings does not get synced

### ISSUE THREAD

**Issue by Ilyes512** [shanalikhan/code-settings-sync#202]
**Visual Studio Code Version :** 1.8.1
**Code Sync Settings Version :** 2.4.2
**Operating System :** MacOS 10.12.2
**Occurs On:** Upload
**Proxy Enabled:** No

When I sync my config it does not upload the keybindings. My current keybindings consist of 4 overwrites. I only see 1 of them in my private gist. The `keybindings.json` is empty while `keybindingsMac.json` consists of 1 of the 4 maps.

Anyone else experiencing this?

**Comment by shanalikhan** [comment]
Duplicate https://github.com/shanalikhan/code-settings-sync/issues/194
Post there.

**Comment by shanalikhan** [comment]
Its fixed in the newer version. Let me know if you have problem
