### ISSUE TITLE
Getting shared settings from a public GIST ID without Personal Access Token.

### ISSUE THREAD

**Issue by marcevrard** [shanalikhan/code-settings-sync#203]
Computer A
**Visual Studio Code Version :** 1.8.1
**Code Sync Settings Version :** 2.4.3
**Operating System :** macOS 10.12.3
**Proxy Enabled:** No

Computer B
**Visual Studio Code Version :** 1.8.1
**Code Sync Settings Version :** 2.4.3
**Operating System :** Ubuntu 16.04.1
**Occurs On:** Download
**Proxy Enabled:** No

I have 2 computers running VSCode and I need to save the configuration on only one of them (A), the other (B) would just receive the setting changes).
I followed the procedure to make the gist public one the computer A and I reset the extension on the computer B.
Now, when I try to download the settings on B, the extension first requests the GIST personal access token (PAT), before the GIST ID (even though the latter is public).
Does that mean that I cannot just add a GIST ID, I need to have a PAT with a different GIST account for B, in order to receive the shared settings from A without allowing for the setting changes from B to be recorded?

**Comment by euconectei** [comment]
+1

Computer (A)
Visual Studio Code Version : 1.8.1
Code Sync Settings Version : 2.4.3
Operating System : macOS 10.12.3
Proxy Enabled: No

Computer (B)
Visual Studio Code Version : 1.8.1
Code Sync Settings Version : 2.4.3
Operating System : Win 10 Build 14393
Occurs On: Download
Proxy Enabled: Yes

**Comment by shanalikhan** [comment]
I will see what can be done for syncing the public gist without the token.
Thanks for the scenario !

**Comment by shanalikhan** [comment]
Public build released v2.4.4 Fixing this issue
Let me know if there is some problem.

**Comment by marcevrard** [comment]
Thanks for the quick fix!
It works very fine both on my macOS and Ubuntu.
Though it seems I'm not able to configure sync to autoload at startup on the "slave" for some reasons. No time now, I'll investigate that further later on.

**Comment by shanalikhan** [comment]
Yes, i figured it out. Fixed it
Will be release in the next version
