### ISSUE TITLE
Extensions won't sync. Settings sync sometimes.

### ISSUE THREAD

**Issue by fdncred** [shanalikhan/code-settings-sync#204]
**Visual Studio Code Version :** 1.8.1
**Code Sync Settings Version :** 2.4.3
**Operating System :** Windows 10 Enterprise, Version 1607, Build 14393.693
**Occurs On:** Download
**Proxy Enabled:** Yes

I can't get extensions to sync.  The settings file sync works sometimes but is a little glitchy too. I can make a change to my settings.json, then upload the new settings with Shift-Alt-U on one system.  Then I go to another system and hit Shift-Alt-D and it says I already have the latest version of saved settings, which clearly is not true.

I can work around this settings sync problem.  What really bothers me is that the extensions never sync. I am attaching a log file that I saved from the Developer Tools window. Hopefully it will help diagnose what's going on. Here is the log [sync.txt](https://github.com/shanalikhan/code-settings-sync/files/747911/sync.txt).

Thanks,
Darren

**Comment by GertjanReynaert** [comment]
@fdncred had the same issue on my new mac (downloading settings from my old machine). As a workaround I used the `Force download` setting in `advanced settings`.

**Comment by fdncred** [comment]
@GertjanReynaert I have tried Force download several times and it never works for me. I just tried again and it downloaded my settings but still pukes on Extensions.

**Comment by shanalikhan** [comment]
I have already opened on issue https://github.com/shanalikhan/code-settings-sync/issues/123 about extensions and now this is the code API limitation, I have opened an issue for feature request to allow API to get that information. You can comment there in vs code issue and let team know that we need it :)

Force Download will forcefully download the settings. Keep that option turn ON i will see what can be done for that.

**Comment by fdncred** [comment]
I guess I wasn't clear in describing my problem.  I'm not sure how it is the same as #123.  Here's one more try.

1. System 1 has 10 extensions installed.
2. System 2 has 0 extensions installed.
3. I install your extension on system 2.  I expect all settings and all extensions to be sync'd.
4. No extensions are sync'd regardless of Force Download setting. Settings are sync'd.
5. System 2 only has 1 extension installed, the sync extension.

My question is, how do I make system 2 sync all my extensions that System 1 has.

**Comment by shanalikhan** [comment]
Can you please share your GIST from which you uploaded the settings from System 1

**Comment by fdncred** [comment]
I tried to make it public. Hopefully it worked.

https://gist.github.com/fdncred/72011c63827876a198dc15e3e81cbcbe

**Comment by fdncred** [comment]
@shanalikhan See anything wrong with my gist settings?

**Comment by shanalikhan** [comment]
I have just checked now and it did installed all your settings and extensions. 

U need to sync settings using this extension every time when you install any extension.

Is there any console log in the code ? when you sync

**Comment by fdncred** [comment]
I attached the log (sync.txt) in the original thread.

**Comment by fdncred** [comment]
Did the previously attached sync.txt reveal anything interesting?

**Comment by shanalikhan** [comment]
@fdncred i am unable to reproduce this, also the logs you mentioned has stack trace only in the electron not in the extension. The error is mostly about socket connection unable to connect.
Make sure you have internet settings fine for computer and code.
What more we can do it, after opening code clear the logs that are maintained in the developer console. Try hitting `sync:upload` or other command and see the error in the developer console and then paste it.

**Comment by Kenya-West** [comment]
Same here, doesn't sync extensions

**Comment by pciavald** [comment]
same issue with this gist https://gist.github.com/pciavald/816cbcdff7619d7c4adf110dceb0e5e9

settings downloaded but extensions don't install

**Comment by shanalikhan** [comment]
https://github.com/shanalikhan/code-settings-sync/issues/668
