### ISSUE TITLE
Download fails after initial sync

### ISSUE THREAD

**Issue by agross** [shanalikhan/code-settings-sync#206]
**Visual Studio Code Version :** 1.9.0
**Code Sync Settings Version :** 2.3.4
**Operating System :** Windows 10
**Occurs On:** Download
**Proxy Enabled:** No

After installing the extension and uploading for the first time the settings.json snippet is created like this

```json
{
    "sync.gist": "some hash",
    "sync.lastUpload": "2017-02-03T09:38:55.389Z",
    "sync.autoDownload": false,
    "sync.autoUpload": false,
    "sync.lastDownload": null,
    "sync.version": 243,
    "sync.showSummary": true,
    "sync.forceDownload": false,
    "sync.workspaceSync": false,
    "sync.anonymousGist": false
}
```

VS puts squigglies on `"sync.lastDownload": null,` expecting a string.

When I try to download, the extension fails at `let lastDownloadStr: string = syncSetting.lastDownload.toString(): Cannot read property toString of undefined`.

Why am I reporting this?

My production VS Code instance doesn't download any changes, even when there is a newer version available. My json always has January, 1st 1970 as the last download date:

```json
{
    "sync.gist": "c6a31b72704b476730646876caaa7140",
    "sync.lastUpload": "2017-02-03T01:41:59.676Z",
    "sync.autoDownload": true,
    "sync.autoUpload": true,
    "sync.lastDownload": "1970-01-01T00:00:00.000Z",
    "sync.version": 243,
    "sync.showSummary": true,
    "sync.forceDownload": false,
    "sync.workspaceSync": false,
    "sync.anonymousGist": false,
}
```

And I was trying to debug why it doesn't download.

**Comment by agross** [comment]
After manually setting `"sync.lastDownload": "1970-01-01T00:00:00.000Z"`, the next debug run shows that VS Settings Sync does indeed read the Gist as `cloudSettGist`, but it doesn't access its properties to check whether a newer version is online. A search for `cloudSettGist` at least doesn't yield any results in `extension.ts`.

![2017-02-03_11-03-47](https://cloud.githubusercontent.com/assets/16245/22587185/e865ed46-ea00-11e6-8065-4000d21ea0dd.png)

So `stat` is always true because `syncSetting.lastDownload 1.1.1970 === cloudSett.lastUpload 1.1.1970`.

**Comment by agross** [comment]
My next try was to manually set `"sync.lastDownload": "2007-01-01T00:00:00.000Z"`. It downloaded / synced from GH, but after reset to `"sync.lastDownload": "1970-01-01T00:00:00.000Z"`.

**Comment by shanalikhan** [comment]
Thanks, you can search cloud setting in whole folder and see how its adding in the GIST.
Great to know you have debugged it
Send me a pull request once you solve the issue =)

**Comment by agross** [comment]
> Thanks, you can search cloud setting in whole folder and see how its adding in the GIST.

What do you mean by that?

**Comment by shanalikhan** [comment]
Thanks, I will release this in newer version with other fixes.
