### ISSUE TITLE
Unable to Save Settings

### ISSUE THREAD

**Issue by v2beta** [shanalikhan/code-settings-sync#207]
**Visual Studio Code Version :** [ 1.9.0 ]
**Code Sync Settings Version :** [ 2.4.3 ]
**Operating System :** [ VERSION_HERE ]
**Occurs On:** [Upload / Download]
**Proxy Enabled:** [ Yes / No ]

i was upgrade visual studio code to 1.9.0 version and sync settings plugins upload/download crash everytime, i uninstall/install plugins but not work.

-> Sync : Unable to Save Settings. Please make sure you have valid JSON settings.json file. ( e.g : No trailing commas )

**Comment by shanalikhan** [comment]
The message is clear.

**Make sure you dont have trailing commas in settings.json file and its valid JSON**
