### ISSUE TITLE
sync appears to be saving to .config/Code not .config/Code - OSS (headmelted)

### ISSUE THREAD

**Issue by tforster** [shanalikhan/code-settings-sync#209]
**Visual Studio Code Version :** 
Version 1.8.0
Commit 0e62d7ebdb06a825d57a65f96f9b396f4d298920
Date 2016-11-27T10:45:09.406Z
Shell 1.4.6
Renderer 53.0.2785.143
Node 6.5.0
Compiled for ARM as Code - OSS (headmelted)
**Code Settings Sync Version :** 2.4.3
**Operating System :** Ubuntu 16 with XFCE 4 running in a chroot on ChromeOS Version 56.0.2924.87 beta
**Occurs On:** Downloading Settings
**Proxy Enabled:** No
**GIst Id:** Version 56.0.2924.87 beta

I am running VSCode 1.8.0 compiled for ARM from https://code.headmelted.com/. The title bar and help dialog box indicate the app name is Code - OSS (headmelted) and not simply Code as if you had downloaded from MS. It appears that this version is storing data to .config/Code - OSS (headmelted)/User rather than the more typical .config/Code/User. 

FYI, I use (and love) this extension on Windows 10, Ubuntu and ChromeOS on a Dell Chromebook. It's just this little Asus Flip that is giving me grief.

**Comment by shanalikhan** [comment]
This extension only supports Normal and Insiders build. :)
