### ISSUE TITLE
Other installations of VS Code 1.9.0 ignore new settings

### ISSUE THREAD

**Issue by sqnkov** [shanalikhan/code-settings-sync#210]
**Visual Studio Code Version :** 1.9.0
**Code Settings Sync Version :** 2.4.3
**Operating System :** Windows 10
**Occurs On:** Download
**Proxy Enabled:** ??
**GIst Id:** *

I get this `You already have the latest...` notification on my other machines, but the settings that I have uploaded trough my main working machine are not the same. 

No matter what I change / remove / update on one machine - Sync tells me that there are no new settings to download on other machines.

**Comment by bigslycat** [comment]
I confirm.
**Visual Studio Code Version**: 1.10.0-insider
**Code Settings Sync Version**: 2.4.3
**Operating System**: Ubuntu 16.10
**Occurs On**: Download
**Proxy Enabled**: No

**Comment by shanalikhan** [comment]
Try with Sync : Advance Options > Toogle Force Download and turn it to ON.

**Comment by sqnkov** [comment]
Strange, I didn't get a notification about your reply. I will try it later in the day when I get back home and will report back. 

If anyone else already tried the Force Download option, please provide some feedback here.

**Comment by carpjaco** [comment]
I had the same problem. I'm not sure it's limited to VS Code 1.9, as my work system was on 1.8.1. Toggling the Force Download setting to ON did work though.

**Comment by shanalikhan** [comment]
Anyone from you guys have code insiders, i can push a version for insiders fixing this issue and then releasing for public.

**Comment by shanalikhan** [comment]
Its fixed, Public build released. v2.4.4
Let me know if there is still an issue.
