### ISSUE TITLE
What is workspace sync?

### ISSUE THREAD

**Issue by shawnlan** [shanalikhan/code-settings-sync#212]
I'm new to VS Code. It's not very clear what workspace sync does. I have .vscode for each project. I don't see files under .vscode get synced. Your documentation mentioned workspaceStorage. What is it for?

Also, autoUpload seems not working. I'm running on Mac El Captain, VS Code 1.9.1. Every time I saved settings.json, the developer console showed: `extensionHost.ts:282[Extension Host] (node:15059) Warning: Possible EventEmitter memory leak detected. 11 deploy.config.reloaded listeners added. Use emitter.setMaxListeners() to increase limit`

**Comment by shanalikhan** [comment]
> I have .vscode for each project. I don't see files under .vscode get synced.
This extension only sync `User` folder of code that contains workspaceStorage folder.

I will check the autoUpload issue

**Comment by shawnlan** [comment]
Thanks!

So what does workspaceStorage store? My workspaceStorage has no files. I want to know what `workspaceSync` set to true will do.

**Comment by shanalikhan** [comment]
it will sync the `workspaceStorage` folder also when set to true

**Comment by shawnlan** [comment]
Looks like forceDownload set to true will break autoUpload.
