### ISSUE TITLE
Error: Unable to Save Settings. Please make sure you have valid JSON settings.json file.

### ISSUE THREAD

**Issue by ahmetalpbalkan** [shanalikhan/code-settings-sync#214]
**Visual Studio Code Version :** 1.9.1
**Code Settings Sync Version :** 2.4.3
**Operating System :** macOS 10.12.3
**Occurs On:** Download/For
**Proxy Enabled:** No
**GIst Id:** c20f6d5380818c9d002692d1f2a20900

When I run `> Sync: Update / Upload Settings` or `> Sync: Download Settings`, I get error:

    Unable to Save Settings. Please make sure you have valid JSON settings.json file. ( e.g : No trailing commas )e.doShow @ messageService.ts:126
messageService.ts:126Error Logged In Console (Help menu > Toggle Developer Tools). You may open an issue using 'Sync : Open Issue' from advance setting command.e.doShow @ messageService.ts:126

after a while it turns into:

    Cannot read property 'toString' of undefined: TypeError: Cannot read property 'toString' of undefined

Here is a screenshot:

> 
![image](https://cloud.githubusercontent.com/assets/159209/22909014/63f6c202-f206-11e6-9aaf-c8c9af68404d.png)

Console:

> 
![image](https://cloud.githubusercontent.com/assets/159209/22908998/519e995e-f206-11e6-8665-5a7d5e7587a4.png)

My `settings.json`:

```json
...
// Place your settings in this file to overwrite the default settings
{
    "sync.gist": "c20f6d5380818c9d002692d1f2a20900",
    "sync.lastUpload": null,
    "sync.autoDownload": false,
    "sync.autoUpload": false,
    "sync.lastDownload": "1970-01-01T00:00:00.000Z",
    "sync.version": 243,
    "sync.showSummary": true,
    "sync.forceDownload": false,
    "sync.workspaceSync": false,
    "sync.anonymousGist": false,
}
```

**Comment by ahmetalpbalkan** [comment]
Wow it looks like indeed there's a trailing `,` at the last line of JSON as the error says.

I don't think I edited `settings.json` myself. Is there a chance the extension is doing this mistake?

**Comment by shanalikhan** [comment]
No extension doesn't do this by mistake.
This error will be resolved in next cosw version most probably
