### ISSUE TITLE
can't sync the settings

### ISSUE THREAD

**Issue by LuHua10** [shanalikhan/code-settings-sync#215]
**Visual Studio Code Version : 1.9.1
**Code Settings Sync Version : 2.4.3
**Operating System : 10.12.3
**Occurs On: Download
**Proxy Enabled: no
**GIst Id: 86486e96b86b93393662cc9877e3677d

error message:
{"message":"Bad credentials","documentation_url":"https://developer.github.com/v3"}

I can't download the setting 

i am sure the account and gist id are correct

thanks for your reply

**Comment by shanalikhan** [comment]
sometimes it happens alot of users face such problem in github token, this is the their API exception , you need to create new token and try again
