### ISSUE TITLE
sync works once, then stops

### ISSUE THREAD

**Issue by deccos** [shanalikhan/code-settings-sync#216]
**Visual Studio Code Version :** [ 1.9.1 ]
**Code Settings Sync Version :** [ 2.4.3 ]
**Operating System :** [ Windows 10 ]
**Occurs On:** [Upload ]
**Proxy Enabled:** [ No ]
**GIst Id:** [ 400ed6574beaa6c0a7f890132ba39978 ]

I set it up, enter my access key from github, it tells me it syncs OK.  But later, when i have exited and restarted VSCode, it fails to sync.  I get this message in the dev tools:

[1487115427523.TXT](https://github.com/shanalikhan/code-settings-sync/files/775588/1487115427523.TXT)

**Comment by shanalikhan** [comment]
Check the solution here
https://github.com/shanalikhan/code-settings-sync/issues/177
