### ISSUE TITLE
Error Logged In Console (Help menu > Toggle Developer Tools). You may open an issue using 'Sync : Open Issue' from advance setting command.

### ISSUE THREAD

**Issue by xionglongjun** [shanalikhan/code-settings-sync#217]
**Visual Studio Code Version :** [ 1.9.1]
**Code Settings Sync Version :** [ 243 ]
**Operating System :** [ win 10]
**Occurs On:** [Upload / Download / Setting Up]
**Proxy Enabled:** [ Yes / No ]
**GIst Id:** [e71e92f48d819fcd3558a34be5b6d5353b692958 ]

Error Logged In Console (Help menu > Toggle Developer Tools). You may open an issue using 'Sync : Open Issue' from advance setting command

**Comment by shanalikhan** [comment]
Please write the senario what u were trying and what is error logged in developer console

**Comment by joneqing** [comment]
I have got same question: {"message":"Bad credentials","documentation_url":"https://developer.github.com/v3"}

**Comment by shanalikhan** [comment]
@joneqing Check this out https://github.com/shanalikhan/code-settings-sync/issues/177
