### ISSUE TITLE
keybindings.json uploaded on win7, however, it is not downloaded on ubuntu

### ISSUE THREAD

**Issue by jonygli** [shanalikhan/code-settings-sync#220]
**Visual Studio Code Version :** [ 1.9.1 ]
**Code Settings Sync Version :** [ 2.4.3 ]
**Operating System :** [ ubuntu 16 ]
**Occurs On:** [ Download ]
**Proxy Enabled:** [ Yes  ]
**GIst Id:** [ 4f15b34b7eed738e4854cb6f37409b73 ]

keybindings.json uploaded on win7, however, it is not downloaded on ubuntu

I have posted frequently asked questions on 
http://shanalikhan.github.io/2016/11/07/visual-studio-code-frequently-asked-questions.html 
so you may able to resolve the error quickly. 
Please make sure to write the versions and console logged error picture or copied text

**Comment by shanalikhan** [comment]
any exception, or error logged in code?
