### ISSUE TITLE
Customize Gist Title?

### ISSUE THREAD

**Issue by Reificator** [shanalikhan/code-settings-sync#222]
**GIst Id:** 25be31225c271a74932cf720cd3a6f6b

I've been trying to customize the Gist title from `cloudSettings` to `VS Code Settings`, because there are a lot of possible things I might keep settings around for.  However it appears to be dependent on the name of the first file in the Gist.

Presumably the `cloudSettings` file needs to have that name for proper synchronization to occur.  So instead I tried making a new Gist with a single empty file, gave it my desired name, and synchronized with that Gist.  Unfortunately, the file was removed upon the first upload.

Is there anything we can do here to customize the name of the Gist, without getting too hackey?

**Comment by shanalikhan** [comment]
For this i have to rename `cloudSettings` and after renaming any other file could take first place due to order by extension uploading so its not possible only description was allowed by Github so i have already added it.

**Comment by Reificator** [comment]
That's what I figured, but I thought I'd ask just in case.  Thanks for taking the time to reply.
