### ISSUE TITLE
Using CHANGELOG.md will be better

### ISSUE THREAD

**Issue by neilsustc** [shanalikhan/code-settings-sync#224]
As vscode docs [Publishing Tool Reference#advanced-usage](http://code.visualstudio.com/docs/tools/vscecli#_advanced-usage) suggest,

> A `CHANGELOG.md` file at the root of your extension will be used as the contents for the extension's changelog.

It is convenient to see the changelog within vscode extension page. Also the file hosted by GitHub can be easily linked to your blog. 😄

**Comment by shanalikhan** [comment]
Thanks! Will look forward in future.

**Comment by shanalikhan** [comment]
> Also the file hosted by GitHub can be easily linked to your blog

Can you explain this :smile: 
As if i add changelog i have to add in blog also

**Comment by neilsustc** [comment]
The easiest way is just posting the GitHub file link in your blog.
For example, <https://github.com/shanalikhan/code-settings-sync/blob/master/README.md> will looks like this
![image](https://cloud.githubusercontent.com/assets/7588612/26528484/a70b9042-43df-11e7-97a5-f88a6a784e4a.png)

So in this case, it's `https://github.com/shanalikhan/code-settings-sync/blob/master/CHANGELOG.md`

---

Since you are using GitHub Pages, your blog post has the same content with `CHANGELOG.md`. You can just copy the file between your two repos 😂

**Comment by shanalikhan** [comment]
lol
okay Thanks
