### ISSUE TITLE
Ability to copy-paste between settings.json and syncLocalSettings.json for replaceCodeSettings

### ISSUE THREAD

**Issue by fredrikaverpil** [shanalikhan/code-settings-sync#225]
**Visual Studio Code Version :** Version 1.10.0-insider (1.10.0-insider)
**Code Settings Sync Version :** 2.4.4
**Operating System :** macOS Sierra / Windows 10
**Occurs On:** n/a
**Proxy Enabled:** No

I think the new `syncLocalSettings.json`'s `replaceCodeSettings` feature is fantastic.

A small improvement would be if you'd be able to just copy-paste between the two files. Example:

I have this in my `settings.json`:
```json
    "python.pythonPath": "${env.HOME}/miniconda3/envs/pythondev_35",
    "python.linting.pylintPath": "${env.HOME}/miniconda3/envs/pythondev_35/bin/pylint",
    "python.linting.pep8Path": "${env.HOME}/miniconda3/envs/pythondev_35/bin/pep8",
    "python.formatting.autopep8Path": "${env.HOME}/miniconda3/envs/pythondev_35/bin/autopep8",
    "python.formatting.yapfPath": "${env.HOME}/miniconda3/envs/pythondev_35/bin/yapf",
```

Right now in order to get this into `syncLocalSettings.json` you have to carefully reformat that into a list of dictionaries containing the `name` and `value` keys:

```json
{
    "replaceCodeSettings": [
        {
            "name": "python.pythonPath",
            "value": "${env.HOME}/miniconda3/envs/pythondev_35"
        },
        {
            "name": "python.linting.pylintPath",
            "value": "${env.HOME}/miniconda3/envs/pythondev_35/bin/pylint"
        },
        {
            "name": "python.linting.pep8Path",
            "value": "${env.HOME}/miniconda3/envs/pythondev_35/bin/pep8"
        },
        {
            "name": "python.formatting.autopep8Path",
            "value": "${env.HOME}/miniconda3/envs/pythondev_35/bin/autopep8"
        },
        {
            "name": "python.formatting.yapfPath",
            "value": "${env.HOME}/miniconda3/envs/pythondev_35/bin/yapf"
        }
    ]
}

```

**Comment by shanalikhan** [comment]
I think a way can be add option in Advanced Options.
To allow user to ignore file or setting and user need to enter the key and it will copy the key and value to that file.

**Comment by fredrikaverpil** [comment]
> and user need to enter the key and it will copy the key and value to that file

I would personally prefer to be able to manually edit this file more easily. However, since the functionality of overriding settings is already implemented, this is just a cosmetic feature, making it nicer to use.

**Comment by shanalikhan** [comment]
I have added it.
If you have any suggestion to improve it. 
Free free to let me know :)

**Comment by borekb** [comment]
How does it work? I've tried:

```json
"replaceCodeSettings": {
    "window.zoomLevel": 3
}
```

but it doesn't have any effect. (I'm on 2.5.0.)

**Comment by shanalikhan** [comment]
```
"replaceCodeSettings": {
    { "name :"",
       "value":2
    }
}
```

**Comment by borekb** [comment]
@shanalikhan That example worked in 2.4, I thought the point of this issue was that you would be able copy & paste from user settings _exactly_, without the need to transforming it to the `name` and `value` pairs. Right, @fredrikaverpil?

**Comment by shanalikhan** [comment]
Yes i will know about it, will change in next version.

**Comment by shanalikhan** [comment]
I have pushed newer version for this layout.
Old setting file will be deleted
You need to set settings on new one
@borekb 
@fredrikaverpil

**Comment by fredrikaverpil** [comment]
@shanalikhan whohoo! it works!

This is so beautiful. I suddently have somewhat of a cross-platform vscode setup thanks to this. :smile:
