### ISSUE TITLE
Support comments in syncLocalSettings.json

### ISSUE THREAD

**Issue by fredrikaverpil** [shanalikhan/code-settings-sync#226]
**Visual Studio Code Version :** Version 1.10.0-insider (1.10.0-insider)
**Code Settings Sync Version :** 2.4.4
**Operating System :** macOS Sierra / Windows 10
**Occurs On:** n/a
**Proxy Enabled:** No

It would be great to be able to use comments (`// comment`) in `syncLocalSettings.json`. Right now you get an error if you do this. The error is triggered on upload in this case.

![screen shot 2017-02-19 at 16 03 53](https://cloud.githubusercontent.com/assets/994357/23103564/0b3f1306-f6bd-11e6-9cda-5ca892b15d28.png)

**Comment by shanalikhan** [comment]
Why would you need any comments =) in this small JSON that will only contains the file names ?

**Comment by fredrikaverpil** [comment]
I was planning on creating a quite long file if #227 was implemented. But since that's closed, I agree comments might not be needed. It's just one of those things that are "nice to have", not "must have".
