### ISSUE TITLE
Cross-platform compatibility in syncLocalSettings.json

### ISSUE THREAD

**Issue by fredrikaverpil** [shanalikhan/code-settings-sync#227]
**Visual Studio Code Version :** 1.10 insiders
**Code Settings Sync Version :** 2.4.4
**Operating System :** macOS Sierra, Windows 10

Vscode does not offer a way to specify settings on a per-operating system basis. However, it seems perhaps this functionality could get added into the `syncLocalSettings.json`?

So let's say I wish to define a Python interpreter path on my Mac and another path on Windows:

```json
{
    "ignoreUploadFiles": [
        "projects.json",
        "projects_cache_git.json"
    ],
    "ignoreUploadFolders": [
        "workspaceStorage"
    ],
    "replaceCodeSettings": [
        {
            "name": "python.pythonPath",
            "value": "Users/foo/miniconda3/envs/pythondev_35",
            "platform": "osx"
        },
        {
            "name": "python.pythonPath",
            "value": "C:/Python35/",
            "platform": "windows"
        }
    ]
}
```

Just as a note, when taking #225 into account it may look something like this instead:

```json
{
    "ignoreUploadFiles": [
        "projects.json",
        "projects_cache_git.json"
    ],
    "ignoreUploadFolders": [
        "workspaceStorage"
    ],
    "replaceCodeSettings": [
        {
            "platform": {
                "osx": {
                    "python.pythonPath": "Users/foo/miniconda3/envs/pythondev_35"
                },
                "windows": {
                    "python.pythonPath": "C:/Python35/"
                }
            }
        }
    ]
}
```

**Comment by shanalikhan** [comment]
Will do it in next release

Thanks!

**Comment by shanalikhan** [comment]
This file will not be sync. Will be present for both platforms. 
Its better to set
```
{
"name": "python.pythonPath",
"value": "C:/Python35/"
}
```
for one PC , and other file on second PC.

Your both computer will have separate file and will have its own settings that will be already OS dependent for that computer only.

Why would be a need to keep the MAC file settings in Windows Machine if Extension is always going to use Windows Settings and replace that windows settings in settings.json, and for second PC MAC, it will always be using Mac keys and values and wont use Windows Keys?
So its better to define windows keys in Windows Machine, and MAC Python path in mac machine so extension on both computer will use its own file and write those OS dependent paths.
