### ISSUE TITLE
Add palette command to edit `syncLocalSettings.json`

### ISSUE THREAD

**Issue by borekb** [shanalikhan/code-settings-sync#229]
**Visual Studio Code Version :** 1.9
**Code Settings Sync Version :** 2.4.4

There's `syncLocalSettings.json` since 2.4.4, see https://github.com/shanalikhan/code-settings-sync/issues/100. It would be nice if there was something like `Sync: edit local settings` palette command to open it quickly.

**Comment by shanalikhan** [comment]
Yes, it will be added on advance options.

**Comment by shanalikhan** [comment]
Fixed on v2.5.0 
Update ! 😄
