### ISSUE TITLE
Error : ERROR ! Logged In Console. Please open an issue in Github Repo.

### ISSUE THREAD

**Issue by ethyde** [shanalikhan/code-settings-sync#23]
Hi,

I try to use this extension for the first time, but after adding my token this error prompt. I don't see anything in error & warning or debug console.

![error_vscode](https://cloud.githubusercontent.com/assets/409987/14241389/87a107c0-fa4b-11e5-90c3-8870ed24b870.jpg)

What can i do ? :)

VS Code version : 0.10.11

**Comment by shanalikhan** [comment]
Are you sure, you are using the latest version of Extension.?
As i have recently fixed this issue in the last update
 #19

**Comment by ethyde** [comment]
My blame... sorry.
