### ISSUE TITLE
Download settings error

### ISSUE THREAD

**Issue by JamesBliss** [shanalikhan/code-settings-sync#236]
**Visual Studio Code Version :** Version 1.9.1 (1.9.1)
**Code Settings Sync Version :** 2.4.4 
**Operating System :** macOS sierra 10.12.3
**Occurs On:** Download
**Proxy Enabled:** No
**GIst Id:** af461cc409aef03d3ca7fa0ec6c34c4b43c47094

When I try to download synced settings I get a:

`Error Logged In Console (Help menu > Toggle Developer Tools). You may open an issue using 'Sync : Open Issue' from advance setting command.`

When I open console I am greeted with

`extensionHost.ts:282 [Extension Host] {"message":"Not Found","documentation_url":"https://developer.github.com/v3"}`

No other information. It is a fresh install of Visual Studio Code with only Settings Sync installed.

**Comment by shanalikhan** [comment]
This error pop up when GIST not found.
Try updating the GIST in settings.json and update =)

**Comment by JamesBliss** [comment]
Ah, wow. Thought I had copied the URL from one machine to the other.

My bad, me being stupid.

Thanks for quick reply
