### ISSUE TITLE
"Sync: Open issue" is missing?

### ISSUE THREAD

**Issue by ahmetalpbalkan** [shanalikhan/code-settings-sync#237]
I just got this error:

![image](https://cloud.githubusercontent.com/assets/159209/23274655/6b7d5770-f9b8-11e6-9f86-e016b808a649.png)

![image](https://cloud.githubusercontent.com/assets/159209/23274650/688b2222-f9b8-11e6-9738-501992c878b8.png)

Is this feature missing currently?

**Comment by shanalikhan** [comment]
No, Open through "Sync : Advance Options"
