### ISSUE TITLE
Don't commit vsix files

### ISSUE THREAD

**Issue by felixfbecker** [shanalikhan/code-settings-sync#24]
Commiting all versions of the vsix files is a bad idea. They are zip files that contain all dependencies (node_modules) and can be very large. They are binary so they are not handled by git well. Your repo will quickly grow to infinity. Instead, I recommend you to use GitHub's releases system. It uses git tags and you can add binaries like vsix files.

Awesome plugin though!

**Comment by shanalikhan** [comment]
Thank you for your suggestion. I have changed the repository accordingly
