### ISSUE TITLE
Sync Downloads fails / unable to reset

### ISSUE THREAD

**Issue by minthemiddle** [shanalikhan/code-settings-sync#240]
**Visual Studio Code Version :** 1.9.1
**Code Settings Sync Version :** 2.5.1
**Operating System :** OSX 10.12.3
**Occurs On:** Download/Setting up
**Proxy Enabled:** No
**GIst Id:** 566ae75453f734e4b6b9939bd545261

I have Sync set up on three Macs. Syncing just does not work on machine 3 (this issue's machine). Whenever I try to download settings, I get the error displayed in below log.

It asks me to insert `gist id`. Even after trying to reset it via `Sync: Reset Extension Settings`, I do not get back to insert my Git token or Gist.

I even tried to completely uninstall and reinstall VSCode via `brew uninstall --force` and AppDelete. But that did not solve the problem either. I think there are some settings that the uninstaller did not remove.

```log
//Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:133 [Extension Host] {"message":"Not Found","documentation_url":"https://developer.github.com/v3"}
d.logExtensionHostMessage	@	//Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:133
(anonymous function)	@	//Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:133
emitTwo	@	events.js:106
emit	@	events.js:191
process.nextTick	@	internal/child_process.js:744
_combinedTickCallback	@	internal/process/next_tick.js:67
_tickCallback	@	internal/process/next_tick.js:98
```

**Comment by shanalikhan** [comment]
can you share the link for your GIST ? or try with new GIST

**Comment by minthemiddle** [comment]
It works on three machines, so I don't want to try with a new GIST.

Here it is:

https://gist.github.com/minthemiddle/566ae75453f734e4b6b9939bd5452681
