### ISSUE TITLE
Command 'Git: Sync' is not enabled in the current context.

### ISSUE THREAD

**Issue by htmacau** [shanalikhan/code-settings-sync#246]
**Visual Studio Code Version :** [1.10.1]
**Code Settings Sync Version :** [ 2.5.1 ]
**Operating System :** [ Mac OS Sierra ]
**Occurs On:** [Download]
**Proxy Enabled:** [No ]
**GIst Id:** [15f17970716041fd1d971e3cca7e0755308a0c66]

I have posted frequently asked questions on 
http://shanalikhan.github.io/2016/11/07/visual-studio-code-frequently-asked-questions.html 
so you may able to resolve the error quickly. 
Please make sure to write the versions and console logged error picture or copied text

![untitled](https://cloud.githubusercontent.com/assets/19795434/23578563/cc890a9c-0114-11e7-9f7b-c5066e175de0.png)

**Comment by shanalikhan** [comment]
This extension doesnt have any command with Git: Sync
