### ISSUE TITLE
sync.workspaceSync is unknown configuration settings

### ISSUE THREAD

**Issue by kenwarner** [shanalikhan/code-settings-sync#247]
**Visual Studio Code Version :** 1.10.1
**Code Settings Sync Version :** 2.5.1
**Operating System :** MacOS
**Occurs On:** Settings Editing
**Proxy Enabled:** No

Did a setting change recently or something?

![image](https://cloud.githubusercontent.com/assets/829521/23592376/d99f7c5c-01cd-11e7-9077-64bb9b83103b.png)

**Comment by shanalikhan** [comment]
its deleted, you can remove it from settings.json
