### ISSUE TITLE
Not working with Insiders build

### ISSUE THREAD

**Issue by demyte** [shanalikhan/code-settings-sync#25]
**Visual Studio Code Version : 0.10.14-insider
**Code Sync Settings Version : 1.0.0

Please make sure to write the versions and console logged error picture or copied text.
===============================
Hi,

I am using the insiders build and it installs into a separate directory, and it looks like when I sync my settings down into it, they update the files in the directory C:\Users\jsummerton\AppData\Roaming\Code\User instead of C:\Users\jsummerton\AppData\Roaming\Code - Insiders\User

**Comment by shanalikhan** [comment]
you are using the 1.0.0 version of extension.
Currently version is 1.1.7.
Can you update the extension version and let me know.
#13

**Comment by demyte** [comment]
Hi,

Thanks for the prompt reply, updated and all fixed.
