### ISSUE TITLE
Error downloading setting

### ISSUE THREAD

**Issue by ssheeriin** [shanalikhan/code-settings-sync#250]
**Visual Studio Code Version :** [ 1.10 ]
**Code Settings Sync Version :** [ 2.5.1 ]
**Operating System :** [ Windows 10]
**Occurs On:** [ Download]
**Proxy Enabled:** [ Yes ]
**GIst Id:** [ b91e1c1628ecf116667c3f803cf52473 ]

Setting uploaded from vscode ubuntu 16.04

I have posted frequently asked questions on 
http://shanalikhan.github.io/2016/11/07/visual-studio-code-frequently-asked-questions.html 
so you may able to resolve the error quickly. 
Please make sure to write the versions and console logged error picture or copied text

**Comment by shanalikhan** [comment]
>  Please make sure to write the versions and console logged error picture or copied text

**Comment by rohmanhm** [comment]
same here .. v2.5.1
from **macOS Sierra**
