### ISSUE TITLE
unable to download settings

### ISSUE THREAD

**Issue by fasfsfgs** [shanalikhan/code-settings-sync#252]
**Visual Studio Code Version :** [ 1.10.2 ]
**Code Settings Sync Version :** [ 2.5.1 ]
**Operating System :** [ WINDOWS 7 ]
**Occurs On:** [ Download ]
**Proxy Enabled:** [ Yes ]
**GIst Id:** [0d87a08d899ac1e3563382b80ac9fe1a]

I get the following error when trying to download settings on windows 7 behind a proxy.
I upload the settings with a mac with no proxy.
I´m using "replaceCodeSettings" get the proxy config enabled.

[Extension Host] Windows_NT
extensionHost.ts:282 [Extension Host] C:\Users\thiago.almeida\AppData\Roaming/Code/User/keybindings.json
extensionHost.ts:282 [Extension Host] C:\Users\thiago.almeida\AppData\Roaming/Code/User/launch.json
extensionHost.ts:282 [Extension Host] C:\Users\thiago.almeida\AppData\Roaming/Code/User/locale.json
extensionHost.ts:282 [Extension Host] C:\Users\thiago.almeida\AppData\Roaming/Code/User/settings.json
messageService.ts:126 Error Logged In Console (Help menu > Toggle Developer Tools). You may open an issue using 'Sync : Open Issue' from advance setting command.e.doShow @ messageService.ts:126e.show @ messageService.ts:105(anonymous function) @ mainThreadMessageService.ts:64n.Class.derive._oncancel @ winjs.base.raw.js:1641t.showMessage @ mainThreadMessageService.ts:34t.$showMessage @ mainThreadMessageService.ts:28e.handle @ abstractThreadService.ts:34s @ ipcRemoteCom.ts:275f @ ipcRemoteCom.ts:231_combinedTickCallback @ internal/process/next_tick.js:67_tickCallback @ internal/process/next_tick.js:98
extensionHost.ts:282 [Extension Host] C:\Users\thiago.almeida\AppData\Roaming/Code/User/snippets/html.json
extensionHost.ts:282 [Extension Host] C:\Users\thiago.almeida\AppData\Roaming/Code/User/snippets/javascript.json
extensionHost.ts:282 [Extension Host] C:\Users\thiago.almeida\AppData\Roaming/Code/User/snippets/keybindingDefault.json
extensionHost.ts:282 [Extension Host] C:\Users\thiago.almeida\AppData\Roaming/Code/User/snippets/keybindingMac.json
extensionHost.ts:282 [Extension Host] C:\Users\thiago.almeida\AppData\Roaming/Code/User/snippets/typescript.json
extensionHost.ts:282 [Extension Host] C:\Users\thiago.almeida\AppData\Roaming/Code/User/vsicones.settings.json
extensionHost.ts:282 [Extension Host] C:\Users\thiago.almeida\AppData\Roaming/Code/User/vsicons.settings.json
extensionHost.ts:282 [Extension Host] SyntaxError: Unexpected end of JSON input
    at C:\Users\thiago.almeida\.vscode\extensions\Shan.code-settings-sync-2.5.1\out\src\pluginService.js:206:36
    at process._tickCallback (internal/process/next_tick.js:103:7)d.logExtensionHostMessage @ extensionHost.ts:282(anonymous function) @ extensionHost.ts:137emitTwo @ events.js:106emit @ events.js:191process.nextTick @ internal/child_process.js:744_combinedTickCallback @ internal/process/next_tick.js:67_tickCallback @ internal/process/next_tick.js:98

**Comment by shanalikhan** [comment]
1. whats in your `replaceCodeSettings` please share
2. Is Proxy settings defined in `replaceCodeSettings` added in `settings.json` ?

**Comment by fasfsfgs** [comment]
I'll get back to you on monday since I'm having problems at work.

**Comment by fasfsfgs** [comment]
Ok. I'm testing with a fresh vscode insiders instalation.

Before trying to sync, I put my proxy setting on vscode's `settings.json` so it can do stuff.

Then I install your extension and edit my `syncLocalSettings.json` to look like this:
```json
{"ignoreUploadFiles":["projects.json","projects_cache_git.json"],"ignoreUploadFolders":["workspaceStorage"],"replaceCodeSettings":{
    "http.proxy": "http://10.34.240.107:80"
}}
```

Then I try to sync passing my gist id and the error that I mentioned pops up.

After that I check again my `settings.json` and I see that my settings did get downloaded and my proxy setting defined in `replateCodeSettings` did **not** get added. Plus, my previous proxy setting is gone.

Let me know if I can assist you with any more information in order to solve this issue.

**Comment by fasfsfgs** [comment]
just tested on 2.6.1
the problem persists

**Comment by shanalikhan** [comment]
I will new version soon to view the logs in your machine to further evaluate.
Thanks for the patience 
Will update soon

**Comment by fasfsfgs** [comment]
That's alright. No worries. If I can help in any way, please let me know.

**Comment by shanalikhan** [comment]
i have released v2.6.2
> extensionHost.ts:282 [Extension Host] SyntaxError: Unexpected end of JSON input
at C:\Users\thiago.almeida.vscode\extensions\Shan.code-settings-sync-2.5.1\out\src\pluginService.js:206:36

Can you share the developer console window, i need the response whats coming in response that causing JSON parsing error.

**Comment by fasfsfgs** [comment]
Ah I'm on vacation now. I'll be back to work on april 17th, test this again and let you know.

**Comment by shanalikhan** [comment]
Okay, let me know when you can test it
