### ISSUE TITLE
Debug Console contains unconditional os.type() dump from this extension

### ISSUE THREAD

**Issue by bartosz-antosik** [shanalikhan/code-settings-sync#254]
**Visual Studio Code Version :** 1.10.2
**Code Settings Sync Version :** 2.5.1
**Operating System :** Windows 10
**Occurs On:** N/A
**Proxy Enabled:** N/A
**GIst Id:** N/A

Whenever VSCode is started in Extension Development Host os.type() result is dumped to the Debug Console. This happens in environmentPath.js line 38 (unconditional "console.log(os.type());"). 

It is confusing sometimes.

**Comment by shanalikhan** [comment]
Share the console screen.

**Comment by bartosz-antosik** [comment]
![vscode-debug-console](https://cloud.githubusercontent.com/assets/20492548/23762997/47373142-04f8-11e7-964c-5dacdd249b26.JPG)

**Comment by shanalikhan** [comment]
Thanks, Will be fixed in next version.

**Comment by shanalikhan** [comment]
Updated in 2.6.0 
Visible for code insiders.
