### ISSUE TITLE
Error download settings

### ISSUE THREAD

**Issue by whfadsx** [shanalikhan/code-settings-sync#255]
**Visual Studio Code Version :** [ 1.10.2 ]
**Code Settings Sync Version :** [ 251 ]
**Operating System :** [ Windows 10 ]
**Occurs On:** [ Download ]
**Proxy Enabled:** [ No ]
**GIst Id:** [ 77703a98db01d6a55d57bcc0590bd386 ]

![errorsyncsettings](https://cloud.githubusercontent.com/assets/19494216/23752391/e48de48a-04b3-11e7-975e-c2f4ea9da5fe.png)

I have posted frequently asked questions on 
http://shanalikhan.github.io/2016/11/07/visual-studio-code-frequently-asked-questions.html 
so you may able to resolve the error quickly. 
Please make sure to write the versions and console logged error picture or copied text

**Comment by shanalikhan** [comment]
>  Please make sure to write the versions and console logged error picture or copied text
