### ISSUE TITLE
Trouble syncing settings.

### ISSUE THREAD

**Issue by packruler** [shanalikhan/code-settings-sync#257]
**Visual Studio Code Version :** 1.10.2
**Code Settings Sync Version :** 2.5.1
**Operating System :** Mac 10.12.3
**Occurs On:** Upload and Download
**Proxy Enabled:** No
**GIst Id:** 647f880bbe5f8e581245313327b02234

I have posted frequently asked questions on 
http://shanalikhan.github.io/2016/11/07/visual-studio-code-frequently-asked-questions.html 
so you may able to resolve the error quickly. 
Please make sure to write the versions and console logged error picture or copied text

![screen shot 2017-03-14 at 10 53 02 am](https://cloud.githubusercontent.com/assets/770373/23906476/6f781130-08a4-11e7-8bed-332f72323ae4.png)

I get the above error message when trying to sync my settings. I am not going through a proxy.
Though I am not connecting through a proxy I am connecting from work but this happens when I have the ability to access the gist.

**Comment by packruler** [comment]
If you could tell me where this is logged I may be able to troubleshoot on my side.

**Comment by shanalikhan** [comment]
>  I see nothing in any of the tabs in the console.
its in the help > toogle develop console

Take the picture and post here.

**Comment by packruler** [comment]
Ah that's where it is...
![screen shot 2017-03-14 at 12 54 18 pm](https://cloud.githubusercontent.com/assets/770373/23912371/c2cb0ff2-08b5-11e7-8b9d-68f83b11a1a8.png)

First issue was using network that uses self-signed certs for everything. Is there anyway to bypass this check?

I am able to connect to a network that does not resign all certs and get following error.

![screen shot 2017-03-14 at 12 55 27 pm](https://cloud.githubusercontent.com/assets/770373/23912382/cb0e7906-08b5-11e7-9302-dcc8edb40442.png)

**Comment by shanalikhan** [comment]
can you please try this extension in code insiders.
I have updated github APi there so we will be sure its updated from github api :)

**Comment by packruler** [comment]
Ok I install extension v: 2.6.0 on VSCode Insiders: 1.11.0-insider and still get the same errors

**Comment by packruler** [comment]
Quick update. It randomly worked today...
Things that changed:
- Updated settings on a Windows pc that was syncing with the same gist (computer having issues is Mac)
- Connected to network that does not use self signed cert (the one that was throwing ECONNRESET error)
- Opened a new project
- Sync automatically triggered and worked.

This was using:
Visual Studio Code Version : 1.10.2
Code Settings Sync Version : 2.5.1

**Comment by packruler** [comment]
Unsurprisingly the issue has reappeared when I tried to sync again, under the same circumstances that it worked.

**Comment by shanalikhan** [comment]
try with settings "http.proxyStrictSSL": false
and Update

**Comment by shanalikhan** [comment]
Please check for version v2.6.1
and Update

**Comment by packruler** [comment]
Just to note this fix is working for me

**Comment by shanalikhan** [comment]
@packruler can you please confirm download and upload both are working fine, as one the other issue page user have problem in one side. ?

**Comment by packruler** [comment]
@shanalikhan Sadly I was mistaken... Upload is telling me I cannot edit Gist

**Comment by packruler** [comment]
It does appear to work. There is an error telling me it failed but that appears to be caused by another extension
![capture](https://cloud.githubusercontent.com/assets/770373/24111505/01fad08e-0d6d-11e7-989c-80bb40119877.PNG)
