### ISSUE TITLE
Error : Not Found

### ISSUE THREAD

**Issue by lizhuangs** [shanalikhan/code-settings-sync#259]
**Visual Studio Code Version :** [ 1.10.2]
**Code Settings Sync Version :** [ 2.5.1]
**Operating System :** [ win10]
**Occurs On:** [Upload/Download]
**Proxy Enabled:** [  No ]
**GIst Id:** [ 601a5ba4ed49bbb774178b7be2299e184770d8ca]

I have posted frequently asked questions on 
http://shanalikhan.github.io/2016/11/07/visual-studio-code-frequently-asked-questions.html 
so you may able to resolve the error quickly. 
Please make sure to write the versions and console logged error picture or copied text

I tried it many times and change gistid but only successed once .
i really dont know how to do it now.I already read "visual-studio-code-frequently-asked-questions.html ".please help me.

workbench.main.js:136 [Extension Host] typescript (vscode.typescript) uses PROPOSED API which is subject to change and removal without notice
workbench.main.js:136 [Extension Host] Windows_NT
workbench.main.js:136 [Extension Host] vscode-icons is active!
workbench.main.js:136 [Extension Host] Windows_NT
2workbench.main.js:136 [Extension Host] {"message":"Not Found","documentation_url":"https://developer.github.com/v3"}d.logExtensionHostMessage @ workbench.main.js:136
workbench.main.js:103 Error Logged In Console (Help menu > Toggle Developer Tools). You may open an issue using 'Sync : Open Issue' from advance setting command.e.doShow @ workbench.main.js:103

**Comment by shanalikhan** [comment]
Check this https://github.com/shanalikhan/code-settings-sync/issues/59

**Comment by lizhuangs** [comment]
maybe it cause by the GFW...I will try it again

**Comment by shanalikhan** [comment]
Ok let me know if there is problem, issue will be reopened

**Comment by lizhuangs** [comment]
github token with gist:
21644fbadd655b10defd1d04a25ab8af6c82f00d

and in my setting.json:
"sync.gist": "21644fbadd655b10defd1d04a25ab8af6c82f00d",
    "sync.lastUpload": "",
    "sync.autoDownload": false,
    "sync.autoUpload": false,
    "sync.lastDownload": "",
    "sync.version": 251,
    "sync.showSummary": true,
    "sync.forceDownload": false,
    "sync.anonymousGist": false

Is it right? and Can you try it?Tks!

**Comment by lizhuangs** [comment]
I think is maybe an issue,but I dont know why.when I input "Sync : Open Issue" there is nothing too.
the "Personal access tokens" shows that they are never used.It means they never connected success.I install "settings sync" again and angin,but It faild.I can only give up .maybe infuture,this problem will resolve.I will try it that time.

**Comment by lizhuangs** [comment]
I think it maybe an issue,but I dont know why.when I input "Sync : Open Issue" there is nothing too.
the "Personal access tokens" shows that they are never used.It means they never connected success.I install "settings sync" again and angin,but It faild.I can only give up .maybe infuture,this problem will resolve.I will try it that time.

**Comment by lizhuangs** [comment]
I think it maybe an issue,but I dont know why.when I input "Sync : Open Issue" there is nothing too.
the "Personal access tokens" shows that they are never used.It means they never connected success.I install "settings sync" again and angin,but It failed.I can only give up .maybe in future,this problem will resolve.I will try it that time.

**Comment by tombresson** [comment]
I'm having the same issue on macOS. It's weird because I successfully set it up on a Win 10 machine and a Win 7 machine, and those have been working for a while. Tried to set it up in macOS today and it doesn't seem to be working. Token is correct and is scoped properly, so not sure what's going on. Happy to provide more info if needed.

**Comment by dqgthb** [comment]
I'm having the same issue on Windows10. It's weird because I successfully set it up on macOS, and those have been working for a while. Tried to set it up in Windows10 today and it doesn't seem to be working. Token is correct and is scoped properly, so not sure what's going on. Happy to provide more info if needed.

**Comment by shanalikhan** [comment]
Is there any exception logged, would you guys please share the image

**Comment by tombresson** [comment]
This is what is in my Developers Console:
http://i.imgur.com/vKAipUN.png

Is that what your referring to by an exception?

**Comment by shanalikhan** [comment]
@tombresson https://github.com/shanalikhan/code-settings-sync/issues/59
Check this, let me know if it helped.

**Comment by tombresson** [comment]
When I set it up originally on my new machine, I created a new token. It matches the scope of the others (_gist only_). This occurred, so I reset the settings for the extension, created a new token with the same scope and tried again. This is where the system currently sits, still producing the error. I have not tried to use the same token for both systems yet. Maybe that's worth while. 

I did notice that the JSON from the older installs does not match the newer install. There are newly created items in the newer install. I thought maybe this could be causing the discrepancy. 

I will spend a bit of time trying other things this evening.

**Comment by vishalmamidi** [comment]
while trying to use this extension, i created 2 gist files in same access token, i am trying to use one in the other one but i am unable to do it, any one help me

**Comment by vishalmamidi** [comment]
![capture](https://cloud.githubusercontent.com/assets/12382861/24667729/0d238ee4-1982-11e7-889b-7d406a8568c1.PNG)

how to fix this ??

**Comment by shanalikhan** [comment]
@vishalmamidi share your developer console error image.
@tombresson , @lizhuangs can you try setting scope when creating token as:

Select "Gist" in scope while creating the token, please try with "Gist" scope and "User" scope ( including 3 sub scope checkboxes) and update

    GIST
    User
    a. user:read
    b. user:email
    c. user:follow

**Comment by vishalmamidi** [comment]
![capture](https://cloud.githubusercontent.com/assets/12382861/24674079/de6addbc-1997-11e7-8416-afc294651048.PNG)
In the process of fixing i deleted gist after that i am getting this new one

**Comment by shanalikhan** [comment]
@vishalmamidi Check this.
https://github.com/shanalikhan/code-settings-sync/issues/177#issuecomment-269873967

**Comment by lizhuangs** [comment]
I have the same problem with @tombresson .but I upload the image failed several times.I am really sorry for it ,but I only work under win10 OS.

**Comment by lizhuangs** [comment]
Tks!I resolve the problem by this: 
https://github.com/shanalikhan/code-settings-sync/issues/177#issuecomment-269873967
1. select 'sync:reset sync settings'
2. shift + alt + u -> enter your access token
So happy!you can try it.

**Comment by shanalikhan** [comment]
Let me know if anyone is still having the same problem. after following those steps.

**Comment by YousefMMS** [comment]
@shanalikhan I've the same issue as described by @tombresson.

**Comment by shanalikhan** [comment]
@YousefMMS have you tried : https://github.com/shanalikhan/code-settings-sync/issues/177#issuecomment-269873967

**Comment by YousefMMS** [comment]
It works fine thanks

**Comment by dcp12345678** [comment]
Did not work for me.  I get Error Not Found.  I tried to uninstall and reinstall, didn't work either.
