### ISSUE TITLE
error logged

### ISSUE THREAD

**Issue by MontyZhao** [shanalikhan/code-settings-sync#262]
**Visual Studio Code Version :** [ 1.8.0]
**Code Settings Sync Version :** [ 2.4.3 ]
**Operating System :** [ win10 ]
**Occurs On:** [Upload / Download / Help Configuring ]
**Proxy Enabled:** [ Yes  ]
**GIst Id:** [ ID_HERE ]

I have posted frequently asked questions on 
http://shanalikhan.github.io/2016/11/07/visual-studio-code-frequently-asked-questions.html 
so you may able to resolve the error quickly. 
Please make sure to write the versions and console logged error picture or copied text

**Comment by shanalikhan** [comment]
>  Please make sure to write the versions and console logged error picture or copied text
