### ISSUE TITLE
Is it possible to have two machines uploading and sharing settings

### ISSUE THREAD

**Issue by scottmcpherson** [shanalikhan/code-settings-sync#266]
Wondering if it's possible to have two machines share and upload to the same gist?

Right now, it seems that only one machine has write and upload access, while the other machines can only download. Is this correct?

**Comment by shanalikhan** [comment]
No, any machine can upload on the same gist and other one can download it.

**Comment by scottmcpherson** [comment]
I was getting an error saying that one of my machines was unable to write to the gist a couple of back and forth syncs but after I re-set it up, seems to be working now

**Comment by shanalikhan** [comment]
Great you have solve it,
When you get that error please post the exception logged image here and we can further check :)

**Comment by eduncan911** [comment]
The setup page should have this kind of info, as I was not sure if I can have two machines sharing the same Gist.

And still kind of wondering how I do that... 

I'm guessing I go to Advanced and enter the same Gist ID or something.  
Or, perhaps I just enter my Gist ID first on the 2nd machine, and let it "save" the gist id locally.  then, create a new token on the 2nd machine and configure it to upload.

And I suppose enabling "auto-upload" and "auto-download" is highly recommended here, or one machine could easily overwrite when opening.

**Comment by shanalikhan** [comment]
1 gist ID for all machines
1 Token for All Machines.

> And I suppose enabling "auto-upload" and "auto-download" is highly recommended here, or one machine could easily overwrite when opening.

Already in backlog : https://github.com/shanalikhan/code-settings-sync/issues/350

**Comment by eduncan911** [comment]
Yeah, #350 already just happened when I was doing this.

On "dev" machine, I enabled all of this, uploaded, etc.

Then hopped onto "new clean machine" and it wiped out all of my settings.  

Took some time but I am back to where I was.
