### ISSUE TITLE
Doesn't Prompt for Credentials

### ISSUE THREAD

**Issue by GaryFurash** [shanalikhan/code-settings-sync#27]
**Visual Studio Code Version :** [ VERSION_HERE ]
**Code Sync Settings Version :** [ VERSION_HERE ]

When I try to either upload or download settings on a 2nd computer,
1. it only prompts for the token and gist id, never any credentials;
2. fails w/ error

[Plugin Host] {"message":"Bad credentials","documentation_url":"https://developer.github.com/v3"}
messageService.ts:147 ERROR ! Logged In Console. Please open an issue in Github Repo.e.doShow @ messageService.ts:147e.show @ messageService.ts:131(anonymous function) @ extHostMessageService.ts:80n.undefined.t.Class.derive._oncancel @ winjs.base.raw.js:1901e.showMessage @ extHostMessageService.ts:72e.handle @ abstractThreadService.ts:100c @ ipcRemoteCom.ts:172f @ ipcRemoteCom.ts:120doNTCallback0 @ node.js:420_tickCallback @ node.js:349

**Comment by shanalikhan** [comment]
Please read the section to get the TOKEN from your git hub account

> Steps To Get the Github Key.

http://shanalikhan.github.io/2015/12/15/Visual-Studio-Code-Sync-Settings.html

**Comment by GaryFurash** [comment]
Thank you. I did do that. I got the token and it created a gist id on my work computer.

When I went home to my home computer I tried to do the same thing and get the associated error. It prompts me for the token (which I paste in), then asks me for the github gist, then gives me the error above.

Thanks for helping!!!!!

**Comment by shanalikhan** [comment]
this git hub error is showing that either you are posting the wrong token or the token has been deleted.
Make you u post the same token for both office and work environment and also when u generate the GIST ID from your office PC paste that same as it without any spaces in your home environment.

**Comment by GaryFurash** [comment]
OK GOT IT. Anything else I can do to trace it in case it doesn't work? Is there any way I can change the debug level?

**Comment by shanalikhan** [comment]
can you try to reset the settings and try again ?

**Comment by GaryFurash** [comment]
yes I did. do you have a version with debugging settings or something I can install?

**Comment by shanalikhan** [comment]
yes you can clone this respo and run on VScode and check it out.

**Comment by shanalikhan** [comment]
@GaryFurash 
Check this link https://developer.github.com/v3/#failed-login-limit
The error occurs due to invalid credentials so there is nothing much i can do from the extension side.
Im closing this issue.

**Comment by Lutreer** [comment]
I got the same problem,because I **deleted** the old `access token`. 
**Try this:**

1. `F1`
2. enter `sync` -> select `sync:reset sync settings`
3. `shift + alt + u` -> enter your `access token`

So,the old `access token` **(maybe you have deleted or modified)** leads to this problem.
