### ISSUE TITLE
Can't sync my gist data

### ISSUE THREAD

**Issue by italodr** [shanalikhan/code-settings-sync#273]
Hello, I get this error once I download the plugin and try to sync my actual data from a different Mac. I've tried 2 different Macs

```
Error Logged In Console (Help menu > Toggle Developer Tools).
You may open an issue using 'Sync : Open Issue' from advance setting command.
e.doShow @ messageService.ts:126
```

Visual Studio Code: v1.10.2
Code Settings Sync v2.6.1
OSX El Capitan v10.11.6

![captura de pantalla 2017-03-30 a las 21 59 13](https://cloud.githubusercontent.com/assets/2691320/24523682/2f956caa-1594-11e7-9095-6dab956607d1.png)

**Comment by shanalikhan** [comment]
Duplicate to https://github.com/shanalikhan/code-settings-sync/issues/259
Please post the details there
