### ISSUE TITLE
Error : Not Found

### ISSUE THREAD

**Issue by andyd0** [shanalikhan/code-settings-sync#274]
**Visual Studio Code Version :** 1.10.2
**Code Settings Sync Version :** 2.6.1
**Operating System :** Windows 10 - creators update applied
**Occurs On:** Both
**Proxy Enabled:** No proxy
**GIst Id:** is this something to be shared publicly?

Hi.  No matter what I do I can't get syncing to work on my laptop even though it works perfectly on my desktop.  Not sure if it's because I'm not supposed to share between different pcs but not sure what else to think.  The error is the same error as shown in the faq but regenerated the token several times with the same result.  I've even manually edited the settings to add the id with no luck.

![pic](https://cloud.githubusercontent.com/assets/7110426/24582402/3ba18e4c-16fd-11e7-895d-eabe1dcf73c4.PNG)

**Comment by shanalikhan** [comment]
> GIst Id: is this something to be shared publicly?

Yes if there is no confidential settings. So i can try out any time and test.

> The error is the same error as shown in the faq but regenerated the token several times

Have you select "Gist" in scope while creating the token, please try with "Gist" scope and "User" scope ( including 3 sub scope checkboxes) and update
1. GIST
2. User
   a. user:read
   b. user:email
   c. user:follow

**Comment by andyd0** [comment]
I got it now.  I kept using my token instead of switching to GIST.  All good now...thanks!

**Comment by mcardia** [comment]
Tried the workaround that was mentioned, but didn´t work
![capturar](https://cloud.githubusercontent.com/assets/11967511/26039931/985af252-38f6-11e7-83f9-520dddeb3c61.PNG)
![capturar2](https://cloud.githubusercontent.com/assets/11967511/26039939/b3217d68-38f6-11e7-8928-c8402af63013.PNG)
