### ISSUE TITLE
Unable to sync after enabling two factor authentication and cleaning up access tokens

### ISSUE THREAD

**Issue by janegilring** [shanalikhan/code-settings-sync#275]
**Visual Studio Code Version :** [ 1.10.2 ]
**Code Settings Sync Version :** [ 2.6.1 ]
**Operating System :** [ Windows 10 ]
**Occurs On:** [Help Configuring ]
**Proxy Enabled:** [  No ]

Debug console message:
extensionHost.ts:282[Extension Host] {"message":"Bad credentials","documentation_url":"https://developer.github.com/v3"}

I have the Gist ID and the access token for the settings sync Gist, and it's working fine from two different computers against the same Gist. However, after cleaning up personal access tokens and enabling two factor authentication on GitHub, I can't get it to sync on this other computer.
I tried resetting the settings in Settings Sync. After doing so, I'm prompted for the Gist Id when trying to sync. However, it fails with the same message after pressing Enter. It seems like a different token is being used when accessing the Gist from this computer. It suppose the issue could be solved by granting that token permissions on the Gist, but I can't find any options for that on the Gist web page.
The other option would be to change VS Code to use the personal access token which does have permissions, but I`m not prompted for the access token after resetting the Settings Sync Extension settings.

I'm sure there is an easy solution for this, but I`m stuck...any ideas?

**Comment by shanalikhan** [comment]
U need to create new Token with GIST permission from github and then enter it.
> The other option would be to change VS Code to use the personal access token which does have permissions, but I`m not prompted for the access token after resetting the Settings Sync Extension settings

When you reset the extension token and gist were removed, to download the settings you can enter your GIST ID. once you download your settings from that GIST then hit upload settings for one, it will ask for token at that time, but wont ask for GIST and upload the settings to that GIST using new token you have created.

**Comment by janegilring** [comment]
Ah, that worked...thanks!
