### ISSUE TITLE
Format the config file

### ISSUE THREAD

**Issue by diegobernardes** [shanalikhan/code-settings-sync#278]
**Visual Studio Code Version :** 1.10.2
**Code Settings Sync Version :** 2.6.1
**Operating System :** Arch x64
**Occurs On:** Upload / Download
**Proxy Enabled:** No

When we save the settings, the visual studio code automatic format the json, but when the settings are downloaded, they always came out not formated. So, whenever a download of settings is made, it's possible to format the settings?

**Comment by shanalikhan** [comment]
https://github.com/Microsoft/vscode/issues/24541

For this i have to add extension dependency, so when you install this extension that JSON formatting extension will be automatically installed.
