### ISSUE TITLE
cannot download sync'ed settings

### ISSUE THREAD

**Issue by ha-noi** [shanalikhan/code-settings-sync#28]
**Visual Studio Code Version :** [ 1.0 ]
**Code Sync Settings Version :** [ 1.1.7]

Please make sure to write the versions and console logged error picture or copied text.
Successfully installed code-settings-sync on a windows machine.
Successfully created gist ( and saved token and gist ID)
Successfully uploaded settings to a secret gist

Successfully installed code-settings-sync on a Mac Pro laptop with OS 10.9.5
I type alt-option -d
I enter token
I enter gist ID

get this error:
ERROR ! Logged In Console. Please open an issue in Github Repo.

??

**Comment by shanalikhan** [comment]
can you please paste the error that was logged in developer console of VSCode

**Comment by shanalikhan** [comment]
Im closing the issue supposing that its resolved until i get your error logged :)
