### ISSUE TITLE
Bad credentials

### ISSUE THREAD

**Issue by johnmerced** [shanalikhan/code-settings-sync#280]
**Visual Studio Code Version :** 1.10.2
**Code Settings Sync Version :** 2.6.2
**Operating System :** Win10
**Occurs On:** Upload / Download
**Proxy Enabled:** No 
**GIst Id:** 6ee4c45164d90ea69858e4d54b31358c

One of my VS Code instance is giving me a "Bad credentials" error. I wasn't able to find any documentation regards this. It just says that I need to reset my token but, I'm not sure why would I need to do that when the rest of my instances are working as expected.

Thank you,

**Comment by shanalikhan** [comment]
You faced this error after update ?
For now, try this and post comment https://github.com/shanalikhan/code-settings-sync/issues/177

**Comment by johnmerced** [comment]
Yes, I do.

*John Merced*


*General Disclaimer: *The information contained in this electronic
communication is to be considered confidential and intended only for the
use of the recipient named above. The information is or may be legally
privileged and expresses the opinion of the writer only. If the reader of
this message is not the intended recipient, you are hereby notified that
any dissemination, distribution, or copying of this communication, or any
of its contents, is strictly prohibited. If you have received this
communication in error, please re-send this communication to the sender
listed above, delete the original message and any copy of it from your
computer system.

**Comment by johnmerced** [comment]
@shanalikhan I updated my gist but I'm still facing the same issue.

**Comment by shanalikhan** [comment]
People have solved this error using the link i have given above. see this

https://github.com/shanalikhan/code-settings-sync/issues/293
