### ISSUE TITLE
Issue with downloading my settings

### ISSUE THREAD

**Issue by qstiegler** [shanalikhan/code-settings-sync#281]
**Visual Studio Code Version :** 1.11.0
**Code Settings Sync Version :** 2.6.2
**Operating System :** macOS 10.12.3
**Occurs On:** Download
**Proxy Enabled:** No
**GIst Id:** 4e572524c2909668a6866b932587d1cf

An error occurs when i download my gist from my second mac book.

**Comment by shanalikhan** [comment]
What error please please console log

**Comment by qstiegler** [comment]
```
extensionHost.ts:284[Extension Host] TypeError: Parameter "url" must be a string, not undefined
    at Url.parse (url.js:87:11)
    at Object.urlParse [as parse] (url.js:81:5)
    at Function.HttpGetFile (/Users/quirin.stiegler/.vscode/extensions/Shan.code-settings-sync-2.6.2/out/src/util.js:83:24)
    at /Users/quirin.stiegler/.vscode/extensions/Shan.code-settings-sync-2.6.2/out/src/pluginService.js:244:34
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by JReinhold** [comment]
I get the same error.
I've shared my GIST publicly, and when my colleague downloads it, it looks like the settings and extensions are downloaded correctly, but he gets this same error.

**Comment by ikogan** [comment]
Getting the same error, based on the part of the code, it looks like an extension in my gist no longer exists, so it's unable to fetch the URL for it to download?

**Comment by ingro** [comment]
Same error here, anyone find out where the problem lies?

**Comment by samuelsuarezsanchez** [comment]
From what I can see, this happens when an extension is no longer published in VSCode Market. If that's the case, then the extension cannot work out the URL to the extension package to be downloaded and throws the error.

I guess the extension should display a warning indicating that the extension doesn't seem to be available, instead of hiding the error away in the console, or have a setting to quietly ignore.

In my case, the issue was with the now discontinued Stylus and PHP Code Formatter extensions, which I can live without now that support for both languages is completely built-in latest VS Code versions.

**Comment by shanalikhan** [comment]
Can you try again and let me know about the console ? what error is it throwing

**Comment by ikogan** [comment]
```
[Extension Host] TypeError: Parameter "url" must be a string, not undefined
    at Url.parse (url.js:95:11)
    at Object.urlParse [as parse] (url.js:89:5)
    at Function.HttpGetFile (/home/kogan/.vscode/extensions/Shan.code-settings-sync-2.7.0/out/src/util.js:83:24)
    at /home/kogan/.vscode/extensions/Shan.code-settings-sync-2.7.0/out/src/pluginService.js:244:34
    at process._tickCallback (internal/process/next_tick.js:103:7)
d.logExtensionHostMessage @ workbench.main.js:29
(anonymous) @ workbench.main.js:29
emitTwo @ events.js:106
emit @ events.js:191
process.nextTick @ internal/child_process.js:752
_combinedTickCallback @ internal/process/next_tick.js:67
_tickCallback @ internal/process/next_tick.js:98
```

**Comment by shanalikhan** [comment]
@ikogan share your gist id

**Comment by ikogan** [comment]
https://gist.github.com/ikogan/86695e5cdaa429d167bb076280e70d51

**Comment by shanalikhan** [comment]
@ikogan can you remove the extension 
> puppetlinter - Version : 0.1.3
and install from marketplace again and then upload the gist.

I dont find the `puppetlinter` in the marketplace.


@samuelsuarezsanchez yes that is the issue, i will show a error in the developer log and extension will continue downloading other ones.

**Comment by ikogan** [comment]
I'm concerned it might not upload a correct gist as it hasn't successfully downloaded all the extensions. I don't have the machine on which the gist was originally generated. Can I just remove it manually from the gist?

**Comment by shanalikhan** [comment]
yes remove this
```
{
    "metadata": {
      "id": "0485a623-9060-4a1a-afe5-d1dbd4c92046",
      "publisherId": "8487342e-08da-4c74-8c31-34086befd725",
      "publisherDisplayName": "Jason Greathouse"
    },
    "name": "puppetlinter",
    "publisher": "jgreat",
    "version": "0.1.3"
},
```

**Comment by ikogan** [comment]
That did the trick, thanks!

**Comment by SathyaBhat** [comment]
I have a similar problem - this is [the gist](https://gist.github.com/SathyaBhat/4066bffe3c09a2489e4da5cd685ad1fc) Can you let me know which extension is causing the problem?

thanks

**Comment by SathyaBhat** [comment]
nev mind, found the problem. "format-indent" extension is no longer available. 

```
"metadata": {
      "id": "949eb1e5-b41c-413f-99da-6b57cdaed1b4",		
      "publisherId": "d0da30bb-6c9f-4482-8b47-080dc94e6008",		
      "publisherDisplayName": "Martin Kase"		
    },		
    "name": "format-indent",		
    "publisher": "Kasik96",		
    "version": "1.3.0"		
  }
```

**Comment by shanalikhan** [comment]
Its fixed in latest version.
Extension will show an error upon not found but will continue downloading other extensions.

let me know if there is still a problem.
