### ISSUE TITLE
Manual upload destroyed user settings

### ISSUE THREAD

**Issue by Deilan** [shanalikhan/code-settings-sync#283]
**Visual Studio Code Version :** 1.10.2
**Code Settings Sync Version :** 2.6.2
**Operating System :** Windows 10 x64
**Occurs On:** Upload
**Proxy Enabled:** No
**GIst Id:** fb13eb4c010a3bf385c993432bdaa569 (automatically reset to 848ad45edd1515cedea058c79d976053 after relaunch)

Manual upload destroyed my user settings and the extension reset it's own settings after VS Code relaunch (`sync.gist` changed automatically). I suppose low disk space was an attendant circumstance.

[console log.zip](https://github.com/shanalikhan/code-settings-sync/files/902306/-1491475966748.zip)

**Comment by shanalikhan** [comment]
I dont see any exception related with extension.
Is this happening every time ?
