### ISSUE TITLE
Keyboard shortcuts don't work

### ISSUE THREAD

**Issue by Deilan** [shanalikhan/code-settings-sync#285]
**Visual Studio Code Version :** 1.11.1
**Code Settings Sync Version :** 2.6.2
**Operating System :** Windows 10 x64 **via Boot Camp**
**Occurs On:** Upload / Download
**Proxy Enabled:**No
**GIst Id:** fb13eb4c010a3bf385c993432bdaa569 

<kbd>Shift + Alt + U</kbd> and <kbd>Shift + Alt + D</kbd> keyboard shortcuts don't work and have no effect: nothing happens in statusbar upon using the shortcuts. No conflicts detected (see screenshot below). Other keyboard shortcuts within VS Code work well. Manual execution the extension's commands from the Command Palette also works fine.

![capture](https://cloud.githubusercontent.com/assets/4777512/24775829/1c9e8648-1b27-11e7-81a5-f7673c64514a.PNG)

**Comment by ArsProgramma** [comment]
As far as i can tell you need an open file as active document for the shortcuts to work.

**Comment by shanalikhan** [comment]
Its appearing in my editor, as @ArsProgramma also said, you need to open some file in the editor in order to run the commands.
