### ISSUE TITLE
Unable to backup which led to not being able to setup/reinstall (after uninstalling) 

### ISSUE THREAD

**Issue by cbstodd** [shanalikhan/code-settings-sync#288]
**Visual Studio Code Version :** [ 1.11.1 ]
**Code Settings Sync Version :** [ 2.6.2 ]
**Operating System :** [ macOS Sierra v 10.12.4 ]
**Occurs On:** [Upload / Download / Configuring ]
**Proxy Enabled:** [ Yes / No ]
**GIst Id:** [ 7a3720cebe786fc9af211979a42ed57fc5eaec5c ]

Uploading was not working correctly. I looked in the logs, it sad bad credentials so I regenerated a new Gist/Token and am unable to input  ctrl + shift + U (causes error). I then tried to Update/Upload settings my token but I'm getting the same errors.

![screen shot 2017-04-08 at 1 32 58 am](https://cloud.githubusercontent.com/assets/5274093/24826055/5fed88c0-1bfb-11e7-8c18-6ff10ca71f95.png)

I have posted frequently asked questions on 
http://shanalikhan.github.io/2016/11/07/visual-studio-code-frequently-asked-questions.html 
so you may able to resolve the error quickly. 
Please make sure to write the versions and console logged error picture or copied text

**Comment by shanalikhan** [comment]
Check the solutions here : https://github.com/shanalikhan/code-settings-sync/issues/177#issuecomment-269873967

**Comment by cbstodd** [comment]
For future onlookers, What I did to fix it was: open the command prompt by pressing `cmd + shift + P` type `sync` and selected `reset extention settings` which allowed for me to reinstall my Access token. Not sure why it wasn't working last night. Might have to do with me trying to make too many calls. But its working now.
