### ISSUE TITLE
Uploaded Successfully. GIST ID : undefined . Please copy and use this ID in other machines to sync all settings.

### ISSUE THREAD

**Issue by 1msoft** [shanalikhan/code-settings-sync#29]
**Visual Studio Code Version :** [ 1.0 ]
**Code Sync Settings Version :** [ LATEST ]

Uploaded Successfully. GIST ID : undefined . Please copy and use this ID in other machines to sync all settings.

But no glist created.

**Comment by shanalikhan** [comment]
you are sure you are using latest version of extension ?
also please copy the developer console error of VSCode by checking Toggle Developer Tool from Help menu if there is any.

**Comment by shanalikhan** [comment]
@1msoft were you able to solve the problem ?
