### ISSUE TITLE
Server error on automatic upload

### ISSUE THREAD

**Issue by realappie** [shanalikhan/code-settings-sync#291]
**Visual Studio Code Version :** `1.11.1`
**Code Settings Sync Version :** [ VERSION_HERE ]
**Operating System :** macOS el capitan
**Occurs On:** Upload
**Proxy Enabled:** No
**GIst Id:** `697f191ae16b529630fb40762c33ce1c`

At `extensionHost.ts:284` I have been getting this message lately

```
[Extension Host] {"message":"Server Error","documentation_url":"https://developer.github.com/v3/gists/#edit-a-gist"}
```

**Comment by realappie** [comment]
I think Im getting this error whenever Im adding a new project to my [projects manager](https://marketplace.visualstudio.com/items?itemName=alefragnani.project-manager).

**Comment by Rukeith** [comment]
I also have a same issue, but my problem is I can download the setting.
I can't upload my setting, it show Can't edit this gist

**Comment by shanalikhan** [comment]
@realappie  and @Rukeith can you provide the complete stack trace of exception or post an image from the developer console.

**Comment by realappie** [comment]
@shanalikhan I will whenever I encounter this issue again!

**Comment by rnitame** [comment]
@realappie please retry after `Reset Extension Settings` : )
![image](https://cloud.githubusercontent.com/assets/4950792/25419427/a18fe69c-2a8d-11e7-9530-96384cbcfd5b.png)

**Comment by shanalikhan** [comment]
Feel free to post, and i will re open this issue.
