### ISSUE TITLE
Error Logged In Console. You may open an issue using 'Sync:Open Issue'...

### ISSUE THREAD

**Issue by ahdung** [shanalikhan/code-settings-sync#293]
**Visual Studio Code Version :** [1.11.1]
**Code Settings Sync Version :** [2.6.2]
**Operating System :** [Win2k8 r2 x64]
**Occurs On:** [after vscode started]
**Proxy Enabled:** [ No ]
**GIst Id:** [ ahdung ]

Error:
![qq 20170412134418](https://cloud.githubusercontent.com/assets/12094247/24942889/659de45c-1f86-11e7-8a66-464f602ffd97.png)

Not have Sync:Open Issue in F1, just these:
![qq 20170412134501](https://cloud.githubusercontent.com/assets/12094247/24942887/65778bc2-1f86-11e7-913a-5fe5275640c5.png)

and after Enter, no any response. Please check and fix.

**Comment by shanalikhan** [comment]
whats the console image in the developer console.

**Comment by dinos80152** [comment]
I have the same problem, I have done something in this period.

* upload all my extensions
* regenerate my gist access token

Visual Studio Code Version : [1.11.1]
Code Settings Sync Version : [2.6.2]
Operating System : [Win 7 64bit]
Occurs On: [after vscode started, enter Sync: Upload command and Sync: Download command]
Proxy Enabled: [ No ]
GIst Id: [ 829fc52a32c30b115e655c28fbce5430 ]

It has problem in my Windows 7, but it's still work on my Macbook Air.

**Comment by oibanez** [comment]
I get the same problem as well.  I am able to upload my settings from one computer but when I try to download to another computer I get this error.  I've tried generating a new token, uninstalling/reinstalling, clearing my settings, etc.

Here are the error messages that show up in the search console.

```
extensionHost.ts:284[Extension Host] Error: ENOENT: no such file or directory, scandir 'C:\Users\OliverDesktop\AppData\Local\GitHub'
    at Error (native)d.logExtensionHostMessage @ extensionHost.ts:284
2extensionHost.ts:284[Extension Host] {"message":"Not Found","documentation_url":"https://developer.github.com/v3"}d.logExtensionHostMessage @ extensionHost.ts:284
messageService.ts:126Error Logged In Console (Help menu > Toggle Developer Tools). You may open an issue using 'Sync : Open Issue' from advance setting command.e.doShow @ messageService.ts:126
```

Visual Studio Code Version : [1.11.1]
Code Settings Sync Version : [2.6.2]
Operating System : [Win 10 64bit]
Occurs On: [Sync: Download command]
Proxy Enabled: [ No ]
GIst Id: [ e21b74b428112c099eda79c677ba6829068790ee ]

**Comment by darrensimsg** [comment]
+1 Getting same issue. Anyone has any recommendations or have managed to get this working?

**Comment by darrensimsg** [comment]
I managed to get it working using these steps:

1. Retrieved the sync.gist value from my origin machine's settings.json (noticed that it's different from what's generated from Github)

2. Paste the value in the settings.json for sync.gist

3. Exec "Sync: download Settings" and it works

**Comment by ahdung** [comment]
@darrensimsg Thank you first, yes the "download Settings" is well, but "Updata/Upload Settings" still same fail.

**Comment by ahdung** [comment]
@darrensimsg Sorry it's my fail, your solution is work!!! the reason of the problem is i have not Created gist file  before.

**Comment by ahdung** [comment]
Create a empty file on Gist before !!! then you can get the Gist id of the file at URL, name and content not care, as u wish.

**Comment by dinos80152** [comment]
@darrensimsg 
I don't understand what this mean. It's mean the sync.gist value on user settings?
> Retrieved the sync.gist value from my origin machine's settings.json (noticed that it's different from what's generated from Github)

**Comment by ahdung** [comment]
@dinos80152 the sync.gist is a option item, F1>type ">preferences: open user settings" and Enter, at right area add the item, like this:
{
    ....
    "sync.gist": "cac36xxxxx", // id of the gist file, find it in url, https://gist.github.com/ahdung/cac36xxxx
    ....
}

**Comment by darrensimsg** [comment]
@dinos80152 When you open settings.json (use settings), you will see "sync.gist" if you have already installed the plugin and setup it up before. 

Copy the "sync.gist" value to other machines that you want to sync up with. =)

**Comment by shanalikhan** [comment]
Please check this solution to solve these issues. https://github.com/shanalikhan/code-settings-sync/issues/177#issuecomment-269873967

Also it will create the GIST automatically and setup its ID in settings.json when sync.gist is not provided.
Keep the GIST ID saved, and put on other instances in order to sync them also.

**Comment by zhihuilong** [comment]
@ahdung Thx. You are right. The gist value is not the personal access token but the value appending  to the url, like that  https://gist.github.com/ahdung/cac36xxxx.  cac36xxxx is the right sync.gist value. Hope other people can get it.

**Comment by ahdung** [comment]
@zhihuilong you got it. I think the official guide should append these detail infomation.
