### ISSUE TITLE
i can't download my setting from gist

### ISSUE THREAD

**Issue by donnol** [shanalikhan/code-settings-sync#294]
**Visual Studio Code Version :** [ 1.11.2 ]
**Code Settings Sync Version :** [ 2.6.2]
**Operating System :** [ windows 7]
**Occurs On:** [Download ]
**Proxy Enabled:** [ No ]
**GIst Id:** [ 6276d286e7b1cccd99ffec329cff8aa5 ]

i can't download my setting from gist, i just get that Error Logged In Console (Help menu > Toggle Developer Tools). You may open an issue using 'Sync : Open Issue' from advance setting command.

**Comment by shanalikhan** [comment]
Post your details there with the image of developer console.
https://github.com/shanalikhan/code-settings-sync/issues/293
