### ISSUE TITLE
ERROR: Sync : You cant edit GIST for user : XYZ

### ISSUE THREAD

**Issue by phifa** [shanalikhan/code-settings-sync#295]
When trying tu upload my settings, most if the time it does not work and I get this error. When I take out the sync.gist ID, it works. My current gist has three revisions, but now I keep getting this error. 

--

**Visual Studio Code Version :** [ 1.11.2]
**Code Settings Sync Version :** [ 2.6.2 ]
**Operating System :** [ WIN10]
**Occurs On:** [Upload ]
**Proxy Enabled:** [ No ]
**GIst Id:** [ ffbadf42996c9aac32d861ceaa9b820b]

**Comment by igorkulman** [comment]
Same problem here. I installed the extension on Windows, synced my settings. Now I am trying to sync them on macOS to the same gist the Windows version created and getting this error. If I delete the sync.gist ID it creates a new gist and works (but my Windows version is not syncing with my macOS version).

**Comment by shanalikhan** [comment]
@phifa , @igorkulman  You have already provided the valid token to the extension, right ?

**Comment by igorkulman** [comment]
Yes, the token is valid, otherwise it would not work with empty sync.gist ID and would not create a new gist.

**Comment by shanalikhan** [comment]
@igorkulman 
> Also is there any exception logged in the developer console ?

**Comment by igorkulman** [comment]
Yes
![screen shot 2017-04-18 at 17 44 03](https://cloud.githubusercontent.com/assets/4746070/25139809/a94c6138-245e-11e7-989c-2f8aae82fe57.png)

**Comment by zigang93** [comment]
solved?? I am also facing the same problem

**Comment by shanalikhan** [comment]
I need to check from the console log, why its not matching the gist owner and your username.
In next version, when this error occur extension will display both username so we can further evaluate the problem.
Upcoming extension version will show the log.

**Comment by CMTietgen** [comment]
I'm also getting this error. I was able to perform the initial upload from my home PC, then download it to my work PC. But when I use the **>Sync > Update / Upload Settings** I get the error about my user.

**Comment by badrobit** [comment]
I am also experiencing this issue.

**Comment by SirM2z** [comment]
I am also experiencing this issue too,but I solved this after I use **Sync: Advanced Options > Toggle Auto-Upload On Settings Change**.

**Comment by shanalikhan** [comment]
I have released v2.7.
Let me know if there is still problem.
Also please share your developer console image as i have added some logs, if problem occurs.

**Comment by shanalikhan** [comment]
Ok, i havent heard any of you guys, so i think this issue is safe to close assuming its fixed.
