### ISSUE TITLE
Customizable gist description

### ISSUE THREAD

**Issue by toXel** [shanalikhan/code-settings-sync#296]
This would be helpful for e.g. gists for each OS so I could change the description to something like "VS Code Settings Linux" or different locations like home and office.

**Comment by shanalikhan** [comment]
Yes description can be added in `customSyncSettings.json` for both OS.
Will work on it.

**Comment by shanalikhan** [comment]
I have fixed this in 2.7
Let me know if there is any error

**Comment by toXel** [comment]
Works as expected! Thank you 🙂
