### ISSUE TITLE
Unable to Download Settings

### ISSUE THREAD

**Issue by CMTietgen** [shanalikhan/code-settings-sync#297]
**Visual Studio Code Version :** 1.11.2
**Code Settings Sync Version :** 2.6.2
**Operating System :** Windows 10
**Occurs On:** Download
**Proxy Enabled:** No
**Gist Id:** 89a1072321dc06e4a7a0c7ef5a56f6ec

I was able to install the extension on my home computer without issue and the upload worked.

However, after installing the extension on my work PC, I used the Shift+Alt+D key combination and nothing happens. Any thoughts?

NOTE: Using **>Sync** on the Command Palette did allow me to download the settings. It's just the keyboard shortcut that didn't work.

**Comment by shanalikhan** [comment]
You need to open some document then use the shortcuts defined in the readme.
