### ISSUE TITLE
Auto Download Setting Not Working

### ISSUE THREAD

**Issue by CMTietgen** [shanalikhan/code-settings-sync#298]
**Visual Studio Code Version :** 1.11.2
**Code Settings Sync Version :** 2.6.2
**Operating System :** Windows 10
**Occurs On:** Help Configuring
**Proxy Enabled:** No

Every time I use the **Sync : Advance Options > Toggle Auto-Download On Startup** setting, it indicates the setting is OFF. How do I actually enable it?

**Comment by shanalikhan** [comment]
Because when you auto download , the latest settings has key sync.autodownload set to false and this feature turns off in the computer you using.
Upload the settings to true from one computer and when you download that setting it will always keep to auto download enable in every computer.
