### ISSUE TITLE
Extension insists on creating a new gist when I want to upload.

### ISSUE THREAD

**Issue by amivit** [shanalikhan/code-settings-sync#299]
How do I overwrite my current settings on a specific gist, without the extension trying to create an entirely new gist? I can easily download a specific gist, but when I try to upload settings I put in my sync token and the extension just creates a new gist, instead of asking me for which gist id I wish to upload my settings to. So is that intentional, you only want 1 device capable of changing settings. So frustrating!

**Comment by shanalikhan** [comment]
The Gist is public or secret ?
When you upload, check the GIST is available in the `sync.gist` ? or that is empty.

You can use one gist and upload settings every time on it, and download on other computer the updated settings unless its secret gist.

**Comment by amivit** [comment]
Every time I go to Update / Upload settings, it asks for my token and just generates a new gist. I have no idea how to continue working on the same gist. I changed my existing one from secret to public, to see if it would help. It did not.

**Comment by nbara** [comment]
Same problem here...

**Comment by shanalikhan** [comment]
> Every time I go to Update / Upload settings, it asks for my token 

Why does it ask for token every time ?
Is there any exception logged in developer console. ?
When you download the setting, is the `sync.gist` in the settings.json which you used to download ?

Can you provide proper steps to generate this error, as im unable to generate it my end.

also check either the `"sync.anonymousGist": false`. If its true it will always create new gist for uploading.
