### ISSUE TITLE
can you also add sync for tasks.json and my local launch.json is not synced

### ISSUE THREAD

**Issue by NikosEfthias** [shanalikhan/code-settings-sync#30]
**Visual Studio Code Version :** [ 1.0.0 ]

can you also add sync for tasks.json and my local launch.json is not synced

**Comment by shanalikhan** [comment]
Adding custom files are planned for future releases.
Can you tell me how your local launch.json is not synced
Did it give any error message in VSCode. ? Share the develop console error message.
have you checked that its been uploaded correctly in your github gist.

**Comment by NikosEfthias** [comment]
i mean in-project-folder settings which is inside the .vscode both tasks.json and launch.json are inside my project folder

**Comment by shanalikhan** [comment]
I'm sorry , this extension is limited to only general visual studio code settings.
Its a good idea indeed, I'll soon write new extension for this future when i had time.
Meanwhile I'll closing this issue, let me know if u get any problem using the features
