### ISSUE TITLE
Lost all settings except for default sync settings

### ISSUE THREAD

**Issue by richarddavenport** [shanalikhan/code-settings-sync#300]
**Visual Studio Code Version :** Version 1.12.0-insider (1.12.0-insider) 6c5926309d821ce767743c8166ec225fbe9456ef
**Code Settings Sync Version :** 2.6.2
**Operating System :** macOS 10.12.4
**Occurs On:** update
**Proxy Enabled:** No
**GIst Id:** ad38d973d33b130aac48d82cfb29b9eb

VSCode updated (I use insiders) and all my settings were lost. The only settings that were there were the sync settings. I also have extensions set to auto-update. Could this be caused by the extension or VSCode updating?

**Comment by shanalikhan** [comment]
Was the upload in process when other extensions auto-update happened ?
Or it was in process when you restarted the Code ?

**Comment by richarddavenport** [comment]
Thanks @shanalikhan I do believe this was from something else. I'm not 100% sure of what, but I do not think it was this extension. Thanks!
