### ISSUE TITLE
Unable to read syncLocalSettings.json. Make sure its Valid JSON.

### ISSUE THREAD

**Issue by BarDev** [shanalikhan/code-settings-sync#301]
**Visual Studio Code Version :** [ 1.11.2]
**Code Settings Sync Version :** [ 2.6.2]
**Operating System :** [ Windows 10 ]
**Occurs On:** [Upload]
**Proxy Enabled:** [  No ]
**GIst Id:** [ 1be69ce1a0ddc18a632b7f4108df3740]

I followed the instructions and created a GitHub Personal Access Token. 

When I attempted to upload my settings, the following is displayed in VS Code
- ` Cannot read property 'ignoreUploadFiles' of null`
- `Sync : Unable to read syncLocalSettings.json. Make sure its Valid JSON.`

These errors were also shown in VS Code debugger tool.

I went to the following directory C:\Users\???\AppData\Roaming\Code\User and viewed the syncLocalSettings.json and noticed the file was empty.  Based on blog post [Code Settings Sync Customizable Sync](http://shanalikhan.github.io/2017/02/19/Option-to-ignore-settings-folders-code-settings-sync.html), I manually added the following configuration to the syncLocalSettings.json

`{
    "ignoreUploadFiles": [
        "projects.json",
        "projects_cache_git.json"
    ],
    "ignoreUploadFolders": [
        "workspaceStorage"
    ],
    "replaceCodeSettings": 
    {
        "http.proxy" :"",
        "files.autoSave" :"off"
     }
}`

After making these changes, the upload process worked and a gist was created on my GitHub account.

**Comment by shanalikhan** [comment]
Can you delete the file once again, and check the empty file is being created with the json data ?

**Comment by ryanbowden** [comment]
Hi, I am having the same issue so can help you, Now I am unaware where this file has been created, can you give me the directory it will put this file on ubuntu 16.04 as that what I am using.

And I can say what the issue with my file.

**Comment by shanalikhan** [comment]
The file is in the same folder `User` folder where your code settings and other settings are placed

**Comment by ryanbowden** [comment]
```
{
    "ignoreUploadFiles": [
        "projects.json",
        "projects_cache_git.json"
    ],
    "ignoreUploadFolders": [
        "workspaceStorage"
    ],
    "ignoreUploadSettings": {},
    "replaceCodeSettings": {},
    "gistDescription": "Visual Studio Code Settings Sync Gist",
    "version": 270
}
```

That's what my file contains I can't see any issues with the file. shall I delete it and rebuild it?

**Comment by shanalikhan** [comment]
Dont remove this file.
Extension needs this file to upload / download

**Comment by ryanbowden** [comment]
Okay but how come I get the error? saying invalid JSON sometimes?

**Comment by shanalikhan** [comment]
Make sure you donet have trailing commas at the end, when you get, remove the file or backup it somewhere and then remove it.
Restart code, extension will create the file itself.

**Comment by DJviolin** [comment]
Removing the file solved the issue on Windows 10. I tryed to open it before, but vscode said it's binary format or can't open it. Next start the file was recreated, I entered again the gist token and everything works just like before.

**Comment by Chillee** [comment]
I'm getting the same error. There's no `syncLocalSettings.json` in ~/.config/Code/. I've tried restarting VSCode too.

**Comment by markfaine** [comment]
I'm getting the same error.  I've tried everything I can think of including the suggestions in this thread. This only happens in Windows 10.  I also have it installed in Linux and it works fine.  Also, is there a way to disable the opening of browsers all the time.  I'd rather it just print a message in the console with the URL.  I can open a separate ticket for that if it helps.

**Comment by joolius** [comment]
Having the same problem here.. windows 7.

**Comment by TrayHard** [comment]
Same issue, Windows 7, just installed VSCode v 6.1.7601. Maybe it's because of VSCode updates?

**Comment by Nyaasu66** [comment]
I recently encountered the same problem with a message saying: "Sync : Unable to read syncLocalSettings.json. Make sure its Valid JSON."But I solved this problem with just one click. Check "Download Public Gist" in Sync Settings and it will be successfully synchronized.(Or modify {"downloadPublicGist": true} in the `%APPDATA%\Code\User\syncLocalSettings.json` file)

我最近遇到了相同的问题，提示信息显示："Sync : Unable to read syncLocalSettings.json. Make sure its Valid JSON."
但是我只用了一次点击便解决了这个问题，在Sync Settings里面勾选"下载公开Gist"，立刻就能成功同步了。（或者在`%APPDATA%\Code\User\syncLocalSettings.json`文件中修改{"downloadPublicGist": true}）

**Comment by izhar-ali226** [comment]
> I recently encountered the same problem with a message saying: "Sync : Unable to read syncLocalSettings.json. Make sure its Valid JSON."But I solved this problem with just one click. Check "Download Public Gist" in Sync Settings and it will be successfully synchronized.(Or modify {"downloadPublicGist": true} in the `%APPDATA%\Code\User\syncLocalSettings.json` file)
> 
> 我最近遇到了相同的问题，提示信息显示："Sync : Unable to read syncLocalSettings.json. Make sure its Valid JSON."
> 但是我只用了一次点击便解决了这个问题，在Sync Settings里面勾选"下载公开Gist"，立刻就能成功同步了。（或者在`%APPDATA%\Code\User\syncLocalSettings.json`文件中修改{"downloadPublicGist": true}）

still not working

**Comment by shivamAbacus** [comment]
delete the syncLocalSettings.json file from -  %APPDATA%\Code\User\  - repository (folder) and restart vscode.
after restart vs code automatically generate the file and the issue is solved.

**Comment by ghost** [comment]
There is an easier way. Ctrl + Shift + p and type Sync: Reset Extension Settings. Then scroll down on the Extension and Sign in with Github and it should redownload your Gist.

**Comment by miozus** [comment]
If you're having trouble location the syncLocalSettings.json file in Ubuntu, it's here:
~/.config/Code/User/syncLocalSettings.json

I had to add my gist token manually to that file. and then in settings i had to clear my Gist ID. After pressing Alt+Shift+U, it worked and a Gist ID was somehow autmatically generated

---

win10 手动添加 token 字符串， 就可以同步了，自动弹窗下载插件，一个接一个来
