### ISSUE TITLE
what the happend

### ISSUE THREAD

**Issue by HawkingChan** [shanalikhan/code-settings-sync#302]
**Visual Studio Code Version :** [ VERSION_HERE ]
**Code Settings Sync Version :** [ VERSION_HERE ]
**Operating System :** [ VERSION_HERE ]
**Occurs On:** [Upload / Download / Help Configuring ]
**Proxy Enabled:** [ Yes / No ]
**GIst Id:** [ ID_HERE ]

I have posted frequently asked questions on 
http://shanalikhan.github.io/2016/11/07/visual-studio-code-frequently-asked-questions.html 
so you may able to resolve the error quickly. 
Please make sure to write the versions and console logged error picture or copied text

**Comment by chengquan223** [comment]
me too

**Comment by shanalikhan** [comment]
>  Please make sure to write the versions and console logged error picture or copied text
