### ISSUE TITLE
i have error on download

### ISSUE THREAD

**Issue by khzero** [shanalikhan/code-settings-sync#304]
**Visual Studio Code Version :** [ 1.11.2 ]
**Code Settings Sync Version :** [ 2.6.2 ]
**Operating System :** [ windows 10]
**Occurs On:** [ Download ]
**Proxy Enabled:** [ Yes ]
**GIst Id:** [ db7f87629997049f3ba75442819cfba0782283f3]

I have posted frequently asked questions on 
http://shanalikhan.github.io/2016/11/07/visual-studio-code-frequently-asked-questions.html 
so you may able to resolve the error quickly. 
Please make sure to write the versions and console logged error picture or copied text

**Comment by shanalikhan** [comment]
>  Please make sure to write the versions and console logged error picture or copied text

**Comment by khzero** [comment]
here is the error on my console log

[Extension Host] {"message":"Bad credentials","documentation_url":"https://developer.github.com/v3"}d.logExtensionHostMessage @ workbench.main.js:29
workbench.main.js:28 Error Logged In Console (Help menu > Toggle Developer Tools). You may open an issue using 'Sync : Open Issue' from advance setting command.e.doShow @ workbench.main.js:28

and setting sync version is 2.6.2

**Comment by bashirsouid** [comment]
+1 I get the same error. Running VS Code 11.2 on Ubuntu Linux. My Windows machine appears to be fine. Tried with two access tokens.

**Comment by shanalikhan** [comment]
Check this with all the possible solutions and let me know
https://github.com/shanalikhan/code-settings-sync/issues/177

**Comment by bashirsouid** [comment]
@shanalikhan Yeah, I tried those after I saw that most issues were being linked to #177. Same result. Has this plugin been tested on Linux?

**Comment by shanalikhan** [comment]
Yes its verified for linux, osx and Windows.
From the next versions i will set token in a local file in users folders so u xan see where token is stored rather keeping it hidden.
