### ISSUE TITLE
Can't download the settings

### ISSUE THREAD

**Issue by felixfong227** [shanalikhan/code-settings-sync#305]
**Visual Studio Code Version :** 1.10.2
**Code Settings Sync Version :** 2.6.2
**Operating System :** OSX EI Capitan 10.11.6
**Occurs On:** Download
**Proxy Enabled:** Nope
**GIst Id:** 116545624055e15ea702ec5a093ec173

I can upload and sync the settings to the cloud, but can't download the settings from the cloud 😕 
![image](https://cloud.githubusercontent.com/assets/13918481/25511442/7fd965ba-2bf9-11e7-9d04-9dcf3260e619.png)

**Comment by shanalikhan** [comment]
Check this
https://github.com/shanalikhan/code-settings-sync/issues/177

**Comment by felixfong227** [comment]
Thanks, but the next program I got after the auth issues is, it keep saying my `settings.json` have new content, I mean that what syncing does right? changing content, BTW thanks again @shanalikhan 😄 

![image](https://cloud.githubusercontent.com/assets/13918481/25519147/416da9e6-2c29-11e7-95d4-e6a4e428228b.png)

**Comment by shanalikhan** [comment]
Close the settings.json file then hit download and open again.
This is the behavior of code

**Comment by felixfong227** [comment]
Thanks for helping @shanalikhan 😄
