### ISSUE TITLE
Can't download Sync Settings

### ISSUE THREAD

**Issue by vscodeguru** [shanalikhan/code-settings-sync#307]
**Visual Studio Code Version :** [ 1.11.2 ]
**Code Settings Sync Version :** [ 2.6.2 ]
**Operating System :** [ Win-10 64bit ]
**Occurs On:** [ Download ]
**Proxy Enabled:** [ No ]
**GIst Id:** [ d55e4a2550b0a6f7c8e74749ea584a978d0518fe ]

![image](https://cloud.githubusercontent.com/assets/18045792/25557589/3bdddc80-2d32-11e7-8ec2-5fdad4a12113.png)

**Comment by vscodeguru** [comment]
![image](https://cloud.githubusercontent.com/assets/18045792/25557511/5fb4ade8-2d30-11e7-9353-1833d2a3d66f.png)

**Comment by shanalikhan** [comment]
#177
