### ISSUE TITLE
Display List of Available Gist On Connected User Account

### ISSUE THREAD

**Issue by shanalikhan** [shanalikhan/code-settings-sync#308]
Originally from https://github.com/shanalikhan/code-settings-sync/issues/261#issuecomment-298093406

**Showing List of Available GIST on Upload / Download**

**Upload**

When user add token and hit upload. There will be two cases.

If the gist id is already added, it will upload to that gist.
If gist id not added in extension settings, it will scan all the gist and show a list with gist description SORTED BY last updated date only.

**Download**

Similarly when user download the settings.

Two scenarios, if gist ID is added in settings it will download from that settings and if not added, it will scan user gist same with gist description and sorted by last updated gist in a list AND OTHER option to download other user gist by providing the ID.

**Hot Switch**
Hot switch will be used when you want have the one code settings dev environment and you want another, This option will be added in the advance command in extension and will show Download like behaviour and you can switch to other Gist ( or other dev environment )

User wont be able to see list by its gist id or file name but with last updated gist date and gist description.

**Comment by shanalikhan** [comment]
@ioprotium
This issue was created when we done have `host` in Settings Sync.

As you have implemented the feature.
Dont you think by adding providing the "Environment Hot Switch" option in the advance menu we can show the user the available hosts in the `settings.json` to select from. Like `home` and office`. The command should change the `host` on Settings Sync Global Settings to the selected one and just hit the normal download process and all things will be automatically switched.

Thoughts?

**Comment by ioprotium** [comment]
I think downloading the settings again wont be necessary. We just filter the settings for the new host value and write it to the disk. 
I was thinking that the `host` settings should create a separated gist to save all the settings (extensions, keyboard, etc) on it, that will allow the user to replicate the entire environment from another machine, not only the vs settings. I read a feature request for adding git repository support, each host could be a branch and **master** branch could be the **default** settings user wants in every fresh install. It would be better if you publish this ideas on slack or a community with active users of this extension.

**Comment by shanalikhan** [comment]
Instead of hot switch in same env. 
New idea explained on #936 

Displaying the list will be shipped on v3.4.0

**Comment by shanalikhan** [comment]
Duplicate of #506
