### ISSUE TITLE
Automatic syncing

### ISSUE THREAD

**Issue by ebeloded** [shanalikhan/code-settings-sync#31]
I find manual download/upload unnecessary for this extension. Every time I add a snippet, I have to remember to upload my settings to keep it up to date. Is it possible to make this extension to sync data automatically when settings, key bindings or snippets change?

Ideally, I would like to install this extension and forget about it. Just like Chrome settings sync work: You don't need to push a button for syncing to kick in.

**Comment by Kirill** [comment]
+1
I like this. Atom has plaugin witch automatic sync setting on start

**Comment by jeffijoe** [comment]
Sublime has a [Package Syncing](https://github.com/csch0/SublimeText-Package-Syncing) that syncs all installed packages and settings automatically to OneDrive, Dropbox, etc.

Automatic syncing would be awesome!

**Comment by shanalikhan** [comment]
I didnt find any extension API to run any function when VS Code Load Complete, yet.
I will start working on it once i find any solution.

**Comment by Dan1el42** [comment]
Hi @shanalikhan,

I've just wondered if using the activation events API could do the trick. Reference here: https://code.visualstudio.com/docs/extensionAPI/activation-events

I'm not familiar with developing VSCode extensions yet. However, for me implementing the functions for activation_events.* could be an option to resolve this.

Please let us know your thoughts. We might need to open a feature request for VSCode to have a more specific activation event, may be even contribute the code to VSCode.

Cheers
Daniel

**Comment by shanalikhan** [comment]
@Dan1el42 thanks, that might work.
I will start working on it.

Thanks

**Comment by Dan1el42** [comment]
Thanks and of course thanks very much for creating this extremely useful extension for Visual Studio Code.  Keep up the great work.

**Comment by shanalikhan** [comment]
I have recently release the first update for automatic sync. Please have a look and feel free to open an issue or post here.....
