### ISSUE TITLE
Setup Token in Local Setting Config

### ISSUE THREAD

**Issue by shanalikhan** [shanalikhan/code-settings-sync#310]
Currently the token is added in the hidden places using code.

But token can be setup in user `syncLocalSettings.json` so user can manually add github token and remove from there.

**Comment by ekweible** [comment]
@shanalikhan I regenerated the personal access token that I originally configured this plugin to use, and now I'm not able to change it. I tried resetting the settings, but the token isn't affected by that. So now when I try to download/upload my settings, it fails with a "bad credentials" error.

Allow this to be set manually, per this issue, would allow me to fix this.

**Comment by evanweible-wf** [comment]
Thanks @shanalikhan!

**Comment by ekweible** [comment]
Thanks @shanalikhan!
