### ISSUE TITLE
`unknown configuration setting` after updating

### ISSUE THREAD

**Issue by Deilan** [shanalikhan/code-settings-sync#315]
**Visual Studio Code Version :** 1.11.2
**Code Settings Sync Version :** 2.7.0
**Operating System :** Windows 8.1 x64
**Occurs On:** Permanently
**Proxy Enabled:** N/A
**GIst Id:** N/A

`sync.version` and `sync.showSummary` became `unknown configuration setting`:
```
"sync.version": 262,
"sync.showSummary": true,
```
![untitled](https://cloud.githubusercontent.com/assets/4777512/25715350/e4fb099e-3103-11e7-8d2c-4f56530c2364.png)

If they're gone and are not going to come back, consider removing them automatically after an update. If it's impossible display a note to and end-user about actions she should perform manually to keep living on the bleeding edge. :)

**Comment by shanalikhan** [comment]
For now, user need to delete this manually.
This is bug in code itself, unable to remove them
Issue already filled at https://github.com/Microsoft/vscode/issues/25179
