### ISSUE TITLE
Incompatibility with Linux? 

### ISSUE THREAD

**Issue by LordAmit** [shanalikhan/code-settings-sync#317]
**Visual Studio Code Version :** 1.12.1
**Code Settings Sync Version :** 2.7.0
**Operating System :** Kubuntu 64 bit 17.04
**Occurs On:** Upload / Download / Help Configuring 
**Proxy Enabled:** NO
**GIst Id:** N/A

Hi,
I installed the extension. When I wanted to configure it for the first time, this happens.

![image](https://cloud.githubusercontent.com/assets/480479/25865606/41fd015a-3515-11e7-8e16-347427ee3501.png)

Or maybe download settings:
![image](https://cloud.githubusercontent.com/assets/480479/25865683/7bc35b78-3515-11e7-94fc-f04a0b796315.png)

Or reset settings: 
![image](https://cloud.githubusercontent.com/assets/480479/25865709/9b0a94f6-3515-11e7-85fe-cff19ed963eb.png)

**Comment by shanalikhan** [comment]
Please remove this extension, remove folder from code extensions.
And install the extension again.
Extension supports all OS, if problem is still there. 
Post the developer console image

**Comment by LordAmit** [comment]
That worked :open_mouth:
