### ISSUE TITLE
Add support for automatic syncing (Upload / Download) after an interval

### ISSUE THREAD

**Issue by futagoza** [shanalikhan/code-settings-sync#318]
Currently this plugin has support for automatic syncing when the settings change or manual syncing.

Can you add a third option that allows the developer to set an interval in minutes (for example, every 15 minutes, with a minimum of 1 minute, any lower and the plugin should behave as it usually does) where the plugin should check if the settings have changed, and if so, upload the new settings.

```json
{
    "sync.autoUpload": true,
    "sync.quietSync": true,
    "sync.syncInterval": 15
}
```

**Comment by shanalikhan** [comment]
I'm closing this issue in favour of #396 and #123
As i don't feel this is important once auto upload/ download performs perfectly with extensions upload/ download.
