### ISSUE TITLE
locale.json not supported

### ISSUE THREAD

**Issue by jimmyfortinx** [shanalikhan/code-settings-sync#32]
**Visual Studio Code Version :** 1.0.0
**Code Sync Settings Version :** 1.1.8

It could be really nice to people like me to also support **locale.json**.

By default my vscode use the **fr-CA** locale but I want to use the **en-US** locale instead. To do that I ran the command _Changer la langue_ using the F1 command prompt. 

The locale.json is saved under the **%APPDATA%/Code/User** folder.

You can get more information about that [here](https://code.visualstudio.com/docs/customization/locales).

Thanks

**Comment by shanalikhan** [comment]
oh yes, its not supported yet. 
Thanks for letting me know i didnt know about this feature, will work on it

**Comment by shanalikhan** [comment]
Locale.json support is added
I am closing this issue.
let me know if you get any problem.

**Comment by OpportunityLiu** [comment]
Is this feature still working now?
I found my locale.json is not uploaded. Is there a config to enable it?
