### ISSUE TITLE
Dispose `statusBarItem` if there is no more message

### ISSUE THREAD

**Issue by neilsustc** [shanalikhan/code-settings-sync#320]
**Code Settings Sync Version**: 2.7.0

At present, after sync extension displayed some message and then cleared the message after timeout, the statusBarItem still holds a place. This will cause a weird gap between other statusBarItems, e.g.

![enable](https://cloud.githubusercontent.com/assets/7588612/26039673/44ea27be-3950-11e7-94f4-daac5e88a7cf.png)

If I disable the sync extension, this is the normal appearance

![disable](https://cloud.githubusercontent.com/assets/7588612/26039674/496b39b8-3950-11e7-8d31-5594a95d2375.png)

So I think it would be better to dispose the `statusBarItem` if there is no more message. And next time when we need to display a message, we can recreate it or just use `setStatusBarMessage` API

**Comment by shanalikhan** [comment]
Its fixed.

**Comment by neilsustc** [comment]
cool

**Comment by neilsustc** [comment]
Yes, the message 'Reading settings online' is fixed.

But it seems that the message 'you already have the latest settings' isn't fixed?

![image](https://cloud.githubusercontent.com/assets/7588612/26382586/cb1ab180-405f-11e7-9187-5cc8cc64968c.png)
