### ISSUE TITLE
What's the difference between `autoDownload` and `forceDownload`?

### ISSUE THREAD

**Issue by borekb** [shanalikhan/code-settings-sync#322]
They have basically the same description:

sync.autoDownload: "Set it true to Auto Download the settings on code start. [Code Restart Required]"
aync.forceDownload: "Set it to true if you want to download the settings everytime code starts."

What's the difference please? Thanks.

**Comment by shanalikhan** [comment]
LOL

Thanks, i will change it in the upcoming version.

**Comment by shanalikhan** [comment]
Fixed 
Will show description as
"Set it to true if you want to download the settings even when you have latest settings."

Let me know if you have any more ideas.
