### ISSUE TITLE
Stuck on `Sync: Installing Extensions in background`.

### ISSUE THREAD

**Issue by elboletaire** [shanalikhan/code-settings-sync#323]
**Visual Studio Code Version :** 1.12.2
**Code Settings Sync Version :** 2.7.0
**Operating System :** Ubuntu 16.04
**Occurs On:** Downloading extensions
**Proxy Enabled:** NO
**GIst Id:** https://gist.github.com/elboletaire/042243a5fbac6e239f1a067018a89abe

My code gets stuck on `sync: installing extensions in background.

![imatge](https://cloud.githubusercontent.com/assets/153305/26200616/40387a46-3bcf-11e7-9d7b-4f49a640e72f.png)

Does nothing, and there aren't errors on the console:

![imatge](https://cloud.githubusercontent.com/assets/153305/26200627/4a06f232-3bcf-11e7-9934-b42556052d89.png)

I understand that this will be hard to fix, if there aren't errors on the console and you can't reproduce it, but, is there any workaround?

**Comment by elboletaire** [comment]
I've tried removing the entire `.config/Code` folder, and now I face other problems... With the "fresh install", settings sync says there are no extensions to be added... but it's not true.

I'm adding now [the gist ID](https://gist.github.com/elboletaire/042243a5fbac6e239f1a067018a89abe) on top, so you can check it with my currently synced settings.

**Comment by elboletaire** [comment]
Here's the error log when I try to download the settings in the `fresh install`:

![imatge](https://cloud.githubusercontent.com/assets/153305/26203849/1e7aa59c-3bdd-11e7-80c1-304db4d60811.png)

**Comment by elboletaire** [comment]
Removing the `~/.vscode` folder fixed all these issues... 😕

**Comment by shanalikhan** [comment]
This stucks due to problems while downloading the extensions either from the network down or any other reason, sometime specific extension version deosnt download from the marketplace due to network problem.

I am glad you have fixed the issue. 😄

**Comment by elboletaire** [comment]
Yeah but wasn't my case.. in my case was some tempfile stored in `.vscode` folder, because everything was buggy until I removed that folder.

I close the issue, unless I face with it again (or anyone else, ofc).
