### ISSUE TITLE
command 'extension.updateSettings' not found

### ISSUE THREAD

**Issue by JourneyOver** [shanalikhan/code-settings-sync#324]
**Visual Studio Code Version :** [ 1.12.2 ]
**Code Settings Sync Version :** [ 2.7.0 ]
**Operating System :** [ Windows 10 x64 bit ]

Whenever I try running the `Sync : Update / Upload Settings` command from the command palette, and I get the following message on the top:

> command 'extension.updateSettings' not found

Have tried various things from https://github.com/shanalikhan/code-settings-sync/issues/78 but to no avail. this is the only error that seems to produce at all in the dev console http://i.imgur.com/1GvFcc8.png

Edit: seems the whole extension is broken or something, as running any other command just throws out a 

> Command 'extension.%whatever the command was%' not found 

error.

**Comment by JourneyOver** [comment]
or after about half an hour of fiddling with things I seem to have fixed it O_o dunno what I did, but it seems to be working now again..

**Comment by tristan957** [comment]
This is affecting me on Linux

**Comment by nelsonong** [comment]
Same problem for me on Fedora 25.

**Comment by kristoferdoman** [comment]
This is effecting me on macOS.

**Comment by shanalikhan** [comment]
What is the exception in console

**Comment by fkumro** [comment]
Copied from my update in a closed ticket:

![code-settings-sync-console](https://cloud.githubusercontent.com/assets/51793/26749780/f359c726-47df-11e7-91ab-4fda3f28b0e1.png)

Version 1.12.2
Commit 19222cdc84ce72202478ba1cec5cb557b71163de
Date 2017-05-16T08:14:27.220Z
Shell 1.6.6
Renderer 56.0.2924.87
Node 7.4.0

The root path may be `$HOME/.config/Code - OSS` as `$HOME/.config/Code/` doesn't exist.

**Comment by shanalikhan** [comment]
> The root path may be $HOME/.config/Code - OSS

This extension doesnt support OSS version at the moment.

**Comment by fkumro** [comment]
After some reading, I see that 1.12.x is the OSS version. I think `package.json` allows any version 1.x.x to install this extension.

```json
"engines": {
  "vscode": "^1.11.0"
}
```

Restricting the engine version may reduce the number of bugs that are reported by 1.12.x users.

```json
"engines": {
  "vscode": "< 1.12.0"
}
```

I would put a PR in, but I am not sure the minimum engine version you are targeting. If you provide that, I can put a PR in with this change.

**Comment by shanalikhan** [comment]
I have the same Code version with the same commit and the details you have mentioned.
and Its not `Code - OSS`

If we try to `vscode": "< 1.12.0"` it will effect all code versions like insiders and standard Code and wont install on above versions.

What can be done is that extension need to identify which version of code is running - standard / insiders / OSS and make OSS paths, like its doing for Insiders and standard code version.

I will be more happy to accept the PR, if you are willing to do that.

**Comment by fkumro** [comment]
I will take a look into what is involved with setting up a dev env for vscode. In the time being, I looked at how this could be solved. Now I haven't worked with vscode extensions at all, ever, so please feel free to stop me at any time.

https://github.com/shanalikhan/code-settings-sync/blob/master/src/environmentPath.ts#L85-L86

```typescript
 var codePath = this.isInsiders ? '/Code - Insiders' : '/Code';
 this.PATH = this.PATH + codePath;
```

could be changed to

```typescript
this.PATH = getDefaultUserDataPath(process.platform)
```

Function definition -> https://github.com/Microsoft/vscode/blob/master/src/paths.js#L19

Few more sections *may* be able to be refactored but without a dev env currently setup, I can't confirm it would work properly.

**Comment by shanalikhan** [comment]
@fkumro All paths defined in the function is present in the extension file already.
But i am not acknowledge of code providing a API to get the paths ( i'm not sure now, but it was not present when i wrote). But you can try
Its in my roadmap for OSS but i will first solve and implement a chunk of features that are opened in the issue portal.

Open new issue, Lets discuss this there.

**Comment by johnholliday** [comment]
same for me in Windows 10
