### ISSUE TITLE
spawn EACCES: Error: spawn EACCES

### ISSUE THREAD

**Issue by lekhnath** [shanalikhan/code-settings-sync#327]
**Visual Studio Code Version :** [ 1.12.1 ]
**Code Settings Sync Version :** [ 2.8.0 ]
**Operating System :** [ Ubuntu 13.10 ]

In developers tool console I get following error log when hit `shtft+alt+u` shourtcut .

```
spawn EACCES: Error: spawn EACCES
    at exports._errnoException (util.js:1022:11)
    at ChildProcess.spawn (internal/child_process.js:313:11)
    at Object.exports.spawn (child_process.js:399:9)
    at module.exports (/home/lekhnath/.vscode/extensions/Shan.code-settings-sync-2.8.0/node_modules/opn/index.js:74:26)
    at Commons.<anonymous> (/home/lekhnath/.vscode/extensions/Shan.code-settings-sync-2.8.0/out/src/commons.js:189:25)
    at Generator.next (<anonymous>)
    at fulfilled (/home/lekhnath/.vscode/extensions/Shan.code-settings-sync-2.8.0/out/src/commons.js:4:58)
e.onUnexpectedError @ workbench.main.js:29
(anonymous) @ workbench.main.js:29
e.onUnexpectedError @ workbench.main.js:28
o @ workbench.main.js:28
t.onUnexpectedExtHostError @ workbench.main.js:28
e.handle @ workbench.main.js:28
s @ workbench.main.js:28
f @ workbench.main.js:28
_combinedTickCallback @ internal/process/next_tick.js:67
_tickCallback @ internal/process/next_tick.js:98
```

**Comment by shashank7200** [comment]
Confirming the issue:
1. Shift+Alt+U doesn't do anything.
2. How to Configure Shows `Error spawn EACCES`

OS: `Ubuntu 16.10`  VS Code version: `1.12.2`

**Comment by shanalikhan** [comment]
Does setting `chmod +x /home/lekhnath/.vscode/extensions/Shan.code-settings-sync-2.8.0/node_modules/opn/xdg-open` work  ?
Let me know, i will release a build this week to solve this.

https://github.com/sindresorhus/opn/issues/54#issuecomment-303966289

**Comment by lekhnath** [comment]
@shanalikhan Yes! running  the command you provided eliminated that error.

**Comment by elboletaire** [comment]
Uploading throws the `Error span EACCESS` error, but setting `xdg-open` as executable fixes it.

**Comment by shanalikhan** [comment]
Its fixed in v2.8.1
Let me know if there is still a problem

**Comment by jbbr** [comment]
I installed this extension today (2.8.2, vscode 1.13.1, Linux) and have the same problem.
Making `~/.vscode/extensions/Shan.code-settings-sync-2.8.2/node_modules/opn/xdg-open` executable works.

**Comment by rahulthampi** [comment]
this bug still exists in v2.8.2, Ubuntu 16.04. 
But running 
`chmod +x /home/<desktop-username>/.vscode/extensions/<settings-sync-folder-name>/node_modules/opn/xdg-open`
solves the issue. Thanks

**Comment by sanjeevkpandit** [comment]
This bug still exists in v2.8.2, openSUSE Tumbleweed. But, making the `xdg-open` file executable solves the problem. Thanks!

**Comment by tamj0rd2** [comment]
After setting that file to executable the "How to configure" page now opens but `shift + alt + u` still doesn't work

**Comment by kemelzaidan** [comment]
I believe this bug is still valid in 2.8.2.
