### ISSUE TITLE
Show less notifications when upgrading/installing

### ISSUE THREAD

**Issue by beeblebrox3** [shanalikhan/code-settings-sync#328]
**Visual Studio Code Version :** 1.12
**Code Settings Sync Version :** 2.8.0

It's possible to show less notifications after upgrade? This is very annoying :(

![image](https://cloud.githubusercontent.com/assets/767624/26449422/7602a60c-4128-11e7-884a-978ace644ce3.png)

Thanks!

**Comment by shanalikhan** [comment]
😞 
ok
