### ISSUE TITLE
Error on upload after using token

### ISSUE THREAD

**Issue by Mosho1** [shanalikhan/code-settings-sync#33]
**Visual Studio Code Version :** 1.0.0
**Code Sync Settings Version :** 1.1.8

http://imgur.com/jmP5eCg.png

**Comment by shanalikhan** [comment]
Hi 
Have you tried again on different network. were you able to create the GIST or still getting the same problem ?

**Comment by shanalikhan** [comment]
I'm closing the issue until i get your response if the issue still occurs in the new releases
