### ISSUE TITLE
Uploading settings throws `TypeError: Cannot read property forEach of undefined`

### ISSUE THREAD

**Issue by elboletaire** [shanalikhan/code-settings-sync#330]
**Visual Studio Code Version :** 1.12.2
**Code Settings Sync Version :** 2.8.0
**Operating System :** Ubuntu 16.04
**Occurs On:** Uploading settings
**Proxy Enabled:** No
**GIst Id:** https://gist.github.com/elboletaire/042243a5fbac6e239f1a067018a89abe

After setting `xdg-open` as executable the error described in #327 gets fixed, but settings can't upload due to a TypeError:

![imatge](https://cloud.githubusercontent.com/assets/153305/26490686/a8966646-420c-11e7-8402-6e89e3624692.png)

**Comment by shanalikhan** [comment]
Fixed in v2.8.1
