### ISSUE TITLE
Unable to read syncLocalSettings.json. Make sure its Valid JSON

### ISSUE THREAD

**Issue by ByWhiter** [shanalikhan/code-settings-sync#332]
Visual Studio Code Version :1.12.2
Code Settings Sync Version :2.8.0
Operating System :macOs Sierra 
Occurs On: Help Configuring 
Proxy Enabled:No

Error:Sync : Unable to read syncLocalSettings.json. Make sure its Valid JSON.And always jump to your web pages
hi，I have a  question : I  can't  found  the  lsyncLocalSettings.json file  in my computer on the global  environment , how to solve the problem?

**Comment by ByWhiter** [comment]
![nk5zfol4ff](https://cloud.githubusercontent.com/assets/13621465/26517543/3941c378-42cd-11e7-8fdf-d42ae53b1827.gif)

**Comment by shanalikhan** [comment]
> I can't found the lsyncLocalSettings.json file in my computer on the global environment

Can you show me your structure of User folder.

**Comment by ByWhiter** [comment]
Thank you for your answer。
Like this？
![image](https://cloud.githubusercontent.com/assets/13621465/26519263/f31b6b8c-42f0-11e7-8599-21a4a257453b.png)

**Comment by shanalikhan** [comment]
Glad to know you have solved the issue!
how about update a review about extension in that page 😄

**Comment by obust** [comment]
I am on ubuntu 16.04 and I get this error everytime I open a project.

I have looked for the `syncLocalSettings.json` file but cannot find it in these directory:
- `/usr/share/code`
- `/home/<username>/.vscode`
Where is this file located on linux systems ?

**Comment by shanalikhan** [comment]
This file is in your `User` where your code settings are present. Open the code settings in explorer and see the folder
