### ISSUE TITLE
Too many prompts presented to users.

### ISSUE THREAD

**Issue by NickCraver** [shanalikhan/code-settings-sync#335]
**Visual Studio Code Version :** 1.12.2
**Code Settings Sync Version :** 2.8.1
**Operating System :** All
**Occurs On:** Open, Upgrade, etc.

Please consider what you're doing to users with your prompts. Sync is by far the nosiest extension I've ever come across. This is from a single open:
<img width="742" alt="screen shot 2017-06-03 at 07 44 16" src="https://cloud.githubusercontent.com/assets/454813/26753277/0980fad2-4831-11e7-9d67-e26e6a6f51ea.png">

I have no vested interest because this prompted me to uninstall the Sync extension. I'm filing this because what users see really should be taken into account here, they're being bombarded. The amount of prompts a user sees should be drastically reduced. Extensions are there to help the user experience, not get in the way of it. When it harms more than it helps, people will uninstall it as I have.

**Comment by shanalikhan** [comment]
I have changed this from the next update.
U will only see the release notes and write a review message

**Comment by NickCraver** [comment]
@shanalikhan On every update of the extension?

**Comment by shanalikhan** [comment]
These messages appears obly in upgrading the extension once u upgrade
U wont see them from the next use

**Comment by NickCraver** [comment]
@shanalikhan I'm trying to get clarification here: every time you push even a minor version, users get 2 message prompts?

**Comment by RamblingCookieMonster** [comment]
Completely agree with @NickCraver 

Don't really write user facing things, but from my perspective....

* Consider what would happen if every extension did this, or even a minor portion?  vscode would become unusable
* Is there a reason to display anything, outside of cases where you make a breaking change?

Cheers!

**Comment by shanalikhan** [comment]
@RamblingCookieMonster 
Actually these messages are meant for one time only, As i had to change the place for token and make sure user know about it.

Second message is about the new feature.

If you try to find # 14444 issue in vscode repo, currently extension doesnt support _sync_ when user remove any extension, VS Team didnt aware of this scenario when they wrote API i had to show messages to user so they upvote my issue and have about 1000 votes, at the end Code team informed they will work on it in the next version.

I haven't received much complains from the users about the messages, though some reported in the reviews.

> Consider what would happen if every extension did this, or even a minor portion

Yes you are right and i appreciate your behavior.
What i can do is on update - there will be one message to let user see the release notes, or review extension.


@NickCraver Thanks for posting in Twitter even before filing the issue!

**Comment by Tyriar** [comment]
> I haven't received much complains from the users about the messages, though some reported in the reviews.

You need to consider though that some users have over 20 extensions, just imagine if all of them put just one notification up every update - that's a lot of spam. Even a single message telling the user of an update is too much for a regular release imo, most users update the extension manually in which case they can check what the changes are in the changelog (you should add a `CHANGELOG.md`), and a big portion of them probably won't care anyway.

I recommend only showing a message if there is a breaking change that will impact a large percentage of users, such as settings keys changing (if you can detect that the users are using the old setting then even better).

**Comment by JimiC** [comment]
I agree with @Tyriar. Use `README` and `CHANGELOG` files instead of `info` spam.
