### ISSUE TITLE
Allow installing the latest version or extension specific versions from configuration

### ISSUE THREAD

**Issue by borekb** [shanalikhan/code-settings-sync#337]
This is how info about extensions is currently stored:

```json
[
  {
    "metadata": {
      "id": "6e440e71-8ed9-4f25-bb78-4b13096b8a03",
      "publisherId": "38bbe3f0-5204-4170-845e-c2f966d979b8",
      "publisherDisplayName": "Jun Han"
    },
    "name": "auto-rename-tag",
    "publisher": "formulahendry",
    "version": "0.0.12"
  },
  ...
]
```

There are version numbers which means that with every minor update, this file changes and new version of Gist is created. I think it would be better if `extensions.json` excluded those and new version of Gist would be uploaded on a true change of extensions.

**Comment by shanalikhan** [comment]
Actually it was on purpose to install the specified version from the marketplace.
and this is the one of the reason i have not switched to Code CLI so far - which provides a way only to download the latest version of extension , not by version name.

But this can be a option to allow user to have the latest version by default, but only have the specified versions of extensions when he wants with a setting.

**Comment by borekb** [comment]
I'd be interested in stats on how many people actually install concrete, non-latest version of extensions. I think that up until recently, it was even impossible to disable extension auto-updates although I might be wrong on that.

**Comment by shanalikhan** [comment]
https://github.com/Microsoft/vscode/issues/27375

Sometimes extension breaks on the new version though some authors may release in insiders first but if any extension breaks in the latest release, User will end up nothing so he can use the Gist to have the older version of extension. There can be more scenarios for that.


`extensions.autoUpdate` is the key that can be integrated if user installs the non-latest versions of extension it should be set to `false` always.

> I'd be interested in stats on how many people actually install concrete, non-latest version of extensions.

Interaction with user is not possible via information messages, recently users ended up taking it as spam.

I have a plan https://github.com/shanalikhan/code-settings-sync/issues/230 to show the monthly results on blog, after adding Google Analytic for events, if you know any alternative free tool then do share.

**Comment by shanalikhan** [comment]
By default it will now install latest version.
If you need to keep version specific settings then use `useCliBaseInstallation` as `false` in Settings Sync Global Settings.
I will improve it more in next releases.
