### ISSUE TITLE
replaceCodeSettings seems backwards in some cases. Can we get an ignoreCodeSettings property that just lists settings' keys to ignore on upload?

### ISSUE THREAD

**Issue by chevex** [shanalikhan/code-settings-sync#338]
Would it be possible to get an `ignoreCodeSettings` option that is just an array of keys to ignore?

For example, I am using the VS Code Vim extension which has an option to delegate some tasks to Neovim if you have it installed. On Windows I have to provide a path to the Neovim executable.

`"vim.neovimPath": "C:\\Windows\\SysWOW64\\Get-ToolsLocation\\neovim\\Neovim\\bin\\nvim.exe"`

But then on my Macbook, my Mac Pro, and my work Mac the default value of `"nvim"` is sufficient because Neovim lives on my PATH as `nvim`.  So since I **don't** want to set `vim.neovimPath` on any of my Mac machines I now have to add the following to every single Mac machine:

```
"replaceCodeSettings": {
  "vim.neovimPath": ""
}
```

What I'd rather do is just add the following to my Windows machine only:

```
"ignoreCodeSettings: [
  "vim.neovimPath"
]
```

That way I could just set `ignoreCodeSettings` on my Windows machine only instead of me having to set `replaceCodeSettings` on all my other machines. It would also be better in cases where the Code settings need to be a different value on every machine. You could just set `ignoreCodeSettings` on each machine and set the value to be different on each machine. The setting wouldn't even be included in the Gist and you wouldn't have to every worry about those values getting overridden.

**Comment by shanalikhan** [comment]
yes you are right, 
There is already issue opened for it with the same settings you have shown.
https://github.com/shanalikhan/code-settings-sync/issues/232#issuecomment-302949327

Im closing this. Post the ideas there.
