### ISSUE TITLE
the plugs  just only one pc upload? 

### ISSUE THREAD

**Issue by LastKing** [shanalikhan/code-settings-sync#339]
**Visual Studio Code Version :** [ 1.13.0]
**Code Settings Sync Version :** [ 2.8.1]
**Operating System :** [ win10 ]
**Occurs On:** [Upload / Download / Help Configuring ]
**Proxy Enabled:** [ Yes / No ]
**GIst Id:** [ 480ba87d08f3e18036921394571a71f2]

Sorry I'm Englise is very bad!  Personal Acccess Tokens just only use once?  If I have 2 pc ,I want to upload it on two pc.  
Thanks for your help！

**Comment by shanalikhan** [comment]
no , you can set it on both PC with the same token.

**Comment by LastKing** [comment]
thank for your help!~!~!~
