### ISSUE TITLE
error after update to `v1.2.2`

### ISSUE THREAD

**Issue by rozzzly** [shanalikhan/code-settings-sync#34]
### Overview
**Visual Studio Code Version :** (`v1.1.0` :: Microsoft/vscode@c212f0908f3d29933317bbc3233568fbca7944b1) according to `Help -> About`
**Code Sync Settings Version :** `v1.2.2`
**TypeScript Version*:* `^1.9.0-dev.20160514`(nightly)
  * specified via  `"typescript.tsdk": "./node_modules/typescript/lib"` in my `./vscode/settings.json
  * the issue appears to be unrelated to using the "unstable" dev build

**Rundown:**
  * Today I updated from `v1.2.1` to `v1.2.2`. It was working find yesterday
  * I run the update task from the command pallet
  * Get Error :sob: 

---

### Data

Got this error via notification in the workspace, `Cannot find module './package.json'`
Then there's a bunch more in the console, but here's the important part. The rest is included below.
```ts
shell.ts:416 Cannot find module './package.json': Error: Cannot find module './package.json'
```
<details>
<summary>expand to view full stack traces and error Object</summary>

4 things got logged to my console in `Developer Tools`

##### first exception

```ts
shell.ts:416 Cannot find module './package.json': Error: Cannot find module './package.json'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Function.N.n._load (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:17:18321)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Commons.<anonymous> (C:\Users\rozzzly\.vscode\extensions\Shan.code-settings-sync-1.2.2\out\src\commons.js:22:25)
    at next (native)
    at C:\Users\rozzzly\.vscode\extensions\Shan.code-settings-sync-1.2.2\out\src\commons.js:7:65
    at __awaiter (C:\Users\rozzzly\.vscode\extensions\Shan.code-settings-sync-1.2.2\out\src\commons.js:3:12)
    at Commons.InitSettings (C:\Users\rozzzly\.vscode\extensions\Shan.code-settings-sync-1.2.2\out\src\commons.js:19:16)e.onUnexpectedError @ shell.ts:416(anonymous function) @ shell.ts:318e.onUnexpectedError @ errors.ts:73u @ errors.ts:88(anonymous function) @ winjs.base.js:45(anonymous function) @ winjs.base.js:40
winjs.base.js:47 WARNING: Promise with no error callback:201
```

```ts
WARNING: Promise with no error callback:201
```
##### seperate error object logged to console 
_( I used `JSON.stringify(temp1, null, '\t')` to make it presentable )_
```json
{
	"exception": null,
	"error": {
		"name": "Error",
		"message": "Cannot find module './package.json'"
	},
	"promise": {
		"_oncancel": null,
		"_nextState": null,
		"_state": {
			"name": "error",
			"done": null,
			"then": null
		},
		"_listeners": null,
		"_value": {
			"name": "Error",
			"message": "Cannot find module './package.json'"
		},
		"_isException": false,
		"_errorId": 201
	},
	"id": 201
}
```

##### second exception

```ts
Cannot find module './package.json'                                                     messageService.ts:108

e.doShow @ messageService.ts:128
e.show @ messageService.ts:112
e.resume @ messageService.ts:71
(anonymous function) @ workbench.ts:343
e.invoke @ callbackList.ts:63e.fir
e @ event.ts:107
(anonymous function) @ quickOpenController.ts:467
```
</details>

-------

### Mitigation `(Workaround Found)`

  * uninstall **`-->`** restart **`-->`** reinstall **`-->`** restart **`-->`** run upload command via command pallet

    > Same message. No effect.

  * Try to restore the `package.json`

    ###### Steps to Resolve

    1) Locate this extension in the `VS Code` extension directory
    
      * Found path in stack trace:
      * `C:\Users\rozzzly\.vscode\extensions\Shan.code-settings-sync-1.2.2`
      * Extension's root directory contains a `package.json` 

      **Note:** the full line from the stack trace was actually:
          `..\Shan.code-settings-sync-1.2.2\out\src\commons.js:22:25` 

    2) **copy** `./package.json` to `./out/src/`
    3) re-run command from the pallet; it works!

sounds like something is off in your build script

**Comment by shanalikhan** [comment]
Thank you , i have updated the extension. im closing this issue and let me know if you find such error again.

**Comment by rozzzly** [comment]
Works! :) thanks for the quick turn arround

**Comment by shanalikhan** [comment]
actually i was trying to show automatic build release notes on updating the extension. I think adding option in the menu to get the release notes is better than opening automatically.
