### ISSUE TITLE
cant download setting

### ISSUE THREAD

**Issue by zimplexing** [shanalikhan/code-settings-sync#341]
**Visual Studio Code Version :** [ 1.8.0 ]
**Code Settings Sync Version :** [ 2.8.1 ]
**Operating System :** [ win7 ]
**Occurs On:** [ Download  ]
**Proxy Enabled:** [  No ]
**GIst Id:** [ 39b2654812e2498276db0dd405950428 ]

I have posted frequently asked questions on 
http://shanalikhan.github.io/2016/11/07/visual-studio-code-frequently-asked-questions.html 
so you may able to resolve the error quickly. 
Please make sure to write the versions and console logged error picture or copied text

**Comment by shanalikhan** [comment]
> Please make sure to write the versions and console logged error picture or copied text
