### ISSUE TITLE
Cannot read property 'trim' of null

### ISSUE THREAD

**Issue by ferrantejake** [shanalikhan/code-settings-sync#342]
**Visual Studio Code Version :** [ 1.13.0 ]
**Code Settings Sync Version :** [ 2.8.1 ]
**Operating System :** [ Arch Linux x86_64 / 4.11.3-1-ARCH ]
**Occurs On:** [ Upload ]
**Proxy Enabled:** [ No ]
**GIst Id:** [ 941fe3abd89c4cd9ec809c07bb1f4b4a ]

A notification banner appears across the top of my screen indicating an error logged in the developer console. The relevent error and logs proceeding/following

```
extensionHost.ts:297[Extension Host] Sync : File Change Detected On : /home/jakef/.config/Code/User/settings.json
2017-06-15 12:31:49.750 extensionHost.ts:297[Extension Host] Sync : Initiating Auto-upload For File : /home/jakef/.config/Code/User/settings.json
2017-06-15 12:31:53.179 extensionHost.ts:297[Extension Host] TypeError: Cannot read property 'trim' of null
    at /home/jakef/.vscode/extensions/Shan.code-settings-sync-2.8.1/out/src/extension.js:195:73
    at Generator.next (<anonymous>)
    at /home/jakef/.vscode/extensions/Shan.code-settings-sync-2.8.1/out/src/extension.js:7:71
    at __awaiter (/home/jakef/.vscode/extensions/Shan.code-settings-sync-2.8.1/out/src/extension.js:3:12)
    at /home/jakef/.vscode/extensions/Shan.code-settings-sync-2.8.1/out/src/extension.js:191:40
    at process._tickCallback (internal/process/next_tick.js:103:7)
d.logExtensionHostMessage @ extensionHost.ts:297
2017-06-15 12:31:53.184 messageService.ts:125Sync : Error Logged In Console (Help menu > Toggle Developer Tools).
e.doShow @ messageService.ts:125
2017-06-15 12:31:55.245 extensionHost.ts:297[Extension Host] Sync : Connected with user : 'ferrantejake'
```

Best,
Jake

**Comment by sporto** [comment]
Same here, thanks

**Comment by Frankie7462654** [comment]
Visual Studio Code Version : [ 1.13.1 (1.13.1)]
Code Settings Sync Version : [ 2.8.1 ]
Operating System : [ macOS Sierra 10.12.5 (16F73) ]
Occurs On: [ Upload ]
Proxy Enabled: [ Yes ]
GIst Id: [6e839908e3ab7766a3a4e6878a61f032]

`/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:29 [Extension Host] TypeError: Cannot read property 'trim' of null
    at /Users/Frankie/.vscode/extensions/Shan.code-settings-sync-2.8.1/out/src/extension.js:195:73
    at Generator.next (<anonymous>)
    at /Users/Frankie/.vscode/extensions/Shan.code-settings-sync-2.8.1/out/src/extension.js:7:71
    at __awaiter (/Users/Frankie/.vscode/extensions/Shan.code-settings-sync-2.8.1/out/src/extension.js:3:12)
    at /Users/Frankie/.vscode/extensions/Shan.code-settings-sync-2.8.1/out/src/extension.js:191:40
    at process._tickCallback (internal/process/next_tick.js:103:7)
d.logExtensionHostMessage @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:29
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:28 Sync : Error Logged In Console (Help menu > Toggle Developer Tools).
e.doShow @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:28
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:29 [Extension Host] Sync : Connected with user : 'Frankie7462654'
`

**Comment by shanalikhan** [comment]
Will be fixed in next version.

**Comment by shanalikhan** [comment]
I have published new version. 
Let me know if error persists
