### ISSUE TITLE
Sync "Not Found"

### ISSUE THREAD

**Issue by DonSanto** [shanalikhan/code-settings-sync#343]
**Visual Studio Code Version :** 1.13.1
**Code Settings Sync Version :** 2.8.1
**Operating System :** macOS Sierra 10.12.4
**Occurs On:** Download and Upload
**Proxy Enabled:** No
**GIst Id:** Any Gist ID (New, Old)

When trying to Download the Gist settings, I just get the error message _Not Found_:

![image](https://user-images.githubusercontent.com/1021604/27215822-58cca7fc-5273-11e7-9466-248c7f70ebc7.png)

The Gist token is not saved to the settings. But even if I add it manually I still get that same error message.

**Comment by shanalikhan** [comment]
what is the exception in the developer console. Paste image

**Comment by DonSanto** [comment]
If you are referring to the _Debug console_ I get no output. Otherwise, I would like to know how to open the _Developer console_.

**Comment by shanalikhan** [comment]
Help > Toggle Developer tool > Console

**Comment by DonSanto** [comment]
Perfect, thanks!

This is what I get 
![image](https://user-images.githubusercontent.com/1021604/27225135-1e4f7142-5299-11e7-9894-09f63ac6d8f4.png)
****

**Comment by shanalikhan** [comment]
Try this :
https://github.com/shanalikhan/code-settings-sync/issues/177#issuecomment-269873967

**Comment by sherlockednguyen** [comment]
It not work for me also, got the same error with @DonSanto 

After I try #177 then It still get the same error.

**Comment by DonSanto** [comment]
No, that did not help att all.

**Comment by CamilleBC** [comment]
Hello, same error here. Here is the log.


```
messageService.ts:125
Not Found
e.doShow @ messageService.ts:125
e.show @ messageService.ts:104
(anonymous) @ mainThreadMessageService.ts:64
n.Class.derive._oncancel @ winjs.base.raw.js:1641
t.showMessage @ mainThreadMessageService.ts:34
t.$showMessage @ mainThreadMessageService.ts:28
e.handle @ abstractThreadService.ts:34
s @ ipcRemoteCom.ts:275
f @ ipcRemoteCom.ts:231
_combinedTickCallback @ internal/process/next_tick.js:67
_tickCallback @ internal/process/next_tick.js:98

extensionHost.ts:293
[Extension Host] {"message":"Not Found","documentation_url":"https://developer.github.com/v3"}
d.logExtensionHostMessage @ extensionHost.ts:293
(anonymous) @ extensionHost.ts:147
emitTwo @ events.js:106
emit @ events.js:191
process.nextTick @ internal/child_process.js:752
_combinedTickCallback @ internal/process/next_tick.js:67
_tickCallback @ internal/process/next_tick.js:98
```

**Comment by ericop** [comment]
I got this same error on Windows 10 , VS code version is 1.13.1, today after installing https://marketplace.visualstudio.com/items?itemName=johnpapa.angular-essentials . I did an uninstall all (as it is a bucket extension for several others) but it is still giving "**Error** Not Found". 

I then tried to uninstall and reinstall Code Settings Sync extension but again I'm still getting  "**Error** Not Found". I'm uninstalling this extension until this bug is fixed as it's completely non-functional. @shanalikhan this is a super cool extension and I'm glad you've labored away at making it what it is. May you be victorious in solving this bug as well.

**Comment by gunnim** [comment]
Same error "Not Found"
I also get the same output in my developer console, but it ends with 
[Extension Host] Sync : Connected with user : 'gunnim'

on windows 10, vscode 1.13.1

**Comment by scorchgid** [comment]
I am also getting this error. I've look on other posts and it says "well you've likely got the wrong gist". I haven't as I copied it straight from the source after resetting it and yes I did wait a few hours till trying it again. I tried restting the extension and uninstalling it and reinstalling the extension. No effect I am still getting Error Not Found.

I am on Linux Ubuntu 17.04. The following is the error message from the Dev Console

````
extensionHost.ts:293 [Extension Host] {"message":"Not Found",
"documentation_url":"https://developer.github.com/v3"}

d.logExtensionHostMessage @ extensionHost.ts:293
(anonymous) @ extensionHost.ts:147
emitTwo @ events.js:106
emit @ events.js:191
process.nextTick @ internal/child_process.js:752
_combinedTickCallback @ internal/process/next_tick.js:67
_tickCallback @ internal/process/next_tick.js:98
messageService.ts:125 Not Found

e.doShow @ messageService.ts:125
e.show @ messageService.ts:104
t.showMessage @ mainThreadMessageService.ts:64
n.Class.derive._oncancel @ winjs.base.raw.js:1641
t.showMessage @ mainThreadMessageService.ts:34
t.$showMessage @ mainThreadMessageService.ts:28
e.handle @ abstractThreadService.ts:34
s @ ipcRemoteCom.ts:275
f @ ipcRemoteCom.ts:231
_combinedTickCallback @ internal/process/next_tick.js:67
_tickCallback @ internal/process/next_tick.js:98
```

**Comment by shanalikhan** [comment]
can you guys try with the latest version ? and let me know

**Comment by gunnim** [comment]
Got 2.8.2 now, same error.
this is my settings file
{"ignoreUploadFiles":["projects.json","projects_cache_git.json"],"ignoreUploadFolders":["workspaceStorage"],"replaceCodeSettings":{},"gistDescription":"Visual Studio Code Settings Sync Gist","version":282,"token":"<githubgistcode>"}

and this was output in vscode developer tools

![image](https://user-images.githubusercontent.com/17432315/27768907-7c985404-5f0e-11e7-986d-823e56538fe3.png)

**Comment by antonio-rodrigues** [comment]
Code Settings Sync : 2.8.2
Visual Studio Code : 1.13.1
Operating System: macOS Sierra 10.12.5
(vscode) Shift + Cmd + P: Sync: Download settings and Update / Upload settings

**All worked okay** - no errors found.

Thank you!

**Comment by mizutoki79** [comment]
[Code Setting Sync]
Version : 2.8.2
[Visual Studio Code]
Version : 1.13.1
Commit : 379d2efb5539b09112c793d3d9a413017d736f89
[OS]
Edition Windows 10 Pro
Version 1703
OS build 15063.413
and
macOS Sierra
version 10.12.5

WFM
I check both Windows and Mac. I entered my PAToken to sync.gist by mistake.
Try below : 
Ctrl + , (command + ,) -> setting.json -> "sync.gist": "<Enter your Gist ID here>" -> Shift + Alt + D
You need GIST ID for download, NOT TOKEN. Check your setting.json. You don't need change syncLocalSetting.json.
Thank you.

**Comment by tangdaohai** [comment]
@mizutoki79 this right a way, It's working, thanks

**Comment by gunnim** [comment]
Yeah user error on my part as well...

**Comment by EliasCK** [comment]
I'm getting the same error as @gunnim 
https://jumpshare.com/v/TwPgvGrUw5McsBZgGd60

Here are my settings:
`{
    "sync.gist": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", // Generated this a thousands times, tried activating everything on the access token, no luck.
    "sync.lastUpload": "",
    "sync.autoDownload": false,
    "sync.autoUpload": false,
    "sync.lastDownload": "",
    "sync.forceDownload": false,
    "sync.anonymousGist": false,
    "sync.host": "",
    "sync.pathPrefix": "",
    "sync.quietSync": false,
    "sync.askGistName": false
}`

**Comment by shiamalon** [comment]
@mizutoki79 solved my issue, I think this is not super clear on the plugin instructions. thanks for the help.

**Comment by yalishizhude** [comment]
@mizutoki79 It works for me.
Please fix the bug ~ @shanalikhan

**Comment by remyvd** [comment]
@mizutoki79 solved it also for me. I was adding everytime the token. Now used the GistID in the URL and I could download my settings.

Plugin instructions are not clear in this.

**Comment by dankini** [comment]
@mizutoki79 solved for me too.

Existing screenshot in instructions kind of imply its the Token that should be entered.  Should be edited with screenshot showing how to grab Gist ID from URL.  Great extension otherwise.

**Comment by shanalikhan** [comment]
@DonSanto have you checked this solution of @mizutoki79 ?
https://github.com/shanalikhan/code-settings-sync/issues/343#issuecomment-312908504

I will add line to view the readme to check the uploaded gist by URL

**Comment by shanalikhan** [comment]
I'm closing this issue.
Documentation updated.
This message is also changed to let user know the URL from which he can verify the gist

**Comment by DonSanto** [comment]
Yes, finally I've got this working. Thanks @mizutoki79.

The instructions still are not clear. Please remove the image where you highlight the token ID. it is really confusing. Thanks.

**Comment by ksmithut** [comment]
I'm still running into this error, and the gist id is definitely correct. I'm definitely using the gist id:

```
"sync.gist": "********",
```

then `gist.github.com/********` redirects to my gist. But still getting the not found error. It is a secret gist, not sure if that makes a difference...
