### ISSUE TITLE
Cannot read property of 'getRoot', etc

### ISSUE THREAD

**Issue by drewklassen** [shanalikhan/code-settings-sync#345]
**Visual Studio Code Version :** 1.14.0 - Insider
**Code Settings Sync Version :**2.8.1
**Operating System :** Linux X 4.4.0-78-generic #99-Ubuntu SMP Thu Apr 27 15:29:09 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux (Linux Mint)
**Occurs On:** [Up / Down / Sync / Reset ]
**Proxy Enabled:** [No ]
**GIst Id:** [ 584b406b8a6a81be629be72a721ef12d97e1151b ]

Please make sure to write the versions and console logged error picture or copied text

**Comment by shanalikhan** [comment]
> Please make sure to write the versions and console logged error picture or copied text
