### ISSUE TITLE
Keybinding deleted on initial sync between OS

### ISSUE THREAD

**Issue by webdevnerdstuff** [shanalikhan/code-settings-sync#347]
**Visual Studio Code Version :** 1.13.1 (Mac & Win7)
**Code Settings Sync Version :** 2.8.1
**Operating System :** Mac: Sierra, PC: Win7
**Occurs On:** Upload / Download
**Proxy Enabled:** No

When setting up the code sync, I first set it up on the Win7 machine and uploaded the settings. I then set it up on my Mac, and downloaded the settings. When I did this, all of my Max Keybindings were deleted. My Gist does have both the _keybindingsMac.json_ and _keybindings.json_ files. My keybindings on the Win7 machine did and does not delete when I download the settings now. I have tried deleted/reinstalled the extension and have been able to replicate it more than once.

Sync Settings:
`"sync.gist": "secret-gist###",
"sync.autoDownload": false,
"sync.autoUpload": false,
"sync.forceDownload": false,
"sync.anonymousGist": false,
"sync.host": "",
"sync.pathPrefix": "",
"sync.quietSync": false,`

**Comment by shanalikhan** [comment]
Actually i dont have Mac to test the extension.
Can you let me know if you are still getting same behavior in the last update of extension also.
