### ISSUE TITLE
Invalid Expired Token - Not invalid 

### ISSUE THREAD

**Issue by webdevnerdstuff** [shanalikhan/code-settings-sync#348]
Visual Studio Code Version : 1.13.1 (Mac & Win7)
Code Settings Sync Version : 2.8.1
Operating System : Mac: Sierra, PC: Win7
Occurs On: Upload / Download
Proxy Enabled: No

I have uninstalled/reinstalled the extension multiple times all with the same results. I am able to update the settings on one machine where I set up the extension and token first, and I'm able to upload. I am also able to download the settings on the second machine, but if I make a change to the second machine settings and then upload, I get Invalid Token. But it still works if I make the change on the first machine and download on the second. I have tried multiple times and the same thing happens each time.

**Steps Taken:**
1. Added extension to Win7, generated/added token, uploaded settings.
2. Added extension to Mac, download settings, entered token when prompted.
3. Success.
4. Make a change on Win7 settings and upload.
5. Success
6. Download settings on Mac.
7. Success
8. Make a change on Mac settings and upload.
9. Invalid Token
10. Make a change on Win8 settings and upload.
11. Success
12. Download settings on Mac.
13. Success
14. Make a change on Mac settings and upload.
15. Invalid Token

**Error Console:**
2/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:29 [Extension Host] {"message":"Bad credentials","documentation_url":"https://developer.github.com/v3"}

d.logExtensionHostMessage @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:29

/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:28
Sync : Invalid / Expired Github Token. Please generate new token with scopes mentioned in readme. Exception Logged in Console.

e.doShow @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:28

/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:29 [Extension Host] {"message":"Bad credentials","documentation_url":"https://developer.github.com/v3"}

**Comment by shanalikhan** [comment]
can you try with the latest version ?
Reset settings, Create new token or make sure its valid and not expired and perform actions

**Comment by shanalikhan** [comment]
Let me know, i will re open it. 
If having problem

**Comment by fdncred** [comment]
Same problem.  Used to work. Now it doesn't. I reset my settings and now one of my systems works and the other says it's expired. So aggravating!

System that works *AFTER* resetting (which shouldn't be necessary)
Visual Studio Code Version : 1.14.2
Code Settings Sync Version : 2.8.2
Operating System : Win10
Occurs On: Upload / Download
Proxy Enabled: No

System that does not work after resetting
Visual Studio Code Version : 1.14.2 (64-bit)
Code Settings Sync Version : 2.8.2
Operating System : Win10
Occurs On: Upload / Download
Proxy Enabled: No

**Comment by MitjaBezensek** [comment]
Same here, I'm trying to sync between a Windows and Linux machines and this is happening all the time on both machines. I create a new token, can upload once, but when I try to download on the other machine this happens.

**Comment by SoiTrang** [comment]
I have the same problem with MitjaBezensek: can upload on pc1, but cannot download on pc2, token always expired

Visual Studio Code Version : 1.14.2 (both Windows 10)
Code Settings Sync Version : 2.8.2
Operating System : both Windows 10
Ocurs On: Upload / Download
Proxy Enabled: No

**Comment by wangbourne** [comment]
i have the same problem, one is MacbookPro, the other is MacMini
really frustrated :(

**Comment by BiosSun** [comment]
+1

**Comment by yingkeen** [comment]
+1

**Comment by troflog** [comment]
Same problem. Upload on a Windows machine. Try to download on a Ubuntu machine. Token is expired.

**Comment by Stefanbracke** [comment]
Same problem. On MacPro get Invalid/Expired GitHub token.

**Comment by shanalikhan** [comment]
https://github.com/shanalikhan/code-settings-sync/issues/388#issuecomment-344155611
