### ISSUE TITLE
Unable to upload to GitHub Enterprise

### ISSUE THREAD

**Issue by dainman** [shanalikhan/code-settings-sync#349]
**Visual Studio Code Version :** 1.13.1 (1.13.1)
**Code Settings Sync Version :** 2.8.2
**Operating System :**OSX 10.12.5
**Occurs On:** Upload
**Proxy Enabled:** no

Trying to use Github Enterprise.  I have set the sync.host and sync.pathPrefix in the user settings.  I have created a token that has gist and user access.

In the console I get an error "Empty value for parameter 'id'". Seems that I need to put a userName but don't see how to configure.  Tried resetting and using <username>:<token> when I saved the upload settings but that does not work either

**Comment by shanalikhan** [comment]
please share the console screen shoot.

**Comment by dainman** [comment]
Attached is the console log
[1499265156894.txt](https://github.com/shanalikhan/code-settings-sync/files/1125020/1499265156894.txt)

**Comment by shanalikhan** [comment]
is there still a problem or is it resolved by the latest version ?
Reset settings and then upload and let me know :)
