### ISSUE TITLE
cannot reset wrong account token

### ISSUE THREAD

**Issue by achimismaili** [shanalikhan/code-settings-sync#35]
**Visual Studio Code Version :** 1.1.1
**Code Sync Settings Version :** 1.2.3

I wanted to initialize sync. I did set the token wrong in my github account and then I also entered a wrong string when I was asked for the token in the command line of visual studio code (vsc).

I think, I entered the string "default" as access token in vsc

After that, I was not able to get to the command line to reset the token.

Even after deinstallation and reinstallation, the wrong value seemed cached.

Is there a file that I can delete to be able to start again with initialization?

Error says: Please open an issue in Github Repo. Please find attached the console log. 

[1463600575811.txt](https://github.com/shanalikhan/code-settings-sync/files/271277/1463600575811.txt)

**Comment by shanalikhan** [comment]
Type "Sync" and select reset settings in order to remove those settings and try again.
Let me know if issue still occurs.

**Comment by achimismaili** [comment]
Problem solved: 
I used the ctrl + p command line instead of the ctrl + shift + p command palette.
In the command line, "Sync" was not available as a command ... when using command palette everything worked fine just as documented ...
