### ISSUE TITLE
Error - [Spawn Eaccess] On Hitting Extension Commands

### ISSUE THREAD

**Issue by cybersupernova** [shanalikhan/code-settings-sync#352]
**Visual Studio Code Version :** [ 1.13.0 ]
**Code Settings Sync Version :** [ 2.8.2 ]
**Operating System :** [ Ubuntu 17.04 ]
**Occurs On:** [ Help Configuring ]
**Proxy Enabled:** [ No ]
**GIst Id:** [ NA ]

First I thought the key bindings are not working since there was no response,
typing Sync manually into the command palette also didn't work, Then I opened console to see the errors attached.
It may be a permission fault on my system but still, the extensions should through some exception.

![screenshot from 2017-07-07 04-34-03](https://user-images.githubusercontent.com/9431429/27936269-87d6c266-62cd-11e7-85eb-e3c6fd31294c.png)

**Comment by Jimmyscene** [comment]
Having the same issue on Solus.

**Comment by shanalikhan** [comment]
Try this and let me know
https://github.com/shanalikhan/code-settings-sync/issues/327#issuecomment-313500009

**Comment by Jimmyscene** [comment]
That did it. Thanks!

**Comment by cybersupernova** [comment]
thanks it worked, although I suggest handling the exception properly

**Comment by shanalikhan** [comment]
Will be fixed in next version.

**Comment by xiorcal** [comment]
having same issue, provided quickfix worked :)

**Comment by gyermolenko** [comment]
+1 ("having same issue, provided quickfix worked")

**Comment by malagutti** [comment]
I was also having the same issue on Ubuntu 16.04, the solution provided fixed it for me. Thanks. :smile:

**Comment by shanalikhan** [comment]
This issue if fixed in v2.8.3
let me know if there is any problem
