### ISSUE TITLE
Unable to upload: syncSummary.txt content on disk is newer

### ISSUE THREAD

**Issue by wsw70** [shanalikhan/code-settings-sync#353]
**Visual Studio Code Version :** 1.13.1
**Code Settings Sync Version :** 2.8.2
**Operating System :** Windows 10
**Occurs On:** Upload
**Proxy Enabled:** No 
**GIst Id:** 83bad5e7c8fe0571dfcfebcc05810d51

I set up `code-setting-sync` for the first time. I arrived to the point where `syncSummary.txt` is created (gist created, popup informing me to keep it handy to be able to sync from other devices) and probably confirmed  the the initial upload of the settings is correct (I do not think I saw the popup but maybe).

I then wanted to upload to make sure that all settings are indeed in the gist (I can go to GitHub and do see the gist, but wanted to upload anyway).

I get the error

```
Failed to save 'syncSummary.txt': The content on disk is newer. Click on Compare to compare your version with the one on disk.
```

**What does this exactly mean?** If the data on disk is newer and I want to upload them then this should be the normal operation I believe (in order to have in the gist the latest version of the synchronization data).

**Comment by shanalikhan** [comment]
Remove the `syncSummary.txt`
Hit upload / download it will generate valid summary
Close the summary and then hit upload / download to view valid summary

**Comment by thienedits** [comment]
I am running into this issue also what does Hit upload/download mean?
