### ISSUE TITLE
Don't upload/update/download the setting, also "shift+alt+u" is no response.

### ISSUE THREAD

**Issue by kenzhaoyihui** [shanalikhan/code-settings-sync#355]
**Visual Studio Code Version :** [ 1.13.1 ]
**Code Settings Sync Version :** [ 2.8.2]
**Operating System :** [ Fedora 25 workstation]
**Occurs On:** [Upload / Download  ]
**Proxy Enabled:** [ No ]
**GIst Id:** [ NA ]

Don't upload/update/download the setting, also "shift+alt+u" is no response. So the setting sync extenion didn't work well.
![Vscode setting-json](
https://github.com/kenzhaoyihui/issue_picture/blob/master/Screenshot%20from%202017-07-11%2017-36-19.png?raw=true)

**Comment by shanalikhan** [comment]
what is the developer console image. ?

**Comment by shanalikhan** [comment]
I'm closing this issue until i heard feedback from your side.
Feel free!
