### ISSUE TITLE
Feature request: Omit some settings

### ISSUE THREAD

**Issue by NitroGhost** [shanalikhan/code-settings-sync#357]
Would be good to have an option to specify which settings should be omitted from the upload. Reason being is, things like the MSSQL extension store connection credentials in the settings, and you don't want to leak these to a public gist if you want the rest of the settings public

**Comment by shanalikhan** [comment]
Will in implemented in future versions.
Thanks
https://github.com/shanalikhan/code-settings-sync/issues/100
https://github.com/shanalikhan/code-settings-sync/issues/232
