### ISSUE TITLE
Not working with Elementary OS and cuurent code/Insiders

### ISSUE THREAD

**Issue by insspb** [shanalikhan/code-settings-sync#358]
**Visual Studio Code Version :** 1.14.0 /  1.15.0 (Insider)
**Code Settings Sync Version :** 2.8.2
**Operating System :** Elementary OS 0.4 (Based on Ubuntu 16.04)
**Occurs On:** Upload
**Proxy Enabled:** No
**GIst Id:** Not rellevant

I am just migrating to linux desktop and moving from windows. On linux desktop I ever cannot start upload to gist. Errors the same in code and code insiders, screenshots included. 

From code:
![image](https://user-images.githubusercontent.com/1916759/28192018-4f981674-683c-11e7-8c4e-5f6c8699b7e9.png)

From code-insiders:
![image](https://user-images.githubusercontent.com/1916759/28192170-0ae184ba-683d-11e7-961d-5372935b0897.png)

**Comment by shanalikhan** [comment]
https://github.com/shanalikhan/code-settings-sync/issues/352
Post there
Let me know if it solved your issue.

**Comment by insspb** [comment]
Thank you. Works. But for many users manual manipulations with chmod is not a solution :) But they are not programmers :D

**Comment by shanalikhan** [comment]
Yes, will be fixed in future release :)
