### ISSUE TITLE
Show Extension Name on Status bar when downloading

### ISSUE THREAD

**Issue by MacFlurry** [shanalikhan/code-settings-sync#359]
**Visual Studio Code Version :** Version 1.14.1 (1.14.1)
**Code Settings Sync Version :** 2.8.2
**Operating System :** macOS 10.12.5 
**Occurs On:** [Download ]
**Proxy Enabled:** [No ]
**GIst Id:** [ 2aed76b2167be5bf30aefc0f9d7051fb ]

Hello,

first, thank you for this great extension

Is it possible while downloading settings to show a progress bar and the possibility to see settings that it is downloading and the current status?

seems it got stuck on this for a while: 
![capture d ecran 2017-07-15 a 02 34 40](https://user-images.githubusercontent.com/8139322/28235021-d59b2f98-6906-11e7-8bc7-3ad74e7c3b58.png)

thanks for your support,

MacFlurry

**Comment by shanalikhan** [comment]
I will take it as feature request.
In the future updates, it should show status bar as :
`Extension of 1 of 10 - Downloading`

Meanwhile you can check the developer console if there is any exception occurred while downloading.

**Comment by MacFlurry** [comment]
thanks dude

**Comment by shanalikhan** [comment]
Fixed !
