### ISSUE TITLE
Error: spawn EACCESS

### ISSUE THREAD

**Issue by rubencaro** [shanalikhan/code-settings-sync#360]
**Visual Studio Code Version :** [ Code 1.14.0 (b8cd5b9556d8b70ea560d35b903422363f6c5c40, 2017-07-10T20:36:40.018Z) ]
**Code Settings Sync Version :** [ 2.8.2 ]
**Operating System :** [ Linux x64 4.11.9-300.fc26.x86_64 ]
**Occurs On:** [ Upload ]
**Proxy Enabled:** [ No ]
**GIst Id:** [ N/A ]

I have posted frequently asked questions on 
http://shanalikhan.github.io/2016/11/07/visual-studio-code-frequently-asked-questions.html 
so you may able to resolve the error quickly. 
Please make sure to write the versions and console logged error picture or copied text

When hitting 'Upload' it spits out this on the console and does nothing else:

```
[Extension Host] rejected promise not handled within 1 second
h.logExtensionHostMessage @ extensionHost.ts:320
(anonymous) @ extensionHost.ts:176
emitTwo @ events.js:106
emit @ events.js:191
process.nextTick @ internal/child_process.js:752
_combinedTickCallback @ internal/process/next_tick.js:67
_tickCallback @ internal/process/next_tick.js:98
shell.ts:443 

spawn EACCES: Error: spawn EACCES
    at exports._errnoException (util.js:1022:11)
    at ChildProcess.spawn (internal/child_process.js:313:11)
    at Object.exports.spawn (child_process.js:399:9)
    at module.exports (/home/ruben/.vscode/extensions/Shan.code-settings-sync-2.8.2/node_modules/opn/index.js:74:26)
    at Commons.<anonymous> (/home/ruben/.vscode/extensions/Shan.code-settings-sync-2.8.2/out/src/commons.js:189:25)
    at Generator.next (<anonymous>)
    at fulfilled (/home/ruben/.vscode/extensions/Shan.code-settings-sync-2.8.2/out/src/commons.js:4:58)
e.onUnexpectedError @ shell.ts:443
(anonymous) @ shell.ts:403
e.onUnexpectedError @ errors.ts:119
o @ errors.ts:139
t.onUnexpectedExtHostError @ mainThreadErrors.ts:13
e.handle @ abstractThreadService.ts:34
s @ ipcRemoteCom.ts:275
f @ ipcRemoteCom.ts:231
_combinedTickCallback @ internal/process/next_tick.js:67
_tickCallback @ internal/process/next_tick.js:98
```

![imagen](https://user-images.githubusercontent.com/472823/28236850-5f59c030-6931-11e7-9ac2-2bc16de29750.png)

The gist is private, but it is working on other machines for previous version of Code 1.13.x (IDK if settings-sync version is 2.8.1 or 2.8.2, autoupdate is on, so I would say 2.8.2). This happens on a new install, after downloading settings and everything else works ok. If you make a change and then hit upload, it fails. It never got to ask me for the token.

**Comment by shanalikhan** [comment]
Post here.
https://github.com/shanalikhan/code-settings-sync/issues/352
