### ISSUE TITLE
shift + alt + u not working

### ISSUE THREAD

**Issue by MatanYed** [shanalikhan/code-settings-sync#361]
**Visual Studio Code Version :** 1.14.0
**Code Settings Sync Version :** 2.8.2
**Operating System :** Ubuntu 14.04
**Occurs On:** Upload not working
**Proxy Enabled:** No
**GIst Id:** [ ID_HERE ]

**Comment by tamj0rd2** [comment]
I'm also having this problem. Why was the issue marked as invalid?

**Comment by shanalikhan** [comment]
Duplicate https://github.com/shanalikhan/code-settings-sync/issues/352
