### ISSUE TITLE
can't upload settings on linux deepin

### ISSUE THREAD

**Issue by Ttou** [shanalikhan/code-settings-sync#364]
**Visual Studio Code Version :** [ 1.14.1 ]
**Code Settings Sync Version :** [ 2.8.2]
**Operating System :** [ linux deepin ]
**Occurs On:** [ Upload ]
**Proxy Enabled:** [ No ]
**GIst Id:** [ f59470c700828def925c2b266f2b7154 ]

![_ _20170716134728-fs8](https://user-images.githubusercontent.com/4298437/28244970-777c1782-69c0-11e7-821a-9baca8036cee.png)

**Comment by shanalikhan** [comment]
https://github.com/shanalikhan/code-settings-sync/issues/352
