### ISSUE TITLE
Can not upload on Fedora 26

### ISSUE THREAD

**Issue by lednhatkhanh** [shanalikhan/code-settings-sync#370]
**Visual Studio Code Version : 1.14.1 64-bit
**Code Settings Sync Version : 2.8.2
**Operating System : Fedora 26 Workstation 64bit Gnome desktop
**Occurs On: Upload
**Proxy Enabled: No
**GIst Id: 1fd9ec79051b81e6a46bb9159770be20

I just doesn't work, show nothing after I ran the upload command in vscode. Working fine on Windows 10

**Comment by shanalikhan** [comment]
https://github.com/shanalikhan/code-settings-sync/issues/352
