### ISSUE TITLE
Save tasks.json

### ISSUE THREAD

**Issue by tasugo** [shanalikhan/code-settings-sync#371]
As a feature request, I think it would be nice if tasks.json was saved too.

**Comment by shanalikhan** [comment]
Whats the path of the tasks.json ?

**Comment by tasugo** [comment]
`<PROJECT_ROOT>/.vscode/tasks.json`

**Comment by shanalikhan** [comment]
Duplicate : https://github.com/shanalikhan/code-settings-sync/issues/258

Post ideas there
