### ISSUE TITLE
Cannot enter GIST token

### ISSUE THREAD

**Issue by gauthiermartin** [shanalikhan/code-settings-sync#372]
**Visual Studio Code Version :** [ 1.14.2]
**Code Settings Sync Version :** [ 2.8.2 ]
**Operating System :** [ Ubuntu 16.04.2 ]
**Occurs On:** [Upload /  Configuring ]
**Proxy Enabled:** [  No ]
**GIst Id:** [ Cannot set any ]

Hi while i was trying to add my github token throught the upload option I could not get the input window where we do need to fill in the github id.

![error](https://user-images.githubusercontent.com/7561038/28684036-e7e04b88-72d0-11e7-9bd9-1fa79f72bb7b.png)

**Comment by shanalikhan** [comment]
https://github.com/shanalikhan/code-settings-sync/issues/352
