### ISSUE TITLE
Didn't perform autoUpload when VSCode start with autoDownload enabled

### ISSUE THREAD

**Issue by allenyllee** [shanalikhan/code-settings-sync#374]
**Visual Studio Code Version :** [ 1.14.2 ]
**Code Settings Sync Version :** [ 2.8.2 ]
**Operating System :** [ Win10 1703 15063.413]
**Occurs On:** [Upload]
**Proxy Enabled:** [ No ]
**GIst Id:** [ 85f6fe42166c382ff0df126cc3df3666 ]

Hi, I'm very like this plugin, but i encounter a problem.
Reproduce step:
1. Enabled autoDownload and autoUpload and then restart.
2. After restart, change some settings and save.
3. The autoUpload didn't trigger, with no console error.
4. While i manually trigger upload by hitting shift+alt+u, it can success uploaded.
5. Once trigger upload, the autoUpload function works fine.

If i turn off autoDownload and restart, the autoUpload function works normally.

I guess that is because autoDownload function may do something to prevent autoUpload function from triggering first time, and forgot to restore it. When I manually trigger it, however, the condition would break and making it worked normally.

**Comment by mgerb** [comment]
Same issue here with the auto upload. The auto download works on start though.

**Comment by ephillipe** [comment]
Same here.

**Comment by shanalikhan** [comment]
Hi All, 
This issue if fixed in v2.8.3
let me know if there is any problem.
