### ISSUE TITLE
Does not work for 64 bit vscode

### ISSUE THREAD

**Issue by pwaykole** [shanalikhan/code-settings-sync#379]
**Code Settings Sync Version :**  2.8.2
**Operating System :** windows 10
**Occurs On:** Upload / Download
**Proxy Enabled:** [ No ]
**GIst Id:** 16fc25fe9cdf4f2aef011dc10970e8c3

![image](https://user-images.githubusercontent.com/17284036/29367090-ceb5022c-8269-11e7-8134-a571549b84a6.png)

**Comment by shanalikhan** [comment]
what is the exception logged
