### ISSUE TITLE
Sync does not work if VSCode is launched from shell.

### ISSUE THREAD

**Issue by evanmeng** [shanalikhan/code-settings-sync#38]
**Visual Studio Code Version :** [ 1.1.1 ]
**Code Sync Settings Version :** [ 1.2.3 ]
**Operating System :** [ Mac OS X 10.11.5 ]

If VSCode is launched from shell via `code` command, syncing will fail with error:

```
ERROR ! Logged In Console (Help menu > Toggle Developer Tools). Please open an issue in Github Repo.
```

The same error will occur if VSCode is launched from shell via `open -a "visual studio code"`.

If quit VSCode and launched it as normal application from Finder or Spotlight, the sync works fine without problem.

**Comment by chuckhendo** [comment]
Did you check to see what the error logged in the console is?

**Comment by shanalikhan** [comment]
@evanmeng i have Mac environment so i might not be able to resolve it.
You can share the share the console error from the developer console

**Comment by evanmeng** [comment]
@shanalikhan

Unfortunately I cannot reproduce it after upgraded to 1.3.0...
