### ISSUE TITLE
Keyboard settings file not updating

### ISSUE THREAD

**Issue by simonwjackson** [shanalikhan/code-settings-sync#380]
The settings.json will get uploaded and replaced as expected, but the keyboard settings file dosent seem to ever update.

I have to edit this manually on github for it to sync properly

--------------------------------------

**Visual Studio Code Version :** 1.15.0
**Code Settings Sync Version :** 2.8.2
**Operating System :** Windows 10 x64
**Occurs On:** Help Configuring 
**Proxy Enabled:** No
**Gist Id:** e0a7cb634e17d83741f703758c5bddeb

**Comment by shanalikhan** [comment]
Sorry for late reply.
Can you update, is it resolved or provide steps to re produce steps

**Comment by simonwjackson** [comment]
It seems to be working now
