### ISSUE TITLE
Cannot read property 'length' of undefined when downloading

### ISSUE THREAD

**Issue by fdncred** [shanalikhan/code-settings-sync#382]
**Visual Studio Code Version :** [1.15.1]
**Code Settings Sync Version :** [2.8.2]
**Operating System :** [Windows 10 Version 1703 ]
**Occurs On:** [Downloading]
**Proxy Enabled:** [No]
**GIst Id:** [51b15e5ac761a37965d8ee7f805e9fca]

I get this exception when trying to download via sync. All setting are downloaded, none of the extensions are downloaded.
```
extensionHost.ts:335 [Extension Host] C:\Users\20396600\AppData\Roaming/Code/User/keybindings.json
extensionHost.ts:335 [Extension Host] C:\Users\20396600\AppData\Roaming/Code/User/settings.json
extensionHost.ts:335 [Extension Host] C:\Users\20396600\AppData\Roaming/Code/User/snippets/csharp.json
extensionHost.ts:335 [Extension Host] C:\Users\20396600\AppData\Roaming/Code/User/vsicons.settings.json
extensionHost.ts:335 [Extension Host] TypeError: Cannot read property 'length' of undefined
    at C:\Users\20396600\.vscode\extensions\Shan.code-settings-sync-2.8.2\out\src\pluginService.js:210:56
    at process._tickCallback (internal/process/next_tick.js:103:7)
t.logExtensionHostMessage @ extensionHost.ts:335
(anonymous) @ extensionHost.ts:188
emitTwo @ events.js:106
emit @ events.js:191
process.nextTick @ internal/child_process.js:752
_combinedTickCallback @ internal/process/next_tick.js:67
_tickCallback @ internal/process/next_tick.js:98
```

**Comment by Blake-C** [comment]
Visual Studio Code Version : [1.15.1]
Code Settings Sync Version : [2.8.2]
Operating System : [macOS Sierra Version 10.12.6]
Occurs On: [Downloading]
Proxy Enabled: [No]
GIst Id: [fd7517f1a99f6bfcfbca48b445214b4b]

I believe I have the same issue as @fdncred. With a fresh install of VSCode and an initial download of Settings Sync I get two errors. One error on the settings files requiring a diff and another error on "TypeError: Cannot read property 'length' of undefined".

![screen shot 2017-08-17 at 12 33 18 pm](https://user-images.githubusercontent.com/5287911/29425603-7dd71e22-8349-11e7-8f6c-61bb767799d1.jpg)

After fixing the settings file and restarting VSCode and trying to re-download my settings I get just the "TypeError: Cannot read property 'length' of undefined". error.

![screen shot 2017-08-17 at 12 36 12 pm](https://user-images.githubusercontent.com/5287911/29425610-833c3032-8349-11e7-930b-3445e03ee079.jpg)

In both instances my settings download, but my extensions do not download.

**Comment by shanalikhan** [comment]
I have tested both
@fdncred  51b15e5ac761a37965d8ee7f805e9fca
and
@Blake-C fd7517f1a99f6bfcfbca48b445214b4b

But i got same error the day you reported, i think there might be a error from the marketplace that time.
Can you test now and update ?

**Comment by Blake-C** [comment]
@shanalikhan I can confirm that I was able to successfully download my settings and extensions without errors.
