### ISSUE TITLE
Feature: Is it possible add setting that ignore extensions.json sync?

### ISSUE THREAD

**Issue by betimer** [shanalikhan/code-settings-sync#389]
**Visual Studio Code Version :** [ 1.15.1]
**Code Settings Sync Version :** [ 2.8.3 ]

Could we add a feature enable/disable extensions.json sync? Cause there are a few extensions are different from lots my machines, and that causing quite a bit time to install, sometimes causing error (`Extension host terminated unexpectedly.`).

I prefer only my setting.json and keyboard one. 

Thanks

**Comment by shanalikhan** [comment]
Will make it configurable in future updates.

**Comment by betimer** [comment]
Look forward.
Thank you very much.

**Comment by shanalikhan** [comment]
Released with v2.9
Let me know if there are issues
