### ISSUE TITLE
Suggestion: Add platform-specific sync behaviors

### ISSUE THREAD

**Issue by mklement0** [shanalikhan/code-settings-sync#39]
First things first: great extension, thanks for sharing.

For people using VSCode across different platforms, platform-specific behaviors are desirable:

* It would be nice to have an option to have platform-specific `keybindings.json` files; for instance, use VSCode on both OS X and Windows, with distinct key bindings. Currently, the settings on whatever platform I happen to upload from are invariably applied to ALL platforms, which in the case of, say, OS X key bindings doesn't make much sense on Windows (different modifier keys, different system-wide shortcuts to avoid, ...). Also, since only one `keybindings.json` is stored, the different platform versions overwrite each other on uploading.

* On a less important note: some extensions are platform-specific - such as those that integrate with an application only available on a given platform (e.g., https://marketplace.visualstudio.com/items?itemName=deerawan.vscode-dash, which only makes sense on OS X). I'm not sure such extensions are tagged as such, but if they are, download and installation on an incompatible platform could be skipped.

**Comment by shanalikhan** [comment]
Thank you.

1. That is a great idea i will add this in future, currently im into adding automatic syncing for the extension.
2. There are no information in extension file that can analyze the platform. if you know a way then please provide or give me pull request , i will be more happy to accept that.

**Comment by boyvinall** [comment]
As above, great extension thanks.  If/when you do manage to get some platform-specific stuff going, then things like paths are useful too .. e.g. for me GOPATH.  TBH, I'm not sure how you'd pull off this feat, but then I've not looked inside.  Thanks again.

**Comment by drew-wallace** [comment]
You could set up the a gist for each thing you want to sync and have the extension save which gist to look at.

Gists:
Settings
Keybindings PC
Keybindings Mac
Extensions

On my Mac, I would choose the Settings gist to sync settings, Keybindings Mac to sync keybindings, and the Extensions gist to sync extensions.

On my PC, I would choose the Settings gist to sync settings, Keybindings PC to sync keybindings, and the Extensions gist to sync extensions.

**Comment by shanalikhan** [comment]
I have started the working on it, i dont have MAC PC so i wont be able to test it out. Once i publish the updated code, i will need you guys to test it out on MAC. :)

**Comment by shanalikhan** [comment]
I have published the updated code, download the extension :) and let me know
