### ISSUE TITLE
Implement upload delay setting

### ISSUE THREAD

**Issue by Jasius** [shanalikhan/code-settings-sync#390]
**Visual Studio Code Version :** 1.15 
**Code Settings Sync Version :** 2.8.3
**Operating System :** Windows 10 Creators update
**Occurs On:** Upload
**Proxy Enabled:** No
**GIst Id:** https://gist.github.com/Jasius/1d63509b67a4fdf1c3344aa8d90826d2

Hey,

One thing that annoys me the most about this extension is that there's a very short delay upon which upload gets triggered, so lets say whenever you're changing settings, making snippets it uploads all those unfinished changes which in 5 seconds which is unreasonable time frame in my opinion.

My proposal is so that there would be an option which would allow you to set up delay in settings or just make default upload delay 1 minute.

Cheers, Jaska.

**Comment by shanalikhan** [comment]
I think it's better to start the Upload process on Settings and extension changes.
Currently, the auto upload doesn't work well. A goal is to make it behave well instead of having scheduled.

**Comment by Jasius** [comment]
I see, thank you @shanalikhan

**Comment by ZaLiTHkA** [comment]
@shanalikhan, just curious, but have you been able to implement the improvements you mentioned above?

I was about to open an issue and make the same request when I found this one. Thing is, personally I'd actually like to set something like a 30 second or even 1 minute delay before it auto uploads..

Is there any chance of having a configurable delay for this until such time as you change the way it works?

**Comment by shanalikhan** [comment]
@ZaLiTHkA may i know why you want to add a delay. 
It would be more easy to understand if you could provide a real-time scenario to show the need for this feature.

**Comment by ZaLiTHkA** [comment]
sorry for the delay, I've been away from my computer this whole weekend..

I would like a delay in the upload for essentially the same reasons that @Jasius gave: when making changes to things like system settings, key bindings, installed extensions, custom snippets, etc., this extension is constantly uploading the changes.

---

from a usability point of view inside VSCode, I suppose this isn't really *an issue*, but when looking at the change history in the relevant GitHub Gist, it gets really difficult to see all the changes that were made over the period of mere minutes.

**Comment by Jasius** [comment]
I felt the same, I have auto sync disabled nowadays because it was a little frustrating without delay.

**Comment by shanalikhan** [comment]
@arnohovhannisyan Lets add this in `v3.4.0` also.

I think we can add `autoUploadDelay` in Global Settings make it default as 20 seconds.
Users can change the delay in terms of seconds for uploading.

**Comment by Jasius** [comment]
That's awesome, thank you! @shanalikhan

**Comment by shanalikhan** [comment]
v3.4.0 is released containing this fix.
Let me know if you run into issue

**Comment by PHLAK** [comment]
I have v3.4.2 installed and don't see this setting available anywhere.

**Comment by shanalikhan** [comment]
@PHLAK 

See Settings Sync Global Settings

https://github.com/shanalikhan/code-settings-sync#global-settings

Config is `autoUploadDelay`
