### ISSUE TITLE
My short cut not work

### ISSUE THREAD

**Issue by lhwu** [shanalikhan/code-settings-sync#391]
**Visual Studio Code Version :** [ VERSION_HERE ]
**Code Settings Sync Version :** [2.8.2 ]
**Operating System :** [ Ubuntu14.04 ]
**Occurs On:** [Upload]
**Proxy Enabled:** [ Yes / No ]
**GIst Id:** [ 49a5addf5aabded67fadd8b3013e66a724d8c8cf ]

Shift+Alt+U is not work,so i can not upload my gist

**Comment by lhwu** [comment]
vs code vsersion: 1.13.1

**Comment by shanalikhan** [comment]
You can Type Sync : Upload Settings to upload.
Check which command is bind with shortcuts in code

**Comment by lhwu** [comment]
{
  "command": "extension.updateSettings",
  "key": "shift+alt+u",
  "when": "editorTextFocus"
}
{
  "command": "extension.downloadSettings",
  "key": "shift+alt+d",
  "when": "editorTextFocus"
}
I did not make any change。

**Comment by shanalikhan** [comment]
> "when": "editorTextFocus"
It will work when you have open some file.
