### ISSUE TITLE
Does not work for 64 bit vscode

### ISSUE THREAD

**Issue by crazykun** [shanalikhan/code-settings-sync#393]
**Visual Studio Code Version : Code - Insiders 1.16.0-insider (787b31c0474e6165390b5a5989c9619e3e16f953, 2017-09-05T21:00:35.399Z)
**Code Settings Sync Version :|Sha|2.8.3
**Operating System : win10  64bit
**GIst Id: 93c7e17d67329034ff9b65854ed2b05fda68e400

When I upload the configuration, it reminds me like that：

Sync : Invalid / Expired GitHub Token. Please generate new token with scopes mentioned in readme. Exception Logged in Console.

I've tried using a new token，but it does not work too.

log:
extensionHost.ts:384 [Extension Host] {"message":"Bad credentials","documentation_url":"https://developer.github.com/v3"}
t._logExtensionHostMessage @ extensionHost.ts:384
(anonymous) @ extensionHost.ts:194
emitTwo @ events.js:106
emit @ events.js:194
process.nextTick @ internal/child_process.js:766
_combinedTickCallback @ internal/process/next_tick.js:73
_tickCallback @ internal/process/next_tick.js:104
extensionHost.ts:384 [Extension Host] {"message":"Bad credentials","documentation_url":"https://developer.github.com/v3"}
t._logExtensionHostMessage @ extensionHost.ts:384
(anonymous) @ extensionHost.ts:194
emitTwo @ events.js:106
emit @ events.js:194
process.nextTick @ internal/child_process.js:766
_combinedTickCallback @ internal/process/next_tick.js:73
_tickCallback @ internal/process/next_tick.js:104
messageService.ts:125 Sync : Invalid / Expired GitHub Token. Please generate new token with scopes mentioned in readme. Exception Logged in Console.
e.doShow @ messageService.ts:125
e.show @ messageService.ts:104
e._showMessage @ mainThreadMessageService.ts:72
n.Class.derive._oncancel @ winjs.base.raw.js:1641
e._showMessage @ mainThreadMessageService.ts:42
e.$showMessage @ mainThreadMessageService.ts:36
e.invoke @ abstractThreadService.ts:41
e._invokeHandler @ rpcProtocol.ts:109
e._receiveOneMessage @ rpcProtocol.ts:96
(anonymous) @ rpcProtocol.ts:32
(anonymous) @ rpcProtocol.ts:157
e.invoke @ callbackList.ts:63
e.fire @ event.ts:123
(anonymous) @ ipc.net.ts:82
emitOne @ events.js:96
emit @ events.js:191
readableAddChunk @ _stream_readable.js:178
Readable.push @ _stream_readable.js:136
onread @ net.js:560
extensionHost.ts:384 [Extension Host] {"message":"Bad credentials","documentation_url":"https://developer.github.com/v3"}

**Comment by shanalikhan** [comment]
Check this 
https://github.com/shanalikhan/code-settings-sync/issues/177
