### ISSUE TITLE
always on `Sync: Installing Extensions in background`.

### ISSUE THREAD

**Issue by gee1k** [shanalikhan/code-settings-sync#394]
**Visual Studio Code Version :** v1.16.0
**Code Settings Sync Version :** v2.8.3
**Operating System :** Ubuntu 16.04
**Occurs On:** Download 
**Proxy Enabled:** No
**GIst Id:** 463dc44be6f6917d2dc216370080e85d

always on `Sync: Installing Extensions in background`.

![image](https://user-images.githubusercontent.com/12059800/30254991-05942170-96d2-11e7-9e20-32d4608f5d99.png)

**Comment by shanalikhan** [comment]
What is in the developer console log

**Comment by 16Free** [comment]
no errors in the output . It all seems normal

**Comment by 16Free** [comment]
when you install extensions, the logs are normal, but the messages in the status bar never disappear

**Comment by EmilianoTalamo** [comment]
Have you changed the user-data and extensions directory? I did it to have a portable version of VScode and I'm facing the same issue as you.

![image](https://user-images.githubusercontent.com/12476222/30568374-3054f45a-9cab-11e7-882d-8f358eb6953b.png)

**Comment by shanalikhan** [comment]
@EmilianoTalamo this extension doenst support portable version at the moment
Only Stable and Insiders.

**Comment by 16Free** [comment]
@EmilianoTalamo I didn't change any directory

**Comment by mastrauckas** [comment]
I have also noticed this too

**Comment by ffxsam** [comment]
Same

**Comment by dmitrii-davidov** [comment]
[PR](https://github.com/shanalikhan/code-settings-sync/pull/439) should solve the bug.
