### ISSUE TITLE
Not able to sync on ubuntu/windows

### ISSUE THREAD

**Issue by zoliaaz** [shanalikhan/code-settings-sync#395]
**Visual Studio Code Version :** [ 1.16.0]
**Code Settings Sync Version :** [ 2.8.3 ]
**Operating System :** [ Xubuntu 16.04 ]
**GIst Id:** [29f444638a9177802cebc807185cdef5]

Hi,
I'm trying to sync on ubuntu from a gist created on windows machine. I getting an error on windows, but the gist still created.
The error on windows seem to be the same, with different path.
First i though about some permission problem on ubuntu, but since it's the same error on windows, i'm lost.

![capture d ecran_2017-09-12_16-11-45](https://user-images.githubusercontent.com/28677789/30330540-a34045b2-97d5-11e7-85d7-ed165eeec4ec.png)

Thank for all your work.

**Comment by shanalikhan** [comment]
Sorry for late reply, 
Are you still getting it ?

**Comment by ClayBenson94** [comment]
Not the original poster, but I get the same issue @shanalikhan, Ubuntu 16.04.

**Comment by shanalikhan** [comment]
Can you provide the steps and gidt id to reproduce

**Comment by ClayBenson94** [comment]
@shanalikhan I was able to fix the issue by deleting my ~/.config/Code folder on both Windows and Ubuntu. There seemed to be an error trying to write to a file that didn't exist for me. I will make a separate report if I get that error again.
