### ISSUE TITLE
Invalid Expired GIst- Not invalid

### ISSUE THREAD

**Issue by Darcy-FzR** [shanalikhan/code-settings-sync#397]
**Visual Studio Code Version :** [ 1.16.1 ]
**Code Settings Sync Version :** [ 2.8.3 ]
**Operating System :** [ windows-10,64, macOS 10.12.4]
**Occurs On:** [macOS -- Download]
**Proxy Enabled:** [ Yes / No ]
**GIst Id:** [ 4672b40d6b9b9cfee43e0a080a9d48c2]
** gist check ok** [https://gist.github.com/Darcy-FzR/4672b40d6b9b9cfee43e0a080a9d48c2]

**Comment by shanalikhan** [comment]
Check token on the sync settings Json file in Users Folder.
Or you may manually add new token from github in that json file and let me know

**Comment by Darcy-FzR** [comment]
@shanalikhan

**Comment by Darcy-FzR** [comment]
@shanalikhan I try again, and it works. Before, When I copy the gist, some number else  appended to the tail. Thank you anyway.
