### ISSUE TITLE
Upload when multiple VS Code windows are open

### ISSUE THREAD

**Issue by fgallardograzio** [shanalikhan/code-settings-sync#398]
When multiple VS Code windows are open, and the `Sync: Update / Upload Settings` command is executed in one, then all open windows actually do the uploading.

I was extremely confused about the fact that the extension I had just installed wasn't syncing, until I realised a second VS Code window (which I hadn't reloaded after installing the extension) was running the upload process as well and overwriting the updated gist, removing the extension the first window's upload had just added.

By the way, is the AutoUpdate not triggered after an extension is installed?

----

**Visual Studio Code Version :** 1.16.1
**Code Settings Sync Version :** 2.8.3
**Operating System :** Linux Mint 18
**Occurs On:** Upload
**Proxy Enabled:** No

**Comment by shanalikhan** [comment]
By the way, is the AutoUpdate not triggered after an extension is installed?

Currently code limitation, https://github.com/shanalikhan/code-settings-sync/issues/123
You can ask code team on issue opened in the repo.

Can you provide me steps to reproduce at my end in detail ?
