### ISSUE TITLE
launch.json under .vscode does not sync

### ISSUE THREAD

**Issue by jacksun101** [shanalikhan/code-settings-sync#40]
**Visual Studio Code Version :** 1.2.0
**Code Sync Settings Version :** 1.3.0
**Operating System :** Win 10

As title. And the launch.json didn't even upload to my gist, all the others are good.

**Comment by shanalikhan** [comment]
if .vscode is present in project folder rather then your %appdata% then it wont sync those files in that folder.
It only sync the code folder in %appdata%

**Comment by jacksun101** [comment]
Got it, thanks.
