### ISSUE TITLE
Can't Upload/Download on Two Machines

### ISSUE THREAD

**Issue by kevmon** [shanalikhan/code-settings-sync#405]
**Visual Studio Code Version :** Version 1.16.1 (1.16.1)
**Code Settings Sync Version :** v2.8.3
**Operating System :** High Sierra
**Occurs On:** [Upload / Download / Help Configuring ]
**Proxy Enabled:** No
**GIst Id:** [ ID_HERE ]

Hi,

I'm not sure if this is a bug or not a feature of the extension.  I have two different Macs, iMac and MacBook.  One one machine, I can set it up correctly, it uploads fine and downloads fine.  It gives me a string to input on another machine to download, which also works fine. 

However, on that second machine, I can't upload without entering a separate Gist token.  When doing so, the first machine loses the ability to download, without resetting the extension settings.

I'm hoping for the ability to change my settings from either machine, update, and download on the other without a change in Settings Sync setup.  But it seems that I can only update one-way doing this.  Am I missing something?

Thanks in advance

**Comment by shanalikhan** [comment]
>first machine loses the ability to download, without resetting the extension settings

Is there any exception logged ?


When you add token and gist in one machine. 
Copy them 
And paste manually on gist settings and token in sync settings.json file in User folder
Then let me know if that helped or same behaviour.

**Comment by kevmon** [comment]
Hi, there weren't any errors, but it seems to be working now.  Before it wasn't letting me input the same GitHub token into the upload settings of different computers' VSCode.  

Thanks
