### ISSUE TITLE
Mac and Windows are seeing different settings?

### ISSUE THREAD

**Issue by mastrauckas** [shanalikhan/code-settings-sync#407]
**Visual Studio Code Version : 1.18.0.insider
**Code Settings Sync Version : 283
**Operating System : Windows 7 and mac
**Occurs On: both
**Proxy Enabled: No
**GIst Id:*

I have two machines, one is a `mac` and the other is a `Windows` machine.  Switching between the two boxes using `Settings Sync` with the same `Gist Id` for `VS Code` seem to be using different files

1. I installed `Settings Sync` extension on my `mac` and uploaded all settings just fine.

2. I installed `Settings Sync` extension on my `Windows` computer and used `Gist Id` I was supposed to use. As expected all settings from my `mac` were download(Even all extensions).

3. On my `mac` I changed `sync.autoDownload` and `sync.autoUpload` to `true` and upload settings using `Settings Sync`.

4. On `github` made sure the gist for the `Gist Id` was correct.  

5. Went to `Windows` computer and tried downloading latest changes for the 'Gist Id` but when I did, `Settings Sync` said I already had the latest version.

6. Try resetting `Settings Sync` extension on `Windows` and put in the `Gis Id` again and it says all settings are up to date but not seeing the changes to `sync.autoDownload` and `sync.autoUpload`  that is on my `mac`.

7. So I made changes to settings on my `Windows` computer and uploaded it.

8. I looked at the` Gist Id` on `github.com`  and they `sync.autoDownload` and `sync.autoUpload` 
were both `false` as expected.  The other settings I changed was also correct.

9. Went to my `mac` computer and downloaded using the `Gist Id` and it said I already had the latest version.  However the changes I made on my `Windows` computer was not on my `mac` and `sync.autoDownload` and `sync.autoUpload` were both still `true` instead of `false` like my `Windows` computer. 

It's like the two machines are using two completely different settings!

**Comment by mastrauckas** [comment]
I don't think I am quite getting this extension?  It appears every time a change is made to any of the settings, the `Gist Id` changes.  

So to stay in sync you have to constantly give the new`Gist Id`.  

How can I always stay in sync without having to worry about giving it the new `Gist Id`?

**Comment by shanalikhan** [comment]
Looks like u fixed it?

**Comment by mastrauckas** [comment]
Yes, thanks

**Comment by DavidBabel** [comment]
How ? ^^
