### ISSUE TITLE
Version Lens

### ISSUE THREAD

**Issue by UnderNotic** [shanalikhan/code-settings-sync#409]
**Visual Studio Code Version :** [ 1.17.0]
**Code Settings Sync Version :** [ 2.8.3]
**Operating System :** [ WINDOWS_10 ]
**Occurs On:** [Upload ]
**Proxy Enabled:** [ No ]

Hi,
Uploading doesn't work with Version Lens extension.

**Comment by shanalikhan** [comment]
what is the exception logged
