### ISSUE TITLE
cannot see the extension to download via VS code 1.2

### ISSUE THREAD

**Issue by xtianus79** [shanalikhan/code-settings-sync#41]
**Visual Studio Code Version :** 1.2
**Code Sync Settings Version :** [ VERSION_HERE ]
**Operating System :** [ VERSION_HERE ]

Please make sure to write the versions and console logged error picture or copied text.

**Comment by xtianus79** [comment]
figured it out... you need to have visual studio at the beginning of the statement... 

ext install code-settings-sync <<< doesn't work

ext install visualcode-settings-sync <<< works

**Comment by shanalikhan** [comment]
I have opened an issue for vscode, their team will resolve this issue.
[https://github.com/Microsoft/vscode/issues/7398](#7398)
