### ISSUE TITLE
Sync against multiple OS

### ISSUE THREAD

**Issue by ludoo0d0a** [shanalikhan/code-settings-sync#410]
Like many devs, I used several os on different places. And i sync now all my vscode with your great plugin.
But config and OS are various.
A shared path is os dependant, and proxy config cannot be shared (because location dependant).

A kind of profile or ignore, or specific-os features, or env vars-dependant could be a great thing !

The proxy config is the worst since it cuts the network after sync on places where it shouldn't be.

**Comment by shanalikhan** [comment]
You can do something like this at the moment to remove the proxy
```
"replaceCodeSettings": {
        "http.proxy": "XYZ"
    },
```

https://github.com/shanalikhan/code-settings-sync#customized-sync
