### ISSUE TITLE
Error: command 'extension.downloadSettings' not found

### ISSUE THREAD

**Issue by Jancat** [shanalikhan/code-settings-sync#412]
**Visual Studio Code Version :** [ 1.17.1]
**Code Settings Sync Version :** [ 2.8.3]
**Operating System :** [ Win 10 64bit]
**Occurs On:** [Download]
**Proxy Enabled:** [ No ]
**GIst Id:** [ d6d60fedeecf9ec39907d70d5e9fc97a]

![image](https://user-images.githubusercontent.com/11827786/31439967-ccc9a2be-aec0-11e7-94c6-b568a9d0bea6.png)

**Comment by shanalikhan** [comment]
whats the developer console log?

**Comment by Jancat** [comment]
![image](https://user-images.githubusercontent.com/11827786/31440385-41e07c34-aec2-11e7-8a4f-b613d8dbb669.png)

**Comment by Jancat** [comment]
I had reinstalled vscode and remove all relevant data. Then it works!

**Comment by bdlangton** [comment]
For those experiencing the same issue:

I had the same issue, but reinstalling vscode did nothing. This is what worked for me:

1. Uninstall this extension
2. Restart vs code
3. Install this extension
4. Restart vs code
5. Run the sync download command again

**Comment by ThanhTran1324** [comment]
thanks bdlangton . It work for me .

**Comment by Fadeoc** [comment]
for windows 10 users, go to user/yourusername/roaming folder, delete Code folder, restart vscode.

reason would be some cache data is broken, but I am not interested in which one exactly. but definitely not CachedExtensions folder

please do backup this folder before delete, it stores not only the extension settings, but also other settings, like which folder to reopen next time etc.
