### ISSUE TITLE
GitHub Settings nowadays have an extra level of "developer settings"

### ISSUE THREAD

**Issue by fdenzer** [shanalikhan/code-settings-sync#415]
### Affected: Documentation

---

The current GitHub Settings are slightly more complicated than the current documentation reflects:

#### `Settings` page

![image](https://user-images.githubusercontent.com/1089372/31492897-407ea592-af4d-11e7-8964-5ece6e9c5bc6.png)

#### `Developer settings` page

**Settings** / **Developer settings** / **Personal access tokens**
![image](https://user-images.githubusercontent.com/1089372/31492782-d4337ed0-af4c-11e7-919a-e027c1618525.png)

The hyperlinks used in the `code-settings-sync`-readme still work, though!

**Comment by shanalikhan** [comment]
https://github.com/shanalikhan/code-settings-sync/pull/416
Fixed
