### ISSUE TITLE
Confused by docs

### ISSUE THREAD

**Issue by cfjedimaster** [shanalikhan/code-settings-sync#417]
So Sync worked great on my laptop. Now I'm trying to setup my desktop to sync. I installed the extension of course. The docs talk about uploading your settings with the private access token. On my new machine, I'm not sure how I do this. I mean I have access to the token. But when I told the extension to download, it asked for the Gist ID. It tried to read it and failed - 

GITHUB TOKEN: Anonymous
GITHUB GIST: 9177d7fb181b0e4f5924bd6d288a1a14
GITHUB GIST TYPE: Secret

So I guess I need to get the token into my settings on the desktop, but... how?

**Comment by cfjedimaster** [comment]
So I ended up doing Update/Upload and it prompted for the key.

So... I guess I'm ok. Like I have no idea if it detected the existed Gist and updated itself to the laptop settings, but I'm going to hope so I guess.

**Comment by shanalikhan** [comment]
It wont ask token for download only need gist ID
> It tried to read it and failed 
Is there any exception logged there how it failed in the developer console.

> Like I have no idea if it detected the existed Gist and updated itself to the laptop settings
As you have already entered the Gist ID but not token , but when you uploaded settings. it ask token and you put it, it found the settings gist ID and overwrite those settings with new settings.


> So I guess I need to get the token into my settings on the desktop

You can always put token in your sync setting json file 
https://github.com/shanalikhan/code-settings-sync#customized-sync

**Comment by cfjedimaster** [comment]
Did my last question make sense though? What is the workflow for a case where I want 2 machines to be synced automatically?

**Comment by barbalex** [comment]
Same here: The docs only explain how to create a new token. But when you already have it it is not clear at all how to enter an existing token. So you end up trying all the commands. But all that happens is:
- many commands open github
- others fail with an error

:-(

**Comment by shanalikhan** [comment]
Feel free to post https://github.com/shanalikhan/code-settings-sync/issues/468
