### ISSUE TITLE
Doc question on "typical usage"

### ISSUE THREAD

**Issue by cfjedimaster** [shanalikhan/code-settings-sync#418]
I'm a bit confused by these two parts in the docs - 

Toggle Auto Download
Toggle Auto-upload on Change

In both cases, both are turned off. 

So that means to properly sync, I need to force an upload when I know I change something, and on my other machine, I have to force a download?

If so - if I simply want to automate everything, I'd need to turn these two on, right? Ie, if I change something on machine A, I'd want it automatically pushed so that machine B gets it.

To be clear, I'm not asking for this behavior to change - just wanted to be sure I understand what I need to tweak for what I consider the simplest option ("Just keep things in sync and I never have to tell the extension to do anything").

**Comment by shanalikhan** [comment]
Yes you need to keep auto upload and auto download as ON.
But make sure when sync process is going on, editor dont have any file opened like settings.json or any other file.
