### ISSUE TITLE
Issue with downloading my exiting settings

### ISSUE THREAD

**Issue by theRahim** [shanalikhan/code-settings-sync#419]
**Visual Studio Code Version :** 1.17.1
**Code Settings Sync Version :** 2.8.3
**Operating System :** Ubuntu 16.4 LTS
**Occurs On:** Download
**Proxy Enabled:** No
**GIst Id:** https://gist.github.com/theRahim/b1f3e53465f24b79449b8718093ed414

An error occurs when I download my gist from my laptop with new OS. The error below.
_**Sync : Invalid Gist Id Entered. Verify your gist : https://gist.github.com/<your_userName>/<gist_id>.**_

**Comment by shanalikhan** [comment]
What is in your `sync.gist`

**Comment by theRahim** [comment]
Sorry I am not understand what you are looking for. I hop it this is below.
"sync.gist": "https://gist.github.com/theRahim/b1f3e53465f24b79449b8718093ed414",
    "sync.lastUpload": "",
    "sync.autoDownload": true,
    "sync.autoUpload": false,
    "sync.lastDownload": "",
    "sync.forceDownload": true,
    "sync.anonymousGist": true,
    "sync.host": "",
    "sync.pathPrefix": "",
    "sync.quietSync": false,
    "sync.askGistName": fal

**Comment by shanalikhan** [comment]
the sync.gist value should be b1f3e53465f24b79449b8718093ed414

**Comment by theRahim** [comment]
**Thank You**.
    It's working.
