### ISSUE TITLE
Ability to edit which extensions are synced

### ISSUE THREAD

**Issue by jjspace** [shanalikhan/code-settings-sync#421]
Can we have the ability to pick and choose which extensions get synced? I use this extension across different computers and OSes. I love having my settings and everything else synced but there are a couple specific extensions that are only relevant on one machine and not the others. 

This is similar to issue #389 but I don't want to exclude the whole extensions.json because I would like most of my extensions to sync (say I do a new install somewhere and want an env I'm comfortable with) but I would like to ignore a few (like SVN which is only used on one of my systems and would be useless on the others if synced).

**Comment by alanaasmaa** [comment]
I'm also liiking forward for this.

I use VsCode on 3 PC's and only one (sometimes two) i use for java. So on third (work) pc i would not like to get java extensions installed.

**Comment by jharmer95** [comment]
I also would like to see something like this, I don't need the powershell extension for my linux box, and I don't have clang on my Windows box for example.
Maybe what you could do is simply sync extensions even if they are disabled (but not uninstalled), so you can simply disable the extension on the machine you don't need it for, but have it active on all other instances by default

**Comment by leepowell-aviva** [comment]
Rather than choosing which get synced, I would rather an option to ignore specific extensions from syncing

**Comment by shanalikhan** [comment]
Ignore extensions is available in Settings Sync v3.0


 #523
