### ISSUE TITLE
Add Animated Gif in Readme

### ISSUE THREAD

**Issue by shanalikhan** [shanalikhan/code-settings-sync#423]
The documents currently have images, it should contains the animated gif for showing all the processes like Setting up, downloading, uploading and opening local extension settings.

It would be highly appreciated If anyone send me pull request for this.

**Comment by angeliski** [comment]
Hi @shanalikhan !
Your plugin is great! Thanks for share.

That gif, Do you like step by step or the gif for all steps?

**Comment by shanalikhan** [comment]
Gif can of step by step like
1. From settings page to generate token.
2. Hitting upload, and adding token and showing summary page.

For Download:
1. Hitting download from code and pasting the gist ID
2. Showing the downloaded detail and summary page.
