### ISSUE TITLE
var appears to have a typo

### ISSUE THREAD

**Issue by BristleBeard** [shanalikhan/code-settings-sync#424]
https://github.com/shanalikhan/code-settings-sync/blob/c7dbad9150f2d14feb11f66b4f884ffb64e3b672/src/extension.ts#L586

Judging by the surrounding code, it looks as if `var teims` should actually be `var items`.

**Comment by shanalikhan** [comment]
Oh yea, thanks.
Will be fixed

**Comment by guiconti** [comment]
@shanalikhan I opened a PR #429 to fix it. I am confused about the used in this var (elaborated more on PR).
