### ISSUE TITLE
Need platform specific settings to differentiate settings like 'java.home'

### ISSUE THREAD

**Issue by satyapramodh** [shanalikhan/code-settings-sync#426]
**Visual Studio Code Version :** 1.17.2
**Code Settings Sync Version :** 2.8.3
**Operating System :** Ubuntu 16.04.3

I have a custom set java home folder in windows and sadly the settings key is `java.home` and not `windows.java.home` to differentiate platforms. How can we tackle this? [this idea](https://github.com/shanalikhan/code-settings-sync/issues/39#issuecomment-232686057) seems like a good one.

I have looked at custom sync settings, but i could not understand where the 'user' folder is or which folder it is mentioning on windows/ubuntu.
http://shanalikhan.github.io/2017/02/19/Option-to-ignore-settings-folders-code-settings-sync.html

**Comment by shanalikhan** [comment]
https://github.com/shanalikhan/code-settings-sync#customized-sync

Add that key in `replaceCodeSettings` where it gets overwrite
