### ISSUE TITLE
fail to upload the extensions.json content in VS code insider version

### ISSUE THREAD

**Issue by czmecho** [shanalikhan/code-settings-sync#428]
**Visual Studio Code Version :** [ 1.18.0-insider]
**Code Settings Sync Version :** [ 2.8.3 ]
**Operating System :** [ win 10 1709 ]
**Occurs On:** [Upload ]
**Proxy Enabled:** [ Yes]
**GIst Id:** [ 96f48638c9981ac7b9ec1c884e769241]

you can see the [change in my gist](https://gist.github.com/czmecho/96f48638c9981ac7b9ec1c884e769241/revisions#diff-4769e2216318d746f15eec568beffb28)

I change the VS Code from the stable version to the insider version.
after I use the settings-sync upload,the Upload Summary show that:

```
Files Upload.

extensions.json
keybindings.json
settings.json
javascript.json > snippets|javascript.json
vsicons.settings.json
```
but the extensions.json content disappeared.

**Comment by wKovacs64** [comment]
Same here. I've always been on Insiders, though. My `extensions.json` in the gist was wiped out, so I manually repopulated one of my machines with all my extensions and uploaded my settings, but it remains empty.

**Comment by DJviolin** [comment]
Same here. My `extensions.json` gist also empty.

VS Code Insider v1.18.0

**Comment by SaswatPadhi** [comment]
Same here. I see

```
EXTENSIONS ADDED :

No Extension needs to install.
```

with VS Code Insider

```
Version 1.18.0-insider
Commit e6a76e4bd3f52ab07452bb181e861f5a9bfb6596
Date 2017-10-27T05:23:12.753Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
```

**Comment by shanalikhan** [comment]
okay
Will release the version in a day or two.

**Comment by wKovacs64** [comment]
Working again for me in v2.8.4. Thanks @shanalikhan!

**Comment by trentrand** [comment]
Another solution for syncing settings between vscode and vscode-insider is to run the following command:
```
code --list-extensions | xargs -L 1 code-insiders --install-extension
```
