### ISSUE TITLE
Update Doc screenshots

### ISSUE THREAD

**Issue by pyros2097** [shanalikhan/code-settings-sync#43]
**Visual Studio Code Version :** 1.2
**Code Sync Settings Version :** 1.3.0
**Operating System :** Archlinux

I think you need to update the docs in the extension page for generating an access token as the screenshots are outdated and the new github page allows a person to give access to their private repositories. So they might accidently do it.

**Comment by shanalikhan** [comment]
Yes thanks, will update it

**Comment by sksea** [comment]
+1

**Comment by shanalikhan** [comment]
updated !
