### ISSUE TITLE
VS Code Multi-root Capabile Setting Sync

### ISSUE THREAD

**Issue by seanmcbreen** [shanalikhan/code-settings-sync#435]
Hi,

I hope all is going well people love your extension and it fills a key gap :)

We had a quick glance at your code and it looks like it's multi-root ready with no additional changes.  But given the polarity of the extension (the the fact I keep recommending it as @code :)) I'd love you to check as well (details in [this guide](https://github.com/Microsoft/vscode/wiki/Extension-Authoring:-Adopting-Multi-Root-Workspace-APIs)).

>**Request:** if you agree it's all looking good we would love you to add `multi-root ready` to your `package.json` i.e. `"keywords": ["multi-root ready"]`.  If you upgrade to `VSCE 1.32.0` this can be added to any existing keywords and will not be counted against the maximum of 5 allowed keywords.

Happy Coding!
Sean
VS Code Team

cc: @bpasero

**Comment by shanalikhan** [comment]
Sean, 

> it's multi-root ready with no additional changes

Thanks ! 
I will release new version in upcoming days with this keyword.
Can you tell me why this keyword is required for new extensions to work.
