### ISSUE TITLE
Remove "Unknown config. setting" warning of "sync.version" in VS Code settings

### ISSUE THREAD

**Issue by ThisIsManta** [shanalikhan/code-settings-sync#436]
**Visual Studio Code Version :** 1.17.2
**Code Settings Sync Version :** 2.8.4
**Operating System :** Windows 10 Enterprise
**Occurs On:** Always

VS Code shows "Unknown configuration setting" warning of `sync.version` in my settings, which I believe the record was added by **Code Setting Sync** extension. Can we remove this warning by adding a placeholder in `package.json` of the extension?

![image](https://user-images.githubusercontent.com/5592654/32359521-3a1eb8f0-c081-11e7-8b11-8729dbd6cc32.png)

**Comment by shanalikhan** [comment]
@ThisIsManta this issue are for users that have been updating from much older extension.
New version doenst support `sync.version` in `setting.json` and therefore it is safe to delete this key.

**Comment by ThisIsManta** [comment]
Oh, thanks for the info. Yes, I have been using this extension from the very beginning.

**Comment by ntwb** [comment]
Is there any documentation for these deprecated settings @shanalikhan ?

I see 3 settings show this and like @ThisIsManta I've been using this plugin for a long time

```
"sync.version": 262,
"sync.showSummary": true,
"sync.workspaceSync": false,
```

The thing also though is after I've run `Sync: Reset Extension Settings` these settings remain, I would have thought it would remove those /shrug

**Comment by ntwb** [comment]
p.s. The docs at https://shanalikhan.github.io/2016/07/31/Visual-Studio-code-sync-setting-edit-manually.html should also be updated and have those removed :)
