### ISSUE TITLE
Shift-Alt-D does nothing

### ISSUE THREAD

**Issue by Neutrino-Sunset** [shanalikhan/code-settings-sync#438]
**Visual Studio Code Version : 1.17.2
**Code Settings Sync Version : 2.8.4
**Operating System : Win7 Ult
**Occurs On: configuring download
**Proxy Enabled: No

I installed sync on my work machine, created a Github token, syn created a gist and I copied the gist id. All seems fine.

I installed sync on my home machine. Pressing shift-alt-d does nothing. After restarting it requested by Github id, so I gave it my Github id token. It then created a new gist. I don't seem to be able to to tell it to use the gist already created by my work machine.

I've tried uninstalling Sync, deleting sync.lock and syncLocalSettings.json and reinstalling.

On reinstalling a message appears 'Settings Created. Thankyou for installing !'. I press shift-alt-d and all that happens in a message in the status bar that says I already have the latest settings.

I've entered Sync > Reset Extension Settings, even after that shift-alt-d does nothing.

I'm expecting to have to enter the ID of the gist that my work machine saved its settings to somewhere, but I don't see any way to do that. Am I misunderstanding what I need to do?

**Comment by Neutrino-Sunset** [comment]
Sorted it.

Entering Sync > Download Settings in the command palette I got a promt to enter the Gist ID. don't know why shift-alt-d doesn't do anything. I've checked the keyboard shortcuts and its configured correctly.

**Comment by shanalikhan** [comment]
Is there any exception logged in developer console when you try using Shortcuts ?

**Comment by Neutrino-Sunset** [comment]
No, there was no error in the console.
