### ISSUE TITLE
Error when trying to download on other pc

### ISSUE THREAD

**Issue by elypma** [shanalikhan/code-settings-sync#44]
**Visual Studio Code Version :** [ 1.2.1]
**Code Sync Settings Version :** [ 1.3.0]
**Operating System :** [ win10]

Please make sure to write the versions and console logged error picture or copied text.

[Extension Host] {"message":"Not Found","documentation_url":"https://developer.github.com/v3"}
ERROR ! Logged In Console (Help menu > Toggle Developer Tools). Please open an issue in Github Repo.

1. Entered Personal Access Token (something like 8997e8c316b6fe2bd943dd336d16d7486535e2a6)
2. GIST ID???? -> No idea what this is. Is it the name of the token (e.g. VS_CODE)

**Comment by shanalikhan** [comment]
When you upload your data for the first time. it shows the gist ID it created that you need to copy and paste in other PC.
Check this image.
http://shanalikhan.github.io/img/upload2.png

Read the step once
http://shanalikhan.github.io/2015/12/15/Visual-Studio-Code-Sync-Settings.html

**Comment by elypma** [comment]
I must be missing something:
All seems to work fine on the first PC where I setup & upload the stuff.
The other PC (the one I want to sync) I can download once and then I have
to reset and renew the gist stuff.
I had hoped I had to setup all systems only once.

Egbert.



Op do 16 jun. 2016 om 07:52 schreef Shan Khan <notifications@github.com>:
