### ISSUE TITLE
Extensions not being installed/removed

### ISSUE THREAD

**Issue by cthree** [shanalikhan/code-settings-sync#440]
**Visual Studio Code Version :** 1.17.2
**Code Settings Sync Version :** 2.8.4
**Operating System :** Win10+MacOS 10.12
**Occurs On:** Download
**Proxy Enabled:** No

Extensions aren't being installed on Download. The status bar says extensions are being installed in the background and the JS console shows the URLs for the extensions but they never get installed on any of the 3 workstations I'm syncing: 2 Macbooks and a ThinkPad.

**Comment by shanalikhan** [comment]
fixed.
Update the extension and hit upload and download the settings.
Let me know if there is still a problem
