### ISSUE TITLE
Release notes link outdated

### ISSUE THREAD

**Issue by Stanzilla** [shanalikhan/code-settings-sync#441]
**Visual Studio Code Version :** [ VERSION_HERE ]
**Code Settings Sync Version :** [ VERSION_HERE ]
**Operating System :** [ VERSION_HERE ]
**Occurs On:** [Upload / Download / Help Configuring ]
**Proxy Enabled:** [ Yes / No ]
**GIst Id:** [ ID_HERE ]

The release notes link in your notification that the extension got updated is pointing to to some super old release notes page at http://shanalikhan.github.io/2016/05/14/Visual-studio-code-sync-settings-release-notes.html

**Comment by shanalikhan** [comment]
added 2.8.5 release notes
Done
