### ISSUE TITLE
Error: Unable to write to User Settings because sync.version is not a registered configuration.

### ISSUE THREAD

**Issue by VictorioBerra** [shanalikhan/code-settings-sync#444]
**Visual Studio Code Version :** 1.18.0 Insiders
**Code Settings Sync Version :** 2.8.5
**Operating System :** Windows 10
**Occurs On:** VSCode Start and Download
**Proxy Enabled:** No
**GIst Id:** It is a private gist.

What I did was install VSC, Install the sync plugin, and then I added my token and then I edited my user settings and told it to use my existing gist. (sidenote, I think the app should ask you if you want to use an existing gist or create a new one. Getting a fresh install of VSC up and running is not a friendly experience.)

![image](https://user-images.githubusercontent.com/2934507/32530778-b8f4b404-c405-11e7-9563-1b9e8383580e.png)

**Comment by shanalikhan** [comment]
Remove the `sync.version` from `settings.json` and try.
Did you install Settings Sync first time ? or updated / reinstalled after a long time ?
As this key is removed from settings.json

**Comment by VictorioBerra** [comment]
@shanalikhan I installed the normal non-insiders build and everything is working.

It appears your extension is broken on the insiders build of Visual Studio Code.

**Comment by VictorioBerra** [comment]
Didn't mean to close this. Re-opened.

**Comment by shanalikhan** [comment]
What is the exception on insiders

**Comment by VictorioBerra** [comment]
`Error: Unable to write to User Settings because sync.version is not a registered configuration.`

`/resources/app/out/vs/workbench/workbench.main.js:10`

**Comment by shanalikhan** [comment]
Have u tried removing sync version key from settings in insiders build?
Or is it occuring everytime even after removing that key from settings json

**Comment by VictorioBerra** [comment]
That key does not exist. I think that is what the error is saying. It's
saying it can't find that key.

On Nov 8, 2017 9:25 AM, "Shan Khan" <notifications@github.com> wrote:

Have u tried removing sync version key from settings in insiders build?
Or is it occuring everytime even after removing that key from settings json

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/shanalikhan/code-settings-sync/issues/444#issuecomment-342851653>,
or mute the thread

**Comment by icylogic** [comment]
It does happen in the stable release of VS Code (1.18). And I could not find `sync.version` in my User Settings. There is a "version" key which should appear in `syncLocalSettings.json`

This error message comes from https://github.com/Microsoft/vscode/blob/06d659f33fa4aaacc1ac874417d898f00acef216/src/vs/workbench/services/configuration/node/configurationEditingService.ts#L281

And the meaning of this [error code](https://github.com/Microsoft/vscode/blob/06d659f33fa4aaacc1ac874417d898f00acef216/src/vs/workbench/services/configuration/node/configurationEditingService.ts#L37-L40):
> Error when trying to write a configuration key that is not registered.

The trace shows that it is caused by calling `writeConfiguration`. Apparently this method is still deeply inside VS Code API, so I could not find the real cause.

PS. The file `onfigurationEditingService.ts` I mentioned above has changed in last few days. The most recent change happened 2 days ago. The history: https://github.com/Microsoft/vscode/commits/master/src/vs/workbench/services/configuration/node/configurationEditingService.ts

**Comment by shanalikhan** [comment]
i will need your GIST ID in order to reproduce at my end.
Also check either you have saved `sync.version` in `settings.json` inside your GIST.
If Gist contains it, remove this from gist from github and then download the gist again and let me know

**Comment by danutzcodrescu** [comment]
It seems that as soon as I have upgraded to 1.18 it triggered this error. I have tested on 2 computers and it worked fine on 1.17, but after the upgrade this error showed up.

**Comment by shanalikhan** [comment]
@danutzcodrescu does your gist have sync.version in settings.json file ?

**Comment by danutzcodrescu** [comment]
@shanalikhan I do not have a sync.version any more and I still get the error. I have deleted the sync.version prop as soon as I have upgraded to 1.18 both in the settings.json and in the gist. However, the error still shows up. I have even tried with a clean new installation and a new gist.

**Comment by m-murygin** [comment]
Have the same issue with ubuntu 16.04

**Comment by faustinoaq** [comment]
Have the same issue on Manjaro Linux

Visual Studio Code Version 👉  1.18.0
Code Settings Sync Version 👉  2.8.5
Operating System 👉  Manjaro Linux 17.0.2
Occurs On 👉 VSCode start new window
Proxy Enabled 👉  No
GIst Id 👉 It is a private gist 😎

**Comment by atom0s** [comment]
Have this issue too. sync.version does not exist in my settings.json.

**Comment by sjess** [comment]
Same Problem here,

Visual Studio Code Version 👉 1.18.0

**Comment by shanalikhan** [comment]
v2.8.6 release fixing this.
Let me know if anyone have still problem.

**Comment by szobonyatomi** [comment]
same here
