### ISSUE TITLE
Get always error about "Expired GitHub Token"

### ISSUE THREAD

**Issue by Michel73** [shanalikhan/code-settings-sync#445]
**Visual Studio Code Version :** 1.17.1
**Code Settings Sync Version :**  2.8.5 
**Operating System :**  ubuntu1404 
**Occurs On:** Upload 
**Proxy Enabled:** [ Yes / No ]
**GIst Id:** 

I used the plugin for a long time. Upload / Download worked on several machines. Since today I always get an error about `Expired GitHub Token` while uploading. I regenerated the token and created a  new one and pasted it in `user.settings` under `gist.sync`. But always get the same error.

**Comment by shanalikhan** [comment]
Check the place where you need to put the token text manually.
https://github.com/shanalikhan/code-settings-sync#customized-sync

**Comment by Michel73** [comment]
Ah, now I recognized my mistake.  I was confused about `github-token`and `gist-id`. Thanks.
