### ISSUE TITLE
can't auto download and install synced extensions

### ISSUE THREAD

**Issue by ljporljp** [shanalikhan/code-settings-sync#450]
**Visual Studio Code Version :** [ 1.18.1 ]
**Code Settings Sync Version :** [ 2.8.5 ]
**Operating System :** [ win7 service pack1 ]
**Occurs On:** [ Download ]
**Proxy Enabled:** [ No ]
**GIst Id:** [ 151521f4634a7bf6005e4d5da9de2db0 ]

 It can't download my other extensions, don't know why.

**Comment by shanalikhan** [comment]
what is the exception logged in the developer console.

**Comment by ljporljp** [comment]
I have installed two versions of vscode, one is the insider version, i was using the insider version to test the 
setting sync update/upload, looks like this method can't work through.

**Comment by shanalikhan** [comment]
what is the error you have faced?

**Comment by ljporljp** [comment]
The insider version of Vscode with setting sync'downloading setting command cannot auto download and install  the extensions that already installed in my machine's another formal version of vscode.

**Comment by ljporljp** [comment]
I have update/upload the config by the formal version of vscode to my gist: this is my gist url:[https://gist.github.com/ljporljp/151521f4634a7bf6005e4d5da9de2db0](url)

**Comment by shanalikhan** [comment]
let me know if there is any exception, with the image
