### ISSUE TITLE
correct token been added but the plugin keep saying its invalid

### ISSUE THREAD

**Issue by adamchenwei** [shanalikhan/code-settings-sync#452]
Visual Studio Code Version : version 1.19.0
Code Settings Sync Version : 2.8.6
Operating System : Mac OS X
Occurs On: [Upload & Download & Help Configuring ]
Proxy Enabled: [ No ]
GIst Id: [ https://gist.github.com/adamchenwei/bd846fbef0ece06ae73ca99a1619cfeb ]

I pasted the exact id of `bd846fbef0ece06ae73ca99a1619cfeb ` into the field popped up. But it keep saying its invalid with these two errors

`Sync : Error Logged In Console (Help menu > Toggle Developer Tools).`
`Sync : Invalid / Expired GitHub Token. Please generate new token with scopes mentioned in readme. Exception Logged in Console.`
*and there is NO errors records in the console. Also it directs me to my gist page.

**Comment by shanalikhan** [comment]
`bd846fbef0ece06ae73ca99a1619cfeb` is your GIST ID
it is not token.
Read the readme once again thoroughly

**Comment by Modelmat** [comment]
I have the same issue. AND I HAVE BEEN FOLLOWING THE TUTORIAL.

**Comment by Modelmat** [comment]
The token menu doesn't even come up, tried reinstalling.

**Comment by shanalikhan** [comment]
@Modelmat whats your gist id
and may i know where you have placed the token

**Comment by Modelmat** [comment]
The thing I generated on github is: `48d1a7ac399af303ae3922e415bd79812f670dde`. I can't enter it anywhere. Placing it in the "sync.gist" didn't work/.

**Comment by shanalikhan** [comment]
you need to place the token here. 
https://github.com/shanalikhan/code-settings-sync#customized-sync

**Comment by Modelmat** [comment]
I don't have a syncLocalSettings.json in my C:\Users\Me\.vscode\ folder anywhere

**Comment by Lindar90** [comment]
The same issue for me. And I can't syncLocalSettings.json in my system

**Comment by Modelmat** [comment]
@shanalikhan I figured it out. I had to delete the `syncLocalSettings.json` from `%appdata%\Code\User\`.

Maybe make a FAQ, it is pretty hidden.

**Comment by adamchenwei** [comment]
I just simply started using another plugin, works a lot better.

**Comment by shanalikhan** [comment]
Adam and modelmat,

Feel free to send me pull request in order to improve the document to help other users understanding much better i will release new version for it

**Comment by Modelmat** [comment]
Yep. When I have some time, I can make some Wiki pages for you

**Comment by shanalikhan** [comment]
we can link them in readme page

But i think user wont go wiki pages that much they will read the readme most of the time.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Modelmat** [comment]
Yeah. The README is a bit overcrowded too. Should we make a new issue?

**Comment by shanalikhan** [comment]
Lets go with the Wiki pages, we can reference them in readme.

**Comment by Modelmat** [comment]
See issue #468

**Comment by ZuleikaRose** [comment]
For the people who are getting the same error as OP.
Go to this url:
https://github.com/shanalikhan/code-settings-sync#customized-sync

Pick one of the below paths for your OS:
Windows, this is %APPDATA%\Code\User\syncLocalSettings.json. 
Mac, $HOME/Library/Application Support/Code/User/syncLocalSettings.json. 
Linux, ~/.config/Code/User/syncLocalSettings.json. 

cd into your User folder below.
Remove the JSON file
