### ISSUE TITLE
Can't setup. After launching github, clicking back just shows errs. No chance to paste token.

### ISSUE THREAD

**Issue by dylanh724** [shanalikhan/code-settings-sync#453]
**Visual Studio Code Version :** [ 1.18.1 ]
**Code Settings Sync Version :** [ 2.8.6 ]
**Operating System :** [ w10 ]
**Occurs On:** [ Help Configuring ]
**Proxy Enabled:** [No ]
**GIst Id:** [ Didn't get that far. I have my key though. ]

I have posted frequently asked questions on 
http://shanalikhan.github.io/2016/11/07/visual-studio-code-frequently-asked-questions.html 
so you may able to resolve the error quickly. 
Please make sure to write the versions and console logged error picture or copied text

Anytime I try to sync, it launches github, then gives me no chance to paste my key in:

![image](https://user-images.githubusercontent.com/8840024/32990783-58a7e7ec-cd6a-11e7-95dc-dcce36c0a65b.png)

**Comment by Mentor1073** [comment]
I have exactly the same problem ... Have you got some soluces ?

**Comment by shanalikhan** [comment]
what is the exception logged in the Console ( Developer Tool )
