### ISSUE TITLE
Python Directories on Different Computers

### ISSUE THREAD

**Issue by Modelmat** [shanalikhan/code-settings-sync#457]
**Visual Studio Code Version:** 1.18 (N/A)
**Code Settings Sync Version:** 2.8.6
**Operating System :** Windows 10 Home/Education v1706/v1607
**Occurs On:** Download
**Proxy Enabled:** No
**Gist Id:** (Isn't this insecure, besides, works with different ones two)

This occurs when I have two different directories for Python, one in `C:\Python36\python.exe`, and the other in `D:\Python36\python.exe` ON DIFFERENT COMPUTERS. Every time I sync this extension, the computer with `C:\Python36\python.exe` gets reset to `D:\Python36\python.exe`, which means I have to reset the environment again. 

Any way to disable this I could not find, so please help.

**Comment by shanalikhan** [comment]
https://github.com/shanalikhan/code-settings-sync#customized-sync

For now, you have to define which settings you want to override, 
https://shanalikhan.github.io/2017/02/19/Option-to-ignore-settings-folders-code-settings-sync.html

**Comment by Modelmat** [comment]
Where is the python path stored? Besides, in `.vscode` I only see /extensions, and in yours (/extensions/Shan.code-settings-sync-2.8.6/) there is no synclocalsettings.json

**Comment by Modelmat** [comment]
Never mind, wrong User folder.

**Comment by shanalikhan** [comment]
> synclocalsettings.json
In User folder.


Let me know if it helped

**Comment by Modelmat** [comment]
Which folder/file is the Python path stored?

**Comment by shanalikhan** [comment]
> Every time I sync this extension, the computer with C:\Python36\python.exe gets reset to D:\Python36\python.exe

Supposedly its in code settings.

**Comment by Modelmat** [comment]
Nope: settings.json```{
    "sync.gist": "--------------------",
    "sync.lastUpload": "2017-11-24T23:40:06.003Z",
    "sync.autoDownload": true,
    "sync.autoUpload": true,
    "sync.lastDownload": "",
    "sync.forceDownload": false,
    "sync.anonymousGist": false,
    "sync.host": "",
    "sync.pathPrefix": "",
    "sync.quietSync": false,
    "sync.askGistName": false,
    "workbench.colorTheme": "Atom One Dark",

    "files.autoSave": "afterDelay",
    "files.autoSaveDelay": 30000,
    "emmet.triggerExpansionOnTab": true,
    "terminal.integrated.shell.windows": "C:\\Windows\\System32\\cmd.exe",
    "workbench.iconTheme": "material-icon-theme",
    "window.zoomLevel": 0,
    "python.linting.pylintArgs": [
        "--disable=C0103",
        "--disable=C0301",
        "--disable=C0111"
    ],
    "git.enableSmartCommit": true,
    "workbench.panel.location": "right",
    "dateTime.showSeconds": true,
    "editor.minimap.enabled": false,
    "autoDocstring.includeDescription": false
}

**Comment by shanalikhan** [comment]
share your gist url

**Comment by Modelmat** [comment]
Can't you upload to it though ?

**Comment by Modelmat** [comment]
ff2112d2ba895206826cbdabd1091a2d

**Comment by Modelmat** [comment]
@shanalikhan The issue is with workspaces, not you.
Sorry.
