### ISSUE TITLE
Adding Raspbian Support

### ISSUE THREAD

**Issue by hammad-awan** [shanalikhan/code-settings-sync#458]
**Visual Studio Code Version :** 1.14.0-1497990172
**Code Settings Sync Version :** 2.8.2
**Operating System :** Raspbian 
**Occurs On:** Download
**Proxy Enabled:** No
**GIst Id:** f1b5daf828287f0c9daa108d86f8aaaf

VS Code for Raspbian was installed from here: https://code.headmelted.com/

I installed the Settings Sync manually, and for some reason the latest version is 2.8.2 in the Extensions list. On other OSes like Windows 10 it is 2.8.6.

It downloads the other files, but on Installing Extensions in the background, it does nothing. It says in the console window that it is installing from such and such URL, but it doesn't actually do anything and slows the system until it finishes which takes four or five minutes.

VISUAL STUDIO CODE SETTINGS SYNC 
Version: 2.8.2

Download Summary

--------------------
GITHUB TOKEN: Anonymous
GITHUB GIST: f1b5daf828287f0c9daa108d86f8aaaf
GITHUB GIST TYPE: Secret

--------------------

Anonymous Gist Cant be edited, extension will always create new one during upload.

If current theme / file icon extension is not installed. Restart will be Required to Apply Theme and File Icon.

Files Download.

extensions.json
keybindings.json
settings.json
settings.json-1507160804861.backup
vsicons.settings.json

EXTENSIONS REMOVED :

No Extension needs to be removed.

EXTENSIONS ADDED :

No Extension needs to install.

**Comment by shanalikhan** [comment]
> VS Code for Raspbian

Currently Raspbian isnt support.
Pull Request is welcome

**Comment by shanalikhan** [comment]
It is fixed by the latest version `v3.1.2`
Let me know if there is any issue. I will reopen this.
