### ISSUE TITLE
Nothing happening at setup

### ISSUE THREAD

**Issue by dylanh724** [shanalikhan/code-settings-sync#459]
**Visual Studio Code Version :** [ Latest]
**Code Settings Sync Version :** [ Latest ]
**Operating System :** [ 10 ]
**Occurs On:** [ Help Configuring ]
**Proxy Enabled:** [ No ]
**GIst Id:** [ ID_HERE ]
The hotkeys don't work, nothing happens. None of the shortcuts work:

1. Upload Key : Shift + Alt + U
2. Download Key : Shift + Alt + D

On my desktop, first upload would instantly say invalid gist, without ever giving me a chance to enter it.

On my laptop, nothing simply happens after installing and none of the hotkeys work.

Both rigs failed ;(

**Comment by shanalikhan** [comment]
> On my desktop, first upload would instantly say invalid gist, without ever giving me a chance to enter it.

What is the exception logged in the developer console

>On my laptop, nothing simply happens after installing and none of the hotkeys work.

Hot keys will work when the focus is on any opened editor page.
