### ISSUE TITLE
worspaces are not synced?

### ISSUE THREAD

**Issue by EugenMayer** [shanalikhan/code-settings-sync#460]
**Visual Studio Code Version :**  1.18.1 
**Code Settings Sync Version :** 2.8.6
**Operating System :** macos
**Occurs On:** Upload
**Proxy Enabled:** No
**GIst Id:** https://gist.github.com/EugenMayer/32c9236877476c3cdea0dd3c68f4c219

I cannot see how to make workspace-settings synced somehow or i did probably missunderstood the feature? I saved my workspace under ~/Documents/vs-workspaces/<>, but there is nothing about that in the syncs. 

I have posted frequently asked questions on 
http://shanalikhan.github.io/2016/11/07/visual-studio-code-frequently-asked-questions.html 
so you may able to resolve the error quickly. 
Please make sure to write the versions and console logged error picture or copied text

**Comment by shanalikhan** [comment]
Settings Sync dont sync workspaces.

**Comment by EugenMayer** [comment]
@shanalikhan 
![image](https://user-images.githubusercontent.com/136934/33237881-4731aed8-d280-11e7-9675-a4ad46e8a235.png)

not sure how to understand that in the docs? could you shortly explain?

**Comment by shanalikhan** [comment]
It means `workspace storage` folder inside User folder as written above all extension and complete User folder

**Comment by EugenMayer** [comment]
could you put the difference between those in short words, google did not exactly help me on that. What is stored in the `workspace_storage` ?

**Comment by shanalikhan** [comment]
It stores some internal settings for work spaces, u need to check them though.

Sure, i will put it, also i am always looking to improve documentation for users to understand in configuring and work of extension. Feel free to send a pull request where ever you need is possible.

**Comment by dannysood** [comment]
@shanalikhan is there a way to sync workspace settings as well maybe if we can put all .code-workspace files in a specific location. vscode allows workspace files to be present anywhere not just inside the workspace. It would be awesome to sync workspace settings as well.

**Comment by YesThatAllen** [comment]
I came here looking for this..  I don't see how to do it..

what was the intent in this change from `Workspaces` to `Workspaces Folder`?

https://github.com/shanalikhan/code-settings-sync/commit/262d03c5ea8c03d9ecb9424d22658a118a7630b1#diff-04c6e90faac2675aa89e2176d2eec7d8R39
