### ISSUE TITLE
Suggestion: Mention Access Token when downloading for the first time

### ISSUE THREAD

**Issue by philno** [shanalikhan/code-settings-sync#461]
Hello,

I finally got your plugin running on my home pc + laptop.
You only mention the Gist token in the 'how to download your settings...' section. But it doesn't work on my laptop without the access token. It's only mentioned as 'if you want to upload...' but that is clearly not the case.
The extension only asks for the Gist token, but not for the access token even though it is missing/undefined. As a result, the gist can not be accessed.
But it is very hard to find out that I have to go in the advanced options myself, enter the access token and then retry.

I think it would be great to cover that in your readme or even let the extension ask for both tokens (access & gist) when downloading...

**Comment by shanalikhan** [comment]
Actually it does `Download` the gist when you dont have access token.
For upload it required the token thought.

To make it consistent, i will add option to add token also before downloading.

**Comment by barbalex** [comment]
I have been spending hours trying to get this to work.

The docs say

> Press Shift + Alt + U it will ask your GitHub account access token.

Well, this does not work for me. And has never on any of my four pc's I work with (one macOS, three Windows).

Also: It is not clear what has to happen in what sequence.

Every time so far I have had an epic battle to get this to work.

And today it seems that I am loosing this battle :-(

PLEASE just open a simple form where users can input token and gist id. Just like any other program that needs user input to work.

**Comment by barbalex** [comment]
Well, I now opened the advanced settings in the command. But it is absolutely unclear what command would enable entering the token.

How can I input the token other than typing `Shift + Alt + U`?

**Comment by barbalex** [comment]
O.k., so finally `Sync: Update / Upload Settings` did not just open GitHub (which is completely unnecessary because I want to enter the token I have to download my existing settings), but also opened a field to enter the token!

Yay :-)

But after entering the existing token I get told that a new token was created and the settings were uploaded.

:-(

O.k., so back to resetting all and trying for the (guessed) 20th time.

**Comment by barbalex** [comment]
So the 20th time I decided not to use `Sync: Update / Upload Settings` but try again, if this by directly using `Sync: Download Settings`. I had tried that before and all I got was errors, some of them claiming the token did not exist.

Well, this time it worked. After almost an hour of trying.

I am very confused though: As no token was entered, what will happen when I change Settings on this notebook? Will it ever be uploaded?

**Comment by barbalex** [comment]
O.k., so after seemingly winning the battle: this is what I could expect this tool to do:

- give me a dead simple way to input and check token and gist id
- not to keep leading me to github: only tell me to do this if I do not input token and gist id

Obviously there is at least one pretty well known developer that was also to "dumb" to navigate efficiently through the now very confusing installation precedure: https://github.com/shanalikhan/code-settings-sync/issues/417

**Comment by barbalex** [comment]
Now on all my computers I am left with only one single extension: Settings Sync. All the others seem to have ben nuked when I installed the new computer yesterday and had my epic battle to download my settings.

This is EXTREMELY frustrating.

**Comment by shanalikhan** [comment]
Feel free to post there. https://github.com/shanalikhan/code-settings-sync/issues/468

**Comment by shanalikhan** [comment]
New version release ,solving this.
