### ISSUE TITLE
Limitation on Windows behind a PAC corporate proxy

### ISSUE THREAD

**Issue by gsemet** [shanalikhan/code-settings-sync#463]
Hello

Current version of setting sync suffer some limitations when using on windows behind a PAC proxy.
When launching vscode without any argument, it requests automatically the proxy credential in an "Authentication required" window.
This can be skipped if vscode has been launched with the `--proxy-pac-url=<pac-file-url>` argument, using the corporate PAC url.

However, code-setting-sync does not seem to use it and raise javascript error (401 host not found). The only way I found to make it work under windows is to set an User Environment variable `http_proxy` to something like `http://username:password@proxyip:port`. 

Expected behavior: propagate the proxy setting from vscode defined in https://code.visualstudio.com/docs/setup/network.

**Comment by shanalikhan** [comment]
![image](https://user-images.githubusercontent.com/8774556/33707059-f3e64582-db57-11e7-8c0f-eb5569feaf08.png)

See this
https://github.com/Microsoft/vscode/issues/12588

**Comment by Stibbons** [comment]
No pbl, I understand :)

**Comment by gpion** [comment]
@shanalikhan so no solution or workaround to have the extension works behind a corporate proxy requiring authentication then?
BTW, I've also tried to set  
`"http.proxy": "http://<user>:<pass>@<proxyhost>:<proxyport>" `
in settings.json and I'm getting the following error in dev console 
`HttpError: request to https://api.github.com/gists?access_token=<mytoken> failed, reason: getaddrinfo ENOTFOUND <user> <user>:80`

**Comment by gsemet** [comment]
Use HTTP_PROXY and HTTPS_PROXY environment variables (or lower case version)

**Comment by gpion** [comment]
> Use HTTP_PROXY and HTTPS_PROXY environment variables (or lower case version)

Just tried it, 
I can confirm that env variables are correctly set since a command line curl works fine (and not after the variables have been unset)
However, in VS Code I'm getting the exact same error:
`HttpError: request to https://api.github.com/gists?access_token=<mytoken> failed, reason: getaddrinfo ENOTFOUND <user> <user>:80`

 (I've commented out http.proxy in settings.json)

**Comment by gpion** [comment]
@gsemet @shanalikhan no other idea of a possibly working solution ?

**Comment by gpion** [comment]
Ok then: I've switched to a OneDrive based approach using another plugin. Hope it will suit my needs.
