### ISSUE TITLE
Wiki Pages + FAQ for GitHub 

### ISSUE THREAD

**Issue by Modelmat** [shanalikhan/code-settings-sync#468]
This is the discussion thread for creating the wiki pages.

**Comment by shanalikhan** [comment]
**Pages**
1. Insert Github Token and Gist ID Manually
2. Errors that most Users face with their solutions.

**Comment by Modelmat** [comment]
3. Customising folder sync

**Comment by Modelmat** [comment]
@shanalikhan Or do we want to use github pages?

**Comment by Modelmat** [comment]
Apparently, pull request don't exist for wikis-  here's the .git though. https://github.com/Modelmat/code-settings-sync.wiki.git

**Comment by shanalikhan** [comment]
I have pushed in the wiki. 
Thanks!

**Comment by shanalikhan** [comment]
WIKI are open for Public users. 
Anyone can edit it.
We can discuss it over slack or you can make a change.
Closing this issue.
