### ISSUE TITLE
extension download failed

### ISSUE THREAD

**Issue by guidorice** [shanalikhan/code-settings-sync#47]
**Visual Studio Code Version : 1.2.1
**Code Sync Settings Version : 1.3.0
**Operating System : Win10

Hi, I am opening an issue because there as an error, and code-settings-sync said to open an issue :)

I am not sure that the problem was exactly, because I was able to uninstall- and reinstall the Python extension without any troubles, after seeing this error.

![vscode-settings-sync](https://cloud.githubusercontent.com/assets/766758/16322868/85432e48-3963-11e6-9bc3-963eec9540bf.png)

**Comment by shanalikhan** [comment]
i think this is an NPM inssue.
Can you try to upload the settings after installing python extension manually, and check again in downloading the other extension in other PC, let me know if this occurs each time.

**Comment by guidorice** [comment]
Hi, I am able to install the Python extension manually, with apparently no errors. Only when a) it's missing and b) I run the command Sync: download settings, does it error out on the python extension.
