### ISSUE TITLE
Discussion : Improving Startup Time

### ISSUE THREAD

**Issue by lovelyjuice** [shanalikhan/code-settings-sync#472]
- Extension Name: code-settings-sync
- Extension Version: 2.8.7
- OS Version: Windows_NT x64 10.0.16299
- VSCode version: 1.19.0

 We have written the needed data into your clipboard. Please paste:
```json 
{
	"activationTimes": {
		"startup": true,
		"codeLoadingTime": 346,
		"activateCallTime": 1,
		"activateResolvedTime": 261,
		"activationEvent": "*"
	}
}
```

![default](https://user-images.githubusercontent.com/20644461/34069296-11fe3f06-e289-11e7-998b-2a3918bb93a8.PNG)

Is it possible that the plugin was partly loaded at the vscode starting up,  and then entirely loaded when I use it to synchonize my settings?

**Comment by shanalikhan** [comment]
can you share your settings sync settings

**Comment by lovelyjuice** [comment]
@shanalikhan 
```
{ 
    "sync.gist": "ae956d6743ce0053f3bcb198ff6083cb",
    "sync.lastUpload": "",
    "sync.autoUpload": false,
    "sync.quietSync": false,
    "sync.autoDownload": false,
    "sync.lastDownload": "2017-12-17T09:37:53.357Z",
    "sync.forceDownload": false,
    "sync.anonymousGist": false,
    "sync.host": "",
    "sync.pathPrefix": "",
    "sync.askGistName": false
}
```
That's all settings about settings sync in my user settings file

**Comment by shanalikhan** [comment]
I have renamed this thread as discussion and open for pull request from anyone having ideas to improve the startup.
Feel free to discuss here.
https://github.com/shanalikhan/code-settings-sync/blob/868642424a0d70ef0590d0347f2cebe4dc0aa60c/src/extension.ts#L32

https://github.com/shanalikhan/code-settings-sync/blob/868642424a0d70ef0590d0347f2cebe4dc0aa60c/src/extension.ts#L33

https://github.com/shanalikhan/code-settings-sync/blob/868642424a0d70ef0590d0347f2cebe4dc0aa60c/src/extension.ts#L34
On startup, currently these things are performed:
1. Migration Process to update the versions and settings
2. Read across settings to allow auto upload and download on startup

**Comment by axetroy** [comment]
@shanalikhan 
I found that in source code.

```
    "activationEvents": [
        "*",
        "onCommand:extension.updateSettings",
        "onCommand:extension.downloadSettings",
        "onCommand:extension.resetSettings",
        "onCommand:extension.HowSettings",
        "onCommand:extension.otherOptions"
    ],
```

It means the extension is always be activated.

I know this may be the function of automatically synchronizing settings when starting VSCode.

And we have to consider that: **Do we really need to sync automatically?**

So, here is my solution:

1.  Turn off auto download. **BREAKING CHANGE**
2.  Optimized `activate` function

Here are some sync method will blocking thread in `activate` function.

```ts
let lockExist: boolean = await FileService.FileExists(en.FILE_SYNC_LOCK);
if (!lockExist) {
  fs.closeSync(fs.openSync(en.FILE_SYNC_LOCK, 'w'));
}

let locked: boolean = lockfile.checkSync(en.FILE_SYNC_LOCK);
if (locked) {
  lockfile.unlockSync(en.FILE_SYNC_LOCK);
}
```

**Comment by shanalikhan** [comment]
> Do we really need to sync automatically? Turn off auto download. BREAKING CHANGE

Yes Settings sync needs to supports auto upload and auto download features.
They are **turned off by default** but user can set it ON and use that.
In activation it checks either those modes are on or off and then perform the functions if found ON

**Comment by shanalikhan** [comment]
Well, Lets keep this automatic for now.

**Comment by shanalikhan** [comment]
Startup Time in Linux :

![startup](https://user-images.githubusercontent.com/8774556/44842229-bb0e9b00-ac5e-11e8-911b-5274870f7517.png)
