### ISSUE TITLE
Can't download and install some extensions

### ISSUE THREAD

**Issue by experdot** [shanalikhan/code-settings-sync#473]
**Visual Studio Code Version :** [ 1.18.1 ]
**Code Settings Sync Version :** [ 2.8.7 ]
**Operating System :** [ Windows 10.0.16299.98 ]
**Occurs On:** [ Download ]
**Proxy Enabled:** [ No ]
### Description
When I pressed Shift+Alt+D to download settings,some extensions are installed properly, but others are not.I've had this problem on two different computers.
### log
```
console.ts:123 [Extension Host] Sync : Extension : 'debugger-for-chrome' - Version : '3.5.0' Invalid or unsupported zip format. No END header found
console.ts:123 [Extension Host] Sync : Extension : 'live-sass' - Version : '1.1.0' Invalid or unsupported zip format. No END header found
console.ts:123 [Extension Host] Sync : Extension : 'LiveServer' - Version : '3.0.0' Invalid or unsupported zip format. No END header found
```

**Comment by shanalikhan** [comment]
are you still facing this error ?

**Comment by experdot** [comment]
I haven't synchronized settings since I met this problem.But I just tried, and it works:)
### Versions
**Visual Studio Code Version :** [ 1.19.1 ]
**Code Settings Sync Version :** [ 2.8.7 ]
**Operating System :** [ Windows 10.0.16299.125 ]
### Output
```
CODE SETTINGS SYNC DOWNLOAD SUMMARY
Version: 2.8.7
--------------------
GitHub Token: -
GitHub Gist: -
GitHub Gist Type: Secret

Restarting Visual Studio Code may be required to apply color and file icon theme.
--------------------
Files Downloaded:

Extensions Removed:
  No extensions removed.

Extensions Added:
  debugger-for-chrome v4.0.0
  LiveServer v3.0.2
  live-sass v1.2.0
--------------------
Done.
```
