### ISSUE TITLE
Clarify GIST ID vs Github Token/Key in documentation

### ISSUE THREAD

**Issue by StevenCHowell** [shanalikhan/code-settings-sync#478]
It would be helpful to add clarification to the documentation on the difference between a GIST ID and a Github token.  As I was trying to get the settings on multiple computers to sync, it took a bit to realize this difference.  On the [How To Configure Page](http://shanalikhan.github.io/2015/12/15/Visual-Studio-Code-Sync-Settings.html), Key and Token are used interchangeably.  For a person who does not use Github GIST much, it is easy to think Token/Key is also referring to the GIST ID.

To improve clarity, I recommend the following changes:

1. replace the use of the word "Key" with "Token" for consistency
2. add a comment to the section "Upload Your Settings For the First Time" saying, "...**gives you GIST ID in the system message.**  *This GIST ID is different from the Github Token; it is the file in which the settings will be stored on your Github account.*  The GIST ID is needed to access..."
3. add a comment to the section "Download your Settings" saying "*Y*ou need to enter your GIST ID in order to download the files you have *previously* uploaded with Shift + Alt + U.  *The extension provided this as output when you uploaded your file.  If you did not record this, you can find it by <fill this in>.*"

**Comment by shanalikhan** [comment]
Thanks, Will look into it.

**Comment by ejwhite1** [comment]
Agreed. It wasn't clear to me that these were different things until I watched the gifs in VS code that made it a bit more clear as to why my sync was failing on machine B. Then a bit more searching and finding this issue resulted in a successful configuration.

**Comment by benshabatnoam** [comment]
I agree. I'm still not sure what is 'GitHub Personal Access Token' is.
I've tried to download my uploaded settings for an hour now but can't seems to get it right. Any help on this?

**Comment by ejwhite1** [comment]
I should have documented exactly what I did to get things working. I seem to recall that it's not clear, but during the process you will create 2 different tokens, even though you think you're using one throughout. As StevenCHowell wrote, the GIST ID and the Github token are two different things. I believe that you need to manually record the GIST ID that's displayed in the system message the first time you upload your settings so you can use it when you try to download settings in the future.

**Comment by shanalikhan** [comment]
Public WIKI are available. You can always make a change.
https://github.com/shanalikhan/code-settings-sync/blob/master/CONTRIBUTING.md#wiki

I will update the Page there soon.

**Comment by ChadRidings** [comment]
Yes, calling keys tokens ids, etc makes things very confusing. They are named a certain way to avoid precisely this kind of cross-referencing.  This is not just a confusion for this project, Github could do a better job of explaining the difference, and where to retrieve yours.

**Comment by shanalikhan** [comment]
I'm open , feel free to send PR in improving the readme and public wiki.

**Comment by ChadRidings** [comment]
@shanalikhan I should have some time this weekend to pull the repo and submit a PR for a documentation update. I have a good idea of how to present the info since I jusr went through sorting my confusion. This is a great tool for Atom users.

**Comment by BrightJovanny** [comment]
> Thanks, Will look into it.

Please, the settings sync windows that allows one to use the "login with github"  doesn't come up. Although, I saw it the first time I installed this extension but wasn't able to use it. Without that, I just don't know how to go about setting up this extension.

**Comment by sarogersz** [comment]
Same experience as @BrightJovanny here.  Seems like it would be quite valuable, but I can't see how to get started.  The links in the Extension documentation page don't work, but there is enough ambiguity in the explanation of Github token and GIST ID that I'm not even sure where "Login with Github" refers to.  There are multiple "Login with Gitub" references that look like links, but none of them are.
