### ISSUE TITLE
Error on attempt to sync settings

### ISSUE THREAD

**Issue by con-ssc** [shanalikhan/code-settings-sync#48]
![image](https://cloud.githubusercontent.com/assets/8189808/16450558/ef6371fe-3dfd-11e6-97ba-9753d40b5301.png)

![image](https://cloud.githubusercontent.com/assets/8189808/16450564/01cbc9ae-3dfe-11e6-85ca-41af2579c9ca.png)

I tried to upload my settings via https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync and encountered above error

**Comment by shanalikhan** [comment]
can you update, and then reset the extension settings ( check from the readme , how to do it) and let me know if the error persists.

**Comment by con-ssc** [comment]
No, I cannot update.

**Comment by con-ssc** [comment]
It is still not working with the same error in the current insider.

**Comment by shanalikhan** [comment]
Can you please update to latest version 2.0.1, i have added handled exceptions more. and let me know if the error is resolved :)
