### ISSUE TITLE
Different defaultCloneDirectory per OS

### ISSUE THREAD

**Issue by krestaino** [shanalikhan/code-settings-sync#483]
**Visual Studio Code Version :** 1.19.2
**Code Settings Sync Version :** 2.8.7
**Operating System :** Windows 10.0.16299
**Occurs On:** n/a
**Proxy Enabled:** no
**GIst Id:** c7208a6b636c7002a4a7147eac30999f

I use VSCode on a Mac at work and Windows at home. I use Settings Sync to keep the 2 installs in sync. Problem is, defaultCloneDirectory needs to be formatted differently on these two platforms. It would be great if there was a way to specify specific settings per OS.

**Comment by krestaino** [comment]
Hmm, maybe posted this too fast. I think this will do.

#457

**Comment by shanalikhan** [comment]
> Hmm, maybe posted this too fast. I think this will do.

So do you want to close this issue or to discuss it with your scenario details
