### ISSUE TITLE
Extension is missed on upload.

### ISSUE THREAD

**Issue by niksite** [shanalikhan/code-settings-sync#484]
**Visual Studio Code Version :** 1.19.2
**Code Settings Sync Version :** 2.8.7
**Operating System :** OSX High Sierra
**Occurs On:** Upload
**Proxy Enabled:** No

I have "File Utils" extension installed. But on setting upload I see no "File Utils" in the "Extensions Added" list. So, when I download settings later, the extension got removed.

**Comment by shanalikhan** [comment]
have you restarted the code when you installed the File Util - Before Uploading ?

**Comment by niksite** [comment]
No, it seems I did't. Today (after some restarts), I see the "vscode-fileutils" in the uploaded settings.
