### ISSUE TITLE
Sync error with GHE, a cookie or id issue ?

### ISSUE THREAD

**Issue by jmarandet** [shanalikhan/code-settings-sync#486]
**Visual Studio Code Version :** 1.19.2
**Code Settings Sync Version :** 2.8.7
**Operating System :** Windows 7 x64
**Occurs On:** [Upload / Download / Help Configuring ]
**Proxy Enabled:** Yes
**GIst Id:** [ ID_HERE ]

Hi,

I would like to use your plugin in order to share my settings within our Github Enterprise.
I have read carefully your FAQ and documentation, I created a token on my Github account with gist scope.
I have edited my VSCode user settings with **sync.host** ( and also **http.proxy** and **http.proxyStricSSL:false**).
The V3 api of our GHE is working ( https:// <sync.host> /api/v3 ), so I didn't had to set the **sync.pathPrefix**.

I am not getting any exception message "not found", so I guess that my token is okay.
But when I do "**F1 > Sync : Update / Upload Settings**", I get an error ;
![image](https://user-images.githubusercontent.com/32270488/35288290-96e5e27a-0064-11e8-850c-5be6c12b8244.png)

and I can see a cookie error and an id error within the development-console, here is the screenshot : 
![image](https://user-images.githubusercontent.com/32270488/35288066-1605b00e-0064-11e8-9e1b-b575f7cf19c1.png)

Here is my syncLocalSettings.json : 
![image](https://user-images.githubusercontent.com/32270488/35288434-f67e2526-0064-11e8-8f50-1a1a1ec91c52.png)

Is there a specific setting that I have missed somewhere ?

**Comment by shanalikhan** [comment]
can you try on other network.
i cant test this feature due to unavailability of environment.

**Comment by jmarandet** [comment]
I am afraid that I can't change the network of my company...
Maybe you could ask for help to other developers ?
I am also using the VSCode-Github plugin that is working great with Github Enterprise : https://github.com/KnisterPeter/vscode-github

**Comment by shanalikhan** [comment]
Currently im the only one who is managing this extension, and looking forward to have active contributors.
Randomly user send me pull request through which i accept.
Looks like you have to wait for it.

**Comment by shanalikhan** [comment]
Try using putting GHR Url as a part of `Global Settings`
Check the readme for details.
Fixed with v3.1.0.

Let me know in case of query.
