### ISSUE TITLE
Uninstall previous sync extensions

### ISSUE THREAD

**Issue by miguelchico** [shanalikhan/code-settings-sync#49]
**Visual Studio Code Version :** 1.2.1
**Code Sync Settings Version :** 1.3.0
**Operating System :** Windows 7

Steps to reproduce:
1. Setup vscode and code-settings-sync in 2 different environments (A and B)
2. Install an extension in environment A and sync settings.
3. Download settings in environment B and the extension is installed.
4. Uninstall the extension in environment B and sync settings. (Check gist and the extension.json file doesn't have the extension).
5. Download settings in environment A.

Expected situation: The extension is removed.
Actual situation: The extension remains installed.

**Comment by shanalikhan** [comment]
yes i have not written the code to remove the extension, started working on it :)

**Comment by shanalikhan** [comment]
I have updated the extension. I am closing this issue. Feel free to re open if there is any error.

**Comment by miguelchico** [comment]
It's working perfect!

thank you very much!
