### ISSUE TITLE
Settings sync ignores new global "xxx.code-snippets" files

### ISSUE THREAD

**Issue by robert914** [shanalikhan/code-settings-sync#491]
**Visual Studio Code Version :** 1.20.0
**Code Settings Sync Version :** 2.8.7
**Operating System :** MacOSX 10.12.6
**Occurs On:** Upload
**Proxy Enabled:** No
**GIst Id:** private

With the latest 1.20.0 version release of VSCode, it now supports new "Global" snippets files that are created in "snippets" with extension ".code-snippets" (e.g. so you may have something like "snippets/global.code-snippets" or whatever). These files exist alongside the normal snippet JSON files (e.g. javascript.json, perl.json, etc.).

However, Settings Sync ignores these new files, and does not sync them to the GIST. They are completely ignored. Please fix this when you can! Thanks!

**Comment by qadszilla** [comment]
Would love to know if this in the works and expected release date if possible please.

**Comment by shanalikhan** [comment]
Released with v2.9
let me know if there are issues.

**Comment by robert914** [comment]
Thanks. It works!
