### ISSUE TITLE
cant reset the gist token

### ISSUE THREAD

**Issue by Wallenberg12** [shanalikhan/code-settings-sync#494]
Hi, I revoked the gist token to set up Settings Sync afresh, even deleted the respective settings in vscode. but whenever I try to reinstall Sync it gets an Error: Sync : Unable to clear settings. Error Logged on console. Please open an issue.

How can I properly reset Sync?

merci 

Wal

**Comment by trsdln** [comment]
hey, I got similar problem (extension stored invalid github token and I wasn't able to reset it).

Removal of `~/.vscode` (extensions) and `~/Library/Application Support/Code` (vscode settings itself) helped.

**Comment by shanalikhan** [comment]
can you guys post the image of console logs

**Comment by Wallenberg12** [comment]
Sync : Invalid / Expired GitHub Token. Please generate new token with scopes mentioned in readme. Exception Logged in Console.

![screen shot 2018-02-15 at 23 21 54](https://user-images.githubusercontent.com/23232503/36284182-0c60ef50-12a7-11e8-8726-351eab61b270.png)

**Comment by shanalikhan** [comment]
Have you tried this
https://github.com/shanalikhan/code-settings-sync#reset-token--gist-settings

Or 
manually remove the token from here.
https://github.com/shanalikhan/code-settings-sync#customized-sync

Then generate new token from github and insert and let me know

**Comment by Wallenberg12** [comment]
as for the first question: yes I did and it yielded to: Sync : Unable to clear settings. Error Logged on console. Please open an issue.

then i deleted the config file. after putting in the new token I got this error in the console: 

  | e.doShow | @ | /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2925
-- | -- | -- | --
