### ISSUE TITLE
Feature Request: Add a comment line to ignore next line on sync

### ISSUE THREAD

**Issue by konqui** [shanalikhan/code-settings-sync#496]
I'm a user of this vscode extension for quite some time. Between my Linux and Mac it works really well. Gerat Work Thanks.

Since i'm working for another Company now i'm some what lost. At my new Company i'm not allowed to use my Private Mac (and have to work eith a Windows PC) but i'd still like to keep my Settings for vscode in sync but there is now one big issue since windows doesn't have a unix/linux core some of the binary paths added to my vscode settings (like eg. php executable needed by php-cs)   don't work on cross between mac/linux and windows sync.

Since those are just a few settings it would be possible for me to manage them by my self but i can't figure out a way to make code sync exluding those line from sync.

Maybe there is already a way that i just didn't find by now please let me know if so.

**Comment by shanalikhan** [comment]
> Since those are just a few settings it would be possible for me to manage them by my self but i can't figure out a way to make code sync exluding those line from sync.

It would be great if you share the path of file and content with image.
So i can explain you

**Comment by konqui** [comment]
Sorry for letting you wait. I'm currently really busy at work. Also i just broke my private Macbook so i can't add Screenshots or anything right now. I'll add them when i have my Macbook back.

Thanks for your Help so far.


Kind Regards Konqui

**Comment by shanalikhan** [comment]
Closing this issue for now, feel free to post scenario with real example when possible - I will reopen and we will discuss it further.
