### ISSUE TITLE
Please clarify how "Sync: Update / Upload Settings" works

### ISSUE THREAD

**Issue by osya** [shanalikhan/code-settings-sync#499]
**Visual Studio Code Version :1.20,1
**Code Settings Sync Version :2.8.7
**Operating System :Windows 10 x64 Pro
**Occurs On: Not applicable
**Proxy Enabled: No
**GIst Id:094e42e4a4ef3a34f8f35aaa163ba313

Please clarify how he function "Sync: Update / Upload Settings" works. Does it really sync settings or just upload local settings to Gitsts and rewrite it? If it just upload settings then:
- to be able to sync settings (by date) User should download settings at first and only then make upload, right? 
- Is this possible to get status of current settings - is it synced or not - before download settings. May be settings already synced and download settings is not necessary

I expected that function "Sync: Update / Upload Settings" sync settings by date, without comparing settings content and not just uploading local settings to Gist. If on Gists settings with newer date then they should overwrite local settings. If local settings newer then they should overwrite settings in Gist.

Is it possible to create some Gist webhook to be able to push changes to VS Codes when settings in Gist changes?

**Comment by shanalikhan** [comment]
> Does it really sync settings or just upload local settings to Gitsts and rewrite it?
yes upload the settings and overwrite them upon uploading again.

>  If on Gists settings with newer date then they should overwrite local settings.

yes when you have latest settings, it shows message that you have latest settings and wont download the settings again until you turn on force download.


> Is it possible to create some Gist webhook to be able to push changes to VS Codes when settings in Gist changes?

set auto upload and auto download to enable and it will work.

**Comment by osya** [comment]
If command "Sync: Update / Upload Settings" just upload settings without downloading it, then I suggest to rename it to just "Sync: Upload Settings". To avoid confusing
