### ISSUE TITLE
Extension host terminated unexpectedly

### ISSUE THREAD

**Issue by Raulis** [shanalikhan/code-settings-sync#500]
**Visual Studio Code Version :** 1.20.1
**Code Settings Sync Version :** 2.8.7
**Operating System :** Win 10
**Occurs On:** On any action. Can't upload, download, reset.
**Proxy Enabled:** no

![image](https://user-images.githubusercontent.com/20267355/36640573-3f25d61e-1a2a-11e8-9f29-19fe7ffb532b.png)

**Comment by shanalikhan** [comment]
try with latest version of settings syn and let me know

**Comment by Raulis** [comment]
Works perfectly now, thanks 👍
