### ISSUE TITLE
Only show Output window if an error happened or on user command

### ISSUE THREAD

**Issue by 3v1n0** [shanalikhan/code-settings-sync#503]
**Visual Studio Code Version :** 1.19.1
**Code Settings Sync Version :** 2.8.7
**Operating System :** Ubuntu 16.04
**Occurs On:** Upload / Download
**Proxy Enabled:** No

All the times I save my keybindings or settings file, the output window opens as per #137 change.
It's ok to save the output there, but the window should not popup all the times.

I guess it should happen only if an error really occurred or if the user has explicitly requested an Upload / Download.

In fact you should use `RevealOutputChannelOn.NEVER` in normal cases.

**Comment by shanalikhan** [comment]
Have you tried setting "sync.quietSync" to true ?
