### ISSUE TITLE
command 'extension.*' not found

### ISSUE THREAD

**Issue by Chiliyago** [shanalikhan/code-settings-sync#509]
**Visual Studio Code Version : 1.21.0
**Code Settings Sync Version : 2.9
**Operating System : Win Svr 2012 RS
**Occurs On: F1 | Sync | any command
**Proxy Enabled: NO
**GIst Id: 
![image](https://user-images.githubusercontent.com/4322241/37248494-7ecd06ee-2488-11e8-8ece-45c7c46d919a.png)

I just installed the lasts VSCode. The first thing I added was Settings Sync extension so nothing else was added.  This was a clean install of VSCode.

Pressing F1 and choosing Sync no matter which option I choose VS Code complains like this:

command 'extension.resetSettings' not found

As such I cannot configure this extension.

**Comment by shanalikhan** [comment]
Try removing the installing the extension again.

**Comment by Chiliyago** [comment]
I tried that also but the problem persists.

**Comment by quemica** [comment]
I have the same problem, cant found any comand.

**Comment by shanalikhan** [comment]
Im unable to reproduce that error. May be you can provide some steps for start so i can reproduce

**Comment by oliverharrison** [comment]
I had this happen too. The fix is to uninstall the plugin, go to /users/%you%/.vscode/extensions and delete the files for Shan.code-settings.etc . Now reinstall the plugin in vscode and reload. You should be able to make it sync now.

**Comment by Chiliyago** [comment]
I tried as you suggested but still did not work. I then removed the PowerShell extension which was the first and only extension I manually installed. Then deleted all the extension folders  in /users/%you%/.vscode/extensions  and reinstalled Sync and it finally worked!

**Comment by arvigeus** [comment]
Does not work for me as well. Version 3.0, VS Code: 1.25.1

**Comment by johnholliday** [comment]
Same problem here.  
VS Code version 1.30.1
OS: Windows_NT x64 10.0.17134

**Comment by Green-unicorn** [comment]
我也是这个问题，我是win10系统
