### ISSUE TITLE
Unable to sync extensions using OSS version of vscode.

### ISSUE THREAD

**Issue by JacobHenner** [shanalikhan/code-settings-sync#510]
**Visual Studio Code Version :** 1.21.0
**Code Settings Sync Version :** 2.9.0
**Operating System :** Arch Linux
**Occurs On:** Download
**Proxy Enabled:** No
**Gist Id:** N/A

When using the OSS (non-branded) version of Visual Studio Code, the extension fails to sync other extensions due to an incorrect path assumption during a mkdir.

```
Sync : Extension : 'python' - Version : '2018.2.1' 
Error: ENOENT: no such file or directory,
mkdir '/home/user/.vscode/extensions/ms-python.python-2018.2.1'
```

With the OSS version, the proper directory is ~/.vscode-oss

**Comment by JacobHenner** [comment]
The following workaround is available: `ln -s ~/.vscode-oss/ ~/.vscode`

**Comment by shanalikhan** [comment]
Thanks!
Will be released in next update

**Comment by JacobHenner** [comment]
Excellent, thank you. #511 seems to be working as expected.
