### ISSUE TITLE
Github Access Token issue

### ISSUE THREAD

**Issue by SheepDomination** [shanalikhan/code-settings-sync#512]
Numerous attempts at trying to get and upload a GitHub personal access token; instead I get this error;
![code_2018-03-12_22-26-01](https://user-images.githubusercontent.com/6827459/37319308-fe95fd50-2644-11e8-9dd8-1a626003739d.png)

**Comment by zzhhbyt1** [comment]
Can you please provide more info?
...like "What error is logged in the so said console?"
This will help people to under stand your issue rather than label as "info needed" and ignore away.

**Comment by SheepDomination** [comment]
I get my personal access token, as described within the overview section for this extension, I copy it. Within code I open the command palette with >sync upload, then attempt to paste my access token only to get an error ?

**Comment by zzhhbyt1** [comment]
Hi, I mean, if you could, please try paste:
![image](https://user-images.githubusercontent.com/11014745/37447370-c90e506e-285c-11e8-884d-4e92b692f1cf.png)

**Comment by zzhhbyt1** [comment]
Hi, I mean, please first paste your:
![image](https://user-images.githubusercontent.com/11014745/37447409-f89e57b6-285c-11e8-96d8-a753b809ba7c.png)

**Comment by SheepDomination** [comment]
I hope this is what you wanted ?
![syncsettings_error](https://user-images.githubusercontent.com/6827459/37551945-263fa466-2981-11e8-9971-45a0327040c4.png)
I created two git tokens both didn't work.

**Comment by zzhhbyt1** [comment]
Hello, good to hear you again. 👍 
Here is what I did:
1. `command palette` > `Sync : Reset Extension Settings`
2. (Then follow the [steps](https://github.com/shanalikhan/code-settings-sync#steps-to-get-a-personal-access-token-from-github) as the developer described) `command palette` > `Sync : Update / Upload Settings`
3. This opens a webpage to let you create a `Personal access token`
4. Click `Generate new token` > fill the `Token description` & check `gist` > click `Generate token`
5. Copy the token and switch back to VS Code, there should be an prompt input field, paste the token and hit `Enter` or click the listed item
6. And Sync works fine here on my PC.

All software latest, including Windows 10, VS Code, Sync, Firefox.
Can't reproduce.
Anything related to how to reproduce is welcomed.

Please make sure you didn't miss or mess up with any steps and 
if you are in a country (e.g.: China) with limited internet access like me, please verify your accessibility to GitHub Gist.

**Comment by SheepDomination** [comment]
Hi, re-setting the extension setting solved the problem. 👍

**Comment by shanalikhan** [comment]
Guys feel free to send me PR, or improve the wiki if you get some problem in understanding. !
