### ISSUE TITLE
"sync.anonymousGist" is an unknown configuration setting

### ISSUE THREAD

**Issue by Stephanyan** [shanalikhan/code-settings-sync#514]
**Visual Studio Code Version :** [ 1.21.0 ]
**Code Settings Sync Version :** [ 2.9.0 ]
**Operating System :** [ macOS High Sierra 10.13.3 ]

Hi,

Visual Studio Code doesn't recognize this configuration setting anymore, as you can see:

<img width="369" alt="screen shot 2018-03-13 at 14 55 46" src="https://user-images.githubusercontent.com/5939522/37346552-e35433e6-26cf-11e8-850f-4e9da7d98679.png">

Does this configuration still exist? Because you still can find it on the [Wiki page](https://github.com/shanalikhan/code-settings-sync/wiki/Settings-Guide#anonymous-gist) and the Visual Studio [Marketplace](https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync) description of this extension.

I can't find in the default settings file.

```json
  // Ask gist name upon creating. Helps you to identify the gist if you have multiple gists.
  "sync.askGistName": false,

  // Set it true to Auto Download the settings on code start. [Code Restart Required]
  "sync.autoDownload": false,

  // Set it true to Auto Upload on the settings change. [Code Restart Required]
  "sync.autoUpload": false,

  // Set it to true if you want to download the settings even when you have latest settings.
  "sync.forceDownload": false,

  // GitHub GIST ID for Settings Sync.
  "sync.gist": "",

  // Set it to your GitHub Enterprise host if you want to use GHE.
  "sync.host": "",

  // Settings Sync last download date. Set it as empty if you want to manually hit download.
  "sync.lastDownload": "",

  // Settings Sync last upload date. Set it as empty if you want to manually hit download.
  "sync.lastUpload": "",

  // Set it to your GitHub Enterprise api prefix if you want to use GHE. Normally '/api/v3'. Only used when host is set.
  "sync.pathPrefix": "",

  // When set to true, will show the result in status bar instead of summary page.
  "sync.quietSync": false,

  // Set it to false if you dont want to remove extensions while downloading.
  "sync.removeExtensions": true,

  // Set it to false if you dont want to upload / download the extensions.
  "sync.syncExtensions": true,
```

**Comment by shanalikhan** [comment]
This is safe to remove from `settings.json`.
`anonymousGist` support has been removed from Github.

**Comment by shanalikhan** [comment]
Wiki Pages are outdated. Feel free to contribute and improve as i'm the only one to manage this project.

**Comment by Angristan** [comment]
Ok, thanks @shanalikhan

**Comment by Stephanyan** [comment]
Thanks @shanalikhan !
