### ISSUE TITLE
Conflicts every time I try to sync

### ISSUE THREAD

**Issue by leepowellcouk** [shanalikhan/code-settings-sync#517]
**Visual Studio Code Version :** 1.21.1
**Code Settings Sync Version :** 2.9.0
**Operating System :** OS X
**Occurs On:** Upload / Download
**Proxy Enabled:** On one side
**GIst Id:** Private

Everytime I attempt to sync between two machines (work and home) I get a conflict error of `Failed to save 'settings.json': The content on the disk is newer. Please compare your version with the one on disk.`

This might be because I am using the `replaceCodeSettings` feature for setting the proxy at work and removing it at home ... the changes this makes seem to get pushed back up when I sync. Should this happen?

Is there a way of just ignoring some settings in the `settings.json` file from being added to the sync? This might stop the issue.

**Comment by shanalikhan** [comment]
Make sure `settings.json` is closed from editor when you start download process.
