### ISSUE TITLE
Download on other machine doesn't work at all

### ISSUE THREAD

**Issue by DanDvoracek** [shanalikhan/code-settings-sync#518]
**Occurs On:** [Download ]
**Proxy Enabled:** [ No ]

I have a problem and nothing seems to work.

I basically created a public gist on machine A. Now I want to download that gist from another machine but whatever I do I get 

```
Invalid / Expired GitHub Token. Please generate new token with scopes mentioned in readme. Exception Logged in Console.
```

I can't understand why it comes back invalid/expired as I can still upload my setting from the other machine B. Really, what to do, what token/id etc to use isn't clear enough. I watched the gif a hundred time and I still keep having something different happening for me.

What is the clear process to achieve what I wanna do?

Thanks

**Comment by leepowellcouk** [comment]
I've had this a few times, try clearing your sync settings (Sync: Reset Extension Settings), remove any extension settings in your user settings, then uninstall the extension. Restart vscode, install the extension, attempt to sync your settings, then add the api key and gist id when prompted.

**Comment by DanDvoracek** [comment]
Thanksfor the tips. When you say "api key".. What is this api key ? ^^

I already gave up on this, but might give it another go at some point.

Thanks

**Comment by leepowellcouk** [comment]
Your github api key that you should have created to allow the extension access to write to the gist

Lee Powell
lee@leepowell.co.uk
https://uk.linkedin.com/in/leepowell

**Comment by leepowellcouk** [comment]
Sorry, I meant an access token ... steps can be found here:

[https://github.com/shanalikhan/code-settings-sync#steps-to-get-a-personal-access-token-from-github](https://github.com/shanalikhan/code-settings-sync#steps-to-get-a-personal-access-token-from-github)

You'll then need to go and create a gist under your account here: 

[gist.github.com](gist.github.com)

You'll need both the access token, and the created gist id in order to use the extension.

**Comment by DanDvoracek** [comment]
Right. The gist id is the name/ref of the gist right?

I tried that too unfortunately.

**Comment by jschumme** [comment]
I can confirm the problem

**Comment by shanalikhan** [comment]
> Entered: vscode-settings

Why you entering the vscode-settings on prompt on download settings. You need to insert **GITHUB TOKEN** first prompt and **GIST ID** in second prompt while downloading.

Already written in https://github.com/shanalikhan/code-settings-sync#download-your-settings

_Feel free to send me pull request to improve documentation or WIKI, where required._

**Comment by jschumme** [comment]
@shanalikhan 

I entered my github token first - that is "vscode-settings". Then, I was prompted to enter my gist and I entered "4f937150aa...". Maybe I'm mixing things up here, too...

**Comment by shanalikhan** [comment]
You need to insert the token here which is generated by github by doing the following steps.
https://github.com/shanalikhan/code-settings-sync#steps-to-get-a-personal-access-token-from-github

**Comment by alxpsr** [comment]
Same problem. I can't download settings on another machine.
1. `> Sync: Download setting`
2. `insert token` then enter
3. `insert gist id`

Get an error
```
Invalid / Expired GitHub Token. Please generate new token with scopes mentioned in readme. Exception Logged in Console.
```

What i am do it wrong?
