### ISSUE TITLE
Unable to download settings

### ISSUE THREAD

**Issue by KevisLuo** [shanalikhan/code-settings-sync#519]
**Visual Studio Code Version : 1.21.1
**Code Settings Sync Version : 2.9.0
**Operating System : Windows 10
**Occurs On: Upload
**Proxy Enabled: No

Getting Internet Not Connected error below
![image](https://user-images.githubusercontent.com/13983534/37698443-f8985418-2d1d-11e8-8b14-9a2d9fe3bfa8.png)

![image2](https://user-images.githubusercontent.com/13983534/37698977-4ac967e8-2d20-11e8-8ae8-713723201ecf.png)

**Comment by shanalikhan** [comment]
Try on other network

**Comment by KevisLuo** [comment]
Thanks, i try it on other network and it works
