### ISSUE TITLE
Can't download settings

### ISSUE THREAD

**Issue by VitalySenko** [shanalikhan/code-settings-sync#52]
**Visual Studio Code Version :** 1.3.1
**Code Sync Settings Version :** 1.4.2
**Operating System :** Win10

Setting upload was successful.
Maybe i am too dumb, but what should i enter in 2 inputs for first download?
As placeholder says, at first input i should enter Github Personal Access Token, but your readme says that i should enter github account. And the second input is Gist ID - this is my personal access token, right?

Nevertheless, i tried to enter my name + token, my email + token, token + token, and i couldn't figure out what's wrong. Can you help me please?)

P.S. I have multiple git profiles, maybe it somehow relies on my global git username or email?

**Comment by shanalikhan** [comment]
Select One Github Account.


Lets Get from Start - **Upload**

> i should enter Github Personal Access Token, but your readme says that i should enter github account

Its actually the place where you need to insert personal access token.
As you are uploading it will create GIST in your github profile and gives you the ID of Gist which you will need in other machines to download those settings from that GIST File.

**Download**
> i should enter Github Personal Access Token, but your readme says that i should enter github account
 - Access Token - Same you used in uploading Time.

> And the second input is Gist ID - this is my personal access token, right?

Its the GIST ID that was generated at the time of uploading. you need to enter that ID here in other to download the settings.

I'm closing this issue , let me know if you have further questions.
