### ISSUE TITLE
Feature Request: Download settings on interval

### ISSUE THREAD

**Issue by MrTravisB** [shanalikhan/code-settings-sync#520]
Auto download on start is a nice feature. Unfortunately I (and most developers I know) rarely if ever restart our computers and also don't restart VSCode. It would be nice if we could set an interval to check for new settings and download.

**Comment by shanalikhan** [comment]
Duplicate of #318

**Comment by MrTravisB** [comment]
@shanalikhan #318 is specifically about uploading changed settings not downloading changed settings which is why I didn't consider it a dupe.

**Comment by shanalikhan** [comment]
Thanks, i have changed the title there.
Lets track it there.
