### ISSUE TITLE
Erorr in console

### ISSUE THREAD

**Issue by RandallFlagg** [shanalikhan/code-settings-sync#522]
**Visual Studio Code Version :** 1.20.1
**Code Settings Sync Version :** 2.9.0
**Operating System :** Win 10 x64 - 1703
**Occurs On:** Don't know
**Proxy Enabled:** No
**GIst Id:** [ ID_HERE ]

Attached the log from VSCode
[Shan.code-settings-sync-2.9.0.log](https://github.com/shanalikhan/code-settings-sync/files/1839732/Shan.code-settings-sync-2.9.0.log)

**Comment by shanalikhan** [comment]
You have vs code portable installed.
Settings Sync dont support portable.
