### ISSUE TITLE
Settings across different operating systems

### ISSUE THREAD

**Issue by jpsala** [shanalikhan/code-settings-sync#524]
Is there a way to support differences in settings acress different oss? what I mean is for example different paths, like:
   "php.validate.executablePath": "c:\\users\\jp\\php\\php",
   "phpfmt.php_bin": "c:\\users\\jp\\php\\php"
this settings are different in my windows box and in my linux box :(

**Comment by shanalikhan** [comment]
Nope, PR is welcome for it.

**Comment by jpsala** [comment]
I'm not capable but thanks for answer

**Comment by igomezal** [comment]
You could use:

> **askGistName** : false by default. When set to true allows user to set Gist name while creating new one. Very helpful when you have multiple environments ( e.g Home Settings, Work Settings ) you can name those gist and download them by identifying.

If you use askGistName you can create two different settings one for your linux machine and another for your windows one (You sync one time your shared configuration and then you create two different with the singularities of the linux's settings and the windows's settings)

**Comment by jpsala** [comment]
Great, thanks a lot

**Comment by shanalikhan** [comment]
@jpsala
Do u want a feature for it
I think by having multiple settings is the beat idea
