### ISSUE TITLE
When sharing, where do public Gists get created?

### ISSUE THREAD

**Issue by GollyJer** [shanalikhan/code-settings-sync#528]
Here are the versions I'm running.
![2018-03-29_22h35_58](https://user-images.githubusercontent.com/689204/38122199-98e8bbae-33a1-11e8-8ab1-25b32020f5f9.png)

I have a private sync set up and working great.  
Then I went to `Sync: Advanced Options` > `Sync: Share settings with public GIST`.

It progressed successfully and the said something like "you're good to go, share this ID with others".

What I'm having trouble is figuring the ID.  I don't see a public gist created under my Gist profile and the success message didn't mention it either.

Thanks for any help!

**Comment by GollyJer** [comment]
Hey. Wanted to report back how I fixed my own problem.  

I had to run the command  
`Sync: Download Settings from Public Gist`  
before running  
`Sync: Share Setting with Public Gist.`

Doing it in that order created the Gist and returned ID correctly.

Best,
Jeremy

**Comment by shanalikhan** [comment]
Glad to know it helped
