### ISSUE TITLE
Error Logged In Console。。。

### ISSUE THREAD

**Issue by Sunday96** [shanalikhan/code-settings-sync#529]
**Visual Studio Code Version :** [ 1.21.1]
**Code Settings Sync Version :** [ 2.9.0 ]
**Operating System :** [ windows 10  ]
**Occurs On:** [Upload / Download / H
![20180331202932](https://user-images.githubusercontent.com/20500528/38163191-42b20cf4-3522-11e8-9de0-279ac57b1427.png)
elp Configuring ]
**Proxy Enabled:** [ Yes / No ]
**GIst Id:** [ ID_HERE ]

**Comment by shanalikhan** [comment]
Whats the exception logged in developer console

**Comment by Sunday96** [comment]
Nothing

**Comment by shanalikhan** [comment]
Yes, you have invalid token, create new token from github and then try

**Comment by Sunday96** [comment]
no no,When I update or download, I get an error (token has not been filled in)

**Comment by shanalikhan** [comment]
U need to inert the token from github in sync setting file in users folder

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
