### ISSUE TITLE
Cannot input initial settings using Insiders build

### ISSUE THREAD

**Issue by QuietusPlus** [shanalikhan/code-settings-sync#53]
### System

**Visual Studio Code Version :** 1.4.0-insider (build 2016-07-22)
**Code Sync Settings Version :** 1.5.0
**Operating System :** Windows 10 (x64, Version 1511, Build 10586.494)

### Steps to Reproduce

1. Open `Visual Studio Code - Insiders`
2. Open the command palette.
3. Choose `Sync: Download Settings`.
4. Extension opens browser (GitHub Settings).
5. Command palette is no longer open.

### Details

Which means I cannot input the access token or repository during initial configuration of the extension. Not entirely sure this is an issue with the extension itself, but the command palette auto-closing seems like expected behaviour (from a quick google search).

**Comment by shanalikhan** [comment]
You need to click on the text bar of the command palette when you get from the new tab.
Also try to reset settings using _Sync : Reset..._ command of the extension to remove all the configuration if there is any to get from start again.

**Comment by QuietusPlus** [comment]
Tried the reset before posting, this issue happens on a clean install of Visual Studio Code... I've done the initial setup multiple times, so the expected behaviour is known to me.

I'll try to explain in a bit more detail:

1. Open `Visual Studio Code - Insiders`.
2. Command palette > `Sync: Download Settings`.
3. Extension opens browser. It's at this point the command palette closes (in the background), but is expected to stay open.
4. Return to `Visual Studio Code`. The command palette should still be open at this point (done this in the past).

**Comment by massimocode** [comment]
I am affected by this issue as well... I think it needs fixing urgently because the insiders build feeds into the stable build

**Comment by jbeaudoin11** [comment]
if you are quick enough to be able to paste the first uuid and hit the enter button, the next time you select the download option it's gonna ask only for the gist uuid.

it's kinda stupid but i need to set set firefox as default browser so i could get enough time to paste+entre chrome is to fast !

**Comment by shanalikhan** [comment]
i have checked it , yes its not working in insider build as now they have set if the current window is changed the input box will closed so when browser is opened it automatically closes. A simple way is to stop opening link in browser and let user do it himself by reading from Read Me, to keep it like a old way i am finding alternate solution. Will update soon :)

**Comment by QuietusPlus** [comment]
@shanalikhan A suggestion on the configuration process:

1. Add a command palette entry called `Sync: Open Settings`
2. This entry then opens the .json where both the token and gist repo are stored.
3. Have the extension automatically open this file if the settings are not valid. Either because they haven't been configured, or if the extension cannot access the gist repo (due to the token being changed for example).

You are able to add instructions to the top of the .json via a comment block.

**Comment by massimocode** [comment]
@shanalikhan  I've fixed this here... https://github.com/shanalikhan/code-settings-sync/pull/54

**Comment by shanalikhan** [comment]
@massimocode The user is now bound to use "esc" in order to close the input bar, i have refined the code more.
@QuietusPlus i have added new command , have a look :)

[v1.6.0](https://github.com/shanalikhan/code-settings-sync/releases/tag/v1.6.0) is released.

I am closing this issue, feel free to re open this if found any problem
