### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by LouisChang0520** [shanalikhan/code-settings-sync#536]
**Visual Studio Code Version :** [ 1.22.2 ]
**Code Settings Sync Version :** [ 2.9.0 ]
**Operating System :** [ window 10 ]
**Occurs On:** [Upload / Download / Help Configuring ]
**Proxy Enabled:** [  No ]
**GIst Id:** [ code-settings-sync]

I have posted frequently asked questions on 
http://shanalikhan.github.io/2016/11/07/visual-studio-code-frequently-asked-questions.html 
so you may able to resolve the error quickly. 
Please make sure to write the versions and console logged error picture or copied text

It's not work
``
private onDidNotificationChange(e: INotificationChangeEvent): void {
		if (e.kind === NotificationChangeType.ADD) {

			// ARIA alert for screen readers
			this.ariaAlert(e.item);

			// Always log errors to console with full details
			if (e.item.severity === Severity.Error) {
				console.error(toErrorMessage(e.item.message.value, true));
			}
		}
	}

**Comment by shanalikhan** [comment]
any steps to reproduce / any console logs

**Comment by LouisChang0520** [comment]
picture
https://drive.google.com/drive/folders/19_nRE7gxI3aX06U561ihd5Fvd1U2Ub3V?usp=sharing

**Comment by shanalikhan** [comment]
try with latest version

**Comment by LouisChang0520** [comment]
Sorry,its the same error
error picture:
https://drive.google.com/open?id=19_nRE7gxI3aX06U561ihd5Fvd1U2Ub3V

**Comment by shanalikhan** [comment]
this is because you have invalid token entered from github.
Add valid token from github in configurations, it will be solved.
