### ISSUE TITLE
No apparent error but nothing gets sync'ed with new Electron 2

### ISSUE THREAD

**Issue by carlocardella** [shanalikhan/code-settings-sync#537]
**Visual Studio Code Version :** 
Version 1.23.0-exploration
Commit 5e0fbe54562b6291114d1219f8bf5bbcb77af1b1
Date 2018-04-24T05:58:08.964Z
Shell 2.0.0-beta.7
Renderer 61.0.3163.100
Node 8.9.3
Architecture x64

**Code Settings Sync Version :** 
2.9.0

**Operating System :** 
OS Name: Microsoft Windows 10 Enterprise
OS Version: 10.0.16299 N/A Build 16299

**Occurs On:**
Download

**Proxy Enabled:**
No

I am testing VSCode [Exploration](https://github.com/Microsoft/vscode/issues/45542) and I noticed I can't sync my settings and extensions, both with existing gist (created with a working vscode and sync extension) and a brand new one. 
It seems extensions are supposed to work without changes with the new Electron (https://github.com/Microsoft/vscode/issues/48615), This problem is not a blocker for now but it may become one when VSCode will move to Electron 2.x.

**Comment by shanalikhan** [comment]
Thanks, will look into it.

Can you share the exception logged in console by extension ??

**Comment by carlocardella** [comment]
I did some more tests and it seems the upload is not happening: I see the Gist last modified time gets updated but I don't see the updated content. 
The Gist was creates successfully the very first time (right after I installed vscode-exploration and the Sync extension).

The Output (extensions) console in vscode is empty, this is the Developer Tools console output
[exploration_syncupload.log](https://github.com/shanalikhan/code-settings-sync/files/1979992/exploration_syncupload.log)

**Comment by shanalikhan** [comment]
Its working, closing this issue.
