### ISSUE TITLE
`autoUpload` uses excessive CPU

### ISSUE THREAD

**Issue by erikphansen** [shanalikhan/code-settings-sync#538]
**Visual Studio Code Version :** 1.22.2
**Code Settings Sync Version :** 2.9.0
**Operating System :** macOS 10.13.4
**Occurs On:** idle
**Proxy Enabled:** No
**GIst Id:** b1664b14813bd4d6c882e6cfcb260a58

When `autoUpload` is turned on Activity Monitor shows a Code Helper process constantly using ~7% of a CPU core on a late-2013 15" MBP. Disabling the extension or simply setting `autoUpload` to `false` remedies the situation.

**Comment by ryenus** [comment]
Exactly this, but ~10% idle CPU usage on MBP 2015, 
I just wish I can cast more upvotes more than just 1. It's easy to upvote, but not so easy to identify this extension is the culprit out of all other extensions.

Visual Studio Code Version : `1.24`
Code Settings Sync Version : `2.9.2`
Operating System : macOS `10.13.4`

**Disabling the extension or simply setting `autoUpload` to `false` remedies the situation.**

**Comment by ryenus** [comment]
@shanalikhan any chance to shed some love, for a greener earth? thanks!

**Comment by Deukhoofd** [comment]
Possibly related to [this](https://github.com/paulmillr/chokidar/issues/597) issue with chokidar.

**Comment by shanalikhan** [comment]
Im using `chokidar` at the moment for checking the file change and i think its related to that package.

For now, you can disable the auto upload for fix this.
This is pretty low priority for me as many other items are opened.
Or May anyone can evaluate or send me PR to improve it if you see any.

**Comment by erikphansen** [comment]
Thanks for chiming in @shanalikhan

**Comment by shanalikhan** [comment]
As this is beyond the extensions scope. I am going to close this issue.
Feel free to discuss.
