### ISSUE TITLE
Cannot Download settings with 2.9.1

### ISSUE THREAD

**Issue by pungggi** [shanalikhan/code-settings-sync#540]
**Visual Studio Code Version :** 1.22.2
**Code Settings Sync Version :** 2.9.1
**Operating System :** Windows 8.1
**Occurs On:** Download
**Proxy Enabled:** No
**GIst Id:** f2c89b48376033703694b0a9ec6558b0

I setup a new environment (VSC) and started with this extensions and then tried to download my existing gist configuration.

It downloaded all except my extensions...

All with a similar error like the following... SyntaxError: Unexpected token u in JSON at position 0

mainThreadExtensionService.ts:44 SyntaxError: Unexpected token u in JSON at position 0
	at JSON.parse (<anonymous>)
	at ReadFileContext.callback (C:\Users\giuseppe\.vscode\extensions\Shan.code-settings-sync-2.9.1\out\src\service\pluginService.js:91:35)
	at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:359:13)

**Comment by rvaidya** [comment]
If I look inside the temp folder where the extension has been downloaded, the path names seem to be messed up.  There are no subfolders, and the folder names are all joined by underscores.

Example:

Location: C:\Users\Rahul\AppData\Local\Temp\11841-18196-59qpyt.txxrn
Filename: extension_node_modules_ajv_.tonic_example.js

**Comment by shanalikhan** [comment]
Thanks, Looking into it.

**Comment by wasupwithuman** [comment]
I am having the same issue, with failed downloading.

**Comment by joakimhew** [comment]
For anyone who needs to be able to synchronise while @shanalikhan is working on a fix I recommend just using the previous version, this is what I did. 

To do this simply edit your vscode settings and add `"extensions.autoUpdate": false`, download the VSIX file from release 2.9.0 https://github.com/shanalikhan/code-settings-sync/releases/tag/v2.9.0 and install in vscode by running the following command: ´Extensions: Install from VSIX...´

**Comment by balexandre** [comment]
@joakimhew works like a charm, thxs...

for those wondering how to install the `vsix` file, [here's how](https://stackoverflow.com/a/38866913/28004) :)

**Comment by alexamy** [comment]
Had the same problem with 2.9.1. 2.9.0 works ok.

**Comment by shanalikhan** [comment]
Fixed - Published v2.9.2
let me know if there is any error.

Issue opened for package that caused this issue - https://github.com/cthackers/adm-zip/issues/221
Updating adm-zip caused this.
