### ISSUE TITLE
Support Settings per OS

### ISSUE THREAD

**Issue by augustocdias** [shanalikhan/code-settings-sync#546]
Some settings are not present in different platforms and some have different values between them. I think it would be beneficial to have a per OS settings file.

**Comment by shanalikhan** [comment]
Whats the real scenario, post details

**Comment by shanalikhan** [comment]
you can use `replaceCodeSettings` in each of the OS, when settings will be downloaded - replaceCodeSettings will always replace that JDK setting

**Comment by augustocdias** [comment]
It partially solves the problem, because this file is not synced, right?

**Comment by shanalikhan** [comment]
See the replaceCodeSettings example here

https://medium.com/@itsShanKhan/visual-studio-code-settings-sync-configurations-ed8dd6fd9753
