### ISSUE TITLE
Settings not uploaded after installing/removing extensions

### ISSUE THREAD

**Issue by floatingpurr** [shanalikhan/code-settings-sync#548]
**Visual Studio Code Version :** 1.23.0
**Code Settings Sync Version :** 2.9.2
**Operating System :** MacOS High Sierra
**Occurs On:** Download of new extensions
**Proxy Enabled:** No

When I install/remove new extensions, the remote gist is not updated despite `"sync.syncExtensions": true`.

My settings:

```JSON

"sync.autoDownload": true,
"sync.autoUpload": true,
"sync.lastDownload": "2018-05-07T10:45:15.267Z",
"sync.forceDownload": false,
"sync.askGistName": false,
"sync.quietSync": false,
"sync.removeExtensions": true,
"sync.syncExtensions": true,
"sync.host": "",
"sync.pathPrefix": "",
```

**Comment by shanalikhan** [comment]
Its limitation from code api level
When they allow this i will make a part if this extension

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by floatingpurr** [comment]
Got it, thanks!
