### ISSUE TITLE
"message":"Bad credentials","documentation_url":"https://developer.github.com/v3"

### ISSUE THREAD

**Issue by Lutreer** [shanalikhan/code-settings-sync#55]
**Visual Studio Code Version :** [ 1.3.1]
**Code Sync Settings Version :** [ 1.5.0]
**Operating System :** [ win 8]

![20160801104138](https://cloud.githubusercontent.com/assets/8281336/17282089/a2d4cab8-57d4-11e6-9373-179e0788a386.png)

can't upload setting

**Comment by Lutreer** [comment]
I fixed it

1. `F1`
2. enter `sync` -> select `sync:reset sync settings`
3. `shift + alt + u` -> enter your `access token`

So,the old `access token` (maybe you have deleted or modified) leads to this problem.

**Comment by shanalikhan** [comment]
Great :)
