### ISSUE TITLE
Unable to uninstall extensions

### ISSUE THREAD

**Issue by Andreas-Ntonas** [shanalikhan/code-settings-sync#558]
**Describe the bug**
After installing code-settings-sync I am unable to uninstall other extensions of my Windows machine. I am unable to uninstall even the code-settings-sync. It is stuck in uninstalling. Moreover after installing the plugin there is no confirmation when I click uninstall on a plugin like before. I tried reinstalling Vscode and deleting the extensions and appdata related to vscode in C, but the issue persists. In my other Ubuntu machine the plugin works fine. The issue persists even if I not configure code-settings-sync to sync with gist.

**Visual Studio Code Version :** [1.23.1]
**Code Settings Sync Version :** [2.9.2]
Version 1.23.1
Commit d0182c3417d225529c6d5ad24b7572815d0de9ac
Date 2018-05-10T17:11:17.614Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

**Operating System :** [ Windows 10]
**Occurs On:** [Upload / Download / Help Configuring ]
**Proxy Enabled:** [ No ]
**Gist Id:** [ 601054d628ea88fd466e96bcc95cce7e] (doesn't matter)

**To Reproduce**
1. Install code-settings-sync
2. Install any other plugin
3. Reopen Vscode
4. Try to uninstall the other plugin or code-settings-sync itself
5. Indefenetly wait for uninstall.
6. Nothing happens

![capture](https://user-images.githubusercontent.com/29986185/40495781-d018c10e-5f80-11e8-9ac3-e8867ba18bd3.PNG)

**Comment by shanalikhan** [comment]
This is not due to settings sync.
Try removing the code
Removing settings folder and reinstalling
