### ISSUE TITLE
Is code-settings-sync supposed to install other extensions automatically?

### ISSUE THREAD

**Issue by blueray453** [shanalikhan/code-settings-sync#559]
Earlier I was using `Settings Sync` on windows 10. Now I shifted to Ubuntu 18.04

1, I Installed VSCode
2. Installed code-settings-sync 
3. Gave Github Token & GistID

It downloaded the settings but saying `Sync: No Extensions Needs to Be Installed`

And Gives the following output

```
CODE SETTINGS SYNC DOWNLOAD SUMMARY
Version: 2.9.2
--------------------
GitHub Token: <Private>
GitHub Gist: <Private>
GitHub Gist Type: Secret

Restarting Visual Studio Code may be required to apply color and file icon theme.
--------------------
Files Downloaded:

  Extensions Removed:
  No extensions removed.

Extensions Added:
  No extensions installed.
--------------------
Done.
```
NOTE: I replaced my Token & Gist ID with `<Private>`

However, it preserves the list of extensions I used to use. What is going on here?

**Comment by shanalikhan** [comment]
Do you have extension uploaded in the GIST ?
Yes settings sync install all extensions

**Comment by peterfication** [comment]
For me it also only downloads the settings but does not install anything. In my Gist I see the extensions though.
