### ISSUE TITLE
Downloading settings doesn't work

### ISSUE THREAD

**Issue by lukas2005** [shanalikhan/code-settings-sync#561]
**Describe the bug**
Downloading settings doesn't work

**Visual Studio Code Version :** 1.23.1
**Code Settings Sync Version :** 2.9.2
**Operating System :** Windows 10
**Occurs On:** [Download]
**Proxy Enabled:** [ No ]
**Gist Id:** [ 0b0003b24840806e7fdd801a07e7d18f ]

**To Reproduce**
1. Upload settings
2. Download settings
3. Open devtools (F1 and type "Toggle developer tools")

**Console Error Log**
![image](https://user-images.githubusercontent.com/13919176/40887969-c160560e-6750-11e8-8769-b636c8bf5978.png)

**Comment by shanalikhan** [comment]
This might be due to network.
Try on other network

**Comment by lukas2005** [comment]
? What I have internet

**Comment by shanalikhan** [comment]
i meant try on other internet, from home , office etc

**Comment by immigrantsheep** [comment]
I have the same issue. Upload works fine from one machine. But when I try Sync Download from another (on the same network), nothing happens.

**Comment by johnf9896** [comment]
It's happening to me too. I tried on two different computers and on two different networks. Uploading settings works fine.
![image](https://user-images.githubusercontent.com/12222295/42413260-53095e1a-81e2-11e8-9c95-1aac0959222f.png)

**Comment by shanalikhan** [comment]
Its due to your network settings.
I am closing this and marking this as duplicate 
Need to use code custom CLI to let code extension itself rather then using current systems.

**Comment by shanalikhan** [comment]
Duplicate of #566
