### ISSUE TITLE
'Downloading' uninstalled all my extensions!

### ISSUE THREAD

**Issue by ortonomy** [shanalikhan/code-settings-sync#563]
**Describe the bug**
I tried to sync on my laptop, but instead of installing extensions it uninstalled all my extensions and won't download and install.

**Visual Studio Code Version :** Version 1.23.1 (1.23.1)
**Code Settings Sync Version :** 2.9.2
**Operating System :** Mac OS High Sierra 10.13.5 (17F77)
**Occurs On:** Download
**Proxy Enabled:** No
**Gist Id:** 5f524548da5368b37e5b866ada13d9b4

**To Reproduce**
1. enter personal key
2. enter gist id
3. try to download

**Expected behavior**
I should get all my extensions!

**Console Error Log**
```
CODE SETTINGS SYNC DOWNLOAD SUMMARY
Version: 2.9.2
--------------------
GitHub Token: [redacted]
GitHub Gist: 5f524548da5368b37e5b866ada13d9b4
GitHub Gist Type: Secret

Restarting Visual Studio Code may be required to apply color and file icon theme.
--------------------
Files Downloaded:

  Extensions Removed:
  vscode-eslint v1.4.12

Extensions Added:
  No extensions installed.
--------------------
Done.
```

**Comment by shanalikhan** [comment]
I think the gist was created by this extension
https://marketplace.visualstudio.com/items?itemName=nonoroazoro.syncing#user-content-vscode-user-settings

Try to upload the settings once again in that gist and then download

**Comment by ortonomy** [comment]
D'oh! that is so confusing. Imagine two extensions do exactly the same thing using exactly the same mechanism...

**Comment by shanalikhan** [comment]
Yea i also wanted one extension but that extension owner wanted to create own extension rather them improving this project 😄 

So users have to guess the GIST
