### ISSUE TITLE
Extensions sync could lead to corrupted extensions

### ISSUE THREAD

**Issue by sandy081** [shanalikhan/code-settings-sync#566]
Re - https://github.com/Microsoft/vscode/issues/50976

I see that, this extension, to synchronise extensions, is installing extensions by itself. There are following issues with this

- Extension might miss the necessary metadata what VS Code might expect
- Extension might not be installed correctly as I see there are no precautions to make sure that extension installation is complete.
- It will miss all checks the system takes while getting into the system

All this could end up user having a corrupted extension.

I would recommend to go through the system to install an extension. I know that there is no programmatic API but why not use the CLI to install?

**Comment by ckihneman** [comment]
Confirmed. This is the same as #560 as well. Here is my case.

- Setup new computer, synced to the new computer, all seemed to have ran fine, I can see all the extensions on the extensions screen
- Create new JS file, add code to it, go to format it with Prettier "Format Document", _nothing happens_
- Extension is in fact installed
- Disable the plugin, enable the plugin, try again, not working
- Uninstall the plugin, reinstall the plugin, try again, not working...

Still not working, go more nuclear...

- Uninstall the plugin
- **Quit** VS Code, reopen
- Do fresh install of Prettier (`sophisticode.php-formatter`)
- Press "Reload" after installing
- Open JS file, :boom: "Format Document" works

I went through the same process to confirm with `wix.vscode-import-cost` too, as it also was not working in my JS files. Something about quitting VS Code after uninstalling allows the extension to be installed properly on the next pass.

It is worth noting that many of my extensions do in fact appear to be working, like `coenraads.bracket-pair-colorizer` and `oderwat.indent-rainbow`. So I suppose I'll figure out which plugins are and are not working as I go.

**Comment by sandy081** [comment]
@shanalikhan Can you please provide your opinion on the recommended suggestion.

Thaks

**Comment by shanalikhan** [comment]
Yes @sandy081 you are right.
We already had discussion for better sync support on https://github.com/Microsoft/vscode/issues/14444 and https://github.com/Microsoft/vscode/issues/15466

yes i understand the better way is to either use CLI or from the API.

Would you please guide about the roadmap for code when the extension installation API will be available.

**Comment by sandy081** [comment]
I am sorry to say that there are no plans yet to support the requested API. But, after going through the above two mentioned issues in VS Code, I felt that this issue is independent of the API you requested for.

I see that you want to move to CLI way of installing extensions as you mentioned [here](https://github.com/Microsoft/vscode/issues/14444#issuecomment-303185970). 

So can you please use CLI for installing extensions otherwise this extension might cause users to install corrupted extensions which is not good.

Thanks.

**Comment by shanalikhan** [comment]
Currently extension version is v2.9.2.
I will release v2.9.3 this week.

This feature will be a part of v3.0.0.
I cannot give you the exact schedule but will work on it and release it in month or 2. 
Or you can just send me PR and i will release newer version sooner. ( i can assist if you are willing to help )

**Comment by shanalikhan** [comment]
I have implemented CLI based installation and testing on Windows and Linux.
Dont have Mac Environment to test - I am currently waiting for some users to test the branch on Mac.
Else i will directly have to push on the main place and solve the issues after publishing if anything suspicious thing happened on Mac.

**Comment by shanalikhan** [comment]
This has been fixed as part of `v3.1.0`
Have a look.
there might be some problems for Mac users, i am waiting for PR as i dont have Mac environment and tested in Windows and Linux.
