### ISSUE TITLE
The sync of scaling ratio of vscode

### ISSUE THREAD

**Issue by ShaoyuanLi** [shanalikhan/code-settings-sync#569]
**Describe the bug**
The setting sync synchronize the vscode's scaling ratio which always is inappropriate.In my opnion,setting sync should synchronize plug-ins and keymap instead of scaling ratio.

**Visual Studio Code Version :** [ 1.23.1 ]
**Code Settings Sync Version :** [ 2.9.2]
**Operating System :** [ Windows 10.0.17134 ]
**Occurs On:** [Upload & Download]
**Proxy Enabled:** [ No ]
**Gist Id:** [ 831d44230b794cdc1a50a49a39b75121]

**To Reproduce**
1. In one PC with 26in monitor,upload setting
2. In other PC with 15in monitor(my laptop),download setting
3. The scaling ratio in latter PC is too large

**Expected behavior**
I think setting sync shouldn't synchronize scaling ratio or scaling ratio sync would be a option.

**Comment by shanalikhan** [comment]
try to exclude settings with ignore code settings.
Read post here.
https://medium.com/@itsShanKhan/visual-studio-code-settings-sync-configurations-ed8dd6fd9753

**Comment by ShaoyuanLi** [comment]
Thanks for your help
