### ISSUE TITLE
Cannot Upload settings

### ISSUE THREAD

**Issue by nZeus** [shanalikhan/code-settings-sync#57]
**Visual Studio Code Version :** 1.3.1
**Code Sync Settings Version :** 1.6.3
**Operating System :** Win10

![image](https://cloud.githubusercontent.com/assets/2727326/17364287/9daeadae-597f-11e6-8948-3c17343744a5.png)

**Comment by shanalikhan** [comment]
Have you tried this on other network.
Please reset the settings and try on other network and update :)
