### ISSUE TITLE
Setting to disable opening of github page

### ISSUE THREAD

**Issue by wolf99** [shanalikhan/code-settings-sync#576]
**Is your feature request related to a problem? Please describe.**
when uploading or downloading settings (for the first time), the extension shows the text box to enter the token, but then always opens the GitHub page in the my web browser. This can be quite annoying when it is not wanted.

**Describe the solution you'd like**
A setting to disable the opening of the GitHub web page when asking for a token or gist ID

**Comment by shanalikhan** [comment]
Released in v3.0.0

See the custom settings
