### ISSUE TITLE
Sync don't work

### ISSUE THREAD

**Issue by tiger-regit** [shanalikhan/code-settings-sync#578]
First, I confirm that the gist token c is configured according to the documentation and checked that it is correct. > sync advanced options > edit extension local settings See that the token is the configured value. But I have been unable to upload the configuration to gist.

When I upload with option + shift + U, I get the following prompt

first prompt
![image](https://user-images.githubusercontent.com/6560524/42303280-cb1453d8-8052-11e8-9e76-9d1b884fddea.png)

second prompt
![image](https://user-images.githubusercontent.com/6560524/42303274-c520d276-8052-11e8-9982-ba20f9c32b0a.png)

dev tools error log
![image](https://user-images.githubusercontent.com/6560524/42303435-d4b44564-8053-11e8-82c3-3020e072dc54.png)

**Comment by zelljhos** [comment]
I have the same problem, i using VScode last version, i made a clean intalation of VScode and even so the extension do not work.

**Comment by shanalikhan** [comment]
In next version, i will be updating the Github API. Hope they will fix all these issues.
Currently Github API has older version.

**Comment by shanalikhan** [comment]
This has been fixed.
Have a look.

let me know, i will reopen this issue.
