### ISSUE TITLE
Extension download failed.ERROR !

### ISSUE THREAD

**Issue by theoxuan** [shanalikhan/code-settings-sync#58]
**Visual Studio Code Version :** 1.3.1 
**Code Sync Settings Version :**  1.6.3
**Operating System :** Windows 10 x64

![image](https://cloud.githubusercontent.com/assets/5442563/17442786/1d05c61e-5b6a-11e6-9818-95c2f330815b.png)

![image](https://cloud.githubusercontent.com/assets/5442563/17442858/5c92a09a-5b6a-11e6-8621-8daf61973e9a.png)

**Comment by shanalikhan** [comment]
There must be some connection problem between your PC and market place at the time of downloading extension 
U can delete that folder from extension folder and start the process again and le me know if it appeara again

**Comment by theoxuan** [comment]
Yes it seems to be a connection loss.
I synced other 2 devices and never reproduced this issue.
