### ISSUE TITLE
Where to change GitHub Token?

### ISSUE THREAD

**Issue by Cookiewookie87** [shanalikhan/code-settings-sync#580]
I have entered wrong token. Is there any option to change it? Whenever i predd SHIFT+ALT+D it says:
Sync : Invalid / Expired GitHub Token. Please generate new token with scopes mentioned in readme. Exception Logged in Console.

I know it is wrong and i do not want to generate new one because i allready have one. How to change it? Please help

**Comment by Sciroccogti** [comment]
Sorry but I think that this method should be **highlighted** in the *README*, instead of being hidden in the *Global Settings*, because I really spent several miniutes to find how to change the token. Thanks~
