### ISSUE TITLE
got any plan for i18n?

### ISSUE THREAD

**Issue by axetroy** [shanalikhan/code-settings-sync#581]
If you want it too, I will happy to PR. first to support `english` and `chinese`

**Comment by shanalikhan** [comment]
Yes feel free, add more languages in PR if you can and let me know- Will release in v2.9.3

**Comment by shanalikhan** [comment]
Released in v3.0.0

Let me know if there is any issue

**Comment by linsui** [comment]
"Sync: Download Complete" hasn't be supported

**Comment by axetroy** [comment]
@linsui

Thank you for reminding me.

This is my fault, I missed two translations.

https://github.com/shanalikhan/code-settings-sync/blob/58fd111ff6e1e812b55e2bfb1f252ed36acda200/src/extension.ts#L467

https://github.com/shanalikhan/code-settings-sync/blob/58fd111ff6e1e812b55e2bfb1f252ed36acda200/src/extension.ts#L484

I will do a PR as fast as possible
