### ISSUE TITLE
Code snippets does not sync?

### ISSUE THREAD

**Issue by Cookiewookie87** [shanalikhan/code-settings-sync#583]
I have some code snippets in VS Code. I have made them through this tutorial:
https://code.visualstudio.com/docs/editor/userdefinedsnippets

But when i go on other PC, and run Sync, snippets are not there. Am i doing something wrong?

**Comment by shanalikhan** [comment]
Settings sync support sync.
whats in your settings sync custom settings ?
share your gist id

**Comment by GabrielGlo** [comment]
I have the same problem. Initially html code snippets file has synced when I  first synced on the new machine. Later not - no matter of force update from source machine and then the same on destination machine. HTML code snippets on destination machine still in its initial empty state.
