### ISSUE TITLE
Not Found

### ISSUE THREAD

**Issue by R2dical** [shanalikhan/code-settings-sync#59]
Visual Studio Code Version : 1.4.0
Code Sync Settings Version : 1.6.3
Operating System : Windows 10

When running command Sync: Download Settings:

```
[Extension Host] Windows_NT
[Extension Host] {"message":"Not Found","documentation_url":"https://developer.github.com/v3"}
ERROR ! Logged In Console (Help menu > Toggle Developer Tools). Please open an issue in Github Repo using 'Sync : Open Issue' command.
```

**Comment by shanalikhan** [comment]
this is due to invalid gist ID. please reset the settings by sync reset settings command and then again try to download. also look GIST is already created in your github account
