### ISSUE TITLE
Should tslint or prettier be used to unify the code style?

### ISSUE THREAD

**Issue by axetroy** [shanalikhan/code-settings-sync#590]
I am trying to contribute code to the project.

But I found that the code styles of several people are different, which leads to messy after the project.

E.g:

1.  Use let instead of var
2.  Use const to define a variable if it is not reassigned

So I consider whether to introduce `tslint` or `prettier` to keep the style of the project unified.

I highly recommend using `tslint`, which is more mandatory.

If you want to loosen some, use prettier to automatically format the code before commit

I would be happy to PR if you think this is necessary.

**Comment by shanalikhan** [comment]
Great idea of prettier and tslint
Feel free to send me PR.
