### ISSUE TITLE
Deply current folder, does not respect exclude setting

### ISSUE THREAD

**Issue by strongui** [shanalikhan/code-settings-sync#592]
**Describe the bug**
In my settings.json file I have something like this: 
```
"exclude": [
                    ".DS_Store",
                    ".git",
                    ".vscode",
                    "shared/assets/node_modules/"
                ],
```
When I am at the root of my folder structure, and then do deploye current file /folder, it starts comiting everything, even if inside the folder I have a shared/assets/node_modules folder. 

**Visual Studio Code Version :** 1.25.0
**Code Settings Sync Version :** 14.0.0
**Operating System :** Windows 10
**Occurs On:** Upload
**Proxy Enabled:** No
**Gist Id:** [ ID_HERE ]

**To Reproduce**
Do deploy on root folder of project

**Expected behavior**
Should upload all files/folders expect those in the exclude settings

**Comment by shanalikhan** [comment]
As far i have understand.
You want to upload the files *both in `shared` and `shared\assets`* except `node_modules` inside assets folder.
Right ?

**Comment by strongui** [comment]
@shanalikhan 
Yep exactly, so for a given folder structure like this:

_- project_ <-- Deploy current folder
**--.git** <-- Should not be deployed, but its currently
--shared
---assets
**---node_modules** <-- Should not be deployed, but its currently
--home
---index.html
--about_us
---about_us.html
--robots.txt

When I

**Comment by shanalikhan** [comment]
Whats the scenario for which you need to put the project in `User` folder for VS Code.
Looks like you are trying to make backup for Code Projects by placing the Project folder insides `Users` folder.

**Comment by strongui** [comment]
@shanalikhan Hm not sure what Users folder you're talking about, but the general scenario is this.

I have an FTP server that I sync all my files to. That is to say, on every file save, sync uploads the file via FTP. So far so good.

However, when I do mass edit of files, let's say I edit/save 20 files at once it will try to deploy 20xs and inevitably it will fail, so only 4 files or so are deployed.

So now, my folder is out of sync. I could try to painfully find every file, and edit it manually again to trigger upload, but that is just tedious. Instead, I'd like to just deploy the root folder, and have it upload everything except the exclusions to my server.

**Comment by shanalikhan** [comment]
> In my settings.json file I have something like this: 

it looks like this is your project settings.json file not the visual studio code settings file.

Settings Sync will only sync the vs code configurations that is in the folder

`AppData\Roaming\Code\User`

**Comment by strongui** [comment]
@shanalikhan Hm I am not sure I'm following. I have many project folders.
Project_1, Project_2, Project_3 etc.

Inside every project folder I have a folder **.vscode** and inside every .vscode folder I have a settings.json file. Example:
```

{
    "deploy": {
        "showPopupOnSuccess": false,
        "packages": [
            {
                "name": "Version 2.3.4",
                "description": "Package version 2.3.4",
                "files": [
                    "./**/*.vm"
                ],
                "exclude": [
                    ".DS_Store",
                    ".git",
                    ".vscode",
                    "shared/assets/node_modules/"
                ],
                "deployOnSave": true,
                "useTargetList": true,
                "targets": [
                    "My WEBDAV"
                ]
            }
        ],
        "targets": [
            {
                "type": "ftp",
                "name": "Beta FTP",
                "description": "Root Project_1 Folder",
                "dir": "/",
                "host": "my.server.com",
                "port": 2221,
                "secure": false,
                "user": "username",
                "password": "****"
            }
        ]
    }
}
```

Every project needs a custom settings.json file, because the servers are different, that I need to upload to. Maybe, I'm missing something, and what I need is already supported? But I don't think I need to put the deploy settings into the core VS Code settings, as that would make them global.

**Comment by shanalikhan** [comment]
> Inside every project folder I have a folder .vscode and inside every .vscode 

Settings Sync dont upload / download your project files.
It sync code configurations.

**Comment by strongui** [comment]
@shanalikhan lol I just noticed I posted this in the wrong place ... I mean to post this here: https://github.com/mkloubert/vs-deploy/issues

I also use Settings Sync, and it works perfectly! Carry on!
