### ISSUE TITLE
setting export functionality

### ISSUE THREAD

**Issue by zzzgit** [shanalikhan/code-settings-sync#596]
**Is your feature request related to a problem? Please describe.**
I want to export my vs-code settings to a file.

**Describe the solution you'd like**
Sometimes github.com is banned by the network manager, I can't sync the settings to cloud, so I want to export settings to a locale file.
Is it possible? 

**Describe alternatives you've considered**
.

**Additional context**
.

**Comment by shanalikhan** [comment]
Duplicate of #256
