### ISSUE TITLE
Cross platform synchro problem

### ISSUE THREAD

**Issue by DavidBabel** [shanalikhan/code-settings-sync#599]
Unable to sync a Macbook pro with a windows 10

**Visual Studio Code Version :** both 1.25.1
**Code Settings Sync Version :** 3.0.0
**Operating System :** MacOs Sierra / Windows 10
**Occurs On:** Download
**Proxy Enabled:** No 
**Gist Id:** https://gist.github.com/DavidBabel/4fdb80cd9efd3e711734c3f037b084c2

**To Reproduce**
1. On a mac, i used vscode for years
2. I setup code settings sync, and upload successfully to gist
3. I setup a brand new windows 10 vscode install with the same gist
4. Extensions installs, but no snippets or settings.json is downloaded/replaced

**Expected behavior**
The vscode windows 10 files are replaced by the gist ones

Any hint is welcome.

**Comment by DavidBabel** [comment]
i guess it finally sync but take a very long time and provocate a local conflict to resolve. Did not really understand all this all works

**Comment by kmthorsnes** [comment]
I have the same problem

**Comment by shanalikhan** [comment]
> i guess it finally sync but take a very long time and provocate a local conflict to resolve
Make sure you close the `setting.json` or all the files that are inside `Users` folder.
