### ISSUE TITLE
Incorrect path for Code/User on Linux

### ISSUE THREAD

**Issue by jpambrun** [shanalikhan/code-settings-sync#6]
The path in [extension.ts:29-35](https://github.com/shanalikhan1/code-settings-sync/blob/fd17142e22ccc482e8005eb7d367da2a1ea46a50/src/extension.ts#L29) for Linux is incorrect. It resolves to /var/local/Code/User/ which doesn't exist. I believe ~/.Code/User is the correct path.

**Comment by shanalikhan1** [comment]
i dont have linux right now so im unable to test or develop on other then Windows.
but i will accept the pull request if you can do it for linux :)

**Comment by jpambrun** [comment]
I understand. Your extension is actually one of the very first things I tried with vscode. I might revisit this later, but I am not ready to invest time to learn extension development for an editor that I might not end up using. 

I just wanted to share my findings so it could help others. I really appreciate your initiative and I feel that this is a very important feature. Thanks for the good work ;)

**Comment by shanalikhan** [comment]
@jpambrun im closing this issue if you found problem in linux and let me know
