### ISSUE TITLE
Extension is not working behind a proxy

### ISSUE THREAD

**Issue by npenin** [shanalikhan/code-settings-sync#60]
**Visual Studio Code Version :** [ 1.4 ]
**Code Sync Settings Version :** [ last on 2016-08-08 ]
**Operating System :** [ Windows 7 ]

```
Error: getaddrinfo ENOTFOUND api.github.com api.github.com:443
    at global.sendError (C:\Users\peninni2\.vscode\extensions\Shan.code-settings-sync-1.6.3\node_modules\github4\lib\index.js:753:19)
    at C:\Users\peninni2\.vscode\extensions\Shan.code-settings-sync-1.6.3\node_modules\github4\lib\index.js:762:29
    at callCallback (C:\Users\peninni2\.vscode\extensions\Shan.code-settings-sync-1.6.3\node_modules\github4\lib\index.js:639:17)
    at ClientRequest.<anonymous> (C:\Users\peninni2\.vscode\extensions\Shan.code-settings-sync-1.6.3\node_modules\github4\lib\index.js:710:17)
    at emitOne (events.js:90:13)
    at ClientRequest.emit (events.js:182:7)
    at TLSSocket.socketErrorListener (_http_client.js:295:9)
    at emitOne (events.js:90:13)
    at TLSSocket.emit (events.js:182:7)
    at connectErrorNT (net.js:996:8)
```

**Comment by shanalikhan** [comment]
yes there is some problem working in proxy i am already acknowledged of. You can debug and change the code and send me a pull request, i'll be more happy to accept that- as i tried few things before and was unable to test.

**Comment by shanalikhan** [comment]
@npenin i have changed the dependency package.
can you test if its working ?

**Comment by npenin** [comment]
It is still not working. Please tell me how I can help.

**Comment by shanalikhan** [comment]
I cant test in proxy environment as i dont have one. you can download the code and run the folder from visual studio code and test it out manually and send me pull request, i will be more happy to accept that

**Comment by piggyslasher** [comment]
Hello - could you please provide a way we could manually sync by copy pasting this file? Gist doesn't work behind proxy.

**Comment by nonoroazoro** [comment]
Hi @shanalikhan, to solve this problem, just add proxy into options when you create node-github instance, like:
`new GitHubApi({
    proxy: "http://127.0.0.1:1080" // ss proxy for example.
})`

I've tested in my syncing ext and it worked well. Hope this would help!

**Comment by shanalikhan** [comment]
@nonoroazoro thanks for suggesting, i will do it

**Comment by nonoroazoro** [comment]
@shanalikhan :smile: 
It seems that this only solve the Gist proxy issue, but yes you can also use `https-proxy-agent` with `https` module to solve the same problem in your `Util.HttpPostJson` function :smiley: 

Here's an example:
```javascript
var https = require("https");
var HttpsProxyAgent = require("https-proxy-agent");
var proxy = "http://127.0.0.1:1080";
var agent = new HttpsProxyAgent(proxy);

// then add this agent into your options file like:
var options: https.RequestOptions = {
    host: item.hostname,
    port: +item.port,
    path: item.path,
    method: 'POST',
    headers: newHeader,
    agent: agent
};
```

I found this solution here [reference](http://codingmiles.com/node-js-making-https-request-via-proxy/).

**Comment by kwaxi** [comment]
You could e.g. use Fiddler (http://www.telerik.com/fiddler) to setup a test environment for proxy. This way could can even look which requests where sent to the proxy.

**Comment by nonoroazoro** [comment]
@kwaxi  It's a nice idea. In fact, I took some time to write another sync extension (called `Syncing`)... with proxy supported. :smiling_imp: 
I've tested it in my win 7 system, but don't have time to test in Linux/Mac yet...

**Comment by shanalikhan** [comment]
@nonoroazoro Great to know you are working also. You can send me a pull request rather than developing new extension :)  i will be more happy to accept that.

Or provides issues list due to which you have decided to develop new extension (from this Update)

**Comment by nonoroazoro** [comment]
@shanalikhan I'm sorry for that. I mean no offense, just wanna do some practice... :), and thanks a lot for your great work, it did help me a lot.

**Comment by piggyslasher** [comment]
@nonoroazoro - can you please make a PR? Pull-request. Help the community :)

**Comment by nonoroazoro** [comment]
@piggyslasher  I'm sorry but `Syncing` is a completely new one, can't make any PR...

**Comment by piggyslasher** [comment]
PR made here :) https://github.com/shanalikhan/code-settings-sync/pull/124

@nonoroazoro Cool.

**Comment by shanalikhan** [comment]
@piggyslasher i have accepted the request but as mentioned by @nonoroazoro there is another file that needs to be configured to make it fully proxy enabled . `Util.HttpPostJson` - i will check using fiddler

**Comment by shanalikhan** [comment]
i have just commited the patch supporting proxy.
There is some problem in using fiddler for proxy

Can anyone please download the code from the repo and test on proxy server and let me know so i will push the update in store.

**Comment by shanalikhan** [comment]
I have published the 2.3.4 version with proxy support.

**Comment by evil-shrike** [comment]
On the latest v2.3.8 proxy settings are still synchronized!

**Comment by shanalikhan** [comment]
@evil-shrike yes but some users still reports proxy support not fully integrated at https://github.com/shanalikhan/code-settings-sync/issues/135

**Comment by evil-shrike** [comment]
@shanalikhan  not sure I understand. Is it possible to exclude proxy settings from synchronization?

**Comment by shanalikhan** [comment]
Actually i reference the issue in which users are unable to download the extension behind proxy and i was unable to reproduce the issue from my side (#135)

Anyway No, for now its not possible to exclude proxy settings from synchronization process- i closed that issue https://github.com/shanalikhan/code-settings-sync/issues/100 time ago, i think by adding proxy support again and again , this feature should be added to ignore some settings from sync process.

**Comment by Stibbons** [comment]
I works if you define the http_proxy as user environment variable in windows (something like `http://username:password@proxyip:port`), so your settings can easily be shared

**Comment by Stibbons** [comment]
opened a ticket about current proxy limitation #463

**Comment by jxltom** [comment]
I my ubuntu 16.04, I set ```export HTTP_PROXY=http:127.0.0.1:port``` and ```export HTTPS_PROXY=https:127.0.0.1:port``` and settings sync will show no internet connection...

I am using version 2.9.0 with vscode insider version 1.20.0-insider

**Comment by TYZRPVX** [comment]
problem not solved ?
