### ISSUE TITLE
Errors right after the extension installation

### ISSUE THREAD

**Issue by BurstX** [shanalikhan/code-settings-sync#606]
**Describe the bug**
After the installation of the extension in VSCode and getting the token, the first synchronization via Ctrl+Shift+U produces errors in VSCode. No gist with the settings is created in GitHub

**Visual Studio Code Version :** 1.25.1
**Code Settings Sync Version :** 3.0.0
**Operating System :** Windows 10 Pro, Version 1803, OS build 17134.165
**Occurs On:** Upload
**Proxy Enabled:** not sure
**Gist Id:** n/a

**To Reproduce**
1. Install the extension in VSCode (the settings-sync extension has never been installed before).
1. Reload VSCode.
1. Go to github.com, create a new token for settings-sync.
1. In VSCode, press Ctrl+Shift+U - the default browser opens a github.com page with the tokens.
1. Close the github.com page from the previous step.
1. In VSCode, again press Ctrl+Shift+U, I see the error messages
![image](https://user-images.githubusercontent.com/3790231/43675202-d9c73d48-97e8-11e8-9f03-78d478970859.png)

**Expected behavior**
Not sure what to expect, I didn't get further than the step ["Upload Your Settings For the first time"](https://github.com/shanalikhan/code-settings-sync#upload-your-settings-for-the-first-time) to sync the current VSCode instance's settings for the first time to a gist in my GitHub account.

**Console Error Log**
![2018-08-04 13_17_27-microsoft edge](https://user-images.githubusercontent.com/3790231/43675208-f5e885b8-97e8-11e8-9449-a672b2cae4fd.png)

Same log exported from Console: [-1533377829480.log](https://github.com/shanalikhan/code-settings-sync/files/2259422/-1533377829480.log)

**Comment by shanalikhan** [comment]
I have tried, its working for my side.
Can you try again

**Comment by shanalikhan** [comment]
Duplicate of  #321
