### ISSUE TITLE
Command 'extension.downloadSettings' not found

### ISSUE THREAD

**Issue by bspeice** [shanalikhan/code-settings-sync#617]
🐛 **Describe the bug**  
Potentially not flatpak-related, but when installing to Linux via [flatpak](https://flathub.org/apps/details/com.visualstudio.code), commands aren't registered properly on start.

🌴 **Visual Studio Code Version :** 1.26.1
🌴 **Code Settings Sync Version :** 3.0.0
🌴 **Operating System :** Linux Mint 19
🌴 **Occurs On:** Download
🌴 **Proxy Enabled:** No
🌴 **Gist Id:** N/A

📰 **To Reproduce**
1. Install sync extension
2. Attempt to download
3. Receive error

💪 **Expected behavior**
Command to be called

📺 **Console Error Log** 
![screenshot from 2018-08-25 15-46-43](https://user-images.githubusercontent.com/1199853/44621987-16671480-a87e-11e8-8f5a-a2575b06991b.png)

📺  **Additional context**
Installed via flatpak rather than standard deb/etc., not sure if related.

**Comment by shanalikhan** [comment]
It works for standard version.
I havent tried using flatpak.

try using standard version. if have problem. feel free to report, i will reopen issue.
