### ISSUE TITLE
 Error: native promise missing on Download Settings

### ISSUE THREAD

**Issue by pravic** [shanalikhan/code-settings-sync#619]
🐛 **Describe the bug**  
There is an error during "Download Settings" which is shown via notification message:

> notificationsAlerts.ts:41 Sync : Error Logged In Console

Meta:

🌴 **Visual Studio Code Version :** 1.26.1
🌴 **Code Settings Sync Version :** 3.1.0
🌴 **Operating System :** Windows 7 x64
🌴 **Occurs On:** Download
🌴 **Proxy Enabled:** No
🌴 **Gist Id:** [ ID_HERE ]

📰 **To Reproduce**

0. Update the extension to the newest version (3.1.0)
1. Command Palette: "Sync: Download Settings"
2. See the error

💪 **Expected behavior**

Without an error?

📺 **Console Error Log** 

```
[Extension Host] Error: native promise missing, set fetch.Promise to your favorite alternative
	at fetch (%USERPROFILE%\.vscode\extensions\shan.code-settings-sync-3.1.0\node_modules\node-fetch\lib\index.js:1313:9)
	at request (%USERPROFILE%\.vscode\extensions\shan.code-settings-sync-3.1.0\node_modules\@octokit\rest\lib\request\request.js:42:10)
	at restRequest (%USERPROFILE%\.vscode\extensions\shan.code-settings-sync-3.1.0\node_modules\@octokit\rest\lib\request\index.js:8:10)
	at %USERPROFILE%\.vscode\extensions\shan.code-settings-sync-3.1.0\node_modules\before-after-hook\lib\register.js:38:12
	at <anonymous>
```

📺  **Additional context**

Upd: The same for Upload.

**Comment by shanalikhan** [comment]
I have updated the extension, Reset extension Settings can you uninstall the extension, reload code - install extension

**Comment by pravic** [comment]
I am not sure about all of these steps, but the new version (3.1.1) works without errors now.
So I guess that I don't have to reset its settings.

**Comment by mcintyrechris** [comment]
I am getting this error on 3.1.2, can we reopen this? I reset everything, reinstalled VSCODE, etc.

**Comment by Timbioz** [comment]
Same error. Ver - 3.1.2 Clean installation and new clean Windows

**Comment by n3r0bi0m4n** [comment]
Same, insiders 1.29.0
