### ISSUE TITLE
[Bug] Not Syncing

### ISSUE THREAD

**Issue by tympapost** [shanalikhan/code-settings-sync#62]
**Visual Studio Code Version :** [ 1.4.0]
**Code Sync Settings Version :** [ 1.6.3]
**Operating System :** [ Windows 10 w/ Anniversary Update ]

I set up my Gist ID and Token OK, but every time I try to download I get only this message:
![capture](https://cloud.githubusercontent.com/assets/6545650/17529168/f301f9e6-5e7a-11e6-9af2-e0e544d85a51.JPG)
And everything else halts.
I've let it for some time, but nothing happens.
I tried:
- Restarting VS Code
- Uninstalling extension/ Deleting settings files / Re-installing

**Comment by shanalikhan** [comment]
what is your VS Code user folder structure how many files are there , and which files are in snippet folder ?

**Comment by tympapost** [comment]
You mean from the "upload" pc right? Not the one I'm trying to sync...
I can send you that info when I get to work, where my "uploaded" settings are.

**Comment by tympapost** [comment]
I'm at the "upload" pc and the user folder seems plain and simple. The whole folder with subfolders is 2.1KB in size. To show the structure I've taken some screenshots:
![sync1](https://cloud.githubusercontent.com/assets/6545650/17544616/13041290-5ee1-11e6-843d-490d23e51af0.jpg)
![sync2](https://cloud.githubusercontent.com/assets/6545650/17544618/1706a36c-5ee1-11e6-9500-716e1d7b1b97.jpg)
![sync3](https://cloud.githubusercontent.com/assets/6545650/17544624/1b948af2-5ee1-11e6-99b4-cfcca9f76662.jpg)

All the subfolders under workspaceStorage have a single meta.json file in them, 1KB each.

And for reference, these are my extensions:
![sync5](https://cloud.githubusercontent.com/assets/6545650/17544701/8c2a62be-5ee1-11e6-858c-adff45038d67.jpg)

**Comment by shanalikhan** [comment]
what is your GIST ID ?

**Comment by tympapost** [comment]
It's 6545650

**Comment by shanalikhan** [comment]
Thanks, please dont remove GIST so i will test it, i'm really busy in other works and also working on automatic syncing in free time. Will look into it and let you know

**Comment by shanalikhan** [comment]
can you try again by deleting the other extensions and installing the extension, deleting the user setting file for this extension. Please update

**Comment by tympapost** [comment]
Sorry for the delay, I'm on vacation. I followed the steps you provided but the result was the same.
![capture](https://cloud.githubusercontent.com/assets/6545650/18030476/b084dda6-6cbf-11e6-8dab-e1ae050899f7.JPG)

I can see you've gone ahead and closed this issue. Am I the only one facing this? I can see other people facing sync issues by browsing Github Issues.

**Comment by shanalikhan** [comment]
I have reopened the issue, actually your problem is different to others. Their problem is regarding whole sync is not working.
Please keep that GIST alive, i will work on it and let you know.

**Comment by shanalikhan** [comment]
Whats you gist ID?
im trying to open this URL https://gist.github.com/tympapost/6545650 as per your GIST ID but it doesnt open.

**Comment by tympapost** [comment]
I haven't changed my Gist ID or anything else on github for that matter.
Does this help?
https://gist.github.com/anonymous/6545650

**Comment by shanalikhan** [comment]
Why are you using anonymous Gist ? i dont see edit option in the page to edit that Gist. Are you able to edit the gist online from link, might be you created it ?

**Comment by tympapost** [comment]
I'm sorry, but I don't get what you're saying. 
Is the Sync extension supposed to create the gists? I am not using gists in any other way.
I'm only providing a link I found working. No, I have no option of editing that anonymous gist.

**Comment by shanalikhan** [comment]
U should have go through how to configure. Yes the extension create the GIST and give u ID to put files.

Anonymous gist cant be edited by user so it wont be edited by extension also...
Please go the read me and let me know if it resolve the problem

**Comment by tympapost** [comment]
I've read your instructions thoroughly during my attempts to solve this issue.
I've followed the steps over and over again in order to solve this. No luck.
Was I supposed to create a Gist and give that ID to the extension? That is nowhere to be found in the readme file.

**Comment by shanalikhan** [comment]
Lets start from the start.
Reset the extension settings.

Just Hit the upload command , it will ask the TOKEN ( your github account token) and will generate the GIST with your account token and pop up the ID of that gist which will contains all the settings.

When you download , it will ask for token and GIST ID that was generated during the upload , when you insert that ID it will download the settings.

As i dont see the GIST for your account. 
My GIST : https://gist.github.com/shanalikhan/dcb47ff12b7782d6011c3f63d77fc512
that is created by extension using upload command.

The gist you have provided was created anonymously , so it wont be able to edit or update by the github or extension...

**Comment by tympapost** [comment]
Aha! I found the problem. This:

> ...and will generate the GIST with your account token and pop up the ID of that gist which will contains all the settings.

isn't happening... the "pop up" part that is.
So the problem is at the upload side. I had to manually browse through my Gists to find the correct ID and provide it to the extension. This time it worked. Can you see/edit this?
https://gist.github.com/tympapost/3716dd0e88bd104c580732fcb517a4c4

**Comment by shanalikhan** [comment]
i will check it out the information message about the new GIST, so can you download the settings in other computer using this GIST, its working ?

**Comment by tympapost** [comment]
It's not, that was my issue. 
I will test this again using other pcs to upload, but I won't be able to test until next week when I get back from vacation.
I will report here if the issue was only found at that computer or not.

**Comment by shanalikhan** [comment]
you can also test in this computer by , opening the extension settings from VSCode , remove the GIST value from the JSON file making gist value to "" ( empty ) OR null.
and take a backup of VS settings, removing the installed extensions.
and hit the download process , it will ask GIST ID from you , paste that ID and let it download the all the settings and extensions....

Happy Holidays ! :+1:  :)

**Comment by tympapost** [comment]
I don't know if it's the new updates or something else, but this issue is now fixed. My work pc now shows the Gist ID and we even get a nice text document with the upload summary.
You can close this issue. 
Thanks!
