### ISSUE TITLE
Upload Fails : "cannot read property filename of null"

### ISSUE THREAD

**Issue by pzelnip** [shanalikhan/code-settings-sync#622]
🐛 **Describe the bug**  

Can't sync settings.  When picking "Sync Update/Upload Settings", I get a toast notification saying "Sync : Error Logged In Console (Help menu > Toggle Developer Tools)."

Looking at dev tools, I see the screenshot shown below

🌴 **Visual Studio Code Version :** Version 1.26.1 (1.26.1)
🌴 **Code Settings Sync Version :** 3.1.0
🌴 **Operating System :** OSX Sierra (10.12.6 (16G1510))
🌴 **Occurs On:** Upload
🌴 **Proxy Enabled:** ???

📰 **To Reproduce**
1. Open command pallette
2. Pick "Sync Update/Upload Settings"

💪 **Expected behavior**

It should upload successfully.

📺 **Console Error Log** 
If applicable, add screenshots or paste the console log from developer console of VSCode.

![screen shot 2018-08-27 at 3 05 42 pm](https://user-images.githubusercontent.com/414933/44688995-dc774900-aa0a-11e8-9f8d-a832f43497ee.png)

📺  **Additional context**

This previously was working fine, I've been using this extension for some time now.

**Comment by goodjack** [comment]
Same issue here

![2018-08-28 10 48 07](https://user-images.githubusercontent.com/1116129/44697809-10587a00-aab0-11e8-8c19-123c2385064b.png)

**Comment by shanalikhan** [comment]
v3.1.1 released.

Please report.

**Comment by pzelnip** [comment]
Yup, seems to be fixed for me as well.  TYVM!

**Comment by beck** [comment]
Just installed, getting this error. Maybe a regression?

<img width="1390" alt="screen shot 2019-01-02 at 4 38 43 pm" src="https://user-images.githubusercontent.com/154988/50613866-1242a780-0ead-11e9-9685-825570af816f.png">

**Comment by shanalikhan** [comment]
@beck This issue was fixed.
Please open new issue with the reproducing steps with the folder file image and structure.
