### ISSUE TITLE
Unknown configuration settings

### ISSUE THREAD

**Issue by tcelestino** [shanalikhan/code-settings-sync#625]
🐛 **Describe the bug** 
The settings flags `sync.lastUpload` and `sync.lastDownload`are as unknown and VSCode show me with warning on Output.

🌴 **Visual Studio Code Version :** 1.26.1
🌴 **Code Settings Sync Version :** 3.1.0
🌴 **Operating System :** Ubuntu 18.04
🌴 **Occurs On:**  Help Configuring 
🌴 **Proxy Enabled:** No
🌴 **Gist Id:** 61176c032c3bf7fcd98782b8f7572a69

📺 **Console Error Log** 
![image](https://user-images.githubusercontent.com/190265/44787913-e4e89480-ab6e-11e8-912f-f0540a5c862d.png)

**Comment by shanalikhan** [comment]
Its safe to remove this configurations.
