### ISSUE TITLE
Prompt to reload VSCode after installing extensions

### ISSUE THREAD

**Issue by borekb** [shanalikhan/code-settings-sync#629]
As discussed in https://github.com/shanalikhan/code-settings-sync/issues/618#issuecomment-417201279, it would be useful to prompt the user to reload VSCode after extensions are installed by the sync process.

Right now, the output window just tells that some extensions were successfully installed but they are not visible in the Extensions sidebar.

**Comment by shanalikhan** [comment]
Besides giving a prompt everytime to restart the code to keep streamline with automation.
A key can be added in global settings as `autoRestart` when changed to `true` code will always restart upon downloading.
`false` will be a default.

**Comment by borekb** [comment]
I think that VSCode's approach with its own updates is correct: do not restart automatically but notify the user to do so. I'd probably prefer this behavior for your extension as well.

**Comment by shanalikhan** [comment]
Fixed in v3.2
let me know if there is any problem
