### ISSUE TITLE
Request: Ability to administrate a settings (Be the only one that is allowed to push)

### ISSUE THREAD

**Issue by MLefebvreICO** [shanalikhan/code-settings-sync#63]
**Visual Studio Code Version :** 1.5.0-insiders
**Code Sync Settings Version :** (None, right now ... waiting for this implementation)
**Operating System :** Windows 10 x64

As the title mention it, I would like to be able to use this extension to create a sync between all the vscodes where I work and be the only one that can manage these settings (be the only person that is allowed to push).

**Comment by shanalikhan** [comment]
Yes implementation is in process which will automatically upload and download the latest settings across the latest changed VS Code Instance on VS Code Start.

Would you please elaborate Administrate a setting meaning as github token once saved, will save the settings on your behalf, on what feature or purpose you need for Administrate setting.

**Comment by MLefebvreICO** [comment]
This is not what I want.

Basically, what I want is an extension that can save my plugins, settings and all to a repo from my vscode instance to the others instances in the company I work. I want a system where only I can push settings, extensions, etc.. and others can only fetch it on vscode start.

Would that be possible ?

**Comment by shanalikhan** [comment]
Yes, seems ligit.

Yes its possible, but i'm currently working in the automatic syncing process. Will work on it after that or you can send me a pull request :gem:

**Comment by shanalikhan** [comment]
I have just released 2.2 version with this version.
I will publish a post with complete detail about how to do such tasks tomorrow.

Meanwhile you may explore and let me know of any enhancements...
