### ISSUE TITLE
Doesn't sync extensions when downloading

### ISSUE THREAD

**Issue by dan-dr** [shanalikhan/code-settings-sync#630]
🐛 **Describe the bug**  
I'm trying to sync my settings into a new machine running Solus Linux, and it doesn't install extensions

🌴 **Visual Studio Code Version :** 1.26.1
🌴 **Code Settings Sync Version :** 3.1.1
🌴 **Operating System :** Solus Linux 3.999999
🌴 **Occurs On:** Download
🌴 **Proxy Enabled:** No
🌴 **Gist Id:** 7a12c5b24bac1bd8b819763382969963

📰 **To Reproduce**
Do everything according to the guide. Try to download and sync settings.

💪 **Expected behavior**
All extensions should download and update. You can see them in the gist, but I get No extensions installed.

📺 **Console Error Log** 
No console errors

📺  **Additional context**
the user settings *are* synced! it's only the extensions that don't.

```
Files Downloaded:
  extensions.json > extensions.json
  keybindings.json > keybindings.json
  locale.json > locale.json
  settings.json > settings.json

Extensions Ignored:
  No extensions ignored.

Extensions Removed:
  No extensions removed.

Extensions Added:
  No extensions installed.
--------------------
Done.
```

**Comment by shanalikhan** [comment]
what is the console log while downloading.
Open developer log from help menu from code.
Clear console, hit sync download and paste the screen shot

**Comment by shanalikhan** [comment]
oss isnt supported
Any PR would be welcome
