### ISSUE TITLE
After sync setting, the extensions didn't install

### ISSUE THREAD

**Issue by Rukeith** [shanalikhan/code-settings-sync#633]
🐛 **Describe the bug**  
After I set up my token and gist with code-setting-sync. My extensions didn't install. Then I execute force download. The info show up the setting is already latest version. But extensions still not install

🌴 **Visual Studio Code Version :** [ 1.26.1 ] 
🌴 **Code Settings Sync Version :** [ 3.1.2 ] 
🌴 **Operating System :** [ macOS 10.13.6 ] 
🌴 **Occurs On:** [ Download  ]
🌴 **Proxy Enabled:** [ No ]
🌴 **Gist Id:** [ c5d0a61fb1fd7d111dc43d0f99a17d87 ]

**Comment by shanalikhan** [comment]
are you using code insiders or standard version

**Comment by Rukeith** [comment]
@shanalikhan I used standard version.
I fix that while I reinstall vscode.
