### ISSUE TITLE
vscodium download settings fails

### ISSUE THREAD

**Issue by PhE** [shanalikhan/code-settings-sync#650]
🐛 **Describe the bug**  
Download settings fails on [vscodium](https://github.com/VSCodium/vscodium) build of vscode.

🌴 **Visual Studio Code Version :** N/A
🌴 **vscodium Code Version :** 1.27.2
🌴 **Code Settings Sync Version :** 3.1.2
🌴 **Operating System :** ubuntu 18.04
🌴 **Occurs On:** Download
🌴 **Proxy Enabled:** No
🌴 **Gist Id:** 3a130beb45a528a4d017d789e529891d

📰 **To Reproduce**
1. Install vscodium
2. Install code-settings-sync via the market place
3. reload vscodium
4. Shift + Alt + D

The following notification appears : 
![image](https://user-images.githubusercontent.com/1107924/45740395-7a6ac780-bbf5-11e8-9467-427e586b2699.png)

💪 **Expected behavior**
I expect the same behaviour as in VS code.

📺 **Console Error Log** 
The developer tools console shows :
![image](https://user-images.githubusercontent.com/1107924/45739775-04199580-bbf4-11e8-84aa-14275be16b05.png)

**Comment by shanalikhan** [comment]
> Download settings fails on vscodium build of vscode.

Settings sync doesnt support it at the moment.

**Comment by shanalikhan** [comment]
v3.2 is released with this feature.
@PhE can you verify ?

**Comment by kemelzaidan** [comment]
I'm having the same problem here but a workaround this bug is easy. Where does settings sync expect to find a `code` executable? That being said, it's just a matter of creating the right symbolic link pointing to the vscodium binary...

**Comment by alexandrupetrini** [comment]
Hi guys,
I fixed this issue on Linux (Ubunut 18.10) by making this symlink:

`ln -s /usr/bin/vscodium ~/bin/vscodium`

Turns  out there are some path issues in vscodium. Be sure that you have 'bin' folder in your home folder and that it is added to PATH.
