### ISSUE TITLE
Project Manager projects list is not synchronized

### ISSUE THREAD

**Issue by focussing** [shanalikhan/code-settings-sync#653]
🐛 **Describe the bug**  
I use the Project Manager extension. When synchronizing the projects list is not synchronized.
This file is located in the $HOME/Library/Application Support/Code/User/ directory.

I have a large list on my Macbook which I want to use on my iMac as well.

Basically I need to have a identical setup of my VSCODE environment on both machines.

🌴 **Visual Studio Code Version : 1.27.2
🌴 **Code Settings Sync Version : 3.1.2
🌴 **Operating System : Mac High Sierra
🌴 **Occurs On: Download
🌴 **Proxy Enabled: No

**Comment by shanalikhan** [comment]
See https://github.com/shanalikhan/code-settings-sync#global-settings

ignoreUploadFiles , ignoreUploadFolders keys.
you need to setup properly.

**Comment by focussing** [comment]
Well, I expected and honestly think that synchronising an extension must also synchronise the data (files/folders/settings) of that extension.
The synchronised counterpart would not be exactly the same as the original if it doesn't.
Otherwise it makes no sense at all to sync because one cannot rely on it. I have strong doubts whether I can rely on my iMac system!

The user should not need to care about which files/folders/settings belong to an extension and which ones should be synced or shouldn't be synced.
(Often there is even no documentation about what files belong to an extension as well.)

**Comment by focussing** [comment]
Hi @shanalikhan, good point, that makes sense! 👍 

1) Maybe you can add an explanation in the documentation in the Global Settings ignoreUploadFiles part which files are for what extension?

2) What does the 'workspaceStorage' do?

**Comment by focussing** [comment]
Found another issue;
On one computer I have settings set to true: Auto Download and Auto Upload.
I upload the settings.
On the second computer I download the settings.
The settings Auto Download and Auto Upload are NOT synchronized!

**Comment by shanalikhan** [comment]
> Maybe you can add an explanation in the documentation in the Global Settings ignoreUploadFiles part which files are for what extension?

Public WIKI Edit is enabled, If you want feel free to create new page with these details.

> The settings Auto Download and Auto Upload are NOT synchronized!
Auto upload and download is facing problem at the moment. Check other issues

**Comment by focussing** [comment]
OK hope issues are solved soon.

Question: is there an overview about which folders and files are synchronised?
