### ISSUE TITLE
Folder workspaceStorage is not synchronized

### ISSUE THREAD

**Issue by focussing** [shanalikhan/code-settings-sync#654]
🐛 Describe the bug
When synchronizing the workspaceStorage is not synchronized
This folder is located in the $HOME/Library/Application Support/Code/User/ directory.

Basically I need to have a identical setup of my VSCODE environment on both machines.

🌴 **Visual Studio Code Version : 1.27.2
🌴 **Code Settings Sync Version : 3.1.2
🌴 **Operating System : Mac High Sierra
🌴 **Occurs On: Download
🌴 **Proxy Enabled: No

**Comment by focussing** [comment]
Update; the Project Manager has a setting "alternate storage location" for the projects.json file. This setting is synchronized by code-settings-sync 👍 
However I was wondering why the whole "user" directory is not sychronized... ?

**Comment by shanalikhan** [comment]
It does.
There are certain files for some extensions it doenst sync
Read the global settings `ignoreUploadFiles` key here to see your extension config file.
https://github.com/shanalikhan/code-settings-sync#global-settings

**Comment by focussing** [comment]
Well, I expected and honestly think that synchronising an extension must also synchronise the data (files/folders/settings) of that extension.
The synchronised counterpart would not be exactly the same as the original if it doesn't.
Otherwise it makes no sense at all to sync because one cannot rely on it. I have strong doubts whether I can rely on my iMac system!

The user should not need to care about which files/folders/settings belong to an extension and which ones should be synced or shouldn't be synced.
(Often there is even no documentation about what files belong to an extension as well.)
