### ISSUE TITLE
Long startup activation time on the first start

### ISSUE THREAD

**Issue by alexdevero** [shanalikhan/code-settings-sync#656]
🐛 **Describe the bug**  
It takes significant amount of time to start the extension on first, fresh start of VS Code. This occurs only on the first start in the day. This leads to "Extension runner is unresponsive" error notification in VS Code. Any consequent startup activation time is at least 10x faster, ~950ms.

🌴 **Visual Studio Code Version :**  1.28.0-insider (system setup)
Commit: 2558a72d6902015b142ef45c57b664ce1f09e03f
🌴 **Code Settings Sync Version :** 3.1.2
🌴 **Operating System :** Win 10 Home (1803)
🌴 **Occurs On:** Start of VS Code
🌴 **Proxy Enabled:** No

📰 **To Reproduce**
1. Start fresh VS Code.
2. Open Running Extensions
3. Find Settings Sync
4. See error from VS Code

💪 **Expected behavior**
The first startup activation time should be similar to the consequent (~950ms).

📺 **Console Error Log** 
First start:
![settings-sync](https://user-images.githubusercontent.com/4237724/45872852-5512c080-bd91-11e8-8973-dea8f4be4166.PNG)

Second start:
![settings-sync-2](https://user-images.githubusercontent.com/4237724/45873303-5f818a00-bd92-11e8-8682-8d5336392a2f.PNG)

**Comment by shanalikhan** [comment]
Actually code is the same on first and second startup ...

What is really affecting the time might be the Visual Studio Code extension host.
Can you verify does it happens every time ~25900ms on the _first startup of day_ ?

**Comment by alexdevero** [comment]
So far, I tested this three times and always with positive results -> ~25900ms.

**Comment by hibas123** [comment]
I can confirm this issue.

**Comment by shanalikhan** [comment]
This issue is available for bounty. Fix and earn!

**Comment by shanalikhan** [comment]
@alexdevero this issue is fixed.
