### ISSUE TITLE
not work with vscode-portable

### ISSUE THREAD

**Issue by CyrilTaylor** [shanalikhan/code-settings-sync#658]
🐛 **Describe the bug**  
not work with [vscode-portable](https://github.com/myfreeer/vscode-portable)

🌴 **Visual Studio Code Version :** All 
🌴 **Code Settings Sync Version :** All
🌴 **Operating System :** Win10
🌴 **Occurs On:** [Upload / Download  ]
🌴 **Proxy Enabled:** [ No ]
🌴 **Gist Id:**

**Comment by shanalikhan** [comment]
Duplicate of #331
