### ISSUE TITLE
Unknown configuration setting on openning VSCode Settings

### ISSUE THREAD

**Issue by mtxr** [shanalikhan/code-settings-sync#659]
🐛 **Describe the bug**  
![image](https://user-images.githubusercontent.com/707561/45964530-762b1980-bffc-11e8-889f-d4383f6c97bf.png)

🌴 **Visual Studio Code Version :** Insiders but it happens to any version
🌴 **Code Settings Sync Version :** 3.1.2
🌴 **Operating System :** Ubuntu 16.04 
🌴 **Occurs On:** Open settings
🌴 **Proxy Enabled:** Irrelevant
🌴 **Gist Id:** Irrelevant

📰 **To Reproduce**
Just open VSCode settings

💪 **Expected behavior**
Lastupload and lastDownload settings should be elsewhere but not in settings or be defined as a valid setting.

**Comment by shanalikhan** [comment]
Its safe to remove those settings.
