### ISSUE TITLE
Uploading broken in 1.29 Insiders

### ISSUE THREAD

**Issue by Nxt3** [shanalikhan/code-settings-sync#669]
🐛 **Describe the bug**  
Updating/Uploading my settings doesn't work on 1.29 Insiders.

🌴 **Visual Studio Code Version :** 1.29-Insiders
🌴 **Code Settings Sync Version :** 3.1.2
🌴 **Operating System :** macOS 10.13.6
🌴 **Occurs On:** Upload
🌴 **Proxy Enabled:** No

📰 **To Reproduce**
1. Attempt to Upload settings

💪 **Expected behavior**
Upload success

📺 **Console Error Log** 
<img width="1728" alt="screen shot 2018-10-08 at 3 14 04 pm" src="https://user-images.githubusercontent.com/2940826/46628801-d8137500-cb0c-11e8-86c5-a2a0bbd4b439.png">

**Comment by tmknight** [comment]
There were other issues with recent versions of insiders that seem to have been resolved, including this one, with the 2018-10-09 release.

Version: 1.29.0-insider (system setup)
Commit: 5bd6ebe2dbc4dee510699020a25f70a69784ce8c
Date: 2018-10-09T09:31:07.090Z
Electron: 2.0.11
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

**Comment by Nxt3** [comment]
Yep, updating to 10/9 Insiders has fixed it.

**Comment by shanalikhan** [comment]
Sweet :smile:
