### ISSUE TITLE
Can Revert back to previous Version?

### ISSUE THREAD

**Issue by UTexas80** [shanalikhan/code-settings-sync#677]
Hello, 
Is there anyway to revert back to a previous sync version. If not that would be a great feature request.
Thank you.

**Comment by emptyother** [comment]
Should probably be a feature request for the vscode team instead. Being able to install a specific version of a vscode plugin. Being used to npm, i kinda expected this to work (it didn't):

    code --install-extension Shan.code-settings-sync@3.1.1 --force

**Comment by shanalikhan** [comment]
@UTexas80 report in code repo to allow extensions to install previous extensions.
But if you set `autoupdate` to `false` and then upload the gist, Settings Sync will take care and download the version specific extensions.

**Comment by emptyother** [comment]
Btw, it is possible. [Download the *.vsix from here](https://github.com/shanalikhan/code-settings-sync/releases). Open up code and select "Install from VSIX" (in the action panel). Answer yes to replace the new with the old.

**Comment by MiLeung** [comment]
How do you revert to a previous version of your settings? I accidentally uploaded blank settings.

**Comment by shanalikhan** [comment]
>I accidentally uploaded blank settings.

We can revert to previous version of extension. But if you want to revert your settings to older version. You need to check the revisions from the Gist Page inside github.

To Support Settings Sync to revert to older revision , there is already issue opened. #413
