### ISSUE TITLE
Error: Cannot read property 'token' of undefined

### ISSUE THREAD

**Issue by songxianpeng** [shanalikhan/code-settings-sync#685]
🐛 **Error: Cannot read property 'token' of undefined**  
tips occurred when I use advanced options menu or upload menu. I have tried to reinstall or set a git  but not work.

![image](https://user-images.githubusercontent.com/9303424/47131446-3b519400-d2d1-11e8-915b-da2fb17deff9.png)

![image](https://user-images.githubusercontent.com/9303424/47131468-5de3ad00-d2d1-11e8-9307-81f36b019bf1.png)

🌴 **Visual Studio Code Version :**
🌴 **Code Settings Sync Version :** [3.2.0]
🌴 **Standard or Insiders :** [standard]
🌴 **OSS or Portable :** [ _here_ ] 
🌴 **Operating System :** [windows 10 1803 ]
🌴 **Occurs On:** [Upload /  Help Configuring ]
🌴 **Proxy Enabled:** [  No ]
🌴 **Gist Id:** [ none ]

📺 **Console Error Log** 

![image](https://user-images.githubusercontent.com/9303424/47131386-fcbbd980-d2d0-11e8-9bc9-df285955f499.png)

**Comment by shanalikhan** [comment]
Try `reset the Settings Sync settings`

**Comment by waiaan** [comment]
> Try `reset the Settings Sync settings`

 I deleted all the Sync settings in user settings , it does not work too.
thank you

**Comment by waiaan** [comment]
by the way , vscode is in portable mode

**Comment by shanalikhan** [comment]
what is the path for data folder and extension folder for portable code

**Comment by waiaan** [comment]
> what is the path for
> 
> 1. Code executable
> 2. User directory
> 3. Extensions directory

1.D:\VSCode
2.D:\VSCode\data\user-data
3.D:\VSCode\data\extensions

like this.

**Comment by CyrilTaylor** [comment]
> what is the path for
> 
> 1. Code executable
> 2. User directory
> 3. Extensions directory

Dear shanalikhan,

There is a bug about this issue.

diff --git a/src/environmentPath.ts b/src/environmentPath.ts
index 2230aab..b373ebd 100644
--- a/src/environmentPath.ts
+++ b/src/environmentPath.ts
@@ -79,7 +79,7 @@ export class Environment {
     }`;

     process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";
-    this.PATH = process.env.APPDATA;
+    this.PATH = this.isPortable ? process.env.VSCODE_PORTABLE : process.env.APPDATA;
     this.OsType = OsType.Windows;

     if (!this.PATH && !this.isPortable) {

I resolve it after rebuild.

**Comment by shanalikhan** [comment]
@CyrilTaylor Thanks, i have pushed the changes you have asked, window os is not handled properly.
Will release new version soon.

You can look into the commit here
https://github.com/shanalikhan/code-settings-sync/commit/7f1aacec381a2a57415e0b00fef5067a272155c3#diff-09ef59e49c66636eacf529be73517d36R108

**Comment by shanalikhan** [comment]
v3.2.1 released.
Please verify.
