### ISSUE TITLE
Github Enterprise - Support for different (base) gist url? 

### ISSUE THREAD

**Issue by mrkafk** [shanalikhan/code-settings-sync#688]
💡 **Is your feature request related to a problem? Please describe.**
I cannot use this extension with Github Enterprise version that obviously has different local hostname at the company.

💡 **Describe the solution you'd like**
Ability to set base Gist URL in settings, say `https://gist.github.ACME.com`, any way really, setting it manually in settings.json would be sufficient.

💡 **Additional context**
I'd be more than happy to test this modification where I work.

**Comment by shanalikhan** [comment]
Check the `Global Settings` from the readme that allows enterprise setup.

**Comment by kenime** [comment]
Just for a reference, you will need to put in the **enterprise github API url**, so for example your enterprise github url is `https://github.mycompany.com`, you should put in `https://api.github.mycompany.com`. Check with your enterprise github administrator if this default API url doesn't work.
