### ISSUE TITLE
Can't sync settings with error "Invalid / Expired GitHub Token."

### ISSUE THREAD

**Issue by levblanc** [shanalikhan/code-settings-sync#689]
I checked every related issue, but couldn't solve my problem.

I tried to regenerate my token several times, coupled with my gist id to download, got the error.

Also tried to generate new tokens several times, and then upload (or create a new gist), got the error. 

Really frustrated and don't know what to do.... I really need my settings.

Please please please help. 

---

MacOS: 10.11.6 (EI Capitan)
VS Code : 1.28.2 (freshly reinstall today)
Settings Sync: 3.2.0

VS Code keep telling me today that it can't update, so I decided to reinstall it. 

Before reinstalling, I upload my settings to:

[https://gist.github.com/levblanc/ec97529308d0ecf93ffc253f721bcad5](https://gist.github.com/levblanc/ec97529308d0ecf93ffc253f721bcad5)
(secret gist, named as cloudSettings, no problems in sync before)

After reinstall, I regenerate my token: 

![image](https://user-images.githubusercontent.com/4057887/47277197-28e89a80-d5f0-11e8-8173-f13c967333ab.png)

my token setting:

![image](https://user-images.githubusercontent.com/4057887/47277212-56354880-d5f0-11e8-9e42-152732e78465.png)

my gist id setting: 
![image](https://user-images.githubusercontent.com/4057887/47277218-6e0ccc80-d5f0-11e8-84a1-3535131f0267.png)

got the error and there is nothing logged in the debug console:
![image](https://user-images.githubusercontent.com/4057887/47277221-841a8d00-d5f0-11e8-8456-e0a871eff3b5.png)

**Comment by betsu** [comment]
me too +1

**Comment by OrangeDrangon** [comment]
+1 I just installed it today for the first time so not working on a completely fresh either

**Comment by shanalikhan** [comment]
https://github.com/shanalikhan/code-settings-sync/issues/321

https://github.com/shanalikhan/code-settings-sync/issues/388#issuecomment-404633809
https://github.com/shanalikhan/code-settings-sync/issues/408

**Comment by gwritz** [comment]
This is broken for me as well, none of the resolutions in #321, #388, or #408 have worked for me.

**Comment by shanalikhan** [comment]
you guys are also using Mac ?

**Comment by gwritz** [comment]
![screenshot from 2018-10-29 08-27-57](https://user-images.githubusercontent.com/4153449/47656452-b712d280-db54-11e8-8d2a-5cbbaf29ef5d.png)

**Comment by gwritz** [comment]
I am on Ubuntu 18.04.

**Comment by OrangeDrangon** [comment]
I am on Windows 10

**Comment by betsu** [comment]
I am on win 10

**Comment by cmario92** [comment]
windows 10 as well here

**Comment by JasonMFry** [comment]
Getting the same or similar issue on MacOS 10.14 VSCode 1.29.1.

I reset my settings, generated a new GitHub token, tried to upload settings (shift + alt + u) and got this error.

![image](https://user-images.githubusercontent.com/166681/49738060-72527f00-fc5c-11e8-8102-8409db86301c.png)

```
  | t.onDidNotificationChange | @ | notificationsAlerts.ts:40
-- | -- | -- | --
  | (anonymous) | @ | notificationsAlerts.ts:26
  | e.fire | @ | event.ts:145
  | t.notify | @ | notifications.ts:113
  | t.notify | @ | notificationService.ts:52
  | e._showMessage | @ | mainThreadMessageService.ts:83
  | e._showMessage | @ | mainThreadMessageService.ts:44
  | e.$showMessage | @ | mainThreadMessageService.ts:38
  | t._doInvokeHandler | @ | rpcProtocol.ts:439
  | t._invokeHandler | @ | rpcProtocol.ts:424
  | t._receiveRequest | @ | rpcProtocol.ts:341
  | t._receiveOneMessage | @ | rpcProtocol.ts:271
  | (anonymous) | @ | rpcProtocol.ts:146
  | e.fire | @ | event.ts:145
  | a | @ | ipc.net.ts:103
  | n._socketDataListener | @ | ipc.net.ts:132
  | emitOne | @ | events.js:116
  | emit | @ | events.js:211
  | addChunk | @ | _stream_readable.js:263
  | readableAddChunk | @ | _stream_readable.js:250
  | Readable.push | @ | _stream_readable.js:208
  | onread | @ | net.js:594
```

**Comment by EvangelosKolimitras** [comment]
@levblanc  _Solution to me:_ my friend
1st: Sync: Reset Extension Settings
2nd: Generated  
3rd: Paste the **generated token** into vscode by pressing {Ctrl+Shift+p > paste}
4th: Go to your user https://gist.github.com/{user_name}/{gitst_id} and copy the gist_id
5th:  Go to vscode and open settings.json file and add
```
"sync.gist": "36b8cd5c3cdb8d21ef865a1677647821",
"sync.autoDownload" : true
```

Restart vscode. 

Done!

Hope it helps!

**Comment by yourgotocoder** [comment]
> @levblanc _Solution to me:_ my friend
> 1st: Sync: Reset Extension Settings
> 2nd: Generate access token
> 3rd: Paste the **generated token** into vscode by pressing {Ctrl+Shift+p > paste}
> 4th: Go to your user [https://gist.github.com/{user_name}/{gitst_id}](https://gist.github.com/%7Buser_name%7D/%7Bgitst_id%7D) and copy the gist_id
> 5th: Go to vscode and open settings.json file and add
> 
> ```
> "sync.gist": "gist_id",
> "sync.autoDownload" : true
> ```
> 
> Restart vscode.
> 
> Done!
> 
> Hope it helps!

This worked for me . Thanks a ton!!

**Comment by seriiserii825** [comment]
> @levblanc _Solution to me:_ my friend
> 1st: Sync: Reset Extension Settings
> 2nd: Generate access token
> 3rd: Paste the **generated token** into vscode by pressing {Ctrl+Shift+p > paste}
> 4th: Go to your user [https://gist.github.com/{user_name}/{gitst_id}](https://gist.github.com/%7Buser_name%7D/%7Bgitst_id%7D) and copy the gist_id
> 5th: Go to vscode and open settings.json file and add
> 
> ```
> "sync.gist": "gist_id",
> "sync.autoDownload" : true
> ```
> 
> Restart vscode.
> 
> Done!
> 
> Hope it helps!

this is not a solution, but a instruction. 
The author, who create this question, already have a settings, and he want to come back it.

**Comment by swiftouch** [comment]
I "love" this extension. Its a brilliant disaster. Works fine on one device. Cant get it to work on the other. If MS would just make a built in official version that wasn't 3rd party and actually worked, we could all get back to being productive. ....Instead of spending countless hours browsing the DOZENS of github threads people have created over the years saying they have issues with this extension.

**Comment by Anas-Alhariri** [comment]
Just follow these steps:

![image](https://user-images.githubusercontent.com/48216683/119435385-ffcca100-bce7-11eb-88a4-04b0dd58e428.png)

Then reload your VS code it should take the token automatically. If it didn't, then try the following:

![image](https://user-images.githubusercontent.com/48216683/119435756-ccd6dd00-bce8-11eb-87ef-a353b2de79c9.png)


After you login into your GitHub account, it should work just fine.

Please let me know if this helped.

Thank you.

**Comment by robertmarriott** [comment]
The solution posted by @Anas-Alhariri works... sort of... It ends up discarding your existing gist and creating a new one. The ability to update your token -- something that's bound to come up now and again -- should not be buried several levels deep. As far as I can tell, nowhere in the official instructions or extension settings does it indicate how to do this, which IMHO is a serious UX issue.

**Comment by steffenu** [comment]
1. shift + alt + p
2. type "sync"
3.  look for reset extension settings
4. press shift + alt  + u 
5. you can login again

**Comment by yzhanggithub** [comment]
Thanks for the info. Besides the issue above, I also encountered another one with the same error. One of the extensions in the gist file can't be found and stopped the process, I ended up manually removing the entry from the gist file.
