### ISSUE TITLE
can not upload seetings

### ISSUE THREAD

**Issue by koaqiu** [shanalikhan/code-settings-sync#69]
**Visual Studio Code Version :** [ 1.5.0-insider ]
**Code Sync Settings Version :** [ 1.63]
**Operating System :** [ win 10 pro ]

Please make sure to write the versions and console logged error picture or copied text.
![default](https://cloud.githubusercontent.com/assets/542287/17838552/743682ee-6802-11e6-991e-b57a56b044c9.png)

**Comment by shanalikhan** [comment]
Possible duplicate of [#59](https://github.com/shanalikhan/code-settings-sync/issues/59).
Check the solution. And feel free to reopen

**Comment by koaqiu** [comment]
it is done.

My fault
