### ISSUE TITLE
The built-in plug-ins cannot be synchronized

### ISSUE THREAD

**Issue by linjialiang** [shanalikhan/code-settings-sync#697]
Issue Type: <b>Feature Request</b>

> `The built-in plug-ins cannot be synchronized`

Extension version: 3.2.0
VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.17134

**Comment by shanalikhan** [comment]
Please provide scenario details what you want to achieve.
The current and expected behaviour
