### ISSUE TITLE
Extension config doesn't update in MacOS

### ISSUE THREAD

**Issue by bdougherty** [shanalikhan/code-settings-sync#698]
🐛 **Describe the bug**  
I've installed a couple new extensions, but they are not in the gist when I upload my settings. This was working in the 3.1.2 release.

🌴 **Visual Studio Code Version :** 1.28.2 
🌴 **Code Settings Sync Version :** 3.1.2
🌴 **Standard or Insiders :** standard
🌴 **OSS or Portable :** [ _here_ ] 
🌴 **Operating System :** macOS 10.13.6 
🌴 **Occurs On:** Upload
🌴 **Proxy Enabled:** No
🌴 **Gist Id:** f255f311e4081c53e819ecccdf0f680a

📰 **To Reproduce**
1. Install a new extension
2. Upload settings

💪 **Expected behavior**
The new extension should be added to the extensions.json file in the gist.

📺 **Console Error Log** 
I couldn't find any logs.

**Comment by bdougherty** [comment]
Yes, after restarting and manually uploading the settings, the extensions are not there.

I'm now seeing this error in the console, but it doesn't seem to prevent upload of the settings:

```
ERR EEXIST: file already exists, open '/Users/brad/Library/Application Support/Code/User/sync.lock': Error: EEXIST: file already exists, open '/Users/brad/Library/Application Support/Code/User/sync.lock'
```

That file did not exist when I tried to check for it.

**Comment by virgilwashere** [comment]
> That file did not exist when I tried to check for it.

It's only there for 1 second.

**Comment by shanalikhan** [comment]
I cant test for Mac OS though. Open for PR.

**Comment by shanalikhan** [comment]
Latest version is released, Let me know if it persists in Settings Sync v3.2.8

>OSS or Portable : [ here ]

If you are using OSS code. Settings Sync doesnt support OSS as of now - #668

**Comment by bdougherty** [comment]
v3.2.8 has not fixed the issue. Not seeing that error anymore though.

**Comment by shanalikhan** [comment]
are you using OSS version of code?

**Comment by bdougherty** [comment]
I don't think so, unless the one from the website is the OSS version.

**Comment by shanalikhan** [comment]
have you tried deleting the file and then check it it works?
