### ISSUE TITLE
Auto Upload / Download : Disable change detection for workspace storage folder.

### ISSUE THREAD

**Issue by sevenryze** [shanalikhan/code-settings-sync#708]
🐛 **Describe the bug**  
The extension triggers upload action every time when i click activity bar or open terminal.

🌴 **Visual Studio Code Version :** [ 1.29.1 and latest insider build ] 
🌴 **Code Settings Sync Version :** [ 3.2 ] 
🌴 **Standard or Insiders :** [ both of them are tested ] 
🌴 **Operating System :** [ windows 10 ] 
🌴 **Occurs On:** [ Upload  ]
🌴 **Proxy Enabled:** [  No ]
For note: I use bash on windows as external terminal

📰 **To Reproduce**
1. Go to 'normal workspace'
2. Click on 'any activity bar item or open terminal'
3. See error, the status bar will show "Sync: Upload in progress, please wait"

💪 **Expected behavior**
Should not upload settings when i click the buttons mentioned before.

📺 **Console Error Log** 

![image](https://user-images.githubusercontent.com/30069225/48595433-8b368000-e98f-11e8-808e-017c487e6b04.png)

Seems like the sync extension always detects workspace storage file changes.

📺  **Additional context**
In my code/user folder, the syncLocalSettings.json file is there, which declares that the workspaceStorage folder should be ignored. look like this extension failed to parse the global configure file.

**Comment by shanalikhan** [comment]
> which declares that the workspaceStorage folder should be ignored. look like this extension failed to parse the global configure file.

Can you post your Settings Sync global settings ( See readme where global Settings are present )

**Comment by sevenryze** [comment]
```json
{
  "ignoreUploadFiles": [
    "projects.json",
    "projects_cache_vscode.json",
    "projects_cache_git.json",
    "projects_cache_svn.json",
    "gpm_projects.json",
    "gpm-recentItems.json"
  ],
  "ignoreUploadFolders": ["workspaceStorage"],
  "ignoreExtensions": [],
  "replaceCodeSettings": {},
  "gistDescription": "Visual Studio Code Settings Sync Gist",
  "version": 322,
  "token": "*********************",
  "downloadPublicGist": false,
  "supportedFileExtensions": ["json", "code-snippets"],
  "openTokenLink": true,
  "disableUpdateMessage": false,
  "lastUpload": "2018-11-24T09:48:20.210Z",
  "lastDownload": "2018-11-22T08:31:29.459Z",
  "githubEnterpriseUrl": null,
  "askGistName": false,
  "customFiles": {},
  "hostName": null
}
```

Could these help you? i couldn't find any error in these settings.

**Comment by shanalikhan** [comment]
I think you have set auto upload or download is enabled.

**Comment by tranhl** [comment]
Any updates on this bug?

**Comment by pltrant** [comment]
I also had this issue and had to disable the auto upload feature.  Clicking the activity bar, which many extensions use, should not trigger an upload.  This didn't start happening until VSC 1.31.

**Comment by shanalikhan** [comment]
Its fixed in new version. Please update and let me know.
