### ISSUE TITLE
Discussion : Display Sponsored Deals inside Code

### ISSUE THREAD

**Issue by shanalikhan** [shanalikhan/code-settings-sync#713]
Guys, 

I'm looking forward to add sponsored links in Code. The main goal is to let me support this project as i need to generate revenue in order to keep working and supporting this extension.

Following are the ideas i have my mind :

1. Ask user to show the sponsored posts or deals while installing Settings Sync.
2. Once user allows, extension will show at- least 1-2 message box / week or open 1-2 pages / week in user editor.
3. Revenue will be earned via affiliation from those deals.

The messages wont keep appearing to all users.
Anyone can disable anytime and it wont appear for them anyway.

If anyone have more ideas, feel free to discuss.

**Comment by smbkr** [comment]
I would immediately stop using this extension if it includes advertising. 

One thing I think you should consider is not showing advertising for users who have contributed to the project (either via PR or financial contribution).

**Comment by shanalikhan** [comment]
The messages wont keep appearing to all users.
Anyone can disable anytime and it wont appear for them anyway.

**Comment by damsfx** [comment]
> 
> .... or open 1-2 pages / week in user editor.

Doesn't feel very well with this idea.
Witch type of page !?

Can your sponsors offer you the guarantee of no bloated page?  
I need all my ressource to work, no need of mining scripts.

**Comment by shanalikhan** [comment]
> Can your sponsors offer you the guarantee of no bloated page?

Great point, I will think on handling these situations.

**Comment by cr3ative** [comment]
This extension is already noisy with unnecessary update notifications. This would absolutely be the last straw, and probably would not be compliant with EU regulations if it was automatically opted in.
