### ISSUE TITLE
Not downloading settings correctly on coder.com

### ISSUE THREAD

**Issue by marcorivm** [shanalikhan/code-settings-sync#714]
🐛 **Describe the bug**  
I'm testing coder.com and tried ussing the extension to sync my settings and extensions but it's not updating the settings on code. I see the settings downloaded but it looks like coder.com vscode settings path is different.

🌴 **Visual Studio Code Version :** [ VERSION_HERE ] 
🌴 **Code Settings Sync Version :** [ 3.2.0 ] 
🌴 **Standard or Insiders :** [ Standard? ] 
🌴 **OSS or Portable :** [ _here_ ] 
🌴 **Operating System :** [ coder.com Ubuntu 16 ] 
🌴 **Occurs On:** [ Download ]
🌴 **Proxy Enabled:** [ Not sure ]
🌴 **Gist Id:** [ b9046b70e0c9383425e5cce4c3f48fa4 ]

📰 **To Reproduce**
1. Go to 'coder.com' install sync extension normally
2. Try downloading the settings and the file will download to ~/.config/User/settings.json 
3. VSCode settings wont reflect the downloaded settings and extensions wont install

💪 **Expected behavior**
VSCode settings wont reflect the downloaded settings and extensions wont install

📺 **Console Error Log** 
Couldn't get errorl log on vscode output, any file I can check?

📺  **Additional context**
Coder.com is a web environment for vscode

**Comment by shanalikhan** [comment]
> VSCode settings wont reflect the downloaded settings and extensions wont install

Where does VSCode Settings resides for the coder.com version of Code ?
Can you share the path for the settings.json file

**Comment by marcorivm** [comment]
They are being stored @ /tmp/User/

![image](https://user-images.githubusercontent.com/1222598/49047532-500d2b80-f19d-11e8-941b-00f44538f482.png)

**Comment by shanalikhan** [comment]
As there is no official support of coder.com version of Visual Studio Code - Pretty low priority at the moment.
PR is welcome for it.

**Comment by marcorivm** [comment]
I'll open an issue with coder.com guys to and try to figure it out. 
Do you have any pointers or suggestions for where to start on the pr @shanalikhan ?

**Comment by shanalikhan** [comment]
Here are the paths for user folder and all the required code config folders are initialized.

https://github.com/shanalikhan/code-settings-sync/blob/master/src/environmentPath.ts#L65

**Comment by lincolnzocateli** [comment]
I am having the same problem with Ubuntu 18.04

**Comment by shanalikhan** [comment]
Released with v3.2.3.
