### ISSUE TITLE
Sync check starts when switching views

### ISSUE THREAD

**Issue by thernstig** [shanalikhan/code-settings-sync#727]
🐛 **Describe the bug**  
Whenever I click any icon in the activity bar, e.g. going from Explorer to Search, code-settings-sync seem to try to sync files. I notice in the status bar that it says "Sync: Updating In Progress ... Please Wait.".

Is this intentional? It slows down VS code.

**Comment by shanalikhan** [comment]
Yes, when you upload / download, it works on background.

**Comment by shanalikhan** [comment]
I think you have enabled auto upload. If auto upload is enabled, you need to disable it. There are already issues opened for auto upload / download.

What is the exception logged in your developer console.

**Comment by thernstig** [comment]
Ah, so I suppose one of the open issues catches what I have found. I searched but could not find anything pertaining to this. It does not make sense for me to sync/autoupload just because I for example open Search.

This is the output from the console:

```console
console.ts:134 [Extension Host] rejected promise not handled within 1 second
t.log @ console.ts:134
t._logExtensionHostMessage @ extensionHost.ts:453
(anonymous) @ extensionHost.ts:244
emitTwo @ events.js:126
emit @ events.js:214
emit @ internal/child_process.js:772
_combinedTickCallback @ internal/process/next_tick.js:141
_tickCallback @ internal/process/next_tick.js:180
log.ts:169   ERR EEXIST: file already exists, open 'C:\Users\UserA\AppData\Roaming\Code\User\sync.lock': Error: EEXIST: file already exists, open 'C:\Users\UserA\AppData\Roaming\Code\User\sync.lock'
```
