### ISSUE TITLE
2.0.2 keeps giving me null error on token. I can't set this up as a new install.

### ISSUE THREAD

**Issue by jacobrillema** [shanalikhan/code-settings-sync#73]
**Visual Studio Code Version :** [ 2016-08-25T06:02:25.679Z 1.5 Insiders Preview ]
**Code Sync Settings Version :** [ 2.0.2 ]
**Operating System :** [ 10.11.6 OSX ]

Please make sure to write the versions and console logged error picture or copied text.

**Comment by andreagrandi** [comment]
Hi, I'm having the same problem with Visual Studio Code 1.4
I installed today in my work laptop and I didn't have any problem.
Then I went back home, I upgraded VS to 1.4 (I had not updated it for a while), I installed the extension and tried to sync.. I get the same error.

**Comment by noz482** [comment]
I am getting the same error. VS Code version 1.4.0 on Windows 10 Professional.

**Comment by whanwells** [comment]
Ditto. VS Code 1.4.0, Code Sync Settings 2.0.2, Windows 10 Enterprise.

**Comment by jing2si** [comment]
Ditto

**Comment by jing2si** [comment]
Ditto
I manual download 1.6.3 to cover 2.0.2, it works fine!
this the download [url](https://Shan.gallery.vsassets.io/_apis/public/gallery/publisher/Shan/extension/code-settings-sync/1.6.3/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage)

**Comment by andreagrandi** [comment]
@jing2si when 2.0.2 was released? I installed the extension yesterday for the first time on my work laptop and it's 1.6.3 version. The one I installed at home on the same day it was 2.0.2 :/

**Comment by shanalikhan** [comment]
Can you please update and let me know , i have resolved it.

**Comment by andreagrandi** [comment]
@shanalikhan hi, I've just updated to 2.0.4 and it worked. Thanks!

**Comment by whanwells** [comment]
@shanalikhan the token error has been fixed, but the Gist is not being updated. I took the following steps to confirm:

- Delete the existing Gist
- Create new access token
- Reset extension settings
- Attempt to sync

The Gist was not created.

**Comment by shanalikhan** [comment]
@whanwells  Please check the new update and let me know if its working for you now :)

**Comment by whanwells** [comment]
@shanalikhan still nothing.

**Comment by shanalikhan** [comment]
whats on the console log or any error or its still displaying nothing in error?

**Comment by whanwells** [comment]
No errors are displayed. The status bar says it's updating the settings to GitHub then disappears, but the confirmation never pops up.

**Comment by shanalikhan** [comment]
i have added exceptions logs in more places recently to know atleast whats the problem. I will check out and update.
Meanwhile if you have time you can download the code and run it , debug it the error from your side and send me a pull request or tell me. :)

**Comment by jacobrillema** [comment]
Hi, I've just updated to 2.0.6 and it is working. Thanks!

**Comment by shanalikhan** [comment]
@whanwells its working fine at your end now? Update, reset and let me know

**Comment by whanwells** [comment]
@shanalikhan - it's working now, but there's a small bug: the initial upload created the Gist but didn't write any of the settings. So I triggered another upload, and the settings were written then. Thanks!
