### ISSUE TITLE
upload

### ISSUE THREAD

**Issue by xcsweb** [shanalikhan/code-settings-sync#732]
🐛 **Describe the bug**  

🌴 **Visual Studio Code Version :**
版本: 1.29.1 (user setup)
提交: bc24f98b5f70467bc689abf41cc5550ca637088e
日期: 2018-11-15T19:13:36.375Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
架构: x64
🌴 **Code Settings Sync Version :** Version - 3.2.2 - 26 Nov, 2018
🌴 **Standard or Insiders :** [ _here_ ] 
🌴 **OSS or Portable :** [ _here_ ] 
🌴 **Operating System :** [ VERSION_HERE ] 
🌴 **Occurs On:** [Upload / Download / Help Configuring ]
🌴 **Proxy Enabled:** [ Yes / No ]
🌴 **Gist Id:** [ ID_HERE ]

📰 **To Reproduce**

💪 **Expected behavior**

📺 **Console Error Log** 
![image](https://user-images.githubusercontent.com/20693737/49786242-12dc9800-fd5e-11e8-91bb-3ca5d066a657.png)

📺  **Additional context**

**Comment by shanalikhan** [comment]
Fixed.
