### ISSUE TITLE
Sync : 错误信息已打印在控制台 (帮助 > 切换开发人员工具)

### ISSUE THREAD

**Issue by Zyx-A** [shanalikhan/code-settings-sync#735]
Issue Type: <b>Bug</b>

不知道什么时候出现的。
无论是上传配置，或者下载配置，都会报告这个错误。

Extension version: 3.2.3
VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:07:43.495Z)
OS version: Linux x64 4.15.0-29deepin-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5300U CPU @ 2.30GHz (4 x 2545)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 1, 1|
|Memory (System)|7.51GB (0.36GB free)|
|Process Argv|--extensions-dir=/home/dlyx/.var/app/com.visualstudio.code/data/vscode/extensions --reuse-window|
|Screen Reader|no|
|VM|75%|

</details>

**Comment by shanalikhan** [comment]
Whats the exception logged in developer console

**Comment by odinggg** [comment]
@shanalikhan 我今天ubuntu下也报这个错误。报错如下
![Snipaste_2019-03-19_17-19-11](https://user-images.githubusercontent.com/20553157/54594209-29844080-4a6b-11e9-90d3-e5cd7ee29951.png)
