### ISSUE TITLE
Sync : Error Logged in Console

### ISSUE THREAD

**Issue by kevinpleong** [shanalikhan/code-settings-sync#738]
![image](https://user-images.githubusercontent.com/39684575/50070040-5d587d00-0181-11e9-9a33-7da67488eca7.png)

I keep on trying to download a Gist from my GitHub account and when I try it keeps on giving me the error 

Sync : Error Logged in Console (Help Menu > Toggle Developer Tools). 

Source: Settings Sync (Extension)

I have typed in Alt+Shift+D but it keeps on giving me this error and when I go to my terminal Debugging area nothing is logged. I am at a loss on what to do I have tried deleting and reinstalling Settings Sync and I also tried to go to the command pallet and type in "Sync : Reset Extension Settings" I did and it asks me to put in my Gist  Personal Token but it still gives me the same Error... I need some help I am stuck and am at a loss on what to do.

**Comment by shanalikhan** [comment]
> Error Logged in Console (Help Menu > Toggle Developer Tools).

Whats is error logged in developer console.

**Comment by hello-w0r1d** [comment]
I have the same issue. Running it on Ubuntu 18.04. Sync works fine with the same Gist and Token on other Windows machines.

The error log from developer console:
![error](https://user-images.githubusercontent.com/35628747/50105475-d1168a80-0252-11e9-85b2-4611575e6a56.png)

**Comment by kevinpleong** [comment]
I don’t know how to look that up I can’t find where that is when I go into
my consol on VS code program using ⌘ ~ it doesn’t show any errors

**Comment by CoonHouse** [comment]
Same problem here. Error on Windows 10. on OS-X it's working fine.

**Comment by bumzy** [comment]
I have the same issue on windows 7 and Linux Mint 18.2

**Comment by kevinpleong** [comment]
DID

**Comment by eldark** [comment]
Same error as @kevinpleong 
Did all the things recommended, and even regenerated the gist token.
Still throws that error.
VS Code 1.30.0, Windows 10 Home

**Comment by shanalikhan** [comment]
I always welcome PR of anything.
If you think the document can be improved ,send me a PR.
If you found a way to solve the error yourself, feel free to post in Wiki Troubleshooting page and add your solution there to assist other users.

**Comment by EmbeddedBacon** [comment]
@shanaccelirate Certainly, though I will need to go through the process front to back to offer any meaningful suggestion (at least in my mind).  ;-)

**Comment by hello-w0r1d** [comment]
@EmbeddedBacon @shanaccelirate I'm aware of the Gist ID mechanism. I'm also able to use it across computers running Windows. But this issue still persists on the latest version of VSCode.

**Comment by hello-w0r1d** [comment]
@shanaccelirate  Looks like this issue has something to do with the permissions. I ran vscode with "sudo code --user-data-dir <...>" and I am able to connect to GIST but extensions do not install due to errors like this:

_"/usr/share/code/bin/code" --install-extension eg2.vscode-npm-script
Error: Command failed: "/usr/share/code/bin/code" --install-extension eg2.vscode-npm-script
You are trying to start vscode as a super user which is not recommended. If you really want to, you must specify an alternate user data directory using the --user-data-dir argument._

I installed VSCODE using the deb file on Ubuntu 18.04 and the App Center automatically asks for sudo password. Do you see any issue here?

**Comment by cruizba** [comment]
I have the same error in Ubuntu 18.10. I'll try to upload my settings manually into my gist repository and see if another computer with Windows 10 works, and I'll reinstall VSCode in my Ubuntu machine to see if it works.

**Comment by hello-w0r1d** [comment]
Was able to resolve this @shanaccelirate . So recently, I upgraded from 14.04 to 18.04.
I think the reason for these issues is some corruption issue with the user configuration settings. I managed to **resolve** it by doing the following:

1. Uninstall vscode (sudo apt remove code)

2. Reinstall using deb ( sudo apt install ./code.deb)

3. Remove VSCode settings directory (Ubuntu: ~/.vscode)

4. Remove Extension Configuration directory (This is the step which I had never done earlier and the one that resolved the issue for me) "rm -rf ~/.config/Code/"
From the documentation the extension data should be in these locations 
Windows: %APPDATA%\Code\User\syncLocalSettings.json
Mac: $HOME/Library/Application Support/Code/User/syncLocalSettings.json
Linux: ~/.config/Code/User/settings.json

5. Use normal procedure to connect to GIST

**Comment by cruizba** [comment]
@hello-w0r1d your solution works for me :)

**Comment by shizhao1100** [comment]
@EmbeddedBacon  this right 
if your system is Win10， you already upload,  you have token and gist_id like this
```code
Done.CODE SETTINGS SYNC UPLOAD SUMMARY
Version: 3.2.4
--------------------
GitHub Token: xxxxxxxxxxxxxxxxxxxxxxxxxxx
GitHub Gist: yyyyyyyyyyyyyyyyyyyy
GitHub Gist Type: Secret
```
you should
1. open %APPDATA%\Code\User\settings.json
2. change "sync.gist": "yyyyyyyyyyyyyyyyyyyy"
3. open %APPDATA%\Code\User\syncLocalSettings.json
4. change "token": "xxxxxxxxxxxxxxxxxxxxxxxxxxx"
5. Alt+Shift+D
---
when remove the 'code-settings-sync' please remove the 'syncLocalSettings.json' file and 'sync.gist'(in settings.json file)

**Comment by gustavomrs** [comment]
I had the same problem. In my case I was trying to use **github token** instead of **gist id** to configure the extension on the new machine. Now it's working

**Comment by UbaidillahGit** [comment]
> ![image](https://user-images.githubusercontent.com/39684575/50070040-5d587d00-0181-11e9-9a33-7da67488eca7.png)
> 
> I keep on trying to download a Gist from my GitHub account and when I try it keeps on giving me the error
> 
> Sync : Error Logged in Console (Help Menu > Toggle Developer Tools).
> 
> Source: Settings Sync (Extension)
> 
> I have typed in Alt+Shift+D but it keeps on giving me this error and when I go to my terminal Debugging area nothing is logged. I am at a loss on what to do I have tried deleting and reinstalling Settings Sync and I also tried to go to the command pallet and type in "Sync : Reset Extension Settings" I did and it asks me to put in my Gist Personal Token but it still gives me the same Error... I need some help I am stuck and am at a loss on what to do.



> ![image](https://user-images.githubusercontent.com/39684575/50070040-5d587d00-0181-11e9-9a33-7da67488eca7.png)
> 
> I keep on trying to download a Gist from my GitHub account and when I try it keeps on giving me the error
> 
> Sync : Error Logged in Console (Help Menu > Toggle Developer Tools).
> 
> Source: Settings Sync (Extension)
> 
> I have typed in Alt+Shift+D but it keeps on giving me this error and when I go to my terminal Debugging area nothing is logged. I am at a loss on what to do I have tried deleting and reinstalling Settings Sync and I also tried to go to the command pallet and type in "Sync : Reset Extension Settings" I did and it asks me to put in my Gist Personal Token but it still gives me the same Error... I need some help I am stuck and am at a loss on what to do.

Hi, i had the same issue, but finally resolved it
in my cases, if you have arround 25 extension or setting, you have to see the output window when Sync is installing the extension one by one, when one of them error, you have to install manually the one that get error with extension window on left side of VSCODE , when done, try to Sync again with Shift + alt + d, then the rest of extension will install automatically, when it's done, vscode will auto restart, and all your extension is loaded perfectly

**Comment by pierrenel** [comment]
@ubaidillahSriyudi that solved it for me - turns out a developer unpublished their theme from the VS Code Marketplace (monokay-grey). I had to edit the gist in github, removed the offending theme and try again. A check inside sync if the package doesnt exist would be useful :)

**Comment by tutods** [comment]
I have all time is messagen, i try sync with my desktop and my laptop and appear this error

**Comment by ligantx** [comment]
similar to @pierrenel 
For me Sync tried to install an extension that i couldnt find. Make it wasnt available anymore. I solved it by going in gist in github and deleting the part of extensions that was giving error. At the next sync: Download, it worked fine..

**Comment by nurmdrafi** [comment]
1.  Go to your gists
2.  Click on cloudsettings
3.  Click on Edit
4.  Find your stucked extension name from <code>extensions.json</code> and remove those data </br>as like ---</br> {
    "metadata": {
      "id": "42e46dd6-3444-4b25-be5c-ddd5ecf2baa7",
      "publisherId": "ms-vscode.brackets-pack",
      "publisherDisplayName": "ms-vscode"
    },
    "name": "brackets-pack",
    "publisher": "ms-vscode",
    "version": "0.1.1"
  },
5.  Update
6.  Then try to download again

I hope it will work &#128526;
