### ISSUE TITLE
Cannot synchronize settings (also, cannot read property Token of null)

### ISSUE THREAD

**Issue by loboar** [shanalikhan/code-settings-sync#74]
**Visual Studio Code Version :** 1.4
**Code Sync Settings Version :** 2.01
**Operating System :** Windows 10 Pro (64 bits)

/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:98 [Extension Host] Windows_NT
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:98 [Extension Host] {"message":"Not Found","documentation_url":"https://developer.github.com/v3"}(anonymous function) @ /C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:98
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:98 [Extension Host] {"message":"Not Found","documentation_url":"https://developer.github.com/v3"}
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:89 ERROR ! Logged In Console (Help menu > Toggle Developer Tools). Please open an issue in Github Repo using 'Sync : Open Issue' command.e.doShow @ /C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:89
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:98 [Extension Host] {"message":"Not Found","documentation_url":"https://developer.github.com/v3"}(anonymous function) @ /C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:98
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:98 [Extension Host] {"message":"Not Found","documentation_url":"https://developer.github.com/v3"}
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:89 ERROR ! Logged In Console (Help menu > Toggle Developer Tools). Please open an issue in Github Repo using 'Sync : Open Issue' command.e.doShow @ /C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:89

Other issue: cannot read property Token of null
I modified extension.json. I added the sentence if (syncSetting == null) syncSetting = {}; at line 208.

            function Init() {
                return __awaiter(this, void 0, void 0, function* () {
// <== I added the next line to make syncSettings a valid object when it is null
                     if (syncSetting == null) syncSetting = {};
                     if (syncSetting.Token == null || syncSetting.Token == "") {

**Comment by shanalikhan** [comment]
Can you please update to latest version and let me know

**Comment by loboar** [comment]
I deleted all other plugins and I updated to 2..0.4 but sync is not working. Below is the new log:

threadService.ts:214 [Extension Host] Windows_NT
threadService.ts:214 [Extension Host] {"message":"Not Found","documentation_url":"https://developer.github.com/v3"}(anonymous function) @ threadService.ts:214emitTwo @ events.js:100emit @ events.js:185handleMessage @ internal/child_process.js:718channel.onread @ internal/child_process.js:444
threadService.ts:214 [Extension Host] {"message":"Not Found","documentation_url":"https://developer.github.com/v3"}
messageService.ts:119 ERROR ! Logged In Console (Help menu > Toggle Developer Tools). Please open an issue in Github Repo using 'Sync : Open Issue' command.e.doShow @ messageService.ts:119e.show @ messageService.ts:103(anonymous function) @ mainThreadMessageService.ts:55i.Class.derive._oncancel @ winjs.base.raw.js:1641t.$showMessage @ mainThreadMessageService.ts:25e.handle @ abstractThreadService.ts:34s @ ipcRemoteCom.ts:269f @ ipcRemoteCom.ts:226_combinedTickCallback @ internal/process/next_tick.js:67_tickCallback @ internal/process/next_tick.js:98

**Comment by shanalikhan** [comment]
[#59](https://github.com/shanalikhan/code-settings-sync/issues/59).
> this is due to invalid gist ID. please reset the settings by sync reset settings command and then again try to download. 

and update

**Comment by loboar** [comment]
I reset the settings by sync reset setting command as you said. I recreated the token and tried to download the settings. Error is the same. TIA.

**Comment by loboar** [comment]
I could give you Team Viewer access to this computer if you want.

**Comment by shanalikhan** [comment]
Update pushed, reset extension settings and try again :)

**Comment by loboar** [comment]
Same error:

[Extension Host] Windows_NT
2threadService.ts:214 [Extension Host] {"message":"Not Found","documentation_url":"https://developer.github.com/v3"}(anonymous function) @ threadService.ts:214emitTwo @ events.js:100emit @ events.js:185handleMessage @ internal/child_process.js:718channel.onread @ internal/child_process.js:444
messageService.ts:119 ERROR ! Logged In Console (Help menu > Toggle Developer Tools). Please open an issue in Github Repo using 'Sync : Open Issue' command.e.doShow @ messageService.ts:119e.show @ messageService.ts:103(anonymous function) @ mainThreadMessageService.ts:55i.Class.derive._oncancel @ winjs.base.raw.js:1641t.$showMessage @ mainThreadMessageService.ts:25e.handle @ abstractThreadService.ts:34s @ ipcRemoteCom.ts:269f @ ipcRemoteCom.ts:226_combinedTickCallback @ internal/process/next_tick.js:67_tickCallback @ internal/process/next_tick.js:98

**Comment by loboar** [comment]
I recreated the token and gistid in my Ubuntu instead of using Windows 10. Then I reset the sync settings in Windows 10 and configured the new token and gistid. After that, VSCode installed all extensions which are set in Ubuntu.

So I have this extension working fine right now. Thanks for your time.

Have a nice weekend.

**Comment by loboar** [comment]
I only let you know that I installed your extension in a notebook running Windows 10 and I had no problem synchronizing the settings.
