### ISSUE TITLE
Workspace Settings

### ISSUE THREAD

**Issue by msmith171** [shanalikhan/code-settings-sync#744]
💡 **Describe the solution you'd like**

A feature that let you decide to sync user settings, workspace settings, or both to a gist

💡 **Additional context**
As of now I have workspaces for multiple projects that use different settings as well as extensions and it would be helpful if I was able to sync the settings to different gists.

**Comment by shanalikhan** [comment]
Settings Sync wont sync your all projects workspaces.

but you can manually add this feature using Custom Sync Feature.
Read Wiki here:
https://github.com/shanalikhan/code-settings-sync/wiki/Custom-Sync

**Comment by shanalikhan** [comment]
Duplicate of #258
