### ISSUE TITLE
Correct way to share gist settings with another person once

### ISSUE THREAD

**Issue by Econbrief** [shanalikhan/code-settings-sync#746]
Hi, I have a quick question on sharing my settings with another person.   This is not to sync future changes, but to just give the person an initial setting to work from.  
If I understood correctly, these are the steps to share my settings with another person:
(1) get the gist_ID and give it to the person (no need to generate a gist token, but make the gist public)
(2) have the person go to Sync: Advanced Options
(3) select Sync: Download Setting from a Public Gist
(4) select Sync: Download Settings (shift + alt + d )
     VS Code will ask for the gist_id
     Note: if the person already has some loaded setting here, change the settings with the given id.
(5) have the person select Sync: Reset Extension Settings 
     (or at least point the Gist_ID to a new location)
is this right, or is there a better way to go about?

**Comment by shanalikhan** [comment]
See the post here.
http://shanalikhan.github.io/2016/09/02/how-to-Share-visual-studio-code-settings.html
