### ISSUE TITLE
Logo about extensions

### ISSUE THREAD

**Issue by rulelee** [shanalikhan/code-settings-sync#747]
![j s 94yyi9 gb uc2 fhva](https://user-images.githubusercontent.com/11474005/50980842-955ea000-1534-11e9-97ba-92f04c598422.png)
Please redesign the logo, it is a bit unsightly, it seems to be incompatible with other logos, please

**Comment by shanalikhan** [comment]
do you have any suggestions, i am open for PR.

**Comment by shanalikhan** [comment]
I am closing this ticket, but always open for PR regarding any changes for the icon

**Comment by Pustur** [comment]
Hi,

I tried to create a new logo. Feedback welcome:

![code-settings-sync-512](https://user-images.githubusercontent.com/13663338/63725577-0f8d2c00-c85b-11e9-87ec-593fe043f607.png)

How it would look with the `Light+` theme:

<img width="720" alt="Light" src="https://user-images.githubusercontent.com/13663338/63725607-2895dd00-c85b-11e9-9abf-7b18314360b6.png">

How it would look with the `Dark+` theme:

<img width="720" alt="Dark" src="https://user-images.githubusercontent.com/13663338/63725600-26338300-c85b-11e9-8d0d-53a8dda34e71.png">

In the marketplace:
<img width="743" alt="Marketplace" src="https://user-images.githubusercontent.com/13663338/63725648-44997e80-c85b-11e9-863d-0cde66d77f1d.png">

Here are all the `png` and `sketch` files if someone wants to modify it (you'll need [Sketch](https://www.sketch.com)):
[code-settings-sync-logo.zip](https://github.com/shanalikhan/code-settings-sync/files/3543219/code-settings-sync-logo.zip)

**Comment by shanalikhan** [comment]
> I tried to create a new logo. Feedback welcome:

@Pustur 

Can you remove the blue shade from the cloud and use the exact same image layout with borders like above. I want to keep the current logo but with your improved dark/light theme compatibility.

**Comment by Pustur** [comment]
@shanalikhan Like this? I changed the arrow position to match the current logo and used the same dark grey for both the cloud and the arrows:

<img width="256" alt="New logo version 2" src="https://user-images.githubusercontent.com/13663338/63779250-891e2c00-c8e6-11e9-811f-772a09e7d238.png">

[code-settings-sync-logo-v2.zip](https://github.com/shanalikhan/code-settings-sync/files/3546594/code-settings-sync-logo-v2.zip)

**Comment by shanalikhan** [comment]
Yes this looks better.
@Pustur 
Can you send me PR with the updated images along with the `png` and `sketch` files.
