### ISSUE TITLE
Sync & Download fail in Develop Tools with "HttpError: Not Found"

### ISSUE THREAD

**Issue by h3d0** [shanalikhan/code-settings-sync#748]
**Visual Studio Code Version : [ 1.30.2 ]**
**Code Settings Sync Version : [ 3.2.4 ]**
**Operating System : [ WINDOWS 10 ]**
**Occurs On: [ Sync, Download ]**
**Proxy Enabled: [ No ]**

Fresh install, Windows 10, recent VSC (1.30.2), recent Sync (3.2.4),
- _settings.json_ -> `"sync.gist": "https://github.com/settings/tokens/<my_id>"`
- _syncLocalSettings.json_ -> `"token": "<my_token>"`

Neither upload nor download works. Fails with:

> Sync : Error Logged In Console (Help menu > Toggle Developer Tools).

Developer Tools log:

```
[Extension Host] HttpError: Not Found
	at module.exports.e.exports.i.fetch.then.n.text.then.n (C:\Users\obiol\.vscode\extensions\shan.code-settings-sync-3.2.4\out\extension.js:137:45419)
	at <anonymous>
	at process._tickCallback (internal/process/next_tick.js:188:7)
t.log @ console.ts:134
t._logExtensionHostMessage @ extensionHost.ts:453
(anonymous) @ extensionHost.ts:244
emitTwo @ events.js:126
emit @ events.js:214
emit @ internal/child_process.js:772
_combinedTickCallback @ internal/process/next_tick.js:141
_tickCallback @ internal/process/next_tick.js:180

```

**Comment by luizhenriquerdias** [comment]
I'm getting this error too.

**Comment by shanalikhan** [comment]
Because your gist ID is invalid.
See details here:
https://github.com/shanalikhan/code-settings-sync/wiki/Troubleshooting#invalid-gist-id-or-invalid--expired-github-token

**Comment by luizhenriquerdias** [comment]
Thanks, @shanalikhan. You're right.
I was using my Access Token as the Gist ID. I didn't notice the difference.

**Comment by Dalot** [comment]
I am having the exact the same error but I did not mistake one for the other.
I am using vs code v1.33.1 and sync extension v3.2.9
Linux Mint 19 Tessa

**Comment by jf781** [comment]
I am also getting this same error on Linux Mint 19.  

Works fine on my Win10 laptop.

**Comment by asmyshlyaev177** [comment]
Have same issue, token and gist id are correct.

**Comment by jf781** [comment]
So I was able to figure it out.  User issue.  I was entering the entire gist URL vs just the gist ID.  Once I used only the gist ID it worked perfectly.

**Comment by shanalikhan** [comment]
>  I was entering the entire gist URL vs just the gist ID
I wish i could make the documentation or WIKI more clearer for the guys. Most of the issues are raied by miss understanding.

I am always open for PR that improve the readme.
Also Public Edit in Github Wiki is enabled. Feel free to improve that. where you think there is confusion.

**Comment by ravishankarkota2017** [comment]
I copied github token but not GistId while creating my sync settings. So i lost my GistId  and am able to retrieve it by following below steps.
-  Go to your github account
- Click on your profile and go to 'Your gists'
- Click on cloud settings, it open several settings
- Go to settings.json
- Find and copy value of "sync.gist", this is your GistId
- You can now download all your uploaded settings

Below are few screen shots:
![image](https://user-images.githubusercontent.com/28355897/60002298-011d6b00-9686-11e9-95bc-116701f29f65.png)
![image](https://user-images.githubusercontent.com/28355897/60002312-07134c00-9686-11e9-9a1f-ba22d641b02c.png)
![image](https://user-images.githubusercontent.com/28355897/60002339-15f9fe80-9686-11e9-9382-0037349eb4c3.png)

**Comment by aamsur** [comment]
i'm getting this problem too, just remove **"sync.gist"** on **settings.json** then re-upload again using **shift+alt+u** and the extention will create a gist for you automatically.

**Comment by pauloneill** [comment]
I'm getting the same error but my settings.json doesn't have a sync.gist - can I just add it manually?

**Comment by pauloneill** [comment]
OK solved my problem: my User and Workspace settings had different GistI Ds even though I reset settings several times. 
I fixed this by recreating my personal access token and updating my "master" settings then uploading.
On the target machine I reset everything and started from scratch then checked that my Gist IDs were both set to the new one ==> working!!!! 😄
