### ISSUE TITLE
Cannot upload settings

### ISSUE THREAD

**Issue by peterjuras** [shanalikhan/code-settings-sync#75]
**Visual Studio Code Version :** 1.4.0
**Code Sync Settings Version :** 2.0.2
**Operating System :** Mac OS X 10.11.5

There is no console message and no error or warning message appearing. The uploading stopped working after the new version came out. It just does nothing and the gist is not updated.

**Comment by shanalikhan** [comment]
Can you please update and let me know :)

**Comment by peterjuras** [comment]
still not working :/ Version 2.0.4

**Comment by shanalikhan** [comment]
what is in your sync settings. Please post (except token).
Also try with reset settings if it works

**Comment by peterjuras** [comment]
```json
{
  "Token": "redacted",
  "Gist": "redacted",
  "lastUpload": null,
  "firstTime": true,
  "autoSync": false,
  "lastDownload": null,
  "ProxyIP": null,
  "ProxyPort": null,
  "Version": 204
}
```

What happens if I do reset settings? I can't risk losing my settings.

**Comment by shanalikhan** [comment]
token and gist has "redacted".
It will clear this JSON file only and when you try to update it will ask token and gist again.

No effect to VS Code Settings.

**Comment by peterjuras** [comment]
Yep, it had the original token and gist but I redacted them to post them publicly.





On Fri, Aug 26, 2016 at 1:35 PM +0200, "Shan Khan" <notifications@github.com> wrote:





token and gist has "redacted".
It will clear this JSON file only and when you try to update it will ask token and gist again.

No effect to VS Code Settings.

**Comment by DNLHC** [comment]
i have the same problem after update

**Comment by ssljivic** [comment]
I can also confirm that it is not working in version 1.4.0.

I have a fresh install. It asked me to enter access token, which I did and in the footer status bar reported that sync was OK.

When I try Download Settings after that I am getting GIST ID prompt, but GIST ID was never displayed.

When I open settings file it looks like this:

`
{"Token":"my-token-xxxxxxxxxxxx-xxxx","Gist":null,"lastUpload":null,"firstTime":true,"autoSync":false,"lastDownload":null,"ProxyIP":null,"ProxyPort":null,"Version":204}
`

GitHUb access token reports that it was not used - I created new access token, although I performed Upload Settings from VS Code.

**Comment by lumaxis** [comment]
I can only confirm this. It's updating the `extensions.json` and `cloudSetttings` file just fine but the `settings.json` is just empty.

**Comment by shanalikhan** [comment]
@lumaxis thanks for the showing the quick problem.


I have updated it, please update and let me know if its working fine now.

**Comment by peterjuras** [comment]
It's still not working. Reseting also doesn't help.

Why don't you just revert it to a stable version?

**Comment by DNLHC** [comment]
Not working for me as well. Doesn't update `extensions.json` nor `settings.json`.
Let me know if i can provide information that might help you.

**Comment by shanalikhan** [comment]
@peterjuras @DNLHC some users reported working on version 2.0.6
Let me know if its working at your side
Update, reset settings and let me know 😀

**Comment by peterjuras** [comment]
Thanks, it works now. I didn't even have to reset my settings, which is great. Keep up the good work.

I'm closing this issue since I opened it, if anybody else is still experiencing issues feel free to reopen.

**Comment by shanalikhan** [comment]
I'm the only one developing and testing not a team so i dont have sceneries like u users have to test om thats why it works on my computer and i have to sometime rely of users to test those scenarios thats why reverting isnt an option as i have to add new features...
