### ISSUE TITLE
Sync workspaces between mac/pc?

### ISSUE THREAD

**Issue by weatherhitme** [shanalikhan/code-settings-sync#751]
I've tried uploading setting from Mac installation and downloading on a Windows installation, and all that seems to be missing is the workspace.

My understanding of how workpace sync works is that it syncs the `/User/[user]/Application Support/Code/Workspaces` folder (I could very well be wrong). But from what I can tell, there is no Windows equivalent.

Am I missing something? Or is cross-platform workspace sync not supported?

**Comment by shanalikhan** [comment]
No workspace doesnt get sync. using Settings Sync.

You can achieve this using the following methods.
https://github.com/shanalikhan/code-settings-sync/wiki/Custom-Sync
