### ISSUE TITLE
Updating when nothing has changed

### ISSUE THREAD

**Issue by hmmChase** [shanalikhan/code-settings-sync#754]
🐛 **Describe the bug**  
When you change a value of a setting property that has   `// @sync-ignore` on it, it will still update.  So if you do it a lot, you end up with a gist history like this... 

`@userName userName revised this gist 12 minutes ago.  1 changed file with 1 addition and 1 deletion.
  
2  cloudSettings
@@ -1 +1 @@
{"lastUpload":"2019-01-20T23:35:15.940Z","extensionVersion":"v3.2.4"} 	{"lastUpload":"2019-01-20T23:35:31.712Z","extensionVersion":"v3.2.4"} 
 @userName userName revised this gist 12 minutes ago.  1 changed file with 1 addition and 1 deletion.
  
2  cloudSettings
@@ -1 +1 @@
{"lastUpload":"2019-01-20T23:35:04.064Z","extensionVersion":"v3.2.4"} 	{"lastUpload":"2019-01-20T23:35:15.940Z","extensionVersion":"v3.2.4"} 
 @userName userName revised this gist 12 minutes ago.  1 changed file with 1 addition and 1 deletion.
  
2  cloudSettings
@@ -1 +1 @@
{"lastUpload":"2019-01-20T23:35:00.152Z","extensionVersion":"v3.2.4"} 	{"lastUpload":"2019-01-20T23:35:04.064Z","extensionVersion":"v3.2.4"} 
 @userName userName  revised this gist 12 minutes ago.  1 changed file with 1 addition and 1 deletion.
  
2  cloudSettings
@@ -1 +1 @@
{"lastUpload":"2019-01-20T23:34:56.838Z","extensionVersion":"v3.2.4"} 	{"lastUpload":"2019-01-20T23:35:00.152Z","extensionVersion":"v3.2.4"} 
 @userName userName  revised this gist 12 minutes ago.  1 changed file with 1 addition and 1 deletion.
`

The only change that is being uploaded is a change to date/time.  I change my ignored setting dozens of times per day, so my Gist log looks crazy.  It's a lot of unnecessary uploading.  Could you make it so the anything with a  `// @sync-ignore`  doesn't trigger an upload?  Thank you very much for this awesome tool.

**Comment by shanalikhan** [comment]
>  Could you make it so the anything with a // @sync-ignore doesn't trigger an upload?

@ioprotium how about stopping on-change trigger for upload on the change of value `@sync-ignore` ?

As at the end `@sync-ignore` value wont upload on gist, its better to stop the trigger on the change or addition of `@sync-ignore`.

What do you think about it ?

**Comment by ioprotium** [comment]
@shanalikhan Yes, we should make a diff and determine whether the changes should be upload. Tomorrow I will look at this one!

**Comment by shanalikhan** [comment]
@ioprotium 
That would be great. Looking forward

**Comment by ioprotium** [comment]
@shanalikhan we have a problem. VS doesn't supply with a way to determine what changed in the file. The watcher is triggered only after the file was changed and saved to the system. So, if we need to determine if the changes must be upload we should compare the local file against the gist. This implies download the entire gist. Am I right?

**Comment by shanalikhan** [comment]
Yes, you are right.
We need to extract the `settings.json` file only from the gist and compare it.

**Comment by ioprotium** [comment]
I've got another idea. Every time the upload action is triggered we can persist a copy without all the `@ignore` pragmas, then we use it to compare changes in the next trigger. If other changes rather than `@ignore` were done, the file is uploaded and a new copy is generated. 

What do you think? Could you provide me the needed functions to create and read this "clean" settings file?

**Comment by shanalikhan** [comment]
> we can persist a **copy**

Where you will persist the copy ? Do you have any ideas about that or you are looking to save the copy in `User` folder.

>needed functions to create and read

If you look here, I'm reading the files using this function and saving in a gist.

https://github.com/shanalikhan/code-settings-sync/blob/master/src/sync.ts#L159

Here is the change detection event that will be hit on changing the `settings.json` file

https://github.com/shanalikhan/code-settings-sync/blob/master/src/commons.ts#L138

**Comment by ioprotium** [comment]
> Where you will persist the copy ? Do you have any ideas about that or you are looking to save the copy in `User` folder.
Tell me some folder that is isolated or it will not generate side effects and it should be always available for the extension (maybe created after installation, or the extension folder itself)

**Comment by shanalikhan** [comment]
https://code.visualstudio.com/api/references/vscode-api#ExtensionContext

See here, you can persist the data in states provided by visual studio code api and read to compare.

**Comment by shanalikhan** [comment]
@ioprotium any update ? When you be able to complete ?

**Comment by Revolution1** [comment]
same issue here. any update?

**Comment by jwmann** [comment]
Having the same issue as #553

**Comment by ioprotium** [comment]
Hi, sorry for the long delay. I've just sent the PR #867
