### ISSUE TITLE
Cannot install new /remove extenstion when download

### ISSUE THREAD

**Issue by bearmc27** [shanalikhan/code-settings-sync#755]
Describe the bug
When activating download, either it is on opening vscode with auto-download, or manually activating download function, this error occured. And if there is new extension to be installed, it does not install and attempt to upload setting again because it "detect" changes, which it should have uploaded already

![image](https://user-images.githubusercontent.com/20040663/51621966-95b55d00-1f70-11e9-88d3-0e6e2b1781c0.png)

Something this error happens too:

![image](https://user-images.githubusercontent.com/20040663/51622262-3146cd80-1f71-11e9-8eca-99cc0d918252.png)

🌴 Visual Studio Code Version : 1.30.2
🌴 Code Settings Sync Version : [ 3.2.4 ]
🌴 Standard or Insiders : [ Standard ]
🌴 OSS or Portable : [ No ]
🌴 Operating System : [ Win 10 1803 ]
🌴 Occurs On: [ Download ]
🌴 Proxy Enabled: [ No ]
🌴 Gist Id: [ 34a19519c89cb4312fd4c92ae91861e8]

**Comment by icpm** [comment]
I have same issue here

**Comment by shanalikhan** [comment]
I think you guys have auto download turned on.
Turn off the autoDownload and let me know.

Try with the latest version of Settings Sync

**Comment by bearmc27** [comment]
After using the extension without auto-up and auto-down for about 2 month. I believe that there are some problem with vscode itself rather than your extension, however, reinstalling or installing vscode on a fresh OS (tested on both windows 10 home and ubuntu 18.10) doesn't seems to help with the problem. And i always update to the latest vscode-sync.

I can't reproduce this problem anymore, but i am going to keep using manual update and download anyways.

You may close this issue if no other user reply to this. Thank you for your work👍
