### ISSUE TITLE
Renderer windows error

### ISSUE THREAD

**Issue by EddieNejadi** [shanalikhan/code-settings-sync#759]
Issue Type: <b>Bug</b>

I got the following error:

    Cannot read property 'concat' of undefined
I can see the following error right after opening vs code even without running any extension command

`[2019-01-31 09:17:31.066] [renderer1] [error] Cannot read property 'concat' of undefined: TypeError: Cannot read property 'concat' of undefined at new u (C:\Users\mahdiab\.vscode\extensions\shan.code-settings-sync-3.2.4\out\extension.js:51:4995) at module.exports.t.Sync.<anonymous> (C:\Users\mahdiab\.vscode\extensions\shan.code-settings-sync-3.2.4\out\extension.js:137:71779) at Generator.next (<anonymous>) at module.exports.n (C:\Users\mahdiab\.vscode\extensions\shan.code-settings-sync-3.2.4\out\extension.js:137:71507) at new Promise (<anonymous>) at module.exports.n (C:\Users\mahdiab\.vscode\extensions\shan.code-settings-sync-3.2.4\out\extension.js:137:71284) at module.exports.t.Sync.bootstrap (C:\Users\mahdiab\.vscode\extensions\shan.code-settings-sync-3.2.4\out\extension.js:137:71738) at C:\Users\mahdiab\.vscode\extensions\shan.code-settings-sync-3.2.4\out\extension.js:137:46974 at Generator.next (<anonymous>) at s (C:\Users\mahdiab\.vscode\extensions\shan.code-settings-sync-3.2.4\out\extension.js:137:46614) at <anonymous>`

my other extensions are:
PS C:\WINDOWS\system32> code --list-extensions
DavidAnson.vscode-markdownlint
DotJoshJohnson.xml
eg2.tslint
formulahendry.code-runner
hollowtree.vue-snippets
ms-python.python
ms-vscode.Go
octref.vetur
PeterJausovec.vscode-docker
robertohuertasm.vscode-icons
sdras.vue-vscode-snippets
Shan.code-settings-sync
streetsidesoftware.code-spell-checker
Tyriar.shell-launcher
vscodevim.vim
vscoss.vscode-ansible

    vs code information:
    Version: 1.30.2 (user setup)
    Commit: 61122f8
    Date: 2019-01-07T22:54:13.295Z
    Electron: 2.0.12
    Chrome: 61.0.3163.100
    Node.js: 8.9.3
    V8: 6.1.534.41
    OS: Windows_NT x64 10.0.17763

Extension version: 3.2.4
VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:54:13.295Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4310U CPU @ 2.00GHz (4 x 2594)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.88GB (5.47GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by shanalikhan** [comment]
what is your gist ID ?
Does it happen on upload or download ?

Please update to newer version and verify.

**Comment by shanalikhan** [comment]
Let me know, if it still exists. I will re open this issue.

**Comment by EddieNejadi** [comment]
Hi The issue is resolved after later update to:
Version: 1.31.1 (user setup)
Commit: 1b8e8302e405050205e69b59abb3559592bb9e60
Date: 2019-02-12T02:20:54.427Z
Electron: 3.1.2
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763
