### ISSUE TITLE
Ability to disable info panels that pop up when auto-downloading settings on startup

### ISSUE THREAD

**Issue by xconverge** [shanalikhan/code-settings-sync#76]
When auto-download settings is turned on, whenever you start vscode it pops up a few info panels saying settings were auto downloaded.

I would prefer to have an option to disable this so that I can download settings in the background and not be pestered by a bunch of info panels in my "lightweight" editor that I open and close throughout the day

**Comment by shanalikhan** [comment]
Yes, will do it soon
Thanks

**Comment by andreagrandi** [comment]
How do you auto-download (and maybe auto-upload) settings? It's something that in the equivalent Atom extension was done automatically but I don't know how to do it here, thanks.

**Comment by shanalikhan** [comment]
Im working on it, in next update, it will summary TXT File regarding all the files that are updated/ downloaded , and the extensions that are installed due to download and which are deleted

**Comment by shanalikhan** [comment]
@andreagrandi VSCode provides activation events which runs uopn editor startup in which i have written to execute the download command. :)

**Comment by shanalikhan** [comment]
Now it will show which files are uploaded / downloaded and which extensions are downloaded and removed when upload and download are performed.

Please update and let me know if there is some problem or any kind of exception.

**Comment by xconverge** [comment]
where does summary.txt get created?

**Comment by shanalikhan** [comment]
It's untitled file didn't store in disk until you save

Location is same folder on sync settings file

**Comment by xconverge** [comment]
I still get an info popup saying Sync was done. I wanted to enable a setting that just never displayed anything at all and downloaded in the background.

**Comment by shanalikhan** [comment]
Ok i will do this in the next update.
