### ISSUE TITLE
Extension Causes Source Control Extension to Crash Upon Any Interaction

### ISSUE THREAD

**Issue by dagrooms52** [shanalikhan/code-settings-sync#760]
After installing this extension, my source control extension could not find a source control provider (configured for git). Upon clicking the source control extension, I received a crash message. I disabled the Code Settings Sync extension, and my source control extension works again.

I've also opened a bug on the VS Code project: https://github.com/Microsoft/vscode/issues/67665

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:54:13.295Z)
OS version: Windows_NT x64 10.0.17763
code-settings-sync: 3.2.4

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 x 4200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|63.79GB (46.18GB free)|
|Process Argv|~/.gitconfig|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|0.8.8
gitlens|eam|9.4.1
vscode-html-css|ecm|0.2.0
vsc-material-theme|Equ|2.6.3
prettier-vscode|esb|1.8.0
import-sorter|mik|3.2.0
vscode-autoprefixer|mrm|2.2.0
vscode-azureappservice|ms-|0.11.0
vscode-azurefunctions|ms-|0.13.1
vscode-azurestorage|ms-|0.5.0
mssql|ms-|1.4.0
azure-account|ms-|0.8.0
csharp|ms-|1.17.1
PowerShell|ms-|1.11.0
vscode-typescript-tslint-plugin|ms-|0.4.0
debugger-for-chrome|msj|4.11.1
vscode-docker|Pet|0.5.1
material-icon-theme|PKi|3.6.2
tsimporter|pmn|1.2.14
vscode-css-peek|pra|2.2.0
code-settings-sync|Sha|3.2.4
bootstrap4-vscode|the|6.0.3
vscode-docker-registry-explorer|Tqr|0.1.3
scss-to-css|yut|1.2.0
html-css-class-completion|Zig|1.18.0

</details>

**Comment by shanalikhan** [comment]
is this happening with latest vs code ?
Try removing the Settings sync from code, remove the folder if still exists from extensions folder.
Install again and let me know.

**Comment by dagrooms52** [comment]
Yes, reproduced in VS Code 1.31.1
Uninstalled settings sync, removed folder from `{myuser}/.vscode/extensions/`, restarted VS Code, installed extension, restarted VS Code, clicked source control tab on the left sidebar, got the following messages:

> No source control providers registered
> Extension host terminated unexpectedly

You can see the debug output from the developer tools in [this open issue](https://github.com/Microsoft/vscode/issues/67665).

**Comment by shanalikhan** [comment]
The problem I dont see any reason on crashing the whole vscode source control by my code.
I have updated the packages and pushed newer version v3.2.5

Can you update the extension and let me know
