### ISSUE TITLE
Login error

### ISSUE THREAD

**Issue by dragondgold** [shanalikhan/code-settings-sync#765]
**Visual Studio Code Version :** 1.31.0
**Code Sync Settings Version :** 3.2.4
**Operating System :** Windows 10 x64 1803 build 17134.523
**Occurs On:** Upload
**Proxy Enabled:** No

I had this extension installed from some time and then it stopped working, I didn't care at the time because I had everything synchronized. Now I need it again, even after updating vscode and reinstalling the extension it doesn't work. 

I deleted some leftover files from the extension uninstall so when I install it again it asks me again fro the token, when I enter the token it throws the error in the dev console:

![alt text](https://i.imgur.com/DoWgdOj.png)

**Comment by foughtthelaw** [comment]
I'm new to this extensions but I'm seeing the same error. It works on the laptop that I did the initial upload of settings from but if I try to add a new system this error gets triggered

**Comment by MirceaConstantin** [comment]
I'm new on this extension too, and i get this error.

![capture](https://user-images.githubusercontent.com/26020799/52792277-a63e8c00-3073-11e9-8ce2-6bef83d21eda.PNG)

The error it's on a Windows 10 Pro x64 1809 build 17763.316 and try to get the settings to Ubuntu laptop. I change token in files and the error it's steel there.

**Comment by chevybeef** [comment]
I am seeing this error too when trying to `sync download` for the first time on a new machine?

**Comment by shanalikhan** [comment]
Can you update the extension and let me know same error persists ?

See this `Not found` usually caused by GitHub 
https://github.com/shanalikhan/code-settings-sync/wiki/Troubleshooting#invalid-gist-id-or-invalid--expired-github-token

**Comment by chevybeef** [comment]
I updated but the errors persisted. I managed to get it working using the troubleshooting link.
