### ISSUE TITLE
Move token or (lastUpload|lastDownload) to a different file

### ISSUE THREAD

**Issue by 5nafu** [shanalikhan/code-settings-sync#766]
I try to completely automate my desktop environment to be able to reinstall any system whenever there might be any issue (or when changing hardware :-) )

For this the settings-sync extension is absolutely brilliant. 
Unfortunately, whenever I compare my `syncLocalSettings.json` to the one in my repository, the `lastUpload/lastDownload`-values differs, making it difficult to see real changes.

I understand that one does not want to have the github token in an (worst case: world readable) uploaded file.

It would be great if the `syncLocalSettings.json` file could be static and the current status moved to a different file (e.g. `syncStatus.json`) 
Being able to configure the `token` in a different file would work for me as well, as I did not change anything else in `syncLocalSettings.json`.

**Comment by shanalikhan** [comment]
Nice idea for automation process for putting the `lastUpload/ lastDownload` in separate files.
I will put in a backlog.
Will look into it later on.

**Comment by shanalikhan** [comment]
I am closing this issue, will evaluate on the popularity and reopen this. 
As its very much low priority for me as far as other issues are open.
