### ISSUE TITLE
open VSCode error

### ISSUE THREAD

**Issue by JakeLaoyu** [shanalikhan/code-settings-sync#768]
🌴 **Visual Studio Code Version :** 1.31.1
🌴 **Code Settings Sync Version :** 3.2.4
🌴 **Operating System :** macOS Mojave 10.14.3
🌴 **Proxy Enabled:** No

📰 **To Reproduce**

1. open Visual Studio Code

📺 **Console Error Log** 

<img width="560" alt="jietu20190213-095539 2x" src="https://user-images.githubusercontent.com/16181940/52681215-064f0880-2f76-11e9-8471-60f9f24fd6c0.png">

📺  **Additional context**

<img width="461" alt="jietu20190213-095904 2x" src="https://user-images.githubusercontent.com/16181940/52681277-3eeee200-2f76-11e9-8d86-d0046588a38c.png">

After disable settings sync, it works fine。

**Comment by m92o** [comment]
Duplicate of #762

**Comment by JakeLaoyu** [comment]
@m92o thanks
