### ISSUE TITLE
下载源码报错， 7/5000   Download the source code and report an error

### ISSUE THREAD

**Issue by developers-youcong** [shanalikhan/code-settings-sync#770]
Error message: unable to find module.

For example, the vscode module cannot be found or the HTTP module cannot be found.

The main files for reporting errors are environmentpath. ts and util.ts

**Comment by developers-youcong** [comment]
The problem has been solved.


The reason is that there is no node_modules on git clone github source code, which can be solved by local execution of NPM install and downloading related dependencies.

**Comment by shanalikhan** [comment]
great
