### ISSUE TITLE
v2.3.5 Not working with VSCode 1.31

### ISSUE THREAD

**Issue by Amoystyle** [shanalikhan/code-settings-sync#774]
🐛 **Describe the bug**  
A clear and concise description of what the bug is. You are always welcome to check the [Troubleshooting](https://github.com/shanalikhan/code-settings-sync/wiki/Troubleshooting) section before filing the ticket.

🌴 **Visual Studio Code Version :** [ 1.31.1] 
🌴 **Code Settings Sync Version :** [ 3.2.5] 
🌴 **Standard or Insiders :** [  both of them are tested ] 
🌴 **Operating System :** [ windows 10 ] 
🌴 **Occurs On:** [ Upload ]
🌴 **Proxy Enabled:** [  No ]

📺 **Console Error Log** 
If applicable, add screenshots or paste the console log from developer console of VSCode.
![tim 20190216160404](https://user-images.githubusercontent.com/5343265/52896545-a6ba5c80-3204-11e9-9c90-8e645377dabe.jpg)

**Comment by mkempkes** [comment]
yes, getting the same error

**Comment by niravjethva** [comment]
same problem here

**Comment by lightydo** [comment]
same
 **Visual Studio Code Version :** [ 1.31.1]
 **Code Settings Sync Version :** [ 3.2.5]
 **Standard or Insiders :** [ Standard ]
 **Operating System :** [ Fedora 28 ]
 **Occurs On:** [ Download ]
 **Proxy Enabled:** [ No ]

**Comment by KenanHArik** [comment]
Ditto here. Any workaround?

**Comment by rickrankin** [comment]
Getting the same error on settings download with 1.32-insiders

**Comment by LuisUrrutia** [comment]
@Amoystyle It looks like you're behind a proxy, and haven't set up your proxy config properly and you may need help from your network administrator `xiegongji@gmail.com` (The email is on your screenshot)
@lightydo your error isn't related to this issue and I'm pretty sure that isn't related to this extension at all. Could you try again without any other extension but code-settings-sync?

**Comment by Amoystyle** [comment]
> @Amoystyle It looks like you're behind a proxy, and haven't set up your proxy config properly and you may need help from your network administrator `xiegongji@gmail.com` (The email is on your screenshot)
> @lightydo your error isn't related to this issue and I'm pretty sure that isn't related to this extension at all. Could you try again without any other extension but code-settings-sync?

OK, I try it again

**Comment by KenanHArik** [comment]
> Ditto here. Any workaround?

FYI I was able to get things working again with this workaround:
1) down-grade the add-in version. I chose several revs back.
2) successfully syncing to my gist
3) upgrading the add-in version.

Now everything is back to normal for me.

**Comment by LuisUrrutia** [comment]
@KenanHArik did you have exactly the same error (the red one)? If that's so, could you share us the rev?

**Comment by joehavila** [comment]
I had the same problem. Turns out I simply entered the gist id incorrectly. I thought this was the name of the gist that was used when I initially uploaded my settings. It is in fact an ID number. To get this to work correctly on a fresh download of settings, follow these steps:

1. Reset the extension settings (ctrl-shift-p sync reset).
2. Initiate a download. (ctrl-shift sync download)
3. You will be prompted for the personal access token and the gist. To get the gist id, visit [GitHub Gist](https://gist.github.com/) and find the __*cloudSettings*__ gist. The gist id is the last part of the URL of the gist. Copy that portion of the URL.
4. Paste the gist id into VS Code when prompted.

Your settings will begin to download.

**Comment by rickrankin** [comment]
Turns out that I think I probably reversed the gist id and token. I cleared the settings and tried again and it's working now.

**Comment by Amoystyle** [comment]
Visual Studio Code add setting: 
"http.proxySupport": "off"

**Comment by lightydo** [comment]
> @Amoystyle It looks like you're behind a proxy, and haven't set up your proxy config properly and you may need help from your network administrator `xiegongji@gmail.com` (The email is on your screenshot)
> @lightydo your error isn't related to this issue and I'm pretty sure that isn't related to this extension at all. Could you try again without any other extension but code-settings-sync?

There is no other extension installed and I keep getting the same error. 
Where Can I download a older version of the extension to test?

**Comment by LuisUrrutia** [comment]
@shanalikhan check this comment.
@lightydo thanks for the feedback, but the log that you provided has nothing to do with this issue. The warning about Octokit are just that, warnings, but not an error.
