### ISSUE TITLE
how to modify github's gist access token?

### ISSUE THREAD

**Issue by gadmyth** [shanalikhan/code-settings-sync#777]
I enter the wrong gist access token, but I can't modify it, even if I reinstall the extension again. Can somebody help me?

**Comment by shanalikhan** [comment]
Here are the details for Global Settings for Settings Sync from which you can change the token.

https://github.com/shanalikhan/code-settings-sync#global-settings

**Comment by ctf0** [comment]
@shanalikhan can i ask why the `syncLocalSettings.json` is not also synced , or would it cuz an internal issue to the package if i synced manually ?

**Comment by shanalikhan** [comment]
because `syncLocalSettings.json` contains `token` which is not safe.
Github also doesnt allow token to upload in gist as a content.

**Comment by ctf0** [comment]
@shanalikhan i just tried and added `syncLocalSettings` as custom file to upload and it worked.

i understand the security issue of uploading the token to the gist, but as its private/secret so i think its okay to include it along with the rest of the synced items, still many many thanx for ur hard work :trophy:
