### ISSUE TITLE
Download Other User's Gist without Token

### ISSUE THREAD

**Issue by YouthInnoLab** [shanalikhan/code-settings-sync#780]
I try to setting sync to a new gist, but it was belongs to a github author, I only know its gist, but not the token (obviously), how I upload and using this gist (so my configuration will be the same as his), I am new in VSCODE, please give me the advice, thanks.

**Comment by shanalikhan** [comment]
https://github.com/shanalikhan/code-settings-sync#global-settings

See the Global Settings, you need to turn on the `downloadPublicGist` in order to download other user gist.
