### ISSUE TITLE
Can't upload - Mac OS.

### ISSUE THREAD

**Issue by MichelDiz** [shanalikhan/code-settings-sync#784]
🐛 **Describe the bug**  
A clear and concise description of what the bug is. You are always welcome to check the [Troubleshooting](https://github.com/shanalikhan/code-settings-sync/wiki/Troubleshooting) section before filing the ticket.

🌴 **Visual Studio Code Version :** 1.31.1  
🌴 **Code Settings Sync Version :** 3.2.5 
🌴 **Standard or Insiders :** Standard 
🌴 **OSS or Portable :** OSS 
🌴 **Operating System :** macOS Mojave 10.14.1 
🌴 **Occurs On:** Upload
🌴 **Proxy Enabled:**  No 
🌴 **Gist Id:** d874974cc86da50577a047d23554add3 (the file gist or my own ID?)

💪 **Expected behavior**
Upload my settings.

📺 **Console Error Log** 
![captura de tela 2019-02-26 as 12 35 42](https://user-images.githubusercontent.com/6570955/53425034-0e219a80-39c3-11e9-8fce-1972b4c86811.png)
![captura de tela 2019-02-26 as 12 35 15](https://user-images.githubusercontent.com/6570955/53425046-124db800-39c3-11e9-98d6-856a6906c83b.png)

📺  **Additional context**
It possible to download and apply the settings. But If I try to upload. Gets errors.

**Comment by shanalikhan** [comment]
https://github.com/shanalikhan/code-settings-sync/wiki/Troubleshooting#invalid-gist-id-or-invalid--expired-github-token

**Comment by MichelDiz** [comment]
yeah, is that one.

**Comment by MichelDiz** [comment]
Well, I've "Reset" it. And tried again. Works, but it created a new (diff) gist for this settings. Both (the old and new) are there. That's odd, but okay...

**Comment by shanalikhan** [comment]
you can set the gist id to old one, instead of download, upload the settings there.
