### ISSUE TITLE
Adding token via command palette creates a new gist automatically.

### ISSUE THREAD

**Issue by drewswaycool** [shanalikhan/code-settings-sync#785]
I had sync setup on one machine and went to download settings on another machine.

After generating a new token, and putting it in via the command palette in VSCode, it created and uploaded a new gist... This is problem as I didn't want to create a new gist, I just wanted download the current one I had after putting in the new token.

The only way to get the correct settings downloaded is to manually put the token in in the `syncLocalSettings.json`. That way a new gist is not created and it will use the one that already exists.

**Comment by shanalikhan** [comment]
On Downloading, it ask for both token and gist. 
you need to add both in order to download the existing GIST.
