### ISSUE TITLE
GitHub Enterprise

### ISSUE THREAD

**Issue by tibmeister** [shanalikhan/code-settings-sync#788]
🐛 **Describe the bug**  
When trying to use my GitHub Enterprise, I get the error  "Sync: Internet not connected or unable to connect to GitHub. Exception logged in Console".  I changed the "githubEnterpriseUrl" setting to https://api.github.mycompany.com" and have verified it's valid in my browser.
Is there advanced logging I can enable to see exactly what is going on?

🌴 **Visual Studio Code Version :** 1.31.1
🌴 **Code Settings Sync Version :** 3.2.6 
🌴 **Standard or Insiders :** Standard
🌴 **OSS or Portable :** User Install 
🌴 **Operating System :** Windows 10 Enterprise
🌴 **Occurs On:** Always
🌴 **Proxy Enabled:** No
🌴 **Gist Id:** N/A

**Comment by shanalikhan** [comment]
See on developer tools, from help menu.

**Comment by tibmeister** [comment]
So I did find the logging, but the root issue is still unresolved.   Here's the error message;
`HttpError: request to https://api.github.mycompany.com/gists failed, reason: Hostname/IP does not match certificate's altnames: Host: api.github.mycompany.com. is not in the cert's altnames: DNS:github.mycompany.com`
Is there an option to ignore SSL cert errors if we choose to?  I can see this being a problem for self-signed certs as well.
