### ISSUE TITLE
Extensions settings cleared in uploaded gist; subsequent download flushes all installed extensions

### ISSUE THREAD

**Issue by tillig** [shanalikhan/code-settings-sync#789]
🐛 **Describe the bug**  
As of version 3.2.6, any time I upload my settings to my gist, the list of extensions in extensions.json is entirely empty. Thus, if I then download my settings in a different instance of VS Code... it removes all extensions.

🌴 **Visual Studio Code Version :** 1.31.1 
🌴 **Code Settings Sync Version :** 3.2.6 
🌴 **Standard or Insiders :** Standard
🌴 **OSS or Portable :** OSS 
🌴 **Operating System :** Windows 10 
🌴 **Occurs On:** Upload
🌴 **Proxy Enabled:** No
🌴 **Gist Id:** It appears the syncSettings.json file contains a token of some nature; I'd prefer to not pass that around.

📰 **To Reproduce**
1. Ctrl+Shift+P, Upload Settings
2. View gist for extensions.json - it's empty (`[]`)

💪 **Expected behavior**
The extensions should be in there.

**Comment by chalkygames123** [comment]
Related: https://github.com/shanalikhan/code-settings-sync/issues/756

**Comment by tillig** [comment]
Yep, could be duplicate. I am using the installed version of VS Code, not portable, but it sounds the same.

**Comment by shanalikhan** [comment]
Yes, it will be fixed a day or two.

**Comment by LuisUrrutia** [comment]
So sorry, my PR #782 broke the extension sync on windows systems because the path delimiter (Linux/macOS: `/` and Windows `\`) but it should be fixed with #791.
@shanalikhan I think that It should be released as a hotfix, right?

**Comment by shanalikhan** [comment]
released `v3.2.7`

**Comment by tillig** [comment]
Just tried it, works great. Thanks for the quick fix!
