### ISSUE TITLE
Pipe delimiter in files disables ability to clone gist

### ISSUE THREAD

**Issue by tillig** [shanalikhan/code-settings-sync#793]
🐛 **Describe the bug**  
Usually you can [fork and clone gists](https://help.github.com/en/articles/forking-and-cloning-gists) just like any other git repo. This is useful in cases like #756 where an upload corrupts settings and you want to try and roll back to a previous settings version.

However, files stored in child folders (like snippets) are done so by naming the file using a pipe delimiter:

![Pipe delimiter in filename](https://user-images.githubusercontent.com/1156571/53900298-15632c80-3ff1-11e9-83d1-e0fa162e931f.jpg)

The web UI for a gist doesn't have enough to allow reverting; but you also can't clone the gist with git and do a rollback that way because git won't allow you to put a filename with a pipe in it down into the filesystem. You're stuck.

It'd be nice if the delimiter was something that could be put into the filesystem so in times when the gist needs to be cloned or manipulated with git that would be possible.

🌴 **Visual Studio Code Version :** 1.31.1 
🌴 **Code Settings Sync Version :** 3.2.7 
🌴 **Standard or Insiders :** Standard 
🌴 **OSS or Portable :** OSS
🌴 **Operating System :** Windows 10
🌴 **Occurs On:** Download
🌴 **Proxy Enabled:** No

📰 **To Reproduce**
1. Create a custom snippet.
2. Upload settings to your gist.
3. Try cloning the gist using [the GitHub instructions](https://help.github.com/en/articles/forking-and-cloning-gists)
4. Git fails due to the pipe in the filename.

**Comment by shanalikhan** [comment]
Actually for reverting and other things, Settings Sync will have #413 feature.
So for GIST, I am not looking to improve ,rather move to `git` sync instead of `gist` sync.

So closing this issue.
