### ISSUE TITLE
Set NODE_TLS_REJECT_UNAUTHORIZED to 0 conditionally behind a settings flag

### ISSUE THREAD

**Issue by bernardop** [shanalikhan/code-settings-sync#794]
After the 3.2.6 update I haven't been able to use this extension. Whenever I try to update/upload I get an error (Sync: Internet not connected or unable to connect to GitHub. Exception logged in Console). When I look at the console there's a couple of "unable to verify the first certificate" errors. I have tried setting my `http.proxyStrictSSL` to `false` and launching vs code with the `--ignore-certificate-errors` flag without any luck.

What do you think of having a setting that would set `NODE_TLS_REJECT_UNAUTHORIZED` to 0 right before a network request and set it back to 1 right after?

![screen shot 2019-03-07 at 12 06 54 pm](https://user-images.githubusercontent.com/28455/53974859-8da11f00-40d1-11e9-8be1-c9026e82ced7.png)

**Comment by shanalikhan** [comment]
I would recommend you to discuss this on:

https://github.com/shanalikhan/code-settings-sync/issues/776
