### ISSUE TITLE
Can't update gist setting

### ISSUE THREAD

**Issue by Jvalal** [shanalikhan/code-settings-sync#798]
🐛 When I try to update my gist with a different / correct gist ID I keep getting an error

![image](https://user-images.githubusercontent.com/3803053/54480227-19f2c680-47e3-11e9-8cee-fad0015080ea.png)

🌴 **Visual Studio Code Version :** [ 1.31 AND 1.32 ] 
🌴 **Code Settings Sync Version :** [ 3.27 ] 
🌴 **Standard or Insiders :** [ _here_ ] 
🌴 **OSS or Portable :** [ _here_ ] 
🌴 **Operating System :** [ Mac OSjojave 10.14.3 (18D109) ] 
🌴 **Occurs On:** [Trying to change Help Configuring ]
🌴 **Proxy Enabled:** [ Yes / No ]
🌴 **Gist Id:** [ 566cede45f911db70109f918440b48eb ]

📰 **To Reproduce**

💪 **Expected behavior**
The ability to change / update my gist

📺 **Console Error Log** 
If applicable, add screenshots or paste the console log from developer console of VSCode.

📺  **Additional context**

**Comment by Jvalal** [comment]
Bump!

**Comment by shanalikhan** [comment]
check the troubleshooting page from the wiki page to how to resolve the Not found errors.
