### ISSUE TITLE
Sync doesnt want to upload.

### ISSUE THREAD

**Issue by SirTwsted** [shanalikhan/code-settings-sync#799]
When trying to upload via SYNC , I get an error popup window and the SYNC 
doesnt seem to want to do its job.
Yes, I have already set up a GIST as I followed the instructions.

VS-Code Version: 1.32.3 (system setup)
Date: 2019-03-14T23:43:35.476Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 6.1.7601
.
![Screenshot_38](https://user-images.githubusercontent.com/15247713/54487220-d42d1100-4869-11e9-88f8-a8075434bbba.png)

**Comment by shanalikhan** [comment]
whats the error logged in console ?

**Comment by SirTwsted** [comment]
for some odd reason, there is nothing in console.

**Comment by shanalikhan** [comment]
The console is available on Help Menu > Toogle Developer tools
are shown in the image.

**Comment by digeomel** [comment]
I have the same problem, and the error I get in the console is:

![image](https://user-images.githubusercontent.com/3295889/54526643-a8984c80-4977-11e9-9b93-de3138691a52.png)

In my vscode setttings I have:

"http.proxyStrictSSL": false,

And I'm on Windows 10 behind a corporate proxy.

**Comment by digeomel** [comment]
Notice that back in summer when I installed the extension, I managed to upload fine:

"lastUpload": "2018-08-27T09:37:00.854Z",

**Comment by przpl** [comment]
I can't upload settings because I have the following error:

![Screenshot from 2019-03-19 12-28-42](https://user-images.githubusercontent.com/9073573/54602956-5c1a4300-4a43-11e9-92fc-c9bf281dfc50.png)

**Comment by shanalikhan** [comment]
https://github.com/shanalikhan/code-settings-sync/issues/799#issuecomment-473869577 is due to certificates problem. see the link here 
https://code.visualstudio.com/docs/setup/network#_ssl-certificates

> back in summer when I installed the extension, I managed to upload

Yes as Settings Sync was completely disabling the SSL certificates issue which was reported and fixed : https://github.com/shanalikhan/code-settings-sync/issues/776
Check the comments there and see if any options help

**Comment by digeomel** [comment]
> 
> 
> [#799 (comment)](https://github.com/shanalikhan/code-settings-sync/issues/799#issuecomment-473869577) is due to certificates problem. see the link here
> https://code.visualstudio.com/docs/setup/network#_ssl-certificates
> 
> > back in summer when I installed the extension, I managed to upload
> 
> Yes as Settings Sync was completely disabling the SSL certificates issue which was reported and fixed : #776
> Check the comments there and see if any options help

Thank you for your answer and the links you provided. The only thing that worked for me finally was to set up a Windows environment variable NODE_TLS_REJECT_UNAUTHORIZED=0.
I realize this is a security risk, but when you are behind an MS corporate proxy like ours, you're not left with many choices.

**Comment by SirTwsted** [comment]
I would like to add a small note that my sister figured out.
If you have any errors in the settings.json file after editing that file or something.
Sync will not upload or work until there are no errors in the Settings.json file of VS Code.
just a heads up, something she bumped into recently.

**Comment by shanalikhan** [comment]
Yes, `settings.json` should be valid JSON
