### ISSUE TITLE
auto upload doesn't work when make change on settings

### ISSUE THREAD

**Issue by hfcheng66** [shanalikhan/code-settings-sync#801]
Auto upload doesn't work when make change on settings (MAC)

auto uploading is on.
using cmd+, to open settings page, make change config change. sync setting doesn't upload settings.
if I open settings.json file and press cmd+s to save the file, sync setting starts sync after 5 seconds, worked as expected.

🌴 **Visual Studio Code Version :** [ 1.32.3 ] 
🌴 **Code Settings Sync Version :** [ 3.2.7 ] 
🌴 **Standard or Insiders :** [ standard ] 
🌴 **OSS or Portable :** [ _here_ ] 
🌴 **Operating System :** [ Macpro mojave 10.14.3 ] 
🌴 **Occurs On:** [Upload]
🌴 **Proxy Enabled:** [ No ]
🌴 **Gist Id:** [ ID_HERE ]

📰 **To Reproduce**
open settings page, make change. 
sync setting didn't upload setting

💪 **Expected behavior**
sync setting should upload upon new change.

📺 **Console Error Log** 
If applicable, add screenshots or paste the console log from developer console of VSCode.
no

📺  **Additional context**

**Comment by rafaelrenanpacheco** [comment]
Exactly same behavior on Arch Linux.

:palm_tree: Visual Studio Code Version : [ 1.32.3 ]
:palm_tree: Code Settings Sync Version : [ 3.2.7 ]
:palm_tree: Operating System : [ Arch Linux 5.0.2 ]
:palm_tree: Occurs On: [Upload]
:palm_tree: Proxy Enabled: [ No ]

**Comment by arnohovhannisyan** [comment]
Same on Windows 10 1809 Build 17763.379

**Comment by shanalikhan** [comment]
Its fixed in v2.3.8. Update and let me know

**Comment by saurabh-hirani** [comment]
@shanalikhan Thanks for creating sync-settings - it's really great. I am running into this same issue and I am using the latest version 

Visual Studio Code Version : [ 1.40.2 ]
Code Settings Sync Version : [ v3.4.3 ]
Operating System : [ MacOS Mojave ]
 Occurs On: [Upload]
 Proxy Enabled: [ No ]

I have "sync.autoUpload" set to true and yet on changing settings i.e. making changes to settings.json in VSCode the gist isn't updated. Just wanted to check if I should file a new issue or is there any additional debugging info I can provide?

**Comment by ctf0** [comment]
@shanalikhan  hi , autoupload stopped working for the last couple of months

```
Version: 1.49.0-insider
Commit: e4256dd1a02339bb1d56647ecd9134bf38bc7c03
Date: 2020-09-04T18:47:13.407Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 18.7.0
```
