### ISSUE TITLE
Internet Not Connected or Unable to Connect to GitHub. Exception Logged in Console

### ISSUE THREAD

**Issue by Bill-Stewart** [shanalikhan/code-settings-sync#802]
🐛 **Describe the bug**  
Getting this message: Internet Not Connected or Unable to Connect to GitHub. Exception Logged in Console

🌴 **Visual Studio Code Version :**  1.32.3 (user setup)
🌴 **Code Settings Sync Version :** 3.2.6 and 3.2.7
🌴 **Standard or Insiders :** N/A
🌴 **OSS or Portable :** N/A
🌴 **Operating System :** Windows 10 x64
🌴 **Occurs On:** Any
🌴 **Proxy Enabled:** No
🌴 **Gist Id:** a5f80e27e471936379a4925f173b78b1

📰 **To Reproduce**
1. Sync : Reset Extension Settings
2. Sync : Update / Upload Settings
3. [I enter my personal access token]
4. Get error on status line: Internet Not Connected or Unable to Connect to GitHub. Exception Logged in Console

💪 **Expected behavior**
Settings should upload.

📺  **Additional context**
This was working previously, but not sure exactly when it stopped working.

**Comment by radiocity** [comment]
```
TypeError: Cannot read property 'gists' of null
	at module.exports.t.GitHubService.<anonymous> (C:\Users\Docker\.vscode\extensions\shan.code-settings-sync-3.2.7\out\extension.js:14:32313)
	at Generator.next (<anonymous>)
	at module.exports.n (C:\Users\Docker\.vscode\extensions\shan.code-settings-sync-3.2.7\out\extension.js:14:30756)
	at new Promise (<anonymous>)
	at module.exports.n (C:\Users\Docker\.vscode\extensions\shan.code-settings-sync-3.2.7\out\extension.js:14:30533)
	at module.exports.t.GitHubService.ReadGist (C:\Users\Docker\.vscode\extensions\shan.code-settings-sync-3.2.7\out\extension.js:14:32255)
	at C:\Users\Docker\.vscode\extensions\shan.code-settings-sync-3.2.7\out\extension.js:7:32923
	at Generator.next (<anonymous>)
	at module.exports.n (C:\Users\Docker\.vscode\extensions\shan.code-settings-sync-3.2.7\out\extension.js:7:27414)
	at new Promise (<anonymous>)
	at module.exports.n (C:\Users\Docker\.vscode\extensions\shan.code-settings-sync-3.2.7\out\extension.js:7:27191)
	at C:\Users\Docker\.vscode\extensions\shan.code-settings-sync-3.2.7\out\extension.js:7:32684
	at module.exports.t.Sync.<anonymous> (C:\Users\Docker\.vscode\extensions\shan.code-settings-sync-3.2.7\out\extension.js:7:36663)
	at Generator.next (<anonymous>)
	at s (C:\Users\Docker\.vscode\extensions\shan.code-settings-sync-3.2.7\out\extension.js:7:27247)
```

**Comment by radiocity** [comment]
The following steps help to me: 

1. [Install previous versions](https://code.visualstudio.com/updates/v1_30#_install-previous-versions) of code-settings-sync
2. Generate [new token](https://github.com/settings/tokens/new) with `gist` scope selected
3. Go to `F1` → `Sync: Advanced Options` → `Sync: Edit Extension Local Settings`
4. Fill `token` parameter with new token
5. Save changes
6. [Install last version](https://code.visualstudio.com/updates/v1_30#_install-previous-versions) of code-settings-sync

**Comment by shanalikhan** [comment]
> Exception Logged in Console

Whats the exception logged in console ?

**Comment by Bill-Stewart** [comment]
> Whats the exception logged in console ?

How do I find that?

**Comment by Bill-Stewart** [comment]
> 
> 
> The following steps should help:
> 
>     1. [Install previous versions](https://code.visualstudio.com/updates/v1_30#_install-previous-versions) of code-settings-sync
> 
>     2. Generate [new token](https://github.com/settings/tokens/new) with `gist` scope selected
> 
>     3. Go to `F1` → `Sync: Advanced Options` → `Sync: Edit Extension Local Settings`
> 
>     4. Fill `token` parameter with new token
> 
>     5. Save changes
> 
>     6. [Install last version](https://code.visualstudio.com/updates/v1_30#_install-previous-versions) of code-settings-sync

Thank you. I tried your steps, but I get the identical error as before.

**Comment by Bill-Stewart** [comment]
Disabled extension auto-update and installed 3.2.5. Sync working again.

3.2.7 gives the error, and I can't find the actual exception message anywhere in logs.

**Comment by shanalikhan** [comment]
> How do I find that?

help Menu > Toogle Developer Tools - Console.

Actually Settings Sync disabling all the SSL certificates in `3.2.5` and its fixed now. Before saying anything, lets see whats logged in console

**Comment by Bill-Stewart** [comment]
Ah, that's it - a certificate error. We require a self-signed certificate in the certificate chain (this is required in our organization for web filtering). Is there any way around this?

**Comment by shanalikhan** [comment]
Check this if it helps

https://github.com/shanalikhan/code-settings-sync/issues/776#issuecomment-466420221

**Comment by Bill-Stewart** [comment]
I agree that an extension should not disable certificate errors for all of VS code.

The VS Code page states that if the certificate is trusted by the OS, then Chromium should trust it also.

The certificate is trusted by my machine's OS (Windows 10).

Going to Github works fine in Chrome browser without any certificate errors or problems.

Tried launching code with `--ignore-certificate-errors` on the command line but this had no effect.

Please advise.

**Comment by Bill-Stewart** [comment]
Interesting. I uninstalled and reinstalled the VS Code `win-ca` extension and this seems to have fixed it on one machine.

I will try this on the other machines and report back and possibly close this issue.

**Comment by Bill-Stewart** [comment]
Yes this is the fix - the other machines that exhibited this issue were missing this extension. This is resolved.

**Comment by shanalikhan** [comment]
Glad to know u fixed it. 🙂

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
