### ISSUE TITLE
'Unexpected end of JSON input' on download

### ISSUE THREAD

**Issue by malmaud** [shanalikhan/code-settings-sync#806]
🐛 **Describe the bug**  
A clear and concise description of what the bug is. You are always welcome to check the [Troubleshooting](https://github.com/shanalikhan/code-settings-sync/wiki/Troubleshooting) section before filing the ticket.

🌴 **Visual Studio Code Version :**  1.32.3
🌴 **Code Settings Sync Version :** 3.2.7
🌴 **Standard or Insiders :** standard
🌴 **OSS or Portable :** neither, conventional install
🌴 **Operating System :** os x 10.14
🌴 **Occurs On:** download
🌴 **Proxy Enabled:** no
🌴 **Gist Id:** 64afc42c160cca771c6e871caea06f77

📰 **To Reproduce**
Issue 'Download settings' command after having successfully inputted my gist token.

💪 **Expected behavior**
Settings downloads.

📺 **Console Error Log** 
I get an error dialog that an error was logged to the console. The developer console shows 

```
Extension Host] SyntaxError: Unexpected end of JSON input
	at JSON.parse (<anonymous>)
	at /Users/malmaud/.vscode/extensions/shan.code-settings-sync-3.2.7/out/extension.js:7:33208
	at Generator.next (<anonymous>)
	at s (/Users/malmaud/.vscode/extensions/shan.code-settings-sync-3.2.7/out/extension.js:7:27247)
	at process._tickCallback (internal/process/next_tick.js:68:7)
t.log @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:272
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2328 
```

📺  **Additional context**
I tried uninstalling and reinstalling the extension, and deleting `.vscode/extensions/.shan*` directories, but the error persists.

**Comment by shanalikhan** [comment]
Try running `Sync : Reset ` command

**Comment by malmaud** [comment]
I tried, then tried downloading my settings again, went through the process of reinputting my gist id and token, and then got the same error.

**Comment by shanalikhan** [comment]
Check either this file is invalid - `syncLocalSettings.json` inside User folder
In this file you can manually paste the token.

Also check either your `settings.json` file is valid.

**Comment by malmaud** [comment]
I tried deleting both those files, resetting sync settings, tried again, and got the same error. The settings.json in the gis is valid. I do notice the gist has many files that start with `.mypy_cache` - perhaps that's related? eg https://gist.githubusercontent.com/malmaud/64afc42c160cca771c6e871caea06f77/raw/c1a21478caff6e2eda122cf0558f3c86f77567f6/.mypy_cache%257C3.7%257C_ast.data.json. .

Some of my projects  do have a `.mypy_cache` folder, but I never manually added any its contents to the gist. Could there be a glitch that caused this extension to erroneously add them to the gist, and that's related?

**Comment by shanalikhan** [comment]
https://github.com/shanalikhan/code-settings-sync#global-settings

Try with adding `.mypy_cache` folder into `ignoreUploadFolders` in Global Settings.
Hope that helps.

**Comment by malmaud** [comment]
It doesn't. I've tried resetting sync settings, deleting the old gist, uploading settings, then downloading settings on the same machine after excluding `.mypy_cache`; same error.

**Comment by shanalikhan** [comment]
> eleting the old gist, uploading settings, then downloading settings on the same machine after excluding .mypy_cache

So you have added `.mypy_cache` in to the `ignoreUploadFolders`. Can you verify  `.mypy_cache` is removed from the GIST files or not ?

**Comment by malmaud** [comment]
Thanks!

**Comment by malmaud** [comment]
I just tried updating to 3.2.8, deleting the gist, resetting my code sync settings, uploading and then downloading again, and got the same error.

**Comment by shanalikhan** [comment]
> you have added .mypy_cache in to the ignoreUploadFolders

Try adding the folder in ignoreUploadFolders in new gist. It will stop that folder contents to upload there.

**Comment by malmaud** [comment]
Ok, adding `.mypy_cache` to `ignoreUploadFolders` does solve the problem. But isn't there still a bug here? Why do I need to exclude that folder?

**Comment by shanalikhan** [comment]
Actually the goal is to keep the files that should be valid. 
Some extension may store high binary files or any other data type that is not valid for Sync.

But what is your scenario, what are the content of `.mypy_cache` ?

**Comment by malmaud** [comment]
It's produced by the `mypy` program, which does static type checking of Python files. It seems to consist of a large number of JSON files that represent a cache of its analysis. 

Perhaps the underlying issue is some of those JSON files are invalid according to the VSCode JSON parser, but valid according to whatever JSON system mypy is using internally. But that shouldn't break this extension.

**Comment by jelowin** [comment]
Does anyone have more info about this? I'm having this problem downloading a gist

**Comment by akwala** [comment]
I'm seeing this on one of my hosts. I've tried the following without joy:
- Verified the correctness of `settings.json` and `syncLocalSettings.json` 
- Added `".mypy_cache"` to `ignoreUploadFolders`
- Fresh config dir (~/.config/VSCodium)
- Fresh gist

The error:
```
workbench.desktop.main.js:97 [Extension Host] Sync : Connected with user : 'username'
workbench.desktop.main.js:624   ERR [Extension Host] Sync: Result content is not a valid JSON. Unexpected end of JSON input
workbench.desktop.main.js:97 [Extension Host] Sync: Result content is not a valid JSON. Unexpected end of JSON input
I @ workbench.desktop.main.js:97
workbench.desktop.main.js:624   ERR [Extension Host] TypeError: Cannot read properties of undefined (reading 'trim')
	at e.toggleComments (/home/userx/.vscode-oss/extensions/shan.code-settings-sync-3.4.3-universal/out/extension.js:726:6351)
	at e.checkNextLines (/home/userx/.vscode-oss/extensions/shan.code-settings-sync-3.4.3-universal/out/extension.js:726:6813)
	at e.getIgnoredBlocks (/home/userx/.vscode-oss/extensions/shan.code-settings-sync-3.4.3-universal/out/extension.js:726:6156)
	at e.processBeforeWrite (/home/userx/.vscode-oss/extensions/shan.code-settings-sync-3.4.3-universal/out/extension.js:726:4806)
	at /home/userx/.vscode-oss/extensions/shan.code-settings-sync-3.4.3-universal/out/extension.js:290:23304
	at /home/userx/.vscode-oss/extensions/shan.code-settings-sync-3.4.3-universal/out/extension.js:290:11611
	at Object.next (/home/userx/.vscode-oss/extensions/shan.code-settings-sync-3.4.3-universal/out/extension.js:290:11716)
	at a (/home/userx/.vscode-oss/extensions/shan.code-settings-sync-3.4.3-universal/out/extension.js:290:10462)
workbench.desktop.main.js:97 [Extension Host] TypeError: Cannot read properties of undefined (reading 'trim')
	at e.toggleComments (/home/userx/.vscode-oss/extensions/shan.code-settings-sync-3.4.3-universal/out/extension.js:726:6351)
	at e.checkNextLines (/home/userx/.vscode-oss/extensions/shan.code-settings-sync-3.4.3-universal/out/extension.js:726:6813)
	at e.getIgnoredBlocks (/home/userx/.vscode-oss/extensions/shan.code-settings-sync-3.4.3-universal/out/extension.js:726:6156)
	at e.processBeforeWrite (/home/userx/.vscode-oss/extensions/shan.code-settings-sync-3.4.3-universal/out/extension.js:726:4806)
	at /home/userx/.vscode-oss/extensions/shan.code-settings-sync-3.4.3-universal/out/extension.js:290:23304
	at /home/userx/.vscode-oss/extensions/shan.code-settings-sync-3.4.3-universal/out/extension.js:290:11611
	at Object.next (/home/userx/.vscode-oss/extensions/shan.code-settings-sync-3.4.3-universal/out/extension.js:290:11716)
	at a (/home/userx/.vscode-oss/extensions/shan.code-settings-sync-3.4.3-universal/out/extension.js:290:10462)
I @ workbench.desktop.main.js:97
workbench.desktop.main.js:759 Sync: Error Logged In Console (Help menu > Toggle Developer Tools).
```
Setting Sync v.3.4.3
