### ISSUE TITLE
Null error when using public gist

### ISSUE THREAD

**Issue by jb8893** [shanalikhan/code-settings-sync#809]
🐛 **Describe the bug**  
When trying to download from a public gist I get "Cannot read property 'gists' of null.

🌴 **Visual Studio Code Version : 1.32.3 
🌴 **Code Settings Sync Version : 3.2.7
🌴 **Standard or Insiders : Standard
🌴 **OSS or Portable : OSS
🌴 **Operating System : Windows 10
🌴 **Occurs On: Download
🌴 **Proxy Enabled:  No
🌴 **Gist Id: 15d0974f65ac04578bc76396fb3363fc

📰 **To Reproduce**
1. Go to sync advanced options, and click download from public gist
2. Go to download settings, and enter new public gist

📺  **Additional context**

![Capture](https://user-images.githubusercontent.com/689432/55028474-272b6480-4fde-11e9-9d98-75aa1eabc7be.PNG)

**Comment by arnohovhannisyan** [comment]
Try running `> Sync : Reset Extension Settings` and see if it fixes it. Same error as #816

**Comment by arnohovhannisyan** [comment]
Also, try updating to the newest version, v3.2.8

**Comment by douglasdeoliveira** [comment]
I still have this same problem in version 3.2.8

**Comment by arnohovhannisyan** [comment]
@douglasdeoliveira Try this
https://github.com/shanalikhan/code-settings-sync/issues/816#issuecomment-481623181

**Comment by douglasdeoliveira** [comment]
> @douglasdeoliveira Try this
> [#816 (comment)](https://github.com/shanalikhan/code-settings-sync/issues/816#issuecomment-481623181)

Thank you very much but it is not working completely. Did not download all my synced plugins and did not remove the old ones. But you could help me here.
Waiting for the new release ...

**Comment by arnohovhannisyan** [comment]
@douglasdeoliveira Are `sync.syncExtensions` and `sync.removeExtensions` enabled in your settings?

**Comment by douglasdeoliveira** [comment]
> @douglasdeoliveira Are `sync.syncExtensions` and `sync.removeExtensions` enabled in your settings?

Yeah, both are activated

**Comment by arnohovhannisyan** [comment]
@douglasdeoliveira Since your new issue doesn't have anything to do with this one, you should open a new issue and share some additional information that could help fix it.
