### ISSUE TITLE
Ran sync download, and overwrote a lot of changes I had made

### ISSUE THREAD

**Issue by Frazer** [shanalikhan/code-settings-sync#815]
🐛 **Describe the bug**  

when 2 computers have made changes to the settings, and they are out of sync, running sync download will overwrite changes that have been made locally.

📰 **To Reproduce**
1.  make changes to your settings on 1 computer
2. make changes on another computer
3. upload those settings
4. download settings on first computer

(settings from step 1 will be lost)

possible also happens with:
1.  make changes to your settings
2. download settings

💪 **Expected behavior**
a warning saying that there are uncommitted changes, asking you to merge

**Comment by shanalikhan** [comment]
Settings Sync will be git sync feature in upcoming versions.
We can fix this behavior using `git` sync instead of `gist` sync.
