### ISSUE TITLE
Inserts some empty lines in the beginning of `settings.json` during `Download Settings`

### ISSUE THREAD

**Issue by osya** [shanalikhan/code-settings-sync#819]
🐛 **Describe the bug**  
Inserts some empty lines in the beginning of `settings.json` during `Download Settings`

🌴 **Visual Studio Code Version : 1.32.3 (on both machines)
🌴 **Code Settings Sync Version : 3.2.7 (on both machines)
🌴 **Standard or Insiders : standard (on both machines)
🌴 **OSS or Portable : I am not sure
🌴 **Operating System : Windows 10 Pro x64 (on both machines)
🌴 **Occurs On:** Download
🌴 **Proxy Enabled: No (on both machines)
🌴 **Gist Id: it's private

📰 **To Reproduce**
1. Make `Update / Upload Settings` on 1st machine
2. Make `Download Settings` on 2nd machine. In the `settings.json` on the 2nd machine 
3 empty lines inserted after 1st open curly brace. These lines missed in the `settings.json` on 1st machine

💪 **Expected behavior**
Unnecessary empty lines in `settings.json` should no be inserted during Download

📺 **Console Error Log** 
No Sync errors in the Help Menu > Developer Tool - Console Tab

**Comment by shanalikhan** [comment]
its fixed in `v3.2.9`
