### ISSUE TITLE
Toggle Auto Download not available

### ISSUE THREAD

**Issue by Boggin** [shanalikhan/code-settings-sync#82]
**Visual Studio Code Version :** 1.4.0
**Code Sync Settings Version :** 2.2.2
**Operating System :** W10 Pro

Please make sure to write the versions and console logged error picture or copied text.

In the documentation:
"Select Command "Toggle Auto Download" command to Turn ON / OFF the auto download."

The problem is I don't have such a command.

Also, what is the default for the toggle? I'm guessing it's "public autoSync : boolean = true;" from the settings but it'd be useful to have that stated in the documentation.

I believe this wasn't working for a while as my Gist was quite out of date. Suddenly reverted today. I'm afraid I've no more useful information about that.

**Comment by shanalikhan** [comment]
Toggle Auto Download is now a part of advance options.
I will update the document and write all things with the upcoming update.
Thanks
