### ISSUE TITLE
Error when uploading gist

### ISSUE THREAD

**Issue by larrym** [shanalikhan/code-settings-sync#829]
🐛 **Describe the bug**  
A clear and concise description of what the bug is. You are always welcome to check the [Troubleshooting](https://github.com/shanalikhan/code-settings-sync/wiki/Troubleshooting) section before filing the ticket.

🌴 **Visual Studio Code Version : 1.33.0 
🌴 **Code Settings Sync Version : 3.2.8
🌴 **Standard or Insiders : Standard
🌴 **OSS or Portable : 
🌴 **Operating System : Windows 10 Pro
🌴 **Occurs On: Upload
🌴 **Proxy Enabled: No 
🌴 **Gist Id: 9bd30bdd1594daff0a48b5f72b330db4ea087997

📰 **To Reproduce**
1. Go to Command prompt, Sync, Upload (Shift+Alt+U does not work)
2. Click on Immediate error Sync : Error Logged In Console (Help menu > Toggle Developer Tools).
3. Scroll down to 

💪 **Expected behavior**

📺 **Console Error Log** 
IHttpError: Not Found
	at module.exports.e.exports.then.n.text.then.r (c:\Users\Larry\.vscode\extensions\shan.code-settings-sync-3.2.8\out\extension.js:130:50403)
at process._tickCallback (internal/process/next_tick.js:68:7)

📺  **Additional context**

**Comment by arnohovhannisyan** [comment]
Can you try removing the `sync.gist` setting from `settings.json` and trying to upload again? The error is caused by a 404 status from octokit, which might mean your gist id is invalid.

**Comment by larrym** [comment]
Yes, that did it. I am sorry I categorized this situation as a bug.

**Comment by arnohovhannisyan** [comment]
@larrym It's ok, at least you got it working :)

**Comment by gpgao** [comment]
please, i want to know how to remove the `sync.gist` setting from `settings.json` ?   is that delete the  `"token"` in the` synclocalsettings.json `,  if that's right, why i failed when i try upload again?
