### ISSUE TITLE
Information Message is not auto dismissed

### ISSUE THREAD

**Issue by karuna** [shanalikhan/code-settings-sync#83]
**Visual Studio Code Version :** 1.4.0
**Code Sync Settings Version :** 2.2.2
**Operating System :** LInux

The information message is a bother. Everytime I update extension, restart, the message will show.
`vscode.window.showInformationMessage("No extension need to be installed");`
For this kind of message please use `setStatusBarMessage` instead. 
Reference: https://github.com/Microsoft/vscode/issues/2732
https://code.visualstudio.com/docs/extensionAPI/vscode-api

**Comment by shanalikhan** [comment]
Update to 2.2.3 version 
Its solved
