### ISSUE TITLE
looping and opening links with auto upload on

### ISSUE THREAD

**Issue by k1nghat** [shanalikhan/code-settings-sync#830]
🐛 **Describe the bug**  
this started happening after the march update of VSCode came through. i restarted VSCode and noticed the latest sync update as well. everything seemed fine. auto upload was working on settings change. when i opened another VSCode workspace or editor i get a looping of the auto upload like 5+ times along with it opening this link: https://shanalikhan.github.io/2017/02/19/Option-to-ignore-settings-folders-code-settings-sync.html

🌴 **Visual Studio Code Version :** 1.33
🌴 **Code Settings Sync Version :** 3.2.8
🌴 **Standard or Insiders :** standard
🌴 **OSS or Portable :** OSS
🌴 **Operating System :** KDE Neon Stable
🌴 **Occurs On:** upload
🌴 **Proxy Enabled:** no
🌴 **Gist Id:** 111391f8d8ec31b6b78eed2dec646507

📰 **To Reproduce**
1. update to newest stable versions of both VSCode and Sync.
2. open VSCode project with files(not sure if that matters)
3. see auto upload looping

💪 **Expected behavior**
only cycle once?

📺 **Console Error Log** 
here are some log files:
Log (Extension Host):
https://paste.debian.net/hidden/5bfced26/
Log (Shared):
https://paste.debian.net/hidden/c3b20158/
Log (Window):
https://paste.debian.net/hidden/ab83cb59/
📺  **Additional context**
it seems to be happening only to project directories where i havent opened them yet after the new sync version was pushed yesterday. if i close VSCode and open it again from the same project directory it doesnt happen again. but a new project dir it will.

i dont know if it matters but my sync settings seem to be all over the place in my settings.json. anyways, here is that file:
https://paste.debian.net/hidden/44478cfa/

sync settings:
https://paste.debian.net/hidden/755f91dd/

**Comment by shanalikhan** [comment]
Please post the contents of custom settings of Settings Sync.
Meanwhile, you can turn off the auto upload.

**Comment by arnohovhannisyan** [comment]
You probably need to add the new ignored files and folders to your local config JSON file, or reset settings to add them automatically.

**Comment by k1nghat** [comment]
> You probably need to add the new ignored files and folders to your local config JSON file, or reset settings to add them automatically.

is this something i need to do per project or just once? not sure of the scope.

**Comment by arnohovhannisyan** [comment]
It's a one time thing. The way that files were ignored was updated in v3.2.8, so you need to reset settings to update the config. This will fix the looping.

**Comment by shanalikhan** [comment]
These are your ignore files
```
"ignoreUploadFiles": [
        "projects.json",
        "projects_cache_vscode.json",
        "projects_cache_git.json",
        "projects_cache_svn.json",
        "gpm_projects.json",
        "gpm-recentItems.json",
        "state.vscdb",
        "state.vscdb.backup",
        "syncLocalSettings.json",
        ".DS_Store",
        "sync.lock"
   }
```
@arnohovhannisyan
We need to know what files change event is being observed from the logs.

**Comment by arnohovhannisyan** [comment]
This is already in the code.

```
console.log(`Sync: ${FileService.ExtractFileName(path)} changed`);
```
