### ISSUE TITLE
No settings files saved

### ISSUE THREAD

**Issue by RickOrchard** [shanalikhan/code-settings-sync#84]
**Visual Studio Code Version :** [ 1.4.0 ]
**Code Sync Settings Version :** [ 2.2.3 ]
**Operating System :** [ Fedora 24 ]

It keeps uploading/updating empty settings files, and thus when downloading again erases all my current settings.

![schermafdruk van 2016-09-02 13-22-03](https://cloud.githubusercontent.com/assets/20968832/18202491/86e1b5b4-7110-11e6-897c-5e65431c84a3.jpg)

**Comment by shanalikhan** [comment]
can you post the console log when you upload the settings.

**Comment by RickOrchard** [comment]
It doesnt output anything.



Op 2 sep. 2016 1:42 PM schreef "Shan Khan" <notifications@github.com>:

**Comment by RickOrchard** [comment]
Where should i see its output?

2016-09-02 23:17 GMT+02:00 RiAsRa vdB <riasra05@gmail.com>:

**Comment by shanalikhan** [comment]
can you share the settings.json file contents and its location with a picture with path.

**Comment by RickOrchard** [comment]
I see the problem now, it keeps a separate settings.json file for each
folder/project. I didnt expect that.

2016-09-04 16:43 GMT+02:00 Shan Khan <notifications@github.com>:

**Comment by shanalikhan** [comment]
im sorry , i didnt get that, you have seperate settings.json for each project ?

**Comment by RickOrchard** [comment]
apparently, yes. I dont know why it does that. I have a few folders where i
keep my projects and each of them has a .vscode folder with a settings.json
file.
Weird, and more importantly, unwanted...

2016-09-05 11:28 GMT+02:00 Shan Khan <notifications@github.com>:

**Comment by shanalikhan** [comment]
this extension will only make backup of user settings.json file of vscode. 
Look on official document where user settings.json store.

It wont make any backup for any settings or any data of work spaces or projects.

**Comment by RickOrchard** [comment]
Got it. I guess i misunderstood that.

Tnx for the replies.

2016-09-05 22:50 GMT+02:00 Shan Khan <notifications@github.com>:
