### ISSUE TITLE
Can't upload and update settings

### ISSUE THREAD

**Issue by SamaneYaghoobi** [shanalikhan/code-settings-sync#844]
🐛 **Describe the bug**  
I typed >Sync in command palette and clicked Update/Upload settings, then I got this error:
Cannot read property 'StopWatching' of undefined

🌴 **Visual Studio Code Version :** 1.33.0 
🌴 **Code Settings Sync Version :** v3.2.8 
🌴 **Operating System :** Linux Mint 18.3
🌴 **Occurs On:** Upload

📺  **Additional context**
![screenshot](https://user-images.githubusercontent.com/22401814/56077423-553be180-5df1-11e9-8677-70608c5703a7.png)

**Comment by arnohovhannisyan** [comment]
Duplicate of #832

**Comment by arnohovhannisyan** [comment]
@SamaneYaghoobi Try restarting vscode

**Comment by we-taper** [comment]
Restarting vscode worked for me.

**Comment by SamaneYaghoobi** [comment]
@arnohovhannisyan Thanks, that's worked.
