### ISSUE TITLE
[Feature Request] Add custom CSS to sync

### ISSUE THREAD

**Issue by fakhamatia** [shanalikhan/code-settings-sync#848]
Please add option to upload and sync custom CSS file

**Comment by shanalikhan** [comment]
https://github.com/shanalikhan/code-settings-sync#global-settings

You need to add `css` extension on `supportedFileExtensions` inside Global Settings.
Let me know if it helps

**Comment by fakhamatia** [comment]
Not CSS extension . Custom CSS file for [this](https://marketplace.visualstudio.com/items?itemName=be5invis.vscode-custom-css) extension.
CSS for VSCode appearance In a specified paths

**Comment by shanalikhan** [comment]
What is the path of that file ? and what are the contents

**Comment by fakhamatia** [comment]
the path is changeable but set in setting.json like this:
`"vscode_custom_css.imports": [
        "file:////home/titan/.config/Code/custom.css"
    ],`

and contents CSS for VSCode appearance like this:
`.monaco-workbench .editor-status-indentation,
.monaco-workbench .editor-status-encoding,
.monaco-workbench .editor-status-eol, {
  display: none !important;
}
`
this code hide some items in status bar

**Comment by shanalikhan** [comment]
> "vscode_custom_css.imports": [ "file:////home/titan/.config/Code/custom.css" ],

If you want to add any file in Settings Sync.
Read the process here
https://github.com/shanalikhan/code-settings-sync/wiki/Custom-Sync

**Comment by fakhamatia** [comment]
yes tank you its work
when i download setting if file in new system not exist sync create file?

**Comment by shanalikhan** [comment]
>  when i download setting if file in new system not exist sync create file?

You need to import the file in order to work.
