### ISSUE TITLE
sync result document is shown again

### ISSUE THREAD

**Issue by reflog** [shanalikhan/code-settings-sync#85]
**Visual Studio Code Version :** insiders
**Code Sync Settings Version :** 2.2.3
**Operating System :** windows 10

Every  time VSCode is opened the sync result document is shown again and again, even though no changes were made.

**Comment by shanalikhan** [comment]
you need to toggle the summary to OFF mode so it wont open the page from the advance options.

When it downloads the new version it will only show in statur bar
