### ISSUE TITLE
Ignoring some specific settings

### ISSUE THREAD

**Issue by scythk** [shanalikhan/code-settings-sync#853]
💡 **Is your feature request related to a problem? Please describe.**
I'm working on both Mac and Win so I'm wondering if there's an option to ignore certain setting like font size, python path or else.

💡 **Describe the solution you'd like**
An option to ignore settings, like
"ignoreSettings": [
        "editor.fontSize"
],

**Comment by arnohovhannisyan** [comment]
@scythk There already is a feature for this. See [Sync Pragmas](https://github.com/shanalikhan/code-settings-sync/wiki/Sync-Pragmas)

**Comment by scythk** [comment]
> @scythk There already is a feature for this. See [Sync Pragmas](https://github.com/shanalikhan/code-settings-sync/wiki/Sync-Pragmas)

Oh I got it, thanks a lot!
