### ISSUE TITLE
disable sync output panel report

### ISSUE THREAD

**Issue by ctf0** [shanalikhan/code-settings-sync#856]
💡 **Is your feature request related to a problem? Please describe.**
eveytime u make a change ex"change color scheme" the package will sync the changes which is good but what is really frustrating that focus will be hijacked by the output panel.

💡 **Describe the solution you'd like**
maybe simply show a msg in the status bar about the sync operation status ex.`"sync done/failed"`

**Comment by shanalikhan** [comment]
enable quitesync mode from settings
