### ISSUE TITLE
Update/Uploading setting Sync: Error logged in console

### ISSUE THREAD

**Issue by obamgbopa** [shanalikhan/code-settings-sync#857]
At upload after inputting the token i get the Sync: Error logged in console (Help menu > Toggle Developer Tools). The console log below

![Screenshot 2019-04-22 at 07 10 52](https://user-images.githubusercontent.com/3716281/56486639-2ea43780-64d0-11e9-9d11-4d2ea70ca988.jpg)

🌴 **Visual Studio Code Version : Version 1.33.1 (1.33.1) 
🌴 **Code Settings Sync Version : V 3.2.9
🌴 **Standard or Insiders : Standard 
🌴 **Portable or Installed : Installed
🌴 **OSS or Official Build : Official
🌴 **Operating System : macOS Mojave V10.14
🌴 **Occurs On: Upload 

📰 **To Reproduce**
1. Go to command shift + command + p
2. Click on Sync: Update/ Uploading settings
3. Input Github personal access token
4. See the Sync: Error Logged in Console(Help menu > Toggle Developer Tools)

💪 **Expected behavior**
Should get the GIST id

📺 **Console Error Log** 
![Screenshot 2019-04-22 at 07 30 42](https://user-images.githubusercontent.com/3716281/56486736-9c506380-64d0-11e9-9e78-60d93d0d4fe3.jpg)

**Comment by tayler-ramsay** [comment]
I am receiving the same error as above

**Comment by arnohovhannisyan** [comment]
@obamgbopa What's in your `settings.json` file?

**Comment by SimpleNice** [comment]
I am receiving the same error as above

**Comment by obamgbopa** [comment]
@arnohovhannisyan  

{{
  "workbench.colorTheme": "Material Theme",
  "breadcrumbs.enabled": true,
  "editor.acceptSuggestionOnEnter": "on",
  "editor.detectIndentation": false,
  "editor.fontFamily": "'Source Code Pro', Menlo, Consolas, Courier, monospace",
  "workbench.iconTheme": "material-icon-theme",
  "debug.node.autoAttach": "on",
  "editor.fontSize": 10,
  "workbench.colorTheme": "Material Theme",
  "editor.formatOnSave": true,
  "editor.multiCursorModifier": "ctrlCmd",
  "editor.quickSuggestions": {
    "other": true,
    "comments": true,
    "strings": true
  },
  "editor.renderWhitespace": "none",
  "editor.snippetSuggestions": "top",
  "editor.tabSize": 2,
  "editor.wordWrap": "on",
  "editor.wrappingIndent": "indent",
  "emmet.preferences": {
    "format.forceIndentationForTags": "address,article,aside,audio,blockquote,body,canvas,div,dl,fieldset,figcaption,figure,footer,form,head,header,iframe,main,map,nav,object,ol,p,pre,section,style,table,tbody,td,tfoot,th,thead,tr,ul,video"
  },
  //"extensions.ignoreRecommendations": true,
  //"extensions.showRecommendationsOnlyOnDemand": true,
  //"files.exclude": {
   // "**/._*": true
  //},
  "files.insertFinalNewline": true,
  // Remove the following to enable Git
  "git.enabled": true,
  "html.format.endWithNewline": true,
  "html.format.extraLiners": "body",
  "html.format.indentInnerHtml": true,
  "html.format.unformatted": "b,em,i,span,strong,wbr",
  "html.format.wrapLineLength": 0,
  //"liveSassCompile.settings.autoprefix": null,
  //"liveSassCompile.settings.generateMap": false,
  //"liveServer.settings.donotShowInfoMsg": true,
  //"liveServer.settings.port": 0,
  "path-autocomplete.excludedItems": {
    "**/{.DS_Store,.git,.gitignore,node_modules}": {
      "when": "**"
    }
  },
  "path-autocomplete.extensionOnImport": true,
  "window.zoomLevel": 0,
  "workbench.colorCustomizations": {
    "editorIndentGuide.activeBackground": "#FFA500"
  },
  "workbench.editor.tabSizing": "shrink",
  "workbench.editor.enablePreview": true,
  "workbench.editor.enablePreviewFromQuickOpen": true,
  "eslint.autoFixOnSave": true
}

**Comment by arnohovhannisyan** [comment]
@obamgbopa Try removing the second curly brace on first line.
```
{{
```

**Comment by obamgbopa** [comment]
@andrewkboyd  thanks, worked
