### ISSUE TITLE
where is v3.2.9 release?

### ISSUE THREAD

**Issue by qqqasdwx** [shanalikhan/code-settings-sync#861]
🐛 **Describe the bug**  
please update release v3.2.9 . I have a web vs code [code-server](https://github.com/codercom/code-server), and I need manual update this Extensions .
thanks!

🌴 **Visual Studio Code Version :** [ 1.33.1 ] 
🌴 **Code Settings Sync Version :** [ 3.2.8] 
🌴 **Standard or Insiders :** [ Standard] 
🌴 **Portable or Installed :** [ Installed] 
🌴 **OSS or Official Build :** [ _here_ ] 
🌴 **Operating System :** [ ubuntu 16.04] 
🌴 **Occurs On:** [Upload  ]
🌴 **Proxy Enabled:** [ No ]
🌴 **Gist Id:** [ ID_HERE ]

**Comment by shanalikhan** [comment]
https://github.com/shanalikhan/code-settings-sync/releases/tag/v3.2.9

Added.Change logs are added already.

**Comment by qqqasdwx** [comment]
thanks
