### ISSUE TITLE
@sync-ignore proxy setting double slash gets lost

### ISSUE THREAD

**Issue by bjonen** [shanalikhan/code-settings-sync#865]
🐛 **Describe the bug**  

My settings.json looks like this: 
    // @sync-ignore
    "http.proxy": "http://user:pw@myproxy:port", 
    // @sync-ignore
    "http.proxyStrictSSL": false,

When download my laptop settings to my office computer, the settings.json gets rewritten but the http proxy becomes http:user:pw@myproxy:port (missing the "//") so that all extension downloads fail afterwards. 

🌴 **Visual Studio Code Version :** 1.331

**Comment by ioprotium** [comment]
@shanalikhan I will take this
