### ISSUE TITLE
workbench.main.js:91

### ISSUE THREAD

**Issue by OlegLustenko** [shanalikhan/code-settings-sync#87]
**Visual Studio Code Version :** [ 1.4.0]
**Code Sync Settings Version :** [ 2.2.3]
**Operating System :** [ Windows 10]

Please make sure to write the versions and console logged error picture or copied text.
![image](https://cloud.githubusercontent.com/assets/11524061/18241560/88cda5b2-735a-11e6-8d44-a90c3bf25bc7.png)

**Comment by OlegLustenko** [comment]
This mistake was every time when I open vscode. I manually choose Sync: Update / Upload, and mistake has gone

**Comment by shanalikhan** [comment]
Looks like the process was not completed but u started it again.
Look forward to this problem in future update 

So the issue is solved?

**Comment by OlegLustenko** [comment]
Yes, no error anymore
