### ISSUE TITLE
Issue settings up extension with a proxy server

### ISSUE THREAD

**Issue by zacharyshupp** [shanalikhan/code-settings-sync#88]
**Visual Studio Code Version :** 1.4.0
**Code Sync Settings Version :** 2.2.3
**Operating System :** Windows 7

I recently found this extension and found it very useful. Now all my other computers don't have a restricted proxy. At work when I load vscode I have to set my the below sections in my user settings. When I went to install your extension it kept failing with the attached exception. I did see that in the syncSettings.json you have ha proxyIP and port. I did add those but still receive the same error.  

Any help would be great, I cant get you any of my direct settings because of the network I work on but if you need more details please let me know.
[exception.txt](https://github.com/shanalikhan/code-settings-sync/files/455447/exception.txt)
![vscode_about](https://cloud.githubusercontent.com/assets/5675796/18254622/8160aaa0-736d-11e6-8654-1ed3a823dc42.PNG)

**Comment by shanalikhan** [comment]
I'm closing this issue, please subscribe to [#60](https://github.com/shanalikhan/code-settings-sync/issues/60).
