### ISSUE TITLE
Sync Commands display language

### ISSUE THREAD

**Issue by SSvilen** [shanalikhan/code-settings-sync#886]
🐛 **Describe the bug**  
I have a Windows OS in German. My VS Code is configured in English . 
When I go to Command Palette (Ctrl+Shift+P) and then I type SYNC:  I see the sync commands in English (for instance Sync: How to configure, etc.. ). When I go to 'Sync: Advanced Options' all the commands in the sub-menu are in German. (or most of them).

🌴 **Visual Studio Code Version** : 
Version: 1.33.1 (system setup)
Commit: 51b0b28134d51361cf996d2f0a1c698247aeabd8
Date: 2019-04-11T08:27:14.102Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32

🌴 **Code Settings Sync Version** : 3.2.9
🌴 **Standard or Insiders** : Standard
🌴 **Portable or Installed :** Intalled 
🌴 **OSS or Official Build :** Official Build
🌴 **Operating System :** Windows_NT x64 10.0.16299 
🌴 **Occurs On:** [Using ]
🌴 **Proxy Enabled:** [ Yes]

📰 **To Reproduce**
1. Go to Command Palette (Ctrl+Shift+P) 
2. type  'Sync: Advanced Options' 
3. Enter to choose the menu
4. The sub-menu is in German
![image](https://user-images.githubusercontent.com/10175251/57696709-b43f8100-7651-11e9-9380-6321f9c1a199.png)

💪 **Expected behavior**
I guess it needs to take the language of VS Code.

**Comment by shanalikhan** [comment]
>  I see the sync commands in English (for instance Sync: How to configure, etc.. ). When I go to 'Sync: Advanced Options' all the commands in the sub-menu are in German. (or most of them).

@arnohovhannisyan can we fix this ? We need to read local of vscode instead of windows i suppose.

**Comment by arnohovhannisyan** [comment]
@shanalikhan VSCode creates a file called `locale.json` in the User folder that has the exact same contents as the `localize.ts` config. I guess we can just read that file and parse that instead of the environmental variable.

**Comment by arnohovhannisyan** [comment]
@SSvilen Try this: https://cdn.discordapp.com/attachments/549007146868539408/590855877355896852/code-settings-sync-3.2.9.vsix.

**Comment by shanalikhan** [comment]
I have released new version of Settings Sync v3.3.0 fixing this issue. Im closing this ticket let me know if u guys run into some problem
