### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Ornaldo8** [shanalikhan/code-settings-sync#888]
- Issue Type: `Performance`
- Extension Name: `code-settings-sync`
- Extension Version: `3.2.9`
- OS Version: `Windows_NT x64 10.0.17134`
- VSCode version: `1.33.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\user\Shan.code-settings-sync-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by shanalikhan** [comment]
PR is welcome for it if anyone think process can be further improved.

**Comment by arnohovhannisyan** [comment]
@Ornaldo8 Can you please upload your `cpuprofile.txt` so we can find out what's causing the high CPU usage?
