### ISSUE TITLE
What+s the MacOs keyboard shortcut for Upload Settings?

### ISSUE THREAD

**Issue by MR-T77** [shanalikhan/code-settings-sync#889]
What is the correspondent for MacOs of Shift+Alt+U?

**Comment by arnohovhannisyan** [comment]
@MR-T77 try Shift+Option+U

**Comment by MR-T77** [comment]
It doesn't work...I have a portuguese layout keyboard (PT-pt), maybe because of that.
It would be nice if you provide information support for MacOs and also to this type of keyboards.

**Comment by arnohovhannisyan** [comment]
@MR-T77 you can try going to the keybindings settings and remapping the Download and Upload actions to your preferred layout.

**Comment by MR-T77** [comment]
Sure, but that option is not trivial. Unfortunately, several apps and extensions(like this) disregard and do not support national layout keyboards (mainly in MacOS), thus new keybindings have great chance of clashing with existing shortcuts...what this causes is an appetence to quit using these apps and extensions.

**Comment by shanalikhan** [comment]
Feel free to send PR where required.
