### ISSUE TITLE
Space before colons in command descriptions

### ISSUE THREAD

**Issue by nawordar** [shanalikhan/code-settings-sync#891]
In command palette, between "Sync" and the colon there is annoying space, unlike in built-in commands. Removing them would make it look a lot better.
![Screenshot_2019-05-18_17-06-58](https://user-images.githubusercontent.com/26769700/57971503-60a1a000-798f-11e9-87dd-cc4846102868.png)

**Comment by shanalikhan** [comment]
> unlike in built-in commands

Can you post the image to  which commands you are looking forward to make Settings Sync consistent?

**Comment by shanalikhan** [comment]
I have released new version of Settings Sync v3.3.0 fixing this issue. Im closing this ticket let me know if u guys run into some problem
