### ISSUE TITLE
replaceCodeSettings doesn't seem to be working

### ISSUE THREAD

**Issue by davidbrownell** [shanalikhan/code-settings-sync#893]
```replaceCodeSettings``` values in the file ```syncLocalSettings.json``` aren't being applied. However, other settings within that file (such as ```customFiles``` and ```supportedFileExtensions``` are).

When I run a sync download, the output in the Code Settings Sync output window suggests that everything completed successfully, but the values in ```settings.json``` have not been replaced after a sync.

Extension Info:
```
Name: Settings Sync
Id: shan.code-settings-sync
Description: Synchronize Settings, Snippets, Themes, File Icons, Launch, Keybindings, Workspaces and Extensions Across Multiple Machines Using GitHub Gist.
Version: 3.2.9
Publisher: Shan Khan
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync
```

VSCode Info:
```
Version: 1.34.0 (user setup)
Commit: a622c65b2c713c890fcf4fbf07cf34049d5fe758
Date: 2019-05-15T21:59:37.030Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.18362
```

**Comment by davidbrownell** [comment]
This appears to be a regression introduced in 3.2.2 - 3.2.1 works as expected.

**Comment by shanalikhan** [comment]
`replaceCodeSettings` has been replaced with [Sync Pragmas](https://github.com/shanalikhan/code-settings-sync/wiki/Sync-Pragmas)
