### ISSUE TITLE
how to use environment variable ?

### ISSUE THREAD

**Issue by lizhuangs** [shanalikhan/code-settings-sync#894]
I have some settings between linux and win,of course they are different .I want to set environment variable in each machine .How could I do it ,is there any docs for this ? Tks.

**Comment by lizhuangs** [comment]
the another problem is some settings are secret,but gist is unsafe.anybody else will see them.the environment variable is a good idea.

**Comment by shanalikhan** [comment]
Check the wiki here: https://github.com/shanalikhan/code-settings-sync/wiki/Sync-Pragmas#env-variables-for-settings-or-keybindings

**Comment by lizhuangs** [comment]
Thank you !!! I got It~

**Comment by lizhuangs** [comment]
eeeeh,I think there is still a problem here.I must save all my settings in configuration file and upload it.
but some settings include secret value,like `token` or `password`.
the env support to read the key of environment variable ,but not support to read the value of environment variable .

**Comment by lizhuangs** [comment]
maybe it can use syncLocalSettings.json to save each machine settings.I think this is a good idea too.

**Comment by shanalikhan** [comment]
> the env support to read the key of environment variable ,but not support to read the value of environment variable .

Can you create new issue with clear example that you have created env. variable and xx value and want Sync Pragmas expected behavior so i can look into it in further releases
