### ISSUE TITLE
Can I have multiple settings?

### ISSUE THREAD

**Issue by nuu54262** [shanalikhan/code-settings-sync#895]
I'm using 3 different operating system (Windows, macOS and Ubuntu). They have quite different keybindings and color scheme. So I'm wondering can I upload 3 different settings by using **1 Gist token**?

**Comment by arnohovhannisyan** [comment]
@nuu54262 Yes, this feature already exists. See [Sync Pragmas](https://github.com/shanalikhan/code-settings-sync/wiki/Sync-Pragmas).

**Comment by shanalikhan** [comment]
> So I'm wondering can I upload 3 different settings by using 1 Gist token?

You need to use Sync Pragmas, differentiate the computers by `host`
