### ISSUE TITLE
"Sync Pragmas" documentation is unclear

### ISSUE THREAD

**Issue by darkvertex** [shanalikhan/code-settings-sync#896]
🐛 **Describe the bug**  

With regards to the [_Sync Pragmas_ docs page](https://github.com/shanalikhan/code-settings-sync/wiki/Sync-Pragmas), see [my comment here](https://github.com/shanalikhan/code-settings-sync/issues/805#issuecomment-483426790) and [someone else's here](https://github.com/shanalikhan/code-settings-sync/issues/753#issuecomment-495460505).

Maybe the documentation looks super obvious to you, but it isn't for everybody.

Would it be possible to spell out some examples in the [Sync Pragmas docs](https://github.com/shanalikhan/code-settings-sync/wiki/Sync-Pragmas) to clear our collective confusion? (Much appreciated!)

📰 **To Reproduce**
1. Go to docs: https://github.com/shanalikhan/code-settings-sync/wiki/Sync-Pragmas
2. Read. :book: :eyes:
3. Scroll for examples... Find none. :crying_cat_face:

💪 **Expected behavior**
I'd expect a few syntax examples for sake of clarity.

**Comment by shanalikhan** [comment]
Sure, i will put more examples.
CC :  @njkevlani @ioprotium

**Comment by arnohovhannisyan** [comment]
@darkvertex Do my revisions to the wiki clear things up for you? If not, please tell me what you would like to see revised.

**Comment by darkvertex** [comment]
> @darkvertex Do my revisions to the wiki clear things up for you? If not, please tell me what you would like to see revised.

Way better! Thank you. This clears up my confusion.

(What do you think, @Soxcks? Is it clearer for you now also?)

**Comment by Soxcks** [comment]
This is way better, thanks very much. Very clear to me now.
