### ISSUE TITLE
Feature : Add Proxy Support 

### ISSUE THREAD

**Issue by repocho** [shanalikhan/code-settings-sync#9]
Hi,

I have generated an access token correctly as is described in the README, and after entering in the extension an error is shown:

`ERROR ! Logged In Console. Please open an issue in Github Repo.`

I think this is because I'm behind a **corporate proxy**.

Could you please have a look into it ?

### **UPDATE:**
I have tested in another PC without the **proxy** and the key works like a charm !!
I have configured the proxy in my settings. I can see extensions and install it.
Visual Studio Code Version: **0.10.6**

**Comment by shanalikhan** [comment]
Thanks, i will add more improvements regarding proxies in future updates.
Good to know you were successfully able to sync settings across multiple PC without the proxy :)

**Comment by RePoChO** [comment]
I don't know if this could be an issue of the package github 
Why are there two dependencies in the project "github" and "node-github" ?
"node-github" seems be the an old version of github package, right ?

**Comment by shanalikhan** [comment]
I will check it out soon. 
were you able to sync without proxy settings ?

**Comment by RePoChO** [comment]
Did you fix it ?

**Comment by shanalikhan** [comment]
were are you able to sync without proxy settings ?

**Comment by RePoChO** [comment]
The summary is:

- In a computer without proxy works with my api keys and gist id.
- In a computer with a proxy doesn't work even with the proxy configured in vsc and in the environments variables.

Thanks.

**Comment by shanalikhan** [comment]
yes proxy limitation will be added soon. i will start working on it

**Comment by linkusbob** [comment]
I wanted to mention that I am also awaiting this feature; I am behind a non-optional **corporate proxy** as well.  Thanks for the extension!

**Comment by chuckhendo** [comment]
I believe this is fixed with #37. If @shanalikhan can confirm and merge, we should be good

**Comment by shanalikhan** [comment]
i have updated the code and updated in the marketplace with the new version with 1.3.0

@linkusbob , @repocho 
Can you check its working with the proxies also so we can close this issue
