### ISSUE TITLE
Cannot download setting

### ISSUE THREAD

**Issue by OlegChep** [shanalikhan/code-settings-sync#902]
Extension cannot download my synced setting after providing the token. Results in these errors when trying to sync:

workbench.main.js:238 [Extension Host] HttpError: Not Found
	at module.exports.e.exports.then.n.text.then.r (C:\Users\olegc\.vscode\extensions\shan.code-settings-sync-3.2.9\out\extension.js:176:50169)
	at process._tickCallback (internal/process/next_tick.js:68:7)
t.log @ workbench.main.js:238
workbench.main.js:2365 Sync : Error Logged In Console (Help menu > Toggle Developer Tools).
onDidNotificationChange @ workbench.main.js:2365
workbench.main.js:238 [Extension Host] HttpError: Not Found
	at module.exports.e.exports.then.n.text.then.r (C:\Users\olegc\.vscode\extensions\shan.code-settings-sync-3.2.9\out\extension.js:176:50169)
	at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by jpSimkins** [comment]
Cannot upload either. I was just testing this extension out and ran into this error.

**Comment by jpSimkins** [comment]
This issue appeared for me when I used the account token as the Gist ID. Do not enter anything, just tell it to upload using the shortcut then paste in your token. Then it will give you an ID to use. If you need to find the ID to use for doanload, just open the gist and copy the ID from the URL. See if that helps

**Comment by OlegChep** [comment]
That worked. Thank you!

**Comment by OlegChep** [comment]
Switched to GIST ID from Token and everything worked.

**Comment by shanalikhan** [comment]
I wish i could make the documentation or WIKI clearer for the guys. Most of the issues are raised by miss understanding.

I am always open for PR that improve the readme.
Also Public Edit in Github Wiki is enabled. Feel free to improve that. where you think there is confusion.

**Comment by jpSimkins** [comment]
Thanks, I made a minor edit to the installation as a note. Hopefully that will be more clear
