### ISSUE TITLE
settings-sync github connexion issue

### ISSUE THREAD

**Issue by delcata** [shanalikhan/code-settings-sync#903]
🌴 **Visual Studio Code Version :** [ 1.35.0 ] 
🌴 **Code Settings Sync Version :** [ 3.2.9 ] 
🌴 **Standard or Insiders :** [ Insiders ] 
🌴 **Portable or Installed :** [ Installed ] 
🌴 **OSS or Official Build :** [ Official Build ] 
🌴 **Operating System :** [ Windows 10 64 bit with wsl ] 
🌴 **Occurs On:** [Upload]
🌴 **Proxy Enabled:** [ No ]
🌴 **Gist Id:** [ delcata ]

Hello, I have an issue with setting sync, when I try connecting to my GitHub account with setting sync I have this error:
![Issue2_part1](https://user-images.githubusercontent.com/28787067/59005820-7b3c9b80-880e-11e9-817e-240deb823e97.png)

**Comment by arnohovhannisyan** [comment]
@delcata Try this: https://github.com/shanalikhan/code-settings-sync/issues/668#issuecomment-491119313

**Comment by delcata** [comment]
the connexion with GitHub works but I got another problem:
![Issue2_part2](https://user-images.githubusercontent.com/28787067/59008605-885f8780-881a-11e9-8751-2506e07e2b55.png)
![Issue2_part2](https://user-images.githubusercontent.com/28787067/59008855-1b98bd00-881b-11e9-8de8-3ab6ee91237a.png)
![Issue2_part3](https://user-images.githubusercontent.com/28787067/59008867-24898e80-881b-11e9-88b0-23ad321e9460.png)
![Issue2_part4](https://user-images.githubusercontent.com/28787067/59008873-294e4280-881b-11e9-9ee3-d02a54cc8cad.png)

**Comment by arnohovhannisyan** [comment]
@delcata This might be an issue with your proxy settings on WSL. Are you using a VPN? Also, if you have a proxy set, can you try temporarily disabling it?

**Comment by delcata** [comment]
I'm not using a proxy but I think wsl use a tunnel to corporate between the Linux subsystem and the windows part.

**Comment by shanalikhan** [comment]
Check the [solution for unable to connect to github](https://github.com/shanalikhan/code-settings-sync/wiki/Troubleshooting#fix-sync-internet-not-connected-or-unable-to-connect-to-github-exception-logged-in-console-windows-only) here. It may help.

**Comment by sarahgerweck** [comment]
I had this issue a well. The only way to fix it was to disable and reenable the Settings Sync extension: It seems that something gets cached and eventually breaks. Resetting the OAuth token and rebooting the machine did not help, but disabling and reenabling Settings Sync fixed it immediately.
