### ISSUE TITLE
support syncLocalSettings.json or github private repository

### ISSUE THREAD

**Issue by lizhuangs** [shanalikhan/code-settings-sync#916]
💡 **support save config in syncLocalSettings.json or sync with github private repository**
the gist can be seen by anyone who get the gist url.
It is unsafe.
hope for support to save some secret configs  like `oauth token`,`password` in syncLocalSettings.json or sync with github private repository.may be syncLocalSettings.json is simple to implement,but the private  repository is better experience.

**Comment by shanalikhan** [comment]
Duplicate of #413
