### ISSUE TITLE
Can't sync: Internet not connected or unable to connect to github

### ISSUE THREAD

**Issue by Arbitel** [shanalikhan/code-settings-sync#919]
🐛 **Describe the bug**  
Error while syncing: gives me this error
<img width="579" alt="Screen Shot 2019-06-22 at 10 50 46 PM" src="https://user-images.githubusercontent.com/2641332/59968809-3881ff80-9540-11e9-8d25-f69a1f11bf62.png">

🌴 **Visual Studio Code Version :** [1.35.1 ] 
🌴 **Code Settings Sync Version :** [ 3.2.9 ] 
🌴 **Operating System :** [ MacOS Mojave 10.14.5  ] 

📰 **To Reproduce**
When Syncing

💪 **Expected behavior**

📺 **Console Error Log** 
IfHttpError: token ˆ [my token] is not a legal HTTP header value
	at module.exports.e.exports.then.then.catch.t

📺  **Additional context**

**Comment by shanalikhan** [comment]
Try on latest version of settings sync.

**Comment by Arbitel** [comment]
Not working, still giving the same error
