### ISSUE TITLE
Cannot sync my VS Code Settings

### ISSUE THREAD

**Issue by GoshaFighten** [shanalikhan/code-settings-sync#93]
**Visual Studio Code Version :** [ 1.4.0 ]
**Code Sync Settings Version :** [ 2.2.3 ]
**Operating System :** [ Windows 10 (build: 14393.51) ]

![vs-code-sync](https://cloud.githubusercontent.com/assets/10522139/18279488/6b79d49a-745e-11e6-89ce-64b57ecc2c01.png)

**Comment by shanalikhan** [comment]
Can you update to latest version and let me know if problem is still there.

**Comment by GoshaFighten** [comment]
Works now. Thank you!
