### ISSUE TITLE
supportedFileExtensions stopped working

### ISSUE THREAD

**Issue by that70schris** [shanalikhan/code-settings-sync#931]
🐛 **Describe the bug**  
I have a `styles.css` file stored in the User directory alongside keybindings.json and settings.json.  using `supportedFileExtensions: [ 'code-snippets', 'json', 'css' ]` this was working brilliantly until recently

🌴 **Visual Studio Code Version :** [ 1.35.1 ] 
🌴 **Code Settings Sync Version :** [ 3.3.1 ] 
🌴 **Standard or Insiders :** [ standard ] 
🌴 **Portable or Installed :** [ installed ] 
🌴 **OSS or Official Build :** [ _here_ ] 
🌴 **Operating System :** [ macOS 10.14.5 ] 
🌴 **Occurs On:** [Upload ]
🌴 **Proxy Enabled:** [ No ]
🌴 **Gist Id:** [ ID_HERE ]

📰 **To Reproduce**
1. add a css file in `/Users/<username>/Library/Application Support/Code/User
2. add "css" to the `supportedFileExtensions` array in syncLocalSettings.json
3. Sync Upload
4. notice "css" file wasn't included in the Upload

💪 **Expected behavior**
Files Uploaded in output should show 
```
extensions.json > extensions.json
keybindings.json > keybindings.json
settings.json > settings.json
styles.css > styles.css
```

📺 **Console Error Log** 
If applicable, add screenshots or paste the console log from developer console of VSCode (Help Menu > Developer Tool - Console Tab). 

📺  **Additional context**

**Comment by arnohovhannisyan** [comment]
@that70schris Can you try this version? https://cdn.discordapp.com/attachments/549007146868539408/593317522242011147/code-settings-sync-3.3.1.vsix

Instructions: https://code.visualstudio.com/docs/editor/extension-gallery#_install-from-a-vsix

**Comment by that70schris** [comment]
that version works!

**Comment by that70schris** [comment]
though the autoUpload seems to have stopped working

**Comment by that70schris** [comment]
nvm, seems to have sorted itself out

**Comment by shanalikhan** [comment]
v3.4.0 is released and this has been fixed.
Update the extension and let me know if there is any issue.
