### ISSUE TITLE
Don't overwrite local settings without confirmation or backup

### ISSUE THREAD

**Issue by github-dotcom** [shanalikhan/code-settings-sync#932]
🐛 **Describe the bug**  
I downloaded settings from gist for the first time to try out your extension.
My local settings.json was overwritten without asking for confirmation or providing a backup.
This behavior is not ok. Now I have to try to remember the individual settings I had on this machine. You need to either provide a way to revert or ask for confirmation before overwriting.
The documentation is not clear about this at all. 
"Download your Settings" != "Overwrite Local Settings Without Backup"

**Comment by shanalikhan** [comment]
Restoring the settings to other backup is out of scope of this extension.
We are improve the upload experience that will resist user to replace the updated settings.
