### ISSUE TITLE
Download settings fails on clean install (Ubuntu)

### ISSUE THREAD

**Issue by bengartner** [shanalikhan/code-settings-sync#933]
Installed vscode fresh on Ubuntu, went to download my settings from my synced gist and got a "Sync: Error Logged in Console" which has text as such:

🌴 **Visual Studio Code Version :** 1.35.2
🌴 **Code Settings Sync Version :** Version: 3.3.1
🌴 **Standard or Insiders :** [ standard ] 
🌴 **Portable or Installed :** [ installed ] 
🌴 **OSS or Official Build :** [ official ] 
🌴 **Operating System :** [ Ubuntu 18.04.2 LTS ] 
🌴 **Occurs On:** [ Download  ]
🌴 **Proxy Enabled:** [ No ]
🌴 **Gist Id:** [  ]

📰 **To Reproduce**
Try to download settings on a clean install of VSCode

📺 **Console Error Log** 
workbench.main.js:238 [Extension Host] HttpError: Not Found
        at module.exports.e.exports.then.n.text.then.r (/home/beng/.vscode/extensions/shan.code-settings-sync-3.2.9/out/extension.js:176:50169)
        at process._tickCallback (internal/process/next_tick.js:68:7)
t.log @ workbench.main.js:238
workbench.main.js:2379 Sync : Error Logged In Console (Help menu > Toggle Developer Tools).

**Comment by shanalikhan** [comment]
>  workbench.main.js:238 [Extension Host] HttpError: Not Found

Read the troubleshooting page from the wiki
