### ISSUE TITLE
EPERM errno

### ISSUE THREAD

**Issue by Jakobud** [shanalikhan/code-settings-sync#94]
**Visual Studio Code Version :** 1.4.0
**Code Sync Settings Version :** 2.2.3
**Operating System :** Win 7 x64

Please make sure to write the versions and console logged error picture or copied text.

I previously uploaded my settings on computer A. On computer B, I put in my Github token and Gist ID and hit Download Settings and I get this in the console:

[Extension Host] Windows_NT
threadService.ts:214 [Extension Host] [Object]0: Objectcode: "EPERM"errno: -4048path: "C:\Users\Jake\.vscode\extensions\HookyQR.beautify-0.1.8\README.md"syscall: "open"__proto__: Objectlength: 1__proto__: Array[0](anonymous function) @ threadService.ts:214emitTwo @ events.js:100emit @ events.js:185handleMessage @ internal/child_process.js:718channel.onread @ internal/child_process.js:444
messageService.ts:119 Error Logged In Console (Help menu > Toggle Developer Tools). You may open an issue using 'Sync : Open Issue' from advance setting command.

**Comment by shanalikhan** [comment]
Can you test it again, making a new upload settings with the newer 2.2.5 version and then download again.

You can try updating `HookyQR.beautify-0.1.8` to `0.1.10` 

As this is only in `HookyQR.beautify-0.1.8` and i have this extension and it installs that extension perfectly
