### ISSUE TITLE
can not Download config

### ISSUE THREAD

**Issue by yyman001** [shanalikhan/code-settings-sync#946]
🐛 **Describe the bug**  
A clear and concise description of what the bug is. You are always welcome to check the [Troubleshooting](https://github.com/shanalikhan/code-settings-sync/wiki/Troubleshooting) section before filing the ticket.

🌴 **Visual Studio Code Version :** [ 13.6.0] 
🌴 **Code Settings Sync Version :** [ 3.3.1] 
🌴 **Standard or Insiders :** [ Standard ] 
🌴 **Portable or Installed :** [ Installed ] 
🌴 **OSS or Official Build :** [ Official ] 
🌴 **Operating System :** [ win10 home] 
🌴 **Occurs On:** [Download ]
🌴 **Proxy Enabled:** [  No ]
🌴 **Gist Id:** [ 6d1008774b800710e0fa762934bc16e7f4cad12a]

📰 **To Reproduce**
1. set my gist id to download
2. See error

💪 **Expected behavior**

📺 **Console Error Log** 
If applicable, add screenshots or paste the console log from developer console of VSCode (Help Menu > Developer Tool - Console Tab). 
```cmd
[Extension Host] debugger listening on port 19884
/D:/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:241 [Extension Host] HttpError: request to https://api.github.com/gists/e7f785188363978106a24d0033373be563fea4e3 failed, reason: connect ETIMEDOUT 54.169.195.247:443	at module.exports.then.then.catch.t (C:\Users\lenovo\.vscode\extensions\shan.code-settings-sync-3.3.1\out\extension.js:622:18309)	at process._tickCallback (internal/process/next_tick.js:68:7)
t.log @ /D:/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:241
/D:/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:241 [Extension Host] HttpError: request to https://api.github.com/user failed, reason: connect ETIMEDOUT 54.169.195.247:443	at module.exports.then.then.catch.t (C:\Users\lenovo\.vscode\extensions\shan.code-settings-sync-3.3.1\out\extension.js:622:18309)	at process._tickCallback (internal/process/next_tick.js:68:7)
t.log @ /D:/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:241
/D:/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:241 [Extension Host] HttpError: Not Found	at module.exports.then.t.text.then.t (C:\Users\lenovo\.vscode\extensions\shan.code-settings-sync-3.3.1\out\extension.js:622:17930)	at process._tickCallback (internal/process/next_tick.js:68:7)
t.log @ /D:/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:241
/D:/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2394 Sync : 错误信息已打印在控制台 (帮助 > 切换开发人员工具)
onDidNotificationChange @ /D:/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2394
/D:/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:241 [Extension Host] Sync : Connected with user : 'yyman001'
2webviewElement.ts:363 [Embedded Page] Refused to apply inline style because it violates the following Content Security Policy directive: "style-src vscode-resource:". Either the 'unsafe-inline' keyword, a hash ('sha256-DL2IXj82ZaxyeudYyUlldcmA2Ado0C8vLkhPmTFfEd8='), or a nonce ('nonce-...') is required to enable inline execution.
```

![image](https://user-images.githubusercontent.com/5688485/60723586-9f52e000-9f66-11e9-8f6b-97f971a7b34e.png)

📺  **Additional context**

**Comment by shanalikhan** [comment]
> You are always welcome to check the Troubleshooting section before filing the ticket.

Check the [Troubleshooting](https://github.com/shanalikhan/code-settings-sync/wiki/Troubleshooting) there are details steps to fix the `Not Found` error. This is due to either invalid GIST ID or Github Token ID
