### ISSUE TITLE
Cannot sync settings since 2 weeks

### ISSUE THREAD

**Issue by inwardmovement** [shanalikhan/code-settings-sync#949]
Settings do not sync any more, can you help me please?

🌴 **Visual Studio Code Version :** 1.36.0
🌴 **Code Settings Sync Version :** 3.3.1
🌴 **Standard or Insiders :** standard
🌴 **Portable or Installed :** installed
🌴 **OSS or Official Build :** official
🌴 **Operating System :** windows
🌴 **Occurs On:** Upload (maybe Download but I don't want to try / fear of loosing my actual settings)
🌴 **Proxy Enabled:** [ Yes / No ]
🌴 **Gist Id:** [1b8b7717469c2648bacb57a1498dd84e](https://gist.github.com/inwardmovement/1b8b7717469c2648bacb57a1498dd84e)

📺 **Console Error Log** 
![Extension_ Settings Sync - inwardmovement github io - Visual Studio Code 000189](https://user-images.githubusercontent.com/9438102/60803450-81aa9400-a17b-11e9-875c-56b8f10624f8.png)

**Comment by arnohovhannisyan** [comment]
@inwardmovement Can you try this build? https://cdn.discordapp.com/attachments/549007146868539408/597761688443289610/code-settings-sync-3.4.0.vsix

Instructions: https://code.visualstudio.com/docs/editor/extension-gallery#_install-from-a-vsix

**Comment by shanalikhan** [comment]
@inwardmovement
Can you check on the upcoming build by @arnohovhannisyan 
If still doesnt work for you than i would suggest you to share your entire `User` folder in compressed file( removing private settings)

**Comment by cycomachead** [comment]
🎉 Yay! Thanks! I was running into the same error and this build is working for me.

**Comment by inwardmovement** [comment]
It seems ok with `3.4.0`, thanks!

Can I get rid of the `.vsix` and will the extension sync back with future updates?

**Comment by shanalikhan** [comment]
v3.4.0 is in testing phase, will be released in a week or two.
