### ISSUE TITLE
Latest update wiped out all my extensions

### ISSUE THREAD

**Issue by jdshkolnik** [shanalikhan/code-settings-sync#95]
**Visual Studio Code Version :** [ 1.4.0 ]
**Code Sync Settings Version :** [ 2.2.3 ]
**Operating System :** [ Windows 10 ]

I started up Code and all I see now is your extension; no others. They were all wiped out.

**Comment by shanalikhan** [comment]
By default, extension allows auto download the settings- it already have outdated cloud version file. When you updated it started downloading the older file where it had no extensions so it deleted all the settings.

You might need to upload the latest settings and extensions or you need to toggle auto download to OFF on startup to stop it automatically downloading the settings.
