### ISSUE TITLE
Settings sync keeps bothering me with a pop up to share my ID every single time I save a file and it auto uploads my settings

### ISSUE THREAD

**Issue by jcklpe** [shanalikhan/code-settings-sync#954]
It's super annoying. Hasn't done this before. Is this a new "feature"? Because it's suuuper annoying.

**Comment by shanalikhan** [comment]
> pop up to share my ID every single time

Can you share the image of pop.

> it auto uploads my settings

You can always turn off the `autoUpload` from the settings.

**Comment by jcklpe** [comment]
@shanalikhan 

Thank you, here is an image:

![image](https://user-images.githubusercontent.com/9451726/61008774-27096780-a336-11e9-9755-736055b88ce3.png)


I don't have a problem with it autouploading my settings. I actually prefer it to do that. It's the the pop up that find troublesome.

**Comment by shanalikhan** [comment]
Can you show your extension Global Settings , that are in User/custom sync settings.json file.
You can remove your token.
I need to reproduce to see.

**Comment by jcklpe** [comment]
You're asking for my global settings.js right?

Here's a link to the gist https://gist.github.com/jcklpe/1bed6c262105cbde0f3f857a7fae6163

**Comment by GijsGoudzwaard** [comment]
I'm experiencing the same issue even though I have `Quiet sync` enabled. Each time I modify a setting or download a new plugin this popup shows.
