### ISSUE TITLE
Correctly setup but error uploading

### ISSUE THREAD

**Issue by danielo515** [shanalikhan/code-settings-sync#955]
Issue Type: <b>Bug</b>

After setting up the extension, this is what I get when I try to upload the settings for first time:

```
2console.ts:134 [Extension Host] HttpError: Not Found	at module.exports.then.t.text.then.t (/Users/danielo/.vscode/extensions/shan.code-settings-sync-3.3.1/out/extension.js:622:17930)	at process._tickCallback (internal/process/next_tick.js:68:7)
t.log @ console.ts:134
$logExtensionHostMessage @ mainThreadConsole.ts:38
_doInvokeHandler @ rpcProtocol.ts:394
_invokeHandler @ rpcProtocol.ts:379
_receiveRequest @ rpcProtocol.ts:299
_receiveOneMessage @ rpcProtocol.ts:226
_protocol.onMessage.e @ rpcProtocol.ts:101
fire @ event.ts:558
a @ ipc.net.ts:421
e @ ipc.net.ts:428
fire @ event.ts:558
_receiveMessage @ ipc.net.ts:715
S._socketDisposables.push._socketReader.onMessage.e @ ipc.net.ts:578
fire @ event.ts:558
acceptChunk @ ipc.net.ts:236
_register._socket.onData.e @ ipc.net.ts:197
t @ ipc.net.ts:28
emit @ events.js:182
addChunk @ _stream_readable.js:283
readableAddChunk @ _stream_readable.js:264
Readable.push @ _stream_readable.js:219
onStreamRead @ internal/stream_base_commons.js:94
notificationsAlerts.ts:40 Sync: Error Logged In Console (Help menu > Toggle Developer Tools).
onDidNotificationChange @ notificationsAlerts.ts:40
_register.model.onDidNotificationChange.e @ notificationsAlerts.ts:26
fire @ event.ts:558
addNotification @ notifications.ts:156
notify @ notificationService.ts:55
r @ mainThreadMessageService.ts:83
_showMessage @ mainThreadMessageService.ts:44
$showMessage @ mainThreadMessageService.ts:38
_doInvokeHandler @ rpcProtocol.ts:394
_invokeHandler @ rpcProtocol.ts:379
_receiveRequest @ rpcProtocol.ts:299
_receiveOneMessage @ rpcProtocol.ts:226
_protocol.onMessage.e @ rpcProtocol.ts:101
fire @ event.ts:558
a @ ipc.net.ts:421
e @ ipc.net.ts:428
fire @ event.ts:558
_receiveMessage @ ipc.net.ts:715
S._socketDisposables.push._socketReader.onMessage.e @ ipc.net.ts:578
fire @ event.ts:558
acceptChunk @ ipc.net.ts:236
_register._socket.onData.e @ ipc.net.ts:197
t @ ipc.net.ts:28
emit @ events.js:182
addChunk @ _stream_readable.js:283
readableAddChunk @ _stream_readable.js:264
Readable.push @ _stream_readable.js:219
onStreamRead @ internal/stream_base_commons.js:94
console.ts:134 [Extension Host] Sync : Connected with user : 'danielo515'
```

Extension version: 3.3.1
VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:56:38.504Z)
OS version: Darwin x64 18.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|6, 9, 6|
|Memory (System)|32.00GB (5.98GB free)|
|Process Argv|-psn_0_69649|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by shanalikhan** [comment]
Check the troubleshooting page from the wiki section.
You r not putting the right GIST ID or Token ID in the configuration

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by danielo515** [comment]
The token is correct because you can see the last message says it's logged in as my user.
I was trying without gistId because I want to create a new one. In any case, I tried with an existing gistId and the result is also an error:

```
[Extension Host] Sync : Connected with user : 'danielo515'
console.ts:134 [Extension Host] Sync: file extensions.json has changed
console.ts:134 [Extension Host] HttpError: Not Found	at module.exports.then.t.text.then.t (/Users/danielo/.vscode/extensions/shan.code-settings-sync-3.3.1/out/extension.js:622:17930)	at process._tickCallback (internal/process/next_tick.js:68:7)
```

I'll try with a brand new token though.

**Comment by danielo515** [comment]
Yep, the problem was that the token that I was using had no access to gists.
Sorry
