### ISSUE TITLE
add feat save config for github project?

### ISSUE THREAD

**Issue by yyman001** [shanalikhan/code-settings-sync#958]
💡 **Is your feature request related to a problem? Please describe.**
use plug for my home is error forevery!!!!
💡 **Describe the solution you'd like**
can you add feat save `config.json`  to github project ? do not use gists, i dont konw why it link error. 
    Here's my suggestion. Thank you!!!
💡 **Additional context**
nothing~

**Comment by shanalikhan** [comment]
There is already issue opened to save the configuration in Github Repo.
