### ISSUE TITLE
didnt auto generate gist on fresh install with code-insiders snap package

### ISSUE THREAD

**Issue by k1nghat** [shanalikhan/code-settings-sync#968]
🐛 **Describe the bug**  
tried to add sync to code-insiders snap package and it authed with github just fine but it didnt auto create a gist when i selected that option.

🌴 **Visual Studio Code Version :**
Version: 1.37.0-insider
Commit: 112fa76c775ecb79ac2c9e9e5dba0d711d523543
Date: 2019-07-17T05:29:16.474Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 4.18.0-22-generic snap
🌴 **Code Settings Sync Version :** 3.4.0
🌴 **Standard or Insiders :** insiders
🌴 **Portable or Installed :** snap
🌴 **OSS or Official Build :** official
🌴 **Operating System :** KDE Neon
🌴 **Occurs On:** after install and during setup

📰 **To Reproduce**
1. install
2. auth
3. select auto generate

💪 **Expected behavior**
to setup a new gist and take you to settings screen

📺 **Console Error Log** 
N/A

📺  **Additional context**
i cant reproduce the issue because even if i uninstall and delete the extension from the extensions dir i never get the setup procedure again on reinstall.

**Comment by shanalikhan** [comment]
@arnohovhannisyan can you look into this

**Comment by k1nghat** [comment]
> @k1nghat Did you upload after setup? The gist is generated during the upload process.

after i clicked the auto generate gist it took me to the settings ui and there was no gist string in the gist field and is unclear that anything happen or should happen. i check my gists and there was nothing new there.

**Comment by arnohovhannisyan** [comment]
@k1nghat 

> if i could figure out how to clear the settings existence i could start from scratch.

To reset, run `>Sync: Reset Extension Settings` in the command palette.

**Comment by k1nghat** [comment]
> To reset, run `>Sync: Reset Extension Settings` in the command palette.

1. installed extension again.
2. ran `>Sync: Reset Extension Settings`.
3. clicked `login with github`(was already/still auth'd and got success page).
4. clicked auto generate gist and it took me back to the main setup page w/o creating anything on gist.

fyi i also have settings-sync working with its own gist on a regular, non insiders/snap, install of code.

**Comment by adrn** [comment]
FWIW I'm seeing the same issue - no gist is created.

**Comment by arnohovhannisyan** [comment]
@k1nghat @adrn As I mentioned before, the gist is currently created on the first upload. Please upload with no gist id set to create a new one automatically.

**Comment by k1nghat** [comment]
> @k1nghat @adrn As I mentioned before, the gist is currently created on the first upload. Please upload with no gist id set to create a new one automatically.

ah, got ya. ya it seems to be working fine then. though, the flow could be better i guess.
1. install.
2. auth.
3. select already created gist or auto generate one.
4. auto generate selection takes you to settings page with more used options at the top(setting the description).
5. visually explaining at the top or showing that you need to upload or click save for it to upload for the first time.

maybe the auto generate settings page could be different from the current settings page to distinguish that one is part of the setup process and could have the bare essential global settings to get started. for me i would want to be able to set the name of the gist, for example.

**Comment by shanalikhan** [comment]
@k1nghat If you think we can improve the documentation, feel free to send PR to improve the readme.

**Comment by k1nghat** [comment]
> @k1nghat If you think we can improve the documentation, feel free to send PR to improve the readme.

i dont think its a documentation issue. if you select something that says auto generate i get the impression that its going to take care of uploading and generating a gist for me, at least initially. having the option to set some settings before that happens is a little bit more confusing but is a bonus for ppl who want/need some customization before the initial setup completes.

**Comment by shanalikhan** [comment]
Yes you are right, we are improve the UX.
Will release the hotfix in few days.
