### ISSUE TITLE
Syncing print Github token.

### ISSUE THREAD

**Issue by ccinelli** [shanalikhan/code-settings-sync#974]
The Github token should not be displayed in console.

```
CODE SETTINGS SYNC UPLOAD SUMMARY
Version: 3.4.0
--------------------
GitHub Token: [!!!!!!!]
GitHub Gist: 1234567890
GitHub Gist Type: Secret

Restarting Visual Studio Code may be required to apply color and file icon theme.
--------------------

...
```

Consider encrypting the token in setting too.

**Comment by shanalikhan** [comment]
Since now Settings Sync automatically retrieves token from Github Application. I think its safe to remove from the summary.

**Comment by elfakyn** [comment]
Came here to add a vote for this -- even on a non-autoretrieved token maybe truncate it to the first 4 characters if you need it to display at all? A readwrite gist token is pretty powerful.

**Comment by shanalikhan** [comment]
> maybe truncate it to the first 4 characters

Nice idea, will be fixed in upcoming version.

**Comment by shanalikhan** [comment]
fixed,released
