### ISSUE TITLE
Uninstalled extension keeps redownloading

### ISSUE THREAD

**Issue by willstocks** [shanalikhan/code-settings-sync#980]
🐛 **Describe the bug**  
I recently uninstalled an extension and sync appeared to start doing its thing (which I assumed was upload my new settings/extensions), however when I jumped in to my extensions list a little while later, I noticed that the extension was back in the list! So, I deleted it again, waited a few seconds for sync to complete and it reappeared. It looks like the "download" process was happening before the upload process. So I uninstalled the extension and quickly tried to complete a manual upload, but I clearly am not quick enough. To resolve, I had to jump into my gist and delete the extension manually from there (which did the trick perfectly).

🌴 **Visual Studio Code Version :** 1.36.1
🌴 **Code Settings Sync Version :** 3.4.0 (although I have just updated to the latest version)
🌴 **Standard or Insiders :** Standard 
🌴 **Portable or Installed :** Installed
🌴 **OSS or Official Build :** Official Build
🌴 **Operating System :** Windows 10 1809
🌴 **Occurs On:** Upload
🌴 **Proxy Enabled:** 
🌴 **Gist Id:** 4eaba17f3efbf07257c0503521aa1fab (private)

📰 **To Reproduce**
1. Uninstall an extension
2. See extension reappear
3. No errors logged because _technically_ not an error

💪 **Expected behavior**
Uninstalling an extension should update the gist and leave the extension uninstalled

📺 **Console Error Log** 
N/A

📺  **Additional context**

**Comment by shanalikhan** [comment]
Can you post your settings for `sync.*` inside Settings Sync and Global Settings for Settings Sync.

**Comment by willstocks-tech** [comment]
Hi @shanalikhan 

I was looking through my settings earlier and noticed that "Force Download" was enabled. I have tried disabling this (as I do not want to enable "Force Upload") and weirdly, noticed that when I download a new extension within VSCode, the Auto Upload isn't triggering for some reason... However when I _uninstall_ the auto upload appears to trigger without an issue.

The auto upload _only_ appears to trigger if I go in and change a setting relating to the extension I just downloaded. For instance, I installed JSHint - no upload. Restarted VSCode - no upload. Changed a default JSHint setting - UPLOAD! Uninstall JSHint - UPLOAD!

Previous:
![image](https://user-images.githubusercontent.com/43744514/61803730-9b5e0380-ae2a-11e9-98bc-58a7bd617d5b.png)
![image](https://user-images.githubusercontent.com/43744514/61803749-a6189880-ae2a-11e9-99b6-b0e7e60a9874.png)

Current:
![image](https://user-images.githubusercontent.com/43744514/61805215-512a5180-ae2d-11e9-96d0-53ce7e4bc71a.png)
![image](https://user-images.githubusercontent.com/43744514/61805221-55ef0580-ae2d-11e9-9133-f0d905a52eaa.png)

**Comment by willstocks-tech** [comment]
Don't suppose you have any insight @shanalikhan? 😁

**Comment by willstocks-tech** [comment]
Hi @shanalikhan - I had this happen again today, but I'm now on VSCode 1.37

Let me know if I can provide any further info?

**Comment by shanalikhan** [comment]
@willstocks 

>Don't suppose you have any insight 

Unfortunately, i didn't find time to look into this issue.
I hope i will find some time to look into it in a week. :)

**Comment by willstocks** [comment]
Hey @shanalikhan 

Any luck? I just disabled `vscode.php-language-features` but when the sync cycle next ran, I found it had re-enabled and messed slightly with `intelephpsense` (their instructons say to disable the built-in linting/formatting).

**Comment by willstocks** [comment]
Hey @shanalikhan 
Any thoughts on this one?
Let me know if you need any other info
Thanks,
Will

**Comment by janosh** [comment]
Running into this issue as well.

Setting `"sync.forceDownload": false` (Set it to true if you want to download the settings even when you have the latest settings.) solved the issue in my case. Can't remember why I enabled this in the first place.

**Comment by shanalikhan** [comment]
Can you check the upload process is improved on `v3.4.3` if its fixes this problem. @willstocks 

If it doesn't i will investigate this issue, as recently i'm done with v3.4.3 version :)

**Comment by janosh** [comment]
@shanalikhan I'm no longer seeing auto-reinstalling extensions both with and without `"sync.forceDownload"` enabled. Looks like the issue is fixed. 👍

**Comment by willstocks** [comment]
I haven’t seen this again either @shanalikhan 😄

**Comment by shanalikhan** [comment]
Great, Thanks

**Comment by alelom** [comment]
I've always had this issue and I just had another case where it happened. I keep having to uninstall very old extensions that I only once installed on one of my devices. Any solution?
