### ISSUE TITLE
Exclude Settings/Extensions from Sync

### ISSUE THREAD

**Issue by mashwanimq** [shanalikhan/code-settings-sync#982]
💡 **Is your feature request related to a problem? Please describe.**
There are some settings and extensions that I don't want to sync.

💡 **Describe the solution you'd like**
I want a setting that can be configured in settings.json that allows me to specify extension and setting names that I don't want synced. If a setting or extension is added to this list I want it removed from gist.

💡 **Additional context**
n/a

**Comment by shanalikhan** [comment]
1. Ignore Settings

https://github.com/shanalikhan/code-settings-sync/wiki/Sync-Pragmas

2. Ignore Extensions

You can ignore extension by writing its identifier in `ignoredExtensions` in global settings of settings sync ( see readme )

**Comment by neubreed** [comment]
How do I find the extension identifier?

**Comment by hermes85pl** [comment]
I expected that when I add an extension ID to the `ignoreExtensions` (this is how it's actually called, not `ignoredExtensions`; a typo?) it would not be exported in the list of extensions, however it is not the case: having downloaded the settings in another instance of Code, I see the extension being added there. Hence I tried to add it there to prohibit the extension from being installed there: no luck either.

**Comment by shanalikhan** [comment]
@hermes85pl 

Can you post the `ignoredExtensions` values in Global Settings of Settings Sync.

Settings Sync identifier is `Shan.code-settings-sync`. Try with other extensions identifiers. I think we need to add example in Public Wiki for this as well.

**Comment by ackvf** [comment]
/edit: I created a separate issue for this https://github.com/shanalikhan/code-settings-sync/issues/1124

It says
> Enter one extension per line (full name)

but that's really ambiguous and also wrong.

the full name is: "Settings Sync"
the identifier is: "shan.code-settings-sync"

Maybe you could change the help in the Ignored Extensions field in the sync settings to

> Enter one extension identifier per line.
> Identifier can be found in the marketplace.
> For example, this extension's identifier is `shan.code-settings-sync`
