### ISSUE TITLE
Login  to github button not working on Windows

### ISSUE THREAD

**Issue by githubforsank** [shanalikhan/code-settings-sync#985]
Issue Type: <b>Bug</b>

Install Settings Sync
Go to Login with github in the landing page.
VS Studio code 1.36.1

Extension version: 3.4.1
VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.17763

**Comment by shanalikhan** [comment]
can you post the details that is available when you create new bug.
What is the exception logged in Developer console log.

**Comment by AdrianoCahete** [comment]
Is working, but you need to start VSCode as administrator.

This happen because of Windows UAC doesn't let non-administrator applications "talk" with another applications.

**Comment by shanalikhan** [comment]
> Is working, but you need to start VSCode as administrator.


Have you tried opening code as administrator?

> What is the exception logged in Developer console log.

I'm closing this issue, let me know i'll reopen this.
