### ISSUE TITLE
opening help page every time I open the editor

### ISSUE THREAD

**Issue by MahbbRah** [shanalikhan/code-settings-sync#986]
in recent updates `settings sync` looked hype to me! it was really cool back then!

When I'm opening vs code each time it opens the help page. I don't want this so how could I prevent opening the help page in browser each time i open vs code window. please let me know.

🌴 **Visual Studio Code Version :** [ 1.36.1] 
🌴 **Code Settings Sync Version :** [ 3.4.1] 
🌴 **Standard or Insiders :** [ standard ] 
🌴 **Portable or Installed :** [ installed] 
🌴 **OSS or Official Build :** [ Official Build] 
🌴 **Operating System :** [ windows 10 latest] 
🌴 **Occurs On:** [Help Configuring ]
🌴 **Proxy Enabled:** [ No ]

**Comment by shanalikhan** [comment]
> When I'm opening vs code each time it opens the help page.

Help page ? Do you mean welcome page, welcome page can be disabled by bottom right checkbox.
Let me know if you think I can improve the UX more.


![image](https://user-images.githubusercontent.com/8774556/62190452-d318fe00-b38a-11e9-939b-940890d6a78f.png)

**Comment by MahbbRah** [comment]
> > When I'm opening vs code each time it opens the help page.
> 
> Help page ? Do you mean welcome page, welcome page can be disabled by bottom right checkbox.
> Let me know if you think I can improve the UX more.
> 
> ![image](https://user-images.githubusercontent.com/8774556/62190452-d318fe00-b38a-11e9-939b-940890d6a78f.png)

Hi this page: http://shanalikhan.github.io/2017/02/19/Option-to-ignore-settings-folders-code-settings-sync.html keeps opening on browser while I open new window in vs code. 

also how can I see that settings option in vs code to disable this? I can't see anywhere

**Comment by shanalikhan** [comment]
Can you post your Settings Sync Global Settings ( see path from readme).
You can hide your token.

Post your developer console log image when it appears from help menu.

**Comment by MahbbRah** [comment]
Earlier this plugin was cool. I have used several time on fresh setup. I just had to install and puth to gist with authentication token. that's now it broke.

**Comment by shanalikhan** [comment]
> Post your developer console log image when it appears from help menu.

Post the console image first so i can see the error and fix in next version if there is a bug, and reset the settings and try again to see if it worked.

**Comment by MahbbRah** [comment]
> > Post your developer console log image when it appears from help menu.
> 
> Post the console image first so i can see the error and fix in next version if there is a bug, and reset the settings and try again to see if it worked.

Here you go: 
![image](https://user-images.githubusercontent.com/10045253/62265927-0372a200-b448-11e9-8998-23618b751122.png)
This site is opening each time I open new window from vs code.

**Comment by shanalikhan** [comment]
can you Post your Global Settings.
