### ISSUE TITLE
Settings Sync doesn't sync my settings.json

### ISSUE THREAD

**Issue by nitinshambhu** [shanalikhan/code-settings-sync#988]
🐛 **Settings Sync doesn't sync my settings.json**  
I have my customization of Visual Studio Code done on my official laptop ( **mac** ). When I install the plugin on my personal laptop ( **Linux** ) & download all the editor customization, nothing changes. 

Restarting Visual Code also doesn't help.

🌴 **Visual Studio Code Version :** [ 1.36.1  ] 
🌴 **Code Settings Sync Version :** [ 3.4.1] 
🌴 **Proxy Enabled:** [ No ]

📰 **To Reproduce**
1. Make editor customization on a mac , upload the settings.
2. Go to a Linux machine, Install the VS Code 
3. Install plugin Settings sync
4. Download the settings on the Linux machine. 
5. Editor customization doesn't get reflected

💪 **Expected behavior**
I expected the editor customization to get reflected after downloading the settings through Settings Sync

**Comment by shanalikhan** [comment]
can you share your GIST ID.

Is there any exception logged in developer console log in help menu, post an image.

**Comment by nitinshambhu** [comment]
My gist id : ddfeba8214686d5dea41bf5955da7fd8

I didn't remember seeing any exception. However, I will check once again & post that here once I go back home.

**Comment by shanalikhan** [comment]
> I didn't remember seeing any exception. However, I will check once again & post that here once I go back home.

alright.

**Comment by bymayo** [comment]
Similar issue here on the exact same versions as @nitinshambhu, the Gist isn't being updated.

I checked the console and all that is output is:

`[Extension Host] Sync : Connected with user : 'bymayo'`

When I run `Sync: Update/Upload Settings`

**Comment by shanalikhan** [comment]
@bymayo are you also facing in Mac or its other OS. Can you post your Steps to reproduce the behavior.

**Comment by nitinshambhu** [comment]
This is the screenshot I see. So, it doesn't fail. At the same time, my changes also don't get applied.

![Screenshot from 2019-08-06 18-24-27](https://user-images.githubusercontent.com/7783449/62574729-0a0e7880-b891-11e9-9291-9bfedc653879.png)

**Comment by shanalikhan** [comment]
@nitinshambhu 
Can you try on latest `v3.4.3` version of Settings Sync.
