### ISSUE TITLE
sync:invalid gist id

### ISSUE THREAD

**Issue by dingzuhua** [shanalikhan/code-settings-sync#991]
"token": "208be61ad1ea827182e9268d89f088ce11b55dcd",
"sync.gist": "02d010c815dec4580aa1875ca0cf9203"

gist
https://gist.github.com/dingzuhua/02d010c815dec4580aa1875ca0cf9203

Sync: reset the extension Settings
Sync: downloads Settings
And then always sync:invalid gist id

**Comment by shanalikhan** [comment]
Reset the settings and connect your github with new UI.
Does this happens with UI also ?

**Comment by dingzuhua** [comment]
Yeah, reset doesn't help. I've looked at similar questions that you've already closed, tried all the solutions in the answers, and it still doesn't work

**Comment by dingzuhua** [comment]
![图片1](https://user-images.githubusercontent.com/8717156/62365725-60a94900-b557-11e9-9d25-334b64dce7bf.png)
![图片2](https://user-images.githubusercontent.com/8717156/62365728-62730c80-b557-11e9-9a4c-d35f4997b427.png)
<img width="1297" alt="图片3" src="https://user-images.githubusercontent.com/8717156/62365732-656dfd00-b557-11e9-9438-68617a19138e.png">
![图片4](https://user-images.githubusercontent.com/8717156/62365737-699a1a80-b557-11e9-851b-aef401b23c89.png)
upload
![图片6](https://user-images.githubusercontent.com/8717156/62365740-6b63de00-b557-11e9-9df5-c9792f698fdf.png)

**Comment by shanalikhan** [comment]
Can you share both of the local `sync.*` settings for Settings Sync and Global Settigns.

**Comment by dingzuhua** [comment]
> Can you share both of the local `sync.*` settings for Settings Sync and Global Settigns.
settings.json:
{
    "workbench.iconTheme": "material-icon-theme",
    "workbench.colorTheme": "Dracula Soft",
    "editor.fontSize": 14,
    "window.zoomLevel": 0,
    "explorer.confirmDelete": false,
    "editor.formatOnType": true,
    "editor.formatOnSave": true,
    "go.formatTool": "goimports",
    "vs-kubernetes": {
        "vs-kubernetes.helm-path": "/Users/dingzuhua/.vs-kubernetes/tools/helm/darwin-amd64/helm",
        "vs-kubernetes.minikube-path": "/Users/dingzuhua/.vs-kubernetes/tools/minikube/darwin-amd64/minikube"
    },
    "sync.gist": "02d010c815dec4580aa1875ca0cf9203",
    "sync.autoUpload": false,
    "sync.syncExtensions": true,
    "sync.askGistName": true,
    "sync.autoDownload": false,
    "sync.quietSync": false
}

syncLocalSettings.json:
{
    "ignoreUploadFiles": [
        "state.*",
        "syncLocalSettings.json",
        ".DS_Store",
        "sync.lock",
        "projects.json",
        "projects_cache_vscode.json",
        "projects_cache_git.json",
        "projects_cache_svn.json",
        "gpm_projects.json",
        "gpm-recentItems.json"
    ],
    "ignoreUploadFolders": [
        "workspaceStorage"
    ],
    "ignoreExtensions": [],
    "gistDescription": "Visual Studio Code Settings Sync Gist",
    "version": 341,
    "token": "076889d0915709fd091582d1bdb0597af839b5cc",
    "downloadPublicGist": false,
    "supportedFileExtensions": [
        "json",
        "code-snippets"
    ],
    "openTokenLink": true,
    "disableUpdateMessage": false,
    "lastUpload": null,
    "lastDownload": null,
    "githubEnterpriseUrl": null,
    "askGistName": false,
    "customFiles": {},
    "hostName": null,
    "universalKeybindings": false,
    "autoUploadDelay": 20
}

**Comment by dingzuhua** [comment]
> Can you share both of the local `sync.*` settings for Settings Sync and Global Settigns.

settings.json:
{
"workbench.iconTheme": "material-icon-theme",
"workbench.colorTheme": "Dracula Soft",
"editor.fontSize": 14,
"window.zoomLevel": 0,
"explorer.confirmDelete": false,
"editor.formatOnType": true,
"editor.formatOnSave": true,
"go.formatTool": "goimports",
"vs-kubernetes": {
"vs-kubernetes.helm-path": "/Users/dingzuhua/.vs-kubernetes/tools/helm/darwin-amd64/helm",
"vs-kubernetes.minikube-path": "/Users/dingzuhua/.vs-kubernetes/tools/minikube/darwin-amd64/minikube"
},
"sync.gist": "02d010c815dec4580aa1875ca0cf9203",
"sync.autoUpload": false,
"sync.syncExtensions": true,
"sync.askGistName": true,
"sync.autoDownload": false,
"sync.quietSync": false
}

syncLocalSettings.json:
{
"ignoreUploadFiles": [
"state.*",
"syncLocalSettings.json",
".DS_Store",
"sync.lock",
"projects.json",
"projects_cache_vscode.json",
"projects_cache_git.json",
"projects_cache_svn.json",
"gpm_projects.json",
"gpm-recentItems.json"
],
"ignoreUploadFolders": [
"workspaceStorage"
],
"ignoreExtensions": [],
"gistDescription": "Visual Studio Code Settings Sync Gist",
"version": 341,
"token": "076889d0915709fd091582d1bdb0597af839b5cc",
"downloadPublicGist": false,
"supportedFileExtensions": [
"json",
"code-snippets"
],
"openTokenLink": true,
"disableUpdateMessage": false,
"lastUpload": null,
"lastDownload": null,
"githubEnterpriseUrl": null,
"askGistName": false,
"customFiles": {},
"hostName": null,
"universalKeybindings": false,
"autoUploadDelay": 20
}

**Comment by shanalikhan** [comment]
Can you try with the new version and let me know if there is still problem

**Comment by hipertracker** [comment]
It still does not work. My Gist ID is a valid URL (https://gist.github.com/hipertracker/4047a46c9774bfda9b7ec4bc28699c68), My Access Token is fine. But every time I to do "Sync:Download Settings" my VSCode displays  "Invalid Gist ID" error. This does not make any sense. It worked 2 months ago...

**Comment by shanalikhan** [comment]
@hipertracker try resetting extension settings and then configure to download

**Comment by ayagodinsc** [comment]
The error I am getting:
![image](https://user-images.githubusercontent.com/26547753/68512697-f8d95d00-022d-11ea-81e8-894d692cec32.png)
The gist ID is valid, furthermore I was able to download that empty settings.json file, but I can not upload my settings to Github.

**Comment by ayagodinsc** [comment]
Following all the steps I am still seeing in my github that the extension has read-only access
![image](https://user-images.githubusercontent.com/26547753/68515501-0b579480-0236-11ea-8a9e-09ae38566238.png)
That might be a reason...

**Comment by ayagodinsc** [comment]
Finally working! Following all the steps, the extension still had read-only access. Fixing it solved the problem.

**Comment by linyanyuan** [comment]
> Finally working! Following all the steps, the extension still had read-only access. Fixing it solved the problem.

How exactly to solve it?

**Comment by philsinatra** [comment]
I have the exact same problem trying to setup a new system. I've reset the extension (several times) and even tried reinstalling the app from scratch. Any word on a fix?

**Comment by Paulmicha** [comment]
Same issue. Recap :

- Gist is correctly written from 1st computer
- Github Authentication token and Gist ID are correctly setup on 2nd computer
- Error when attempting to download settings from 2nd computer : `Sync: Invalid Gist ID`

Details :

- 1st computer is Debian/Ubuntu-based Linux (Pop!OS 20.04) and uses **VSCode 1.47.3** / Settings Sync 3.4.3
- 2nd computer is Arch-based Linux (EndeavourOS 2020.07.15) and uses **Code - OSS 1.47.3** / Settings Sync 3.4.3

Important note : Settings Sync does not appear in extensions that can be installed from VSCodium.

**Comment by philsinatra** [comment]
I figured out the issue in my case. Pasting the Gist ID into the extension settings interface was actually adding the ID to the settings twice. I checked the `settings.json` file and found the duplication in the `sync.gist` key. Once I corrected that, the download worked properly.

**Comment by Paulmicha** [comment]
Thanks @philsinatra ! Didn't think to check that, nice catch ! I can confirm this manual fix works.
The path to the file to edit was `~/.config/Code - OSS/User/settings.json` in my case (replaced the duplicated Gist ID).

**Comment by hrgweb** [comment]
@philsinatra it works! Thanks buddy.

**Comment by crevulus** [comment]
I ran into a similar issue and solved it the following way:

1. Create a new gist called `cloudSettings` and put anything in there (it will be overwritten anyway).
2. Copy the ID from the gist's URL.
3. Go to the extension settings and replace the ID. 
 
The extension creates an ID for you but seems like at some point along the way the creation of the new gist in Github fails, so it errors out with "Invalid Gist ID". So this is a manual override that worked for me.
