### ISSUE TITLE
The Snippets configuration can't sync

### ISSUE THREAD

**Issue by dv-vb** [shanalikhan/code-settings-sync#993]
🐛 **Describe the bug**  
I worked between Linux and Windows, when I using the Sync Setting, most configuration of VS-code can work very well, but I found that the Snippets can't sync between Linux and Windows.
I write personal snippets of c.json and cpp.json, and I found it already sync the configuration on Gist. Then I download the configuration on Linux System, the Linux VS-code can't replace the file in correct folders. Like the pic:
![image](https://user-images.githubusercontent.com/24910525/62473606-a8d49f80-b7d3-11e9-8e23-2f4ec63a8531.png)

🌴** Linux Visual Studio Code Version: ** [Version: 1.37.0-insider
Commit: 0bd57ac9efae79f9eb1aedc3818ebbb570b9bf6b
Date: 2019-08-02T21:21:57.165Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 4.15.0-29deepin-generic]
🌴 **Windows Visual Studio Code Version :** [ Version: 1.37.0-insider (user setup)
Commit: 4a03f7e7eff2560d2e53c029321870514d19a2aa
Date: 2019-08-05T09:34:10.366Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.17134 ] 
🌴 **Code Settings Sync Version :** [ 3.4.1 ] 
🌴 **Standard or Insiders :** [ Insiders] 
🌴 **Portable or Installed :** [ Installed] 
🌴 **OSS or Official Build :** [ Offical Build] 
🌴 **Operating System :** [ Windows and Linux] 
🌴 **Occurs On:** [Upload and Download  ]
🌴 **Proxy Enabled:** [ No ]
🌴 **Gist Id:** [ 14ef3d36b4aba6674fd5e71a20401cc4]

📰 **To Reproduce**
1. Go to Windows System do some changes on global snippets, like c.json
2. Click on upload
3. Download the configuration on Linux System
4. The snippets can't work. See error

💪 **Expected behavior**
Fix issues

📺 **Console Error Log** 
No Error log

📺  **Additional context**

**Comment by 0reo27** [comment]
I'm experiencing this issue as well.

Could be related to: https://github.com/shanalikhan/code-settings-sync/issues/988

**Comment by hqabcxyxz** [comment]
I have same issue too

**Comment by shanalikhan** [comment]
Yes. It will be fixed in next version.
Thanks for informing.

**Comment by Jacory** [comment]
same issue with my windows and macOs sync

**Comment by shanalikhan** [comment]
`v3.4.3` Released. Let me know if there is any problem :)
